"""Tests for build_mannequin_glb — mannequin GLB generation from body JSON.

Generated by: Claude Opus 4.6 (1M context)
"""

from __future__ import annotations

import json
import sys
import tempfile
from pathlib import Path

import numpy as np
import pytest

# Add tool path so we can import the module
TOOLS_DIR = Path(__file__).resolve().parent.parent / "session-3" / "human-controller" / "tools"
sys.path.insert(0, str(TOOLS_DIR))

import build_mannequin_glb as bmg  # noqa: E402


EXAMPLES_DIR = Path(__file__).resolve().parent.parent / "session-3" / "examples"
DAVID_JSON = EXAMPLES_DIR / "david.json"


@pytest.fixture
def david_body() -> dict:
    return bmg.load_body(DAVID_JSON)


class TestLoadBody:
    def test_loads_valid_body(self, david_body: dict) -> None:
        assert david_body["schemaVersion"] == "3.0.0"
        assert david_body["name"] == "David"
        assert len(david_body["skeleton"]) == 52

    def test_proportions_present(self, david_body: dict) -> None:
        p = david_body["proportions"]
        assert p["totalHeight"] == 173
        assert p["biologicalSex"] == "male"


class TestBoneLookup:
    def test_all_bones_indexed(self, david_body: dict) -> None:
        lookup = bmg.build_bone_lookup(david_body["skeleton"])
        assert len(lookup) == 52
        assert bmg._normalize_bone_name("Pelvis") in lookup
        assert bmg._normalize_bone_name("Skull") in lookup

    def test_root_bone_has_no_parent(self, david_body: dict) -> None:
        lookup = bmg.build_bone_lookup(david_body["skeleton"])
        assert lookup[bmg._normalize_bone_name("Pelvis")]["parentBoneId"] is None


class TestComputeRig:
    def test_produces_19_rig_bones(self, david_body: dict) -> None:
        rig_bones, ibms, meshes = bmg.compute_rig(david_body)
        assert len(rig_bones) == 19
        assert len(ibms) == 19
        assert len(meshes) == 19

    def test_uses_camel_case_rig_names(self, david_body: dict) -> None:
        rig_bones, _, _ = bmg.compute_rig(david_body)
        rig_names = {rb["name"] for rb in rig_bones}

        assert "upperArmL" in rig_names
        assert "lowerLegR" in rig_names
        assert "clavicleL" in rig_names
        assert "upper_arm.L" not in rig_names
        assert "lower_leg.R" not in rig_names

    def test_hips_is_root(self, david_body: dict) -> None:
        rig_bones, _, _ = bmg.compute_rig(david_body)
        assert rig_bones[0]["name"] == "hips"
        assert rig_bones[0]["parent_index"] == -1

    def test_all_parents_valid(self, david_body: dict) -> None:
        rig_bones, _, _ = bmg.compute_rig(david_body)
        for i, rb in enumerate(rig_bones):
            pi = rb["parent_index"]
            assert pi == -1 or (0 <= pi < i), f"bone {rb['name']} has invalid parent_index {pi}"

    def test_inverse_bind_matrices_are_4x4(self, david_body: dict) -> None:
        _, ibms, _ = bmg.compute_rig(david_body)
        for ibm in ibms:
            assert ibm.shape == (4, 4)
            assert ibm.dtype == np.float32

    def test_ibm_translates_to_origin(self, david_body: dict) -> None:
        rig_bones, ibms, _ = bmg.compute_rig(david_body)
        for rb, ibm in zip(rig_bones, ibms):
            # IBM should negate the world position
            result = ibm @ np.append(rb["world_pos"], 1.0)
            np.testing.assert_allclose(result[:3], [0, 0, 0], atol=1e-4)

    def test_meshes_have_vertices_and_faces(self, david_body: dict) -> None:
        _, _, meshes = bmg.compute_rig(david_body)
        for m in meshes:
            assert len(m.vertices) > 0
            assert len(m.faces) > 0

    def test_no_nan_positions(self, david_body: dict) -> None:
        _, _, meshes = bmg.compute_rig(david_body)
        for m in meshes:
            assert not np.isnan(m.vertices).any()


class TestSegmentMeshes:
    def test_capsule_shape(self) -> None:
        m = bmg.make_segment_mesh("capsule", 30.0, 3.0, 2.5)
        assert len(m.vertices) > 0
        assert len(m.faces) > 0

    def test_box_shape(self) -> None:
        m = bmg.make_segment_mesh("box", 10.0, 8.0, 5.0)
        assert len(m.vertices) > 0

    def test_sphere_shape(self) -> None:
        m = bmg.make_segment_mesh("sphere", 15.0, 12.0, 10.0)
        assert len(m.vertices) > 0


class TestBuildGLB:
    def test_produces_valid_glb_file(self, david_body: dict) -> None:
        rig_bones, ibms, meshes = bmg.compute_rig(david_body)
        gltf = bmg.build_glb(rig_bones, ibms, meshes, "David")

        with tempfile.NamedTemporaryFile(suffix=".glb", delete=False) as f:
            out = Path(f.name)
        gltf.save(str(out))

        assert out.stat().st_size > 0

        # Reload and validate
        import pygltflib
        loaded = pygltflib.GLTF2().load(str(out))
        assert len(loaded.nodes) == 20  # 19 bones + 1 mesh node
        assert len(loaded.skins) == 1
        assert len(loaded.meshes) == 1
        assert len(loaded.skins[0].joints) == 19

        out.unlink()

    def test_skeleton_hierarchy(self, david_body: dict) -> None:
        rig_bones, ibms, meshes = bmg.compute_rig(david_body)
        gltf = bmg.build_glb(rig_bones, ibms, meshes, "David")

        # hips (node 0) should have children: spine, upperLegL, upperLegR
        hips = gltf.nodes[0]
        assert hips.name == "hips"
        assert 1 in hips.children   # spine
        assert 13 in hips.children  # upperLegL
        assert 16 in hips.children  # upperLegR

    def test_skin_attributes_present(self, david_body: dict) -> None:
        rig_bones, ibms, meshes = bmg.compute_rig(david_body)
        gltf = bmg.build_glb(rig_bones, ibms, meshes, "David")

        prim = gltf.meshes[0].primitives[0]
        assert prim.attributes.JOINTS_0 is not None
        assert prim.attributes.WEIGHTS_0 is not None
        assert prim.attributes.POSITION is not None
        assert prim.attributes.NORMAL is not None


class TestAllExamples:
    """Ensure all example bodies produce valid mannequins."""

    @pytest.fixture(params=["david.json", "farnese-atlas.json", "honey-bunny.json", "pumpkin.json"])
    def example_body(self, request: pytest.FixtureRequest) -> dict:
        return bmg.load_body(EXAMPLES_DIR / request.param)

    def test_builds_without_error(self, example_body: dict) -> None:
        rig_bones, ibms, meshes = bmg.compute_rig(example_body)
        assert len(rig_bones) >= 15  # at minimum most bones should map
        gltf = bmg.build_glb(rig_bones, ibms, meshes, example_body.get("name", "Test"))
        assert len(gltf.skins) == 1
