import { z } from "zod";
import { ExtensionsSchema } from "./shared";
import { FieldRefSchema } from "./derivations";

// =============================================================================
// Constitutive Law Layer
//
// Encodes the material and physiological laws that constrain field values.
// Each law is a schema entity that:
//   1. References the fields it constrains (via FieldRef from derivations.ts)
//   2. Declares the functional form (symbolic equation)
//   3. Provides parameter bounds and validity domains
//   4. States when the model breaks down (G3: model boundaries)
//
// Constitutive laws are usually embedded in simulation code, not in a data
// schema. Declaring them here makes the physics auditable without running
// a simulator. A consumer can verify: "Is this MuscleForce.magnitude
// physiologically achievable given the muscle's properties and state?"
//
// Addresses gaps:
//   G2 — No mechanism linking muscle forces to physiology
//   G3 — No model validity boundaries
//
// Cross-domain sources:
//   - Hill (1938), "The heat of shortening and the dynamic constants of muscle"
//   - Zajac (1989), CRC Crit Rev Biomed Eng 17(4):359–411
//   - Woo et al. (1999), Am J Sports Med 27(4):533–543
//   - Mow et al. (1980), J Biomech Eng 102(1):73–84
//
// Generated by: Claude Opus 4.6 (1M context)
// =============================================================================

export const CONSTITUTIVE_LAWS_VERSION = "1.0.0" as const;

// =============================================================================
// Severity of a constraint violation
// =============================================================================

export const ViolationSeverityEnum = z.enum([
  "error",    // Physically impossible — model is invalid
  "warning",  // Outside typical physiological range but not impossible
  "info",     // At boundary of typical range — may warrant inspection
]);

// =============================================================================
// Model Validity Boundary (G3)
//
// Declares when a constitutive law's assumptions break down.
// Every law operates within a validity domain. Outside that domain,
// the law's predictions are unreliable or meaningless. Making this
// explicit addresses G3: "the schema never declares when its model
// breaks down."
// =============================================================================

export const ValidityBoundarySchema = z.object({
  assumption: z
    .string()
    .min(1)
    .describe(
      "The modeling assumption this boundary protects. " +
      "Examples: 'rigid body', 'small deformations', 'quasi-static loading'",
    ),
  validWhen: z
    .string()
    .min(1)
    .describe(
      "Condition under which the assumption holds, as a human-readable predicate. " +
      "Example: 'bone stress < yield stress (~130 MPa cortical, ~5 MPa trabecular)'",
    ),
  violatedWhen: z
    .string()
    .min(1)
    .describe(
      "Condition under which the assumption breaks down. " +
      "Example: 'impact loading with strain rate > 1/s'",
    ),
  consequence: z
    .string()
    .min(1)
    .describe(
      "What goes wrong when the assumption is violated. " +
      "Example: 'bone deformation is non-negligible; rigid body dynamics underestimates joint forces'",
    ),
  reference: z
    .string()
    .optional()
    .describe("Literature reference for the validity domain"),
});

// =============================================================================
// Constitutive Law — Generic Structure
//
// A constitutive law constrains the relationship between field values.
// Unlike a DerivationRule (which computes output from inputs), a
// constitutive law defines an inequality or envelope: the field values
// must satisfy the constraint to be physically valid.
//
// Design: Each law has a `lawType` discriminator with type-specific
// parameters, following Rule 8 (discriminated union over optional fields).
// =============================================================================

export const ConstitutiveLawTypeEnum = z.enum([
  "hill_muscle_model",        // Force-length-velocity for skeletal muscle
  "ligament_force_strain",    // Piecewise nonlinear force-strain
  "cartilage_stress_strain",  // Biphasic linear elastic
  "bone_yield_criterion",     // Failure envelope for rigid body assumption
  "joint_range_limit",        // Soft constraint at ROM boundaries
]);

// =============================================================================
// Hill Muscle Model (G2)
//
// The Hill model decomposes muscle force into three components:
//   F_muscle = F_max × [a(t) × f_L(L) × f_V(V) + f_PE(L)]
//
// Where:
//   F_max  = maximum isometric force (from MuscleSchema.maxIsometricForce)
//   a(t)   = activation level (from MuscleForceSchema.activationLevel)
//   f_L(L) = normalized force-length relationship (bell curve, peak at L_opt)
//   f_V(V) = normalized force-velocity relationship (Hill's equation)
//   f_PE(L) = passive elastic force (exponential, from connective tissue)
//
// Reference: Zajac (1989), Fig. 2. This is the standard three-element model
// used in OpenSim, AnyBody, and virtually all musculoskeletal simulation.
//
// This schema declares the model's parameters — not the solver. A consumer
// can use these parameters to verify that a MuscleForce.magnitude is within
// the achievable envelope for the muscle's current state.
// =============================================================================

export const HillMuscleLawSchema = z.object({
  lawType: z.literal("hill_muscle_model"),
  id: z.string().uuid(),
  name: z.string().min(1).describe("Human-readable label (e.g. 'biceps_brachii_hill_model')"),

  // Which schema fields this law constrains
  constrainedFields: z.object({
    muscleForce: FieldRefSchema.describe("Path to the MuscleForce magnitude (e.g. 'loadingConditions[*].forces[type=muscle].magnitude')"),
    activation: FieldRefSchema.describe("Path to activation level"),
    currentLength: FieldRefSchema.describe("Path to current muscle-tendon length"),
    contractionVelocity: FieldRefSchema.describe("Path to contraction velocity"),
    maxIsometricForce: FieldRefSchema.describe("Path to F_max on MuscleSchema"),
    optimalFiberLength: FieldRefSchema.describe("Path to L_opt on MuscleSchema"),
    maxContractionVelocity: FieldRefSchema.describe("Path to V_max on MuscleSchema"),
  }),

  // Force-Length relationship parameters
  // f_L(L̃) where L̃ = L / L_opt (normalized length)
  forceLength: z.object({
    widthParameter: z
      .number()
      .positive()
      .default(0.56)
      .describe(
        "Width of the Gaussian active force-length curve (γ). " +
        "f_L(L̃) = exp(-((L̃ - 1)/γ)²). Typical: 0.45–0.56. " +
        "Ref: Thelen, J Biomech 36(6):853–862, 2003.",
      ),
    minActiveForceLengthRatio: z
      .number()
      .min(0)
      .max(1)
      .default(0.5)
      .describe("Minimum normalized length for active force production (L̃_min). Typically ~0.5."),
    maxActiveForceLengthRatio: z
      .number()
      .min(1)
      .max(2)
      .default(1.5)
      .describe("Maximum normalized length for active force production (L̃_max). Typically ~1.5."),
  }),

  // Force-Velocity relationship parameters
  // Based on Hill's equation: (F + a)(V + b) = (F₀ + a)b
  // In normalized form: f_V(Ṽ) where Ṽ = V / V_max
  forceVelocity: z.object({
    concentricCurveShape: z
      .number()
      .positive()
      .default(0.25)
      .describe(
        "Shape factor for concentric (shortening) force-velocity curve (A_f). " +
        "Smaller = more curved. Typical: 0.1–0.4. " +
        "Ref: Thelen (2003).",
      ),
    eccentricForceMax: z
      .number()
      .min(1)
      .max(2)
      .default(1.4)
      .describe(
        "Maximum eccentric force as multiple of F_max (F_len). " +
        "Muscles can produce ~1.4–1.8× F_max eccentrically. " +
        "Ref: Katz (1939), Thelen (2003).",
      ),
    eccentricCurveShape: z
      .number()
      .positive()
      .default(0.15)
      .describe("Shape factor for eccentric (lengthening) curve. Typical: 0.1–0.3."),
  }),

  // Passive elastic element parameters
  // f_PE(L̃) — exponential rise above optimal length
  passiveElement: z.object({
    strainAtMaxForce: z
      .number()
      .positive()
      .default(0.6)
      .describe(
        "Normalized strain at which passive force = F_max (ε_M). " +
        "f_PE(L̃) = (exp(k_PE × (L̃ - 1)/ε_M) - 1) / (exp(k_PE) - 1). " +
        "Typical: 0.5–0.7. Ref: Thelen (2003).",
      ),
    exponentialShape: z
      .number()
      .positive()
      .default(4.0)
      .describe("Shape of the passive force exponential (k_PE). Typical: 3–5."),
  }),

  // Tendon compliance (optional — rigid tendon is a common simplification)
  tendonCompliance: z
    .object({
      normalizedSlackLength: z
        .number()
        .positive()
        .describe("Tendon slack length / optimal fiber length (L_T_slack / L_opt). Typical: 0.5–10."),
      strainAtMaxIsometricForce: z
        .number()
        .positive()
        .default(0.033)
        .describe("Tendon strain at F_max. Typical: 0.033 (3.3%). Ref: Zajac (1989)."),
    })
    .optional()
    .describe("Tendon elasticity parameters. If absent, tendon is assumed rigid."),

  // Constraint: the envelope inequality
  constraint: z.object({
    equation: z
      .literal("F_muscle ≤ F_max × [a × f_L(L̃) × f_V(Ṽ) + f_PE(L̃)]")
      .describe("The Hill model constraint in symbolic form"),
    violationSeverity: ViolationSeverityEnum.default("error").describe(
      "Severity when a muscle force exceeds the achievable envelope",
    ),
    toleranceFraction: z
      .number()
      .min(0)
      .max(0.5)
      .default(0.1)
      .describe(
        "Fractional tolerance above the computed envelope before flagging a violation. " +
        "0.1 = allow 10% overshoot (accounts for parameter uncertainty).",
      ),
  }),

  // When does this model break down? (G3)
  validityBoundaries: z.array(ValidityBoundarySchema).min(1),

  extensions: ExtensionsSchema,
});

// =============================================================================
// Ligament Force-Strain Law
//
// Ligaments exhibit a nonlinear force-strain curve:
//   - Toe region (0 < ε < ε_toe): quadratic/exponential ramp-up
//   - Linear region (ε_toe < ε < ε_fail): approximately linear, slope = k
//   - Failure (ε > ε_fail): rupture
//
// Reference: Woo et al. (1999), Fig. 3.
// =============================================================================

export const LigamentForceStrainLawSchema = z.object({
  lawType: z.literal("ligament_force_strain"),
  id: z.string().uuid(),
  name: z.string().min(1),

  constrainedFields: z.object({
    ligamentForce: FieldRefSchema.describe("Path to LigamentousForce.magnitude"),
    strain: FieldRefSchema.describe("Path to LigamentousForce.strain"),
    stiffness: FieldRefSchema.describe("Path to LigamentousForce.stiffness or LigamentSchema.linearStiffness"),
    restingLength: FieldRefSchema.describe("Path to LigamentSchema.restingLength"),
    referenceStrain: FieldRefSchema.describe("Path to LigamentSchema.referenceStrain"),
  }),

  // Piecewise curve parameters
  toeRegion: z.object({
    maxStrain: z
      .number()
      .min(0)
      .max(0.1)
      .describe("Strain at transition from toe to linear region (ε_toe). Typical: 0.03–0.06."),
    curveExponent: z
      .number()
      .positive()
      .default(2.0)
      .describe("Exponent for the quadratic toe region: F = k_toe × ε^n. Typical: 2."),
  }),

  linearRegion: z.object({
    stiffness: z
      .number()
      .positive()
      .describe("Stiffness in the linear region in N/mm (slope of force-displacement). Varies widely by ligament."),
    interceptStrain: z
      .number()
      .min(0)
      .describe("Strain-axis intercept of the linear extrapolation (ε₀). F = k × (ε - ε₀) for ε > ε_toe."),
  }),

  failure: z.object({
    ultimateStrain: z
      .number()
      .positive()
      .describe("Strain at rupture (ε_fail). Typical: 0.10–0.15 for healthy ligament."),
    ultimateLoad: z
      .number()
      .positive()
      .describe("Force at rupture in N. Highly variable: ACL ~2,160 N young adult."),
    reference: z.string().optional().describe("Source for failure data"),
  }),

  constraint: z.object({
    equation: z
      .literal("F_lig = piecewise(ε ≤ 0: 0, ε ≤ ε_toe: k_toe×ε^n, ε ≤ ε_fail: k×(ε-ε₀), ε > ε_fail: FAILURE)")
      .describe("Piecewise force-strain relationship"),
    violationSeverity: ViolationSeverityEnum.default("error"),
    strainTolerance: z
      .number()
      .min(0)
      .default(0.005)
      .describe("Absolute strain tolerance for consistency checking"),
  }),

  validityBoundaries: z.array(ValidityBoundarySchema).min(1),

  extensions: ExtensionsSchema,
});

// =============================================================================
// Cartilage Stress-Strain Law
//
// Biphasic linear elastic model for articular cartilage.
// Assumes equilibrium (drained) conditions — valid for slow loading.
// σ = E × ε (Hooke's law) with aggregate modulus E (= H_A).
//
// Reference: Mow et al. (1980).
// =============================================================================

export const CartilageStressStrainLawSchema = z.object({
  lawType: z.literal("cartilage_stress_strain"),
  id: z.string().uuid(),
  name: z.string().min(1),

  constrainedFields: z.object({
    contactForce: FieldRefSchema.describe("Path to contact/joint reaction force on the cartilage surface"),
    contactArea: FieldRefSchema.describe("Path to CartilageSchema.surfaceArea or ContactSchema.contactArea"),
    youngsModulus: FieldRefSchema.describe("Path to CartilageSchema.youngsModulus"),
    thickness: FieldRefSchema.describe("Path to CartilageSchema.thickness"),
  }),

  // Material parameters (defaults from literature)
  parameters: z.object({
    aggregateModulus: z
      .number()
      .positive()
      .describe("Equilibrium aggregate modulus H_A in MPa. Healthy articular: 0.5–1.5 MPa."),
    poissonRatio: z
      .number()
      .min(0)
      .max(0.5)
      .describe("Poisson's ratio ν. Articular cartilage: 0.1–0.4."),
    maxContactPressure: z
      .number()
      .positive()
      .describe(
        "Maximum tolerable contact pressure in MPa before damage. " +
        "Articular cartilage: ~5–10 MPa static, ~15–25 MPa dynamic. " +
        "Ref: Torzilli et al., J Biomech 32(10):1063–1073, 1999.",
      ),
  }),

  constraint: z.object({
    equation: z
      .literal("σ = F / A ≤ σ_max AND ε = σ / H_A ≤ thickness")
      .describe("Contact stress must not exceed damage threshold; deformation must not exceed thickness"),
    violationSeverity: ViolationSeverityEnum.default("warning"),
    pressureTolerance: z
      .number()
      .positive()
      .default(0.5)
      .describe("Tolerance in MPa for pressure violation threshold"),
  }),

  validityBoundaries: z.array(ValidityBoundarySchema).min(1),

  extensions: ExtensionsSchema,
});

// =============================================================================
// Bone Yield Criterion (G3)
//
// The schema treats bones as rigid bodies. This law declares when that
// assumption is violated: when bone stress approaches or exceeds yield.
//
// Cortical bone: σ_yield ≈ 130 MPa (tension), 190 MPa (compression)
// Trabecular bone: σ_yield ≈ 2–5 MPa (compression)
//
// Reference: Reilly & Burstein, J Bone Joint Surg Am 56(5):1001–1022, 1974.
// =============================================================================

export const BoneYieldCriterionSchema = z.object({
  lawType: z.literal("bone_yield_criterion"),
  id: z.string().uuid(),
  name: z.string().min(1),

  constrainedFields: z.object({
    jointReactionForce: FieldRefSchema.describe("Path to JointReactionForce acting on this bone"),
    boneCrossSectionalArea: FieldRefSchema.optional().describe("Path to bone cross-section (if available) for stress estimation"),
  }),

  // Yield parameters
  parameters: z.object({
    corticalTensileYield: z
      .number()
      .positive()
      .default(130)
      .describe("Cortical bone tensile yield stress in MPa. Ref: Reilly & Burstein (1974)."),
    corticalCompressiveYield: z
      .number()
      .positive()
      .default(190)
      .describe("Cortical bone compressive yield stress in MPa."),
    trabecularCompressiveYield: z
      .number()
      .positive()
      .default(5)
      .describe("Trabecular bone compressive yield stress in MPa (highly variable: 2–12 MPa)."),
    fatigueReductionFactor: z
      .number()
      .min(0)
      .max(1)
      .default(0.6)
      .describe(
        "Reduction factor for cyclic loading fatigue. " +
        "Effective yield ≈ yield × factor for repetitive loading.",
      ),
  }),

  constraint: z.object({
    equation: z
      .literal("σ_bone = F / A ≤ σ_yield (rigid body assumption valid when σ_bone << σ_yield)")
      .describe("Bone stress must remain well below yield for rigid body dynamics to be valid"),
    violationSeverity: ViolationSeverityEnum.default("error"),
  }),

  validityBoundaries: z.array(ValidityBoundarySchema).min(1),

  extensions: ExtensionsSchema,
});

// =============================================================================
// Joint Range Limit (soft constraint)
//
// Joints near their ROM limits generate passive resistance torques.
// This is the rotational analogue of the ligament force-strain law.
// =============================================================================

export const JointRangeLimitSchema = z.object({
  lawType: z.literal("joint_range_limit"),
  id: z.string().uuid(),
  name: z.string().min(1),

  constrainedFields: z.object({
    jointAngle: FieldRefSchema.describe("Path to JointState.angles for the relevant DOF"),
    jointLimit: FieldRefSchema.describe("Path to JointSchema.limits for this DOF"),
    passiveMoment: FieldRefSchema.optional().describe("Path to passive resistance moment (if modeled)"),
  }),

  // Exponential stiffness at ROM boundary
  parameters: z.object({
    bufferAngle: z
      .number()
      .positive()
      .default(5)
      .describe("Angle (degrees) before the hard limit where passive resistance begins. Typical: 3–10°."),
    exponentialStiffness: z
      .number()
      .positive()
      .default(1.0)
      .describe("Stiffness of the exponential barrier in N·cm/degree."),
  }),

  constraint: z.object({
    equation: z
      .literal("θ_min + buffer ≤ θ ≤ θ_max - buffer (passive resistance outside this range)")
      .describe("Joint angle should be within ROM limits; passive torque increases exponentially at boundaries"),
    violationSeverity: ViolationSeverityEnum.default("warning"),
  }),

  validityBoundaries: z.array(ValidityBoundarySchema).min(1),

  extensions: ExtensionsSchema,
});

// =============================================================================
// Constitutive Law — Discriminated Union
// =============================================================================

export const ConstitutiveLawSchema = z.discriminatedUnion("lawType", [
  HillMuscleLawSchema,
  LigamentForceStrainLawSchema,
  CartilageStressStrainLawSchema,
  BoneYieldCriterionSchema,
  JointRangeLimitSchema,
]);

// =============================================================================
// Constitutive Laws Collection
//
// The complete set of constitutive laws for a body model. Analogous to
// DerivationGraph but for inequality/envelope constraints rather than
// functional derivations.
//
// Design: ConstitutiveLaws + DerivationGraph together form C5 (Physical
// Consistency Validator) from the step-change contribution analysis.
// =============================================================================

export const ConstitutiveLawsSchema = z
  .object({
    version: z.literal(CONSTITUTIVE_LAWS_VERSION),
    laws: z.array(ConstitutiveLawSchema).min(1),
  })
  .superRefine((collection, ctx) => {
    // Validate unique IDs across all laws
    const ids = new Set<string>();
    collection.laws.forEach((law, i) => {
      if (ids.has(law.id)) {
        ctx.addIssue({
          code: z.ZodIssueCode.custom,
          message: `Duplicate constitutive law ID: ${law.id}`,
          path: ["laws", i, "id"],
        });
      }
      ids.add(law.id);
    });
  });

// =============================================================================
// Standard Validity Boundaries for the Rigid Body Model (G3)
//
// These are not schema entities — they are reference constants that
// consumers can use when instantiating constitutive laws. Provided
// here as documentation-in-code.
// =============================================================================

export const STANDARD_VALIDITY_BOUNDARIES = {
  rigidBody: {
    assumption: "Bones are rigid bodies",
    validWhen: "Bone stress << yield stress; strain rate < 0.01/s; no fracture or plastic deformation",
    violatedWhen: "Impact loading (strain rate > 1/s), stress approaching yield (~130 MPa cortical), pathological bone (osteoporosis)",
    consequence: "Rigid body dynamics underestimates deformation and energy absorption; joint forces may be overestimated",
    reference: "Reilly & Burstein, J Bone Joint Surg Am 56(5):1001–1022, 1974",
  },
  perfectConstraints: {
    assumption: "Joints are ideal kinematic constraints (no laxity, no deformation)",
    validWhen: "Joint loads within normal physiological range; intact ligaments; healthy cartilage",
    violatedWhen: "Ligament rupture, joint subluxation, large arthroplasty clearances, pathological laxity",
    consequence: "Joint kinematics deviate from the model; actual ROM may exceed modeled limits; contact mechanics are wrong",
    reference: "Woo et al., Am J Sports Med 27(4):533–543, 1999",
  },
  rigidSegments: {
    assumption: "Body segments are rigid (soft tissue wobble mass ignored)",
    validWhen: "Slow to moderate movements; low-impact activities (walking, cycling, lifting)",
    violatedWhen: "High-impact landing (> 3× body weight GRF), sprinting, explosive jumping — soft tissue deforms and oscillates",
    consequence: "Peak forces underestimated by 10–30%; inverse dynamics joint moments less accurate",
    reference: "Pain & Challis, J Appl Biomech 22(3):224–232, 2006",
  },
  quasiStatic: {
    assumption: "Loading is quasi-static (inertial effects negligible)",
    validWhen: "Movement duration >> natural period of the body segment; acceleration << g",
    violatedWhen: "Impact, vibration, rapid voluntary movements with segment accelerations > 2g",
    consequence: "Static equilibrium analysis gives wrong joint forces; must use full dynamic equations",
    reference: "Winter, 'Biomechanics and Motor Control of Human Movement', 4th ed. (2009), Ch. 4",
  },
} as const;

// =============================================================================
// Inferred Types
// =============================================================================

export type ViolationSeverity = z.infer<typeof ViolationSeverityEnum>;
export type ValidityBoundary = z.infer<typeof ValidityBoundarySchema>;
export type HillMuscleLaw = z.infer<typeof HillMuscleLawSchema>;
export type LigamentForceStrainLaw = z.infer<typeof LigamentForceStrainLawSchema>;
export type CartilageStressStrainLaw = z.infer<typeof CartilageStressStrainLawSchema>;
export type BoneYieldCriterion = z.infer<typeof BoneYieldCriterionSchema>;
export type JointRangeLimit = z.infer<typeof JointRangeLimitSchema>;
export type ConstitutiveLaw = z.infer<typeof ConstitutiveLawSchema>;
export type ConstitutiveLaws = z.infer<typeof ConstitutiveLawsSchema>;
