import { z } from "zod";
import {
  BoneId,
  JointId,
  MuscleId,
  SegmentId,
  PoseId,
  ForceId,
  MomentId,
  LoadingConditionId,
  ContactId,
  Vector3Schema,
  UnitVector3Schema,
  ExtensionsSchema,
} from "./shared";
import { LigamentId } from "./connective";

// =============================================================================
// Dynamics — Forces, Moments, Contacts, Loading Conditions
//
// This module models all forces and moments acting on the body. It is
// designed for inverse dynamics (given motion → compute forces) and
// forward dynamics (given forces → compute motion).
//
// Force/moment sign convention:
//   - Forces follow the global frame convention (+X anterior, +Y superior, +Z right)
//   - Joint moments are expressed about the joint coordinate system axes
//   - Positive moment = right-hand rule about the respective axis
//
// Reference: Winter, "Biomechanics and Motor Control of Human Movement",
//            4th ed. (2009), Chapters 4–5.
// =============================================================================

// --- Force Type Discriminator ---
// Forces are a discriminated union because different force types carry
// different metadata. Gravitational forces have no application point
// (they act on the CoM). Muscle forces act along a line of action.
// Contact forces have a surface area and friction. Lumping them into
// one schema with optional fields would lose type safety (Rule 8).

export const ForceTypeEnum = z.enum([
  "gravitational",       // Weight — acts on segment CoM
  "muscle",              // Active force generated by a muscle
  "ground_reaction",     // GRF — from force plate or foot-ground contact
  "joint_reaction",      // Resultant force at a joint (computed via inverse dynamics)
  "external_applied",    // Any external load (carried object, resistance band, etc.)
  "ligamentous",         // Passive force from a ligament resisting motion
  "inertial",            // Pseudo-force in non-inertial frames (d'Alembert)
  "contact",             // General contact (body-to-body, body-to-surface)
  "buoyancy",            // For aquatic biomechanics
  "aerodynamic_drag",    // Wind resistance / drag
]);

// --- Base Force Fields ---

const BaseForceFields = {
  id: ForceId,
  name: z.string().min(1),
  magnitude: z.number().nonnegative().describe("Force magnitude in Newtons (N)"),
  direction: UnitVector3Schema.describe("Force direction as unit vector in global frame"),
  // Convenience: vector = magnitude × direction. Not stored — computed.
  // Annotated per Rule 18.
};

// --- Gravitational Force ---

export const GravitationalForceSchema = z.object({
  ...BaseForceFields,
  forceType: z.literal("gravitational"),
  targetSegmentId: SegmentId.describe("Segment this gravitational force acts on (applied at its CoM)"),
  gravitationalAcceleration: z
    .number()
    .default(981)
    .describe("Gravitational acceleration in cm/s² (default: 981 cm/s² = 9.81 m/s²)"),
  extensions: ExtensionsSchema,
});

// --- Muscle Force ---
// Force generated by active contraction of a muscle. Includes both
// the active contractile component and the passive elastic component.

export const MuscleForceSchema = z.object({
  ...BaseForceFields,
  forceType: z.literal("muscle"),
  muscleId: MuscleId.describe("Muscle generating this force"),

  // Point of application along the line of action
  applicationPoint: Vector3Schema.describe(
    "Point where force is effectively applied in global frame (cm). " +
    "For pennate muscles, this is the effective insertion point along the tendon.",
  ),

  // Force decomposition
  activeComponent: z.number().nonnegative().describe("Active contractile force in N"),
  passiveComponent: z.number().nonnegative().default(0).describe("Passive elastic force in N"),

  // Muscle state at this instant
  activationLevel: z
    .number()
    .min(0)
    .max(1)
    .optional()
    .describe("Neural activation level (0 = fully relaxed, 1 = max voluntary contraction)"),
  currentLength: z
    .number()
    .positive()
    .optional()
    .describe("Current muscle-tendon unit length in cm"),
  contractionVelocity: z
    .number()
    .optional()
    .describe("Rate of change of muscle length in cm/s (negative = shortening)"),

  // Moment arm about the joint this muscle crosses
  momentArm: z
    .number()
    .optional()
    .describe(
      "Perpendicular distance from the joint center to the muscle's line of action (cm). " +
      "τ = F × momentArm gives the moment contribution.",
    ),
  crossedJointId: JointId.optional().describe("Joint this muscle force acts about"),

  extensions: ExtensionsSchema,
});

// --- Ground Reaction Force ---
// Force from the support surface. Standard in gait analysis.
// Reference: Kistler force plate documentation; Winter (2009), Ch. 4.

export const GroundReactionForceSchema = z.object({
  ...BaseForceFields,
  forceType: z.literal("ground_reaction"),

  // Center of pressure
  centerOfPressure: Vector3Schema.describe(
    "Point of application on the ground plane in global frame (cm). " +
    "COP = point where the resultant GRF acts with zero horizontal moment.",
  ),

  // GRF components — redundant with magnitude+direction but biomechanics
  // convention is to report these separately.
  vertical: z.number().describe("Vertical component in N (+Y = upward)"),
  anteroposterior: z.number().describe("A-P component in N (+X = anterior = braking is negative)"),
  mediolateral: z.number().describe("M-L component in N (+Z = right lateral)"),

  // Free moment about the vertical axis
  freeMoment: z.number().optional().describe("Vertical free moment (torque about Y axis) in N·cm"),

  // Which foot / contact area
  contactSide: z.enum(["left", "right", "bilateral"]).optional(),
  contactSegmentId: SegmentId.optional().describe("Foot/segment in contact with the ground"),

  extensions: ExtensionsSchema,
});

// --- Joint Reaction Force ---
// Resultant force at a joint, computed via inverse dynamics.
// This is the force the proximal segment exerts on the distal segment
// through the joint.

export const JointReactionForceSchema = z.object({
  ...BaseForceFields,
  forceType: z.literal("joint_reaction"),
  jointId: JointId.describe("Joint where this reaction force acts"),
  applicationPoint: Vector3Schema.describe("Joint center position in global frame (cm)"),

  // Components in the joint coordinate system (more useful clinically
  // than global components)
  componentsInJCS: z
    .object({
      compression: z.number().describe("Along the bone's longitudinal axis (N). Positive = compressive."),
      anteriorShear: z.number().describe("Anterior-posterior shear (N)"),
      medialShear: z.number().describe("Medial-lateral shear (N)"),
    })
    .optional()
    .describe("Force decomposed into the joint coordinate system"),

  extensions: ExtensionsSchema,
});

// --- External Applied Force ---
// Any user-defined external load: a carried object, a push/pull,
// resistance from equipment, etc.

export const ExternalForceSchema = z.object({
  ...BaseForceFields,
  forceType: z.literal("external_applied"),
  applicationPoint: Vector3Schema.describe("Point of application in global frame (cm)"),
  targetSegmentId: SegmentId.describe("Segment this force is applied to"),
  description: z.string().optional().describe("What this force represents (e.g. 'barbell load', 'wind gust')"),
  distributed: z
    .boolean()
    .default(false)
    .describe("Whether this is a distributed load (pressure) or a point force"),
  contactArea: z.number().positive().optional().describe("Contact area in cm² (if distributed)"),
  extensions: ExtensionsSchema,
});

// --- Ligamentous Force ---

export const LigamentousForceSchema = z.object({
  ...BaseForceFields,
  forceType: z.literal("ligamentous"),
  ligamentId: LigamentId.optional().describe("Reference to the Ligament entity (if connective tissue is modeled)"),
  ligamentName: z.string().min(1).describe("Anatomical name (e.g. 'anterior cruciate ligament')"),
  jointId: JointId.describe("Joint this ligament stabilizes"),
  applicationPoint: Vector3Schema.describe("Effective point of application in global frame (cm)"),
  strain: z.number().min(0).optional().describe("Current strain (ΔL/L₀, dimensionless). Ligaments typically fail at 0.06–0.15."),
  stiffness: z.number().positive().optional().describe("Linear stiffness in N/cm (slope of force-displacement curve)"),
  extensions: ExtensionsSchema,
});

// --- Inertial (d'Alembert) Force ---

export const InertialForceSchema = z.object({
  ...BaseForceFields,
  forceType: z.literal("inertial"),
  targetSegmentId: SegmentId.describe("Segment experiencing this pseudo-force"),
  segmentAcceleration: Vector3Schema.describe("Linear acceleration of the segment CoM (cm/s²)"),
  extensions: ExtensionsSchema,
});

// --- Contact Force (generic) ---

export const ContactForceSchema = z.object({
  ...BaseForceFields,
  forceType: z.literal("contact"),
  contactId: ContactId.describe("Reference to the contact entity"),
  applicationPoint: Vector3Schema.describe("Point of contact in global frame (cm)"),
  normalForce: z.number().nonnegative().describe("Normal component at the contact surface (N)"),
  frictionForce: z.number().nonnegative().optional().describe("Tangential friction force (N)"),
  staticFrictionCoeff: z.number().min(0).optional().describe("μₛ (dimensionless)"),
  kineticFrictionCoeff: z.number().min(0).optional().describe("μₖ (dimensionless)"),
  targetSegmentId: SegmentId.describe("Segment in contact"),
  extensions: ExtensionsSchema,
});

// --- Aerodynamic Drag ---

export const AerodynamicDragSchema = z.object({
  ...BaseForceFields,
  forceType: z.literal("aerodynamic_drag"),
  targetSegmentId: SegmentId.describe("Segment experiencing drag"),
  dragCoefficient: z.number().positive().describe("Cd (dimensionless)"),
  frontalArea: z.number().positive().describe("Cross-sectional area facing the flow (cm²)"),
  fluidDensity: z.number().positive().default(0.001225).describe("Fluid density in g/cm³ (air ≈ 0.001225 g/cm³)"),
  relativeVelocity: Vector3Schema.describe("Velocity of segment relative to fluid (cm/s)"),
  extensions: ExtensionsSchema,
});

// --- Buoyancy Force ---

export const BuoyancyForceSchema = z.object({
  ...BaseForceFields,
  forceType: z.literal("buoyancy"),
  targetSegmentId: SegmentId.describe("Segment experiencing buoyancy"),
  displacedVolume: z.number().positive().describe("Volume of fluid displaced by the segment (cm³)"),
  fluidDensity: z.number().positive().describe("Density of the fluid in g/cm³ (water ≈ 1.0)"),
  centerOfBuoyancy: Vector3Schema.describe("Centroid of displaced volume in global frame (cm)"),
  extensions: ExtensionsSchema,
});

// --- Force Union (discriminated on forceType) ---

export const ForceSchema = z.discriminatedUnion("forceType", [
  GravitationalForceSchema,
  MuscleForceSchema,
  GroundReactionForceSchema,
  JointReactionForceSchema,
  ExternalForceSchema,
  LigamentousForceSchema,
  InertialForceSchema,
  ContactForceSchema,
  AerodynamicDragSchema,
  BuoyancyForceSchema,
]);

// =============================================================================
// Moments / Torques
// =============================================================================

export const MomentTypeEnum = z.enum([
  "joint_resultant",      // Net moment at a joint (from inverse dynamics)
  "muscle_contribution",  // Moment produced by a single muscle about a joint
  "external",             // Moment from an external force about a point
  "gravitational",        // Moment of gravitational force about a joint
  "inertial",             // Moment of inertial pseudo-force
]);

export const MomentSchema = z.object({
  id: MomentId,
  name: z.string().min(1),
  momentType: MomentTypeEnum,

  // Where the moment acts
  aboutJointId: JointId.optional().describe("Joint this moment acts about (if applicable)"),
  aboutPoint: Vector3Schema.optional().describe("Arbitrary point this moment is computed about (cm, global frame)"),

  // Moment vector (axis × magnitude, right-hand rule)
  axis: UnitVector3Schema.describe("Axis of rotation (unit vector in global frame)"),
  magnitude: z.number().describe("Moment magnitude in N·cm (positive = right-hand rule about axis)"),

  // Components in the joint coordinate system
  componentsInJCS: z
    .object({
      flexionExtension: z.number().describe("Moment about the flexion/extension axis (N·cm)"),
      abductionAdduction: z.number().describe("Moment about the ab/adduction axis (N·cm)"),
      internalExternalRotation: z.number().describe("Moment about the rotation axis (N·cm)"),
    })
    .optional()
    .describe("Moment decomposed into JCS axes (standard clinical reporting)"),

  // Source attribution
  sourceForceId: ForceId.optional().describe("Force that produced this moment (if single-source)"),
  sourceMuscleId: MuscleId.optional().describe("Muscle producing this moment (if muscle_contribution)"),

  extensions: ExtensionsSchema,
});

// =============================================================================
// Contact Definition
// =============================================================================

export const ContactTypeEnum = z.enum([
  "foot_ground",         // Standing, walking, running
  "hand_object",         // Grasping, pushing
  "body_surface",        // Sitting, leaning
  "body_body",           // Self-contact or person-to-person
  "body_fluid",          // Swimming, diving
  "body_equipment",      // Sports equipment, tools, assistive devices
]);

export const ContactSchema = z.object({
  id: ContactId,
  name: z.string().min(1),
  contactType: ContactTypeEnum,

  // Participating entities
  segmentId: SegmentId.describe("Body segment involved in the contact"),
  surfaceNormal: UnitVector3Schema.describe("Surface normal at the contact point (pointing away from the contact surface)"),
  contactPoint: Vector3Schema.describe("Contact location in global frame (cm)"),
  contactArea: z.number().positive().optional().describe("Contact area in cm²"),

  // Surface properties
  staticFrictionCoeff: z.number().min(0).optional().describe("μₛ (dimensionless)"),
  kineticFrictionCoeff: z.number().min(0).optional().describe("μₖ (dimensionless)"),
  coefficientOfRestitution: z
    .number()
    .min(0)
    .max(1)
    .optional()
    .describe("e (dimensionless). 1 = perfectly elastic, 0 = perfectly inelastic."),

  // State
  isActive: z.boolean().default(true).describe("Whether this contact is currently engaged"),

  extensions: ExtensionsSchema,
});

// =============================================================================
// Loading Condition
//
// A complete force/moment state at one instant, paired with a pose.
// This is the primary entity for biomechanical analysis: "given this
// body configuration, here are all forces and moments acting on it."
// =============================================================================

export const LoadingConditionSchema = z.object({
  id: LoadingConditionId,
  name: z.string().min(1).describe("Descriptive label (e.g. 'mid_stance_gait', 'max_squat_depth')"),

  // The pose this loading applies to
  poseId: PoseId.describe("Pose (body configuration) at this instant"),

  // All forces acting on the body
  forces: z.array(ForceSchema).describe("All forces acting on the body at this instant"),

  // All moments acting on the body
  moments: z.array(MomentSchema).optional().describe("All moments (may be computed from forces)"),

  // Active contacts
  contacts: z.array(ContactSchema).optional().describe("Active contacts at this instant"),

  // Whole-body equilibrium check (computed)
  equilibrium: z
    .object({
      netForce: Vector3Schema.describe("[Computed] Resultant of all forces (N). Zero = static equilibrium."),
      netMoment: Vector3Schema.describe("[Computed] Resultant moment about the whole-body CoM (N·cm)."),
      isStatic: z.boolean().describe("[Computed] True if |netForce| < tolerance AND |netMoment| < tolerance"),
      residualForceMagnitude: z.number().nonnegative().describe("[Computed] |ΣF| in N"),
      residualMomentMagnitude: z.number().nonnegative().describe("[Computed] |ΣM| in N·cm"),
    })
    .optional()
    .describe("[Computed] Equilibrium check — residuals should be near zero for valid solutions"),

  extensions: ExtensionsSchema,
});

// =============================================================================
// Free Body Diagram (per segment)
//
// All forces and moments acting on a single segment, isolated from
// the rest of the body. This is the fundamental analysis unit in
// inverse dynamics: apply Newton-Euler equations to each segment's
// FBD to solve for unknown joint forces and moments.
// =============================================================================

export const FreeBodyDiagramSchema = z.object({
  segmentId: SegmentId.describe("The isolated segment"),
  loadingConditionId: LoadingConditionId.describe("Parent loading condition"),

  // Forces on this segment (subset of the loading condition's forces)
  forces: z.array(ForceSchema).min(1).describe("All forces acting on this segment"),
  moments: z.array(MomentSchema).optional().describe("All moments acting on this segment"),

  // Newton-Euler equation residuals (computed — Rule 18)
  translationalResidual: Vector3Schema
    .optional()
    .describe("[Computed] ΣF - ma (should be zero vector for a valid solution)"),
  rotationalResidual: Vector3Schema
    .optional()
    .describe("[Computed] ΣM - Iα (should be zero vector for a valid solution)"),

  extensions: ExtensionsSchema,
});

// --- Inferred Types ---

export type Force = z.infer<typeof ForceSchema>;
export type GravitationalForce = z.infer<typeof GravitationalForceSchema>;
export type MuscleForce = z.infer<typeof MuscleForceSchema>;
export type GroundReactionForce = z.infer<typeof GroundReactionForceSchema>;
export type JointReactionForce = z.infer<typeof JointReactionForceSchema>;
export type ExternalForce = z.infer<typeof ExternalForceSchema>;
export type LigamentousForce = z.infer<typeof LigamentousForceSchema>;
export type InertialForce = z.infer<typeof InertialForceSchema>;
export type ContactForce = z.infer<typeof ContactForceSchema>;
export type AerodynamicDrag = z.infer<typeof AerodynamicDragSchema>;
export type BuoyancyForce = z.infer<typeof BuoyancyForceSchema>;
export type Moment = z.infer<typeof MomentSchema>;
export type Contact = z.infer<typeof ContactSchema>;
export type LoadingCondition = z.infer<typeof LoadingConditionSchema>;
export type FreeBodyDiagram = z.infer<typeof FreeBodyDiagramSchema>;
