/**
 * generate-json-schema.ts — Export the Zod v3 HumanBody schema as JSON Schema (draft 2020-12).
 *
 * Usage:  npx tsx src/generate-json-schema.ts > active/human-body-v3.raw.schema.json
 *
 * Generated by: Claude Opus 4.6 (1M context)
 */

import { zodToJsonSchema } from "zod-to-json-schema";
import { HumanBodySchema } from "./body.js";

const jsonSchema = zodToJsonSchema(HumanBodySchema, {
  name: "HumanBody",
  $refStrategy: "root",           // place shared types in definitions
  target: "jsonSchema2019-09",    // closest to draft 2020-12
});

const enriched = {
  $schema: "https://json-schema.org/draft/2020-12/schema",
  $id: "https://example.org/schemas/human-body-v3.schema.json",
  title: "Human Body Schema",
  description:
    "Comprehensive anatomical data schema for human body modeling. " +
    "Generated from Zod v3 TypeScript source (session-3/schemas/src). Schema version 3.0.0.",
  ...jsonSchema,
};

// Remove the $schema that zod-to-json-schema may inject
delete (enriched as any).$ref;

console.log(JSON.stringify(enriched, null, 2));
