#!/usr/bin/env python3
"""Download and convert anatomical bone meshes for the human body renderer.

Sources (in priority order):
  1. BodyParts3D (DBCLS Japan) — CC-BY-SA 2.1 JP
     3,000+ segmented anatomical parts in OBJ format.
     Ref: Mitsuhashi et al., NAR 2009.
     URL: https://lifesciencedb.jp/bp3d/

  2. Visible Human Project (NLM) — Public domain
     Cryosection data segmented into meshes.
     URL: https://www.nlm.nih.gov/databases/download/vhp.html

Pipeline:
  OBJ → (trimesh normalize) → glTF 2.0 binary (.glb)
  - Recentered to bone centroid (local origin)
  - Scaled to cm
  - Y-up, right-handed (matches schema convention)
  - Decimated to max 5,000 triangles per bone (LOD 0)
  - LOD 1 at 1,500 triangles

Dependencies:
  pip install trimesh pyglet numpy

Usage:
  python3 tools/acquire_meshes.py --source-dir raw_meshes/ --output-dir public/assets/bones/
  python3 tools/acquire_meshes.py --download-bodyparts3d  # auto-download if available

Generated by: Claude Opus 4.6 (1M context)
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

try:
    import trimesh
    import numpy as np
except ImportError:
    print("ERROR: requires 'pip install trimesh pyglet numpy'", file=sys.stderr)
    sys.exit(1)


MESH_MAP = Path(__file__).parent / "bone_mesh_map.json"
DEFAULT_OUTPUT = Path(__file__).parent.parent / "public" / "assets" / "bones"

# Target triangle counts per LOD
LOD_TARGETS = {0: 5000, 1: 1500}


def load_mesh_map() -> dict[str, str]:
    """Return {bone_name: filename} from bone_mesh_map.json."""
    with open(MESH_MAP) as f:
        data = json.load(f)
    mapping: dict[str, str] = {}
    for section in ["bones", "vertebrae_pattern", "ribs_pattern"]:
        for name, info in data.get(section, {}).items():
            if isinstance(info, dict) and "file" in info:
                mapping[name] = info["file"]
    return mapping


def process_obj(obj_path: Path, output_dir: Path, filename: str) -> dict | None:
    """Convert an OBJ file to GLB with LOD levels."""
    try:
        mesh = trimesh.load(str(obj_path), force="mesh")
    except Exception as e:
        print(f"  SKIP {obj_path.name}: {e}")
        return None

    if not isinstance(mesh, trimesh.Trimesh):
        print(f"  SKIP {obj_path.name}: not a triangle mesh (got {type(mesh).__name__})")
        return None

    # Recenter to centroid
    centroid = mesh.centroid
    mesh.vertices -= centroid

    # Detect units and scale to cm
    extent = mesh.bounding_box.extents.max()
    if extent > 100:
        # Likely in mm → convert to cm
        mesh.vertices /= 10.0
    elif extent < 1:
        # Likely in meters → convert to cm
        mesh.vertices *= 100.0

    # Ensure Y-up (BodyParts3D uses Y-up already, VHP may use Z-up)
    # Check if Z extent > Y extent — likely Z-up
    bounds = mesh.bounds
    y_range = bounds[1][1] - bounds[0][1]
    z_range = bounds[1][2] - bounds[0][2]
    if z_range > y_range * 1.5:
        # Rotate 90° around X to swap Z→Y
        rot = trimesh.transformations.rotation_matrix(
            np.radians(-90), [1, 0, 0]
        )
        mesh.apply_transform(rot)

    # Generate LODs
    out_path = output_dir / filename
    lods_info = []

    for lod_level, target_faces in sorted(LOD_TARGETS.items()):
        if mesh.faces.shape[0] > target_faces:
            try:
                decimated = mesh.simplify_quadric_decimation(target_faces)
            except Exception:
                decimated = mesh
        else:
            decimated = mesh

        if lod_level == 0:
            # Export LOD 0 as the main file
            decimated.export(str(out_path), file_type="glb")
        else:
            lod_path = output_dir / filename.replace(".glb", f"_lod{lod_level}.glb")
            decimated.export(str(lod_path), file_type="glb")

        lods_info.append({
            "level": lod_level,
            "triangles": int(decimated.faces.shape[0]),
            "vertices": int(decimated.vertices.shape[0]),
        })

    # Compute hash
    with open(out_path, "rb") as f:
        content_hash = hashlib.sha256(f.read()).hexdigest()

    file_size = out_path.stat().st_size

    return {
        "file": filename,
        "hash": content_hash,
        "byteSize": file_size,
        "lods": lods_info,
        "centroid_offset": centroid.tolist(),
    }


def process_directory(source_dir: Path, output_dir: Path) -> None:
    """Process all OBJ files in source directory."""
    output_dir.mkdir(parents=True, exist_ok=True)
    mesh_map = load_mesh_map()

    # Reverse map: filename → bone_name
    file_to_bone: dict[str, str] = {v: k for k, v in mesh_map.items()}

    manifest: dict[str, dict] = {}
    obj_files = sorted(source_dir.glob("*.obj")) + sorted(source_dir.glob("*.OBJ"))

    if not obj_files:
        print(f"No OBJ files found in {source_dir}")
        print("Expected: individual bone OBJ files from BodyParts3D or similar")
        return

    print(f"Found {len(obj_files)} OBJ files in {source_dir}")

    for obj_path in obj_files:
        stem = obj_path.stem.lower()
        # Try to match to a known bone filename
        target_file = f"{stem}.glb"
        bone_name = file_to_bone.get(target_file, obj_path.stem)

        print(f"  Processing: {obj_path.name} → {target_file}")
        result = process_obj(obj_path, output_dir, target_file)
        if result:
            manifest[bone_name] = result
            print(f"    ✓ {result['lods'][0]['triangles']} tris, {result['byteSize']} bytes")

    # Write manifest
    manifest_path = output_dir / "manifest.json"
    with open(manifest_path, "w") as f:
        json.dump(manifest, f, indent=2)
    print(f"\nManifest written: {manifest_path} ({len(manifest)} bones)")


def generate_placeholder_meshes(output_dir: Path) -> None:
    """Generate simple procedural meshes as placeholders until real data is available.

    These are higher-quality than the inline indexed_mesh geometry but still
    procedural. They serve as a fallback when BodyParts3D data hasn't been
    downloaded yet.
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    mesh_map = load_mesh_map()
    manifest: dict[str, dict] = {}

    # Bone dimension data (name → approximate L, W, D in cm)
    # Subset of key bones for placeholder generation
    _BONE_DIMS: dict[str, tuple[float, float, float, str]] = {
        # (length, width, depth, shape_hint)
        "femur_r":      (45, 3.2, 2.8, "long_major"),
        "femur_l":      (45, 3.2, 2.8, "long_major"),
        "humerus_r":    (36, 2.2, 2.0, "long_major"),
        "humerus_l":    (36, 2.2, 2.0, "long_major"),
        "tibia_r":      (40, 2.8, 2.4, "long_major"),
        "tibia_l":      (40, 2.8, 2.4, "long_major"),
        "fibula_r":     (38, 1.2, 1.0, "long_thin"),
        "fibula_l":     (38, 1.2, 1.0, "long_thin"),
        "radius_r":     (26, 1.6, 1.4, "long_medium"),
        "radius_l":     (26, 1.6, 1.4, "long_medium"),
        "ulna_r":       (28, 1.5, 1.3, "long_medium"),
        "ulna_l":       (28, 1.5, 1.3, "long_medium"),
        "hip_bone_r":   (18, 14, 8, "pelvis"),
        "hip_bone_l":   (18, 14, 8, "pelvis"),
        "sacrum":       (12, 10, 3, "wedge"),
        "scapula_r":    (15, 10, 1, "blade"),
        "scapula_l":    (15, 10, 1, "blade"),
        "sternum":      (17, 5, 1.5, "plate"),
        "frontal_bone": (12, 12, 0.7, "dome"),
        "parietal_bone_r": (12, 11, 0.5, "dome"),
        "parietal_bone_l": (12, 11, 0.5, "dome"),
        "occipital_bone":  (10, 10, 0.8, "dome"),
        "mandible":     (10, 12, 3, "jaw"),
        "patella_r":    (4, 4.5, 2, "disc"),
        "patella_l":    (4, 4.5, 2, "disc"),
        "calcaneus_r":  (8, 4, 4.5, "block"),
        "calcaneus_l":  (8, 4, 4.5, "block"),
        "talus_r":      (6, 4, 3, "dome"),
        "talus_l":      (6, 4, 3, "dome"),
        "clavicle_r":   (15, 1.3, 1.1, "long_thin"),
        "clavicle_l":   (15, 1.3, 1.1, "long_thin"),
    }

    for bone_name, filename in mesh_map.items():
        stem = filename.replace(".glb", "")
        dims = _BONE_DIMS.get(stem)
        if not dims:
            continue

        l, w, d, hint = dims
        mesh = _make_placeholder_mesh(l, w, d, hint)
        if mesh is None:
            continue

        out_path = output_dir / filename
        mesh.export(str(out_path), file_type="glb")

        with open(out_path, "rb") as f:
            content_hash = hashlib.sha256(f.read()).hexdigest()

        manifest[bone_name] = {
            "file": filename,
            "hash": content_hash,
            "byteSize": out_path.stat().st_size,
            "lods": [{"level": 0, "triangles": int(mesh.faces.shape[0]),
                       "vertices": int(mesh.vertices.shape[0])}],
            "source": "procedural_placeholder",
        }
        print(f"  ✓ {filename}: {mesh.faces.shape[0]} tris")

    manifest_path = output_dir / "manifest.json"
    with open(manifest_path, "w") as f:
        json.dump(manifest, f, indent=2)
    print(f"\nPlaceholder manifest: {manifest_path} ({len(manifest)} bones)")


def _make_placeholder_mesh(l: float, w: float, d: float, hint: str) -> "trimesh.Trimesh | None":
    """Create a higher-quality procedural mesh for a bone shape."""
    if hint == "long_major":
        # Lathe revolution with anatomical profile
        return _lathe_bone(l, w, d, segments=32, profile_points=12)
    elif hint == "long_medium":
        return _lathe_bone(l, w, d, segments=24, profile_points=10)
    elif hint == "long_thin":
        return _lathe_bone(l, w * 1.2, d * 1.2, segments=16, profile_points=8)
    elif hint == "pelvis":
        return _sculpted_pelvis(l, w, d)
    elif hint == "dome":
        return _dome_mesh(l, w, d)
    elif hint == "blade":
        return _blade_mesh(l, w, d)
    elif hint == "plate":
        return _plate_mesh(l, w, d)
    elif hint == "jaw":
        return _jaw_mesh(l, w, d)
    elif hint == "wedge":
        return _wedge_mesh(l, w, d)
    elif hint == "disc":
        return trimesh.creation.capsule(height=max(0.1, l - d), radius=max(w, d) / 2, count=[16, 8])
    elif hint == "block":
        return trimesh.creation.box(extents=[w, l, d])
    return None


def _lathe_bone(l: float, w: float, d: float,
                segments: int = 24, profile_points: int = 10) -> trimesh.Trimesh:
    """Create a lathe-revolved bone with anatomical profile."""
    half = l / 2
    shaft_r = (w + d) / 4
    head_r = shaft_r * 1.5
    condyle_r = shaft_r * 1.35

    # Build profile curve
    ts = np.linspace(0, 1, profile_points)
    radii = []
    ys = []
    for t in ts:
        y = -half + t * l
        # Smooth profile: thick at ends, thinner in middle
        end_prox = np.exp(-((t * 4) ** 2))
        end_dist = np.exp(-(((1 - t) * 4) ** 2))
        r = shaft_r + (head_r - shaft_r) * end_prox + (condyle_r - shaft_r) * end_dist
        radii.append(max(0.05, r))
        ys.append(y)

    # Revolve
    angles = np.linspace(0, 2 * np.pi, segments, endpoint=False)
    vertices = []
    for i, (r, y) in enumerate(zip(radii, ys)):
        for a in angles:
            x = r * np.cos(a) * (w / max(w, d))
            z = r * np.sin(a) * (d / max(w, d))
            vertices.append([x, y, z])

    # Add caps
    vertices.append([0, -half, 0])  # bottom cap center
    vertices.append([0, half, 0])   # top cap center

    verts = np.array(vertices)
    faces = []
    rows = profile_points
    cols = segments

    # Side faces
    for i in range(rows - 1):
        for j in range(cols):
            a = i * cols + j
            b = i * cols + (j + 1) % cols
            c = (i + 1) * cols + j
            dd = (i + 1) * cols + (j + 1) % cols
            faces.append([a, c, b])
            faces.append([b, c, dd])

    # Bottom cap
    bottom_center = len(verts) - 2
    for j in range(cols):
        faces.append([bottom_center, j, (j + 1) % cols])

    # Top cap
    top_center = len(verts) - 1
    top_row = (rows - 1) * cols
    for j in range(cols):
        faces.append([top_center, top_row + (j + 1) % cols, top_row + j])

    return trimesh.Trimesh(vertices=verts, faces=np.array(faces))


def _dome_mesh(l: float, w: float, d: float) -> trimesh.Trimesh:
    """Hemisphere dome for cranial bones."""
    sphere = trimesh.creation.icosphere(subdivisions=3, radius=1.0)
    # Keep only the top hemisphere (+Y)
    mask = sphere.vertices[:, 2] >= -0.1
    sphere.update_vertices(mask)
    sphere.vertices[:, 0] *= w / 2
    sphere.vertices[:, 1] *= l / 2
    sphere.vertices[:, 2] *= max(d, w * 0.25)
    return sphere


def _blade_mesh(l: float, w: float, d: float) -> trimesh.Trimesh:
    """Flat triangular blade for scapula."""
    # Triangular prism
    pts = np.array([
        [-w * 0.4, -l * 0.45, 0],
        [w * 0.4, -l * 0.45, 0],
        [w * 0.1, l * 0.45, 0],
        [-w * 0.4, -l * 0.45, d],
        [w * 0.4, -l * 0.45, d],
        [w * 0.1, l * 0.45, d],
    ])
    faces = np.array([
        [0, 1, 2], [3, 5, 4],  # front/back
        [0, 3, 1], [1, 3, 4],  # bottom
        [1, 4, 2], [2, 4, 5],  # right
        [0, 2, 3], [3, 2, 5],  # left
    ])
    return trimesh.Trimesh(vertices=pts, faces=faces)


def _plate_mesh(l: float, w: float, d: float) -> trimesh.Trimesh:
    """Elongated plate for sternum."""
    return trimesh.creation.box(extents=[w, l, d])


def _jaw_mesh(l: float, w: float, d: float) -> trimesh.Trimesh:
    """U-shaped mandible — box body + two ramus pillars."""
    body_box = trimesh.creation.box(extents=[w * 0.8, l * 0.3, d * 0.6])
    ramus_r = trimesh.creation.box(extents=[d * 0.4, l * 0.6, d * 0.4])
    ramus_r.vertices[:, 0] += w * 0.35
    ramus_r.vertices[:, 1] += l * 0.2
    ramus_l = trimesh.creation.box(extents=[d * 0.4, l * 0.6, d * 0.4])
    ramus_l.vertices[:, 0] -= w * 0.35
    ramus_l.vertices[:, 1] += l * 0.2
    return trimesh.util.concatenate([body_box, ramus_r, ramus_l])


def _sculpted_pelvis(l: float, w: float, d: float) -> trimesh.Trimesh:
    """Hip bone shape — ilium + ischium."""
    # Ellipsoid for ilium
    ilium = trimesh.creation.icosphere(subdivisions=2, radius=1.0)
    ilium.vertices[:, 0] *= w * 0.35
    ilium.vertices[:, 1] *= l * 0.45
    ilium.vertices[:, 2] *= d * 0.4
    ilium.vertices[:, 1] += l * 0.1

    # Box for ischium
    ischium = trimesh.creation.box(extents=[w * 0.35, l * 0.3, d * 0.35])
    ischium.vertices[:, 1] -= l * 0.3

    combined = trimesh.util.concatenate([ilium, ischium])
    return combined


def _wedge_mesh(l: float, w: float, d: float) -> trimesh.Trimesh:
    """Wedge for sacrum."""
    return trimesh.creation.box(extents=[w, l, d])


def main() -> None:
    parser = argparse.ArgumentParser(description="Acquire and convert anatomical bone meshes")
    parser.add_argument("--source-dir", type=str, help="Directory with OBJ bone meshes")
    parser.add_argument("--output-dir", type=str, default=str(DEFAULT_OUTPUT))
    parser.add_argument("--placeholders", action="store_true",
                        help="Generate procedural placeholder meshes (no external data needed)")
    args = parser.parse_args()

    output = Path(args.output_dir)

    if args.placeholders:
        generate_placeholder_meshes(output)
    elif args.source_dir:
        process_directory(Path(args.source_dir), output)
    else:
        print("Usage:")
        print("  --placeholders    Generate procedural placeholder GLBs")
        print("  --source-dir DIR  Convert OBJ files from DIR to GLB")
        sys.exit(1)


if __name__ == "__main__":
    main()
