#!/usr/bin/env python3
"""Build a rigged humanoid mannequin GLB from a session-3 body JSON.

Reads a HumanBody v3.0.0 JSON (e.g. david.json), maps the anatomical
skeleton to a simplified humanoid rig, generates capsule/box segment
meshes skinned to the skeleton, and exports a single GLB file with
mesh + armature — ready for Three.js AnimationMixer.

Usage:
  python3 tools/build_mannequin_glb.py --body ../examples/david.json --output mannequin.glb
  python3 tools/build_mannequin_glb.py --body ../examples/david.json --output mannequin.glb --debug-skeleton

Generated by: Claude Opus 4.6 (1M context)
Schema: HumanBody v3.0.0
"""

from __future__ import annotations

import argparse
import json
import struct
import sys
from pathlib import Path
from typing import Any

import numpy as np

try:
    import pygltflib
    from pygltflib import GLTF2, Accessor, Asset, Buffer, BufferView, Mesh
    from pygltflib import Node, Primitive, Scene, Skin
    from pygltflib import (
        FLOAT, UNSIGNED_SHORT,
        SCALAR, VEC3, VEC4, MAT4,
        ELEMENT_ARRAY_BUFFER, ARRAY_BUFFER,
    )
except ImportError:
    print("ERROR: requires 'pip install pygltflib'", file=sys.stderr)
    sys.exit(1)

try:
    import trimesh
except ImportError:
    print("ERROR: requires 'pip install trimesh numpy'", file=sys.stderr)
    sys.exit(1)


# ---------------------------------------------------------------------------
# Humanoid rig definition — maps anatomical bones to simplified rig bones
# ---------------------------------------------------------------------------

# Each entry: (rig_bone_name, source_bone_name_in_json, parent_rig_bone_name | None)
# Order matters: parent must appear before child.
HUMANOID_RIG: list[tuple[str, str, str | None]] = [
    ("hips",          "Pelvis",        None),
    ("spine",         "L1 vertebra",   "hips"),
    ("chest",         "T6 vertebra",   "spine"),
    ("neck",          "C4 vertebra",   "chest"),
    ("head",          "Skull",         "neck"),
    ("clavicleL",     "Clavicle (L)",  "chest"),
    ("upperArmL",     "Humerus (L)",   "clavicleL"),
    ("lowerArmL",     "Radius (L)",    "upperArmL"),
    ("handL",         "Hand (L)",      "lowerArmL"),
    ("clavicleR",     "Clavicle (R)",  "chest"),
    ("upperArmR",     "Humerus (R)",   "clavicleR"),
    ("lowerArmR",     "Radius (R)",    "upperArmR"),
    ("handR",         "Hand (R)",      "lowerArmR"),
    ("upperLegL",     "Femur (L)",     "hips"),
    ("lowerLegL",     "Tibia (L)",     "upperLegL"),
    ("footL",         "Foot (L)",      "lowerLegL"),
    ("upperLegR",     "Femur (R)",     "hips"),
    ("lowerLegR",     "Tibia (R)",     "upperLegR"),
    ("footR",         "Foot (R)",      "lowerLegR"),
]


# Segment mesh definitions: which rig bone drives this segment,
# and what shape to use.  Dimensions come from the body JSON.
# (rig_bone, shape_type, scale_factors for length/width/depth)
SEGMENT_SHAPES: dict[str, str] = {
    "hips":          "box",
    "spine":         "capsule",
    "chest":         "box",
    "neck":          "capsule",
    "head":          "sphere",
    "clavicleL":     "capsule",
    "upperArmL":     "capsule",
    "lowerArmL":     "capsule",
    "handL":         "box",
    "clavicleR":     "capsule",
    "upperArmR":     "capsule",
    "lowerArmR":     "capsule",
    "handR":         "box",
    "upperLegL":     "capsule",
    "lowerLegL":     "capsule",
    "footL":         "box",
    "upperLegR":     "capsule",
    "lowerLegR":     "capsule",
    "footR":         "box",
}


def load_body(path: Path) -> dict[str, Any]:
    with open(path) as f:
        body = json.load(f)
    if body.get("schemaVersion") != "3.0.0":
        print(f"WARNING: expected schema v3.0.0, got {body.get('schemaVersion')}")
    return body


def _normalize_bone_name(name: str) -> str:
    """Normalize bone name for case/format-insensitive matching.

    Handles variations like 'Pelvis' vs 'pelvis', 'L1 vertebra' vs 'L1_vertebra',
    'Femur (R)' vs 'femur_r'.
    """
    s = name.lower().strip()
    s = s.replace("_", " ").replace("-", " ")
    # Normalize laterality: "(r)" / "right" → "r", "(l)" / "left" → "l"
    s = s.replace("(r)", "r").replace("(l)", "l")
    s = s.replace(" right", " r").replace(" left", " l")
    # Collapse whitespace
    return " ".join(s.split())


def build_bone_lookup(skeleton: list[dict]) -> dict[str, dict]:
    """Normalized-name → bone dict. Supports multiple naming conventions."""
    lookup: dict[str, dict] = {}
    for b in skeleton:
        lookup[_normalize_bone_name(b["name"])] = b
    return lookup


def _capsule_mesh(length: float, radius: float) -> trimesh.Trimesh:
    """Y-axis aligned capsule centered at origin."""
    h = max(0.01, length - 2 * radius)
    return trimesh.creation.capsule(height=h, radius=radius, count=[16, 8])


def _box_mesh(lx: float, ly: float, lz: float) -> trimesh.Trimesh:
    return trimesh.creation.box(extents=[lx, ly, lz])


def _sphere_mesh(radius: float) -> trimesh.Trimesh:
    return trimesh.creation.icosphere(subdivisions=2, radius=radius)


def compute_vertex_normals(vertices: np.ndarray, faces: np.ndarray) -> np.ndarray:
    """Compute per-vertex normals without SciPy/trimesh sparse helpers."""
    normals = np.zeros_like(vertices, dtype=np.float32)

    for face in faces:
        i0, i1, i2 = (int(face[0]), int(face[1]), int(face[2]))
        v0 = vertices[i0]
        v1 = vertices[i1]
        v2 = vertices[i2]
        face_normal = np.cross(v1 - v0, v2 - v0)
        length = np.linalg.norm(face_normal)

        if length > 1e-8:
          face_normal = face_normal / length
          normals[i0] += face_normal
          normals[i1] += face_normal
          normals[i2] += face_normal

    lengths = np.linalg.norm(normals, axis=1, keepdims=True)
    valid = lengths[:, 0] > 1e-8
    normals[valid] /= lengths[valid]
    normals[~valid] = np.array([0.0, 1.0, 0.0], dtype=np.float32)
    return normals.astype(np.float32)


def make_segment_mesh(
    shape: str, length: float, width: float, depth: float
) -> trimesh.Trimesh:
    """Create a segment mesh in local bone space (Y-up, centered at bone position)."""
    # Convert dimensions from schema (cm) — keep in cm for the GLB
    if shape == "capsule":
        radius = (width + depth) / 4.0
        return _capsule_mesh(length, radius)
    elif shape == "box":
        return _box_mesh(width, length, depth)
    elif shape == "sphere":
        radius = max(width, depth) / 2.0
        return _sphere_mesh(radius)
    else:
        return _box_mesh(width, length, depth)


def compute_rig(
    body: dict[str, Any],
) -> tuple[list[dict], list[np.ndarray], list[trimesh.Trimesh]]:
    """Build the simplified rig from the body JSON.

    Returns:
        rig_bones: list of {name, parent_index, world_pos, source_bone}
        inverse_bind_matrices: list of 4x4 numpy arrays
        segment_meshes: list of trimesh.Trimesh in world space
    """
    bone_lookup = build_bone_lookup(body["skeleton"])
    rig_bones: list[dict] = []
    name_to_index: dict[str, int] = {}

    for rig_name, source_name, parent_rig_name in HUMANOID_RIG:
        src = bone_lookup.get(_normalize_bone_name(source_name))
        if src is None:
            print(f"  WARNING: bone '{source_name}' not found in body, skipping '{rig_name}'")
            continue

        parent_idx = name_to_index.get(parent_rig_name, -1) if parent_rig_name else -1
        pos = src["transform"]["position"]
        world_pos = np.array([pos["x"], pos["y"], pos["z"]], dtype=np.float32)

        idx = len(rig_bones)
        name_to_index[rig_name] = idx
        rig_bones.append({
            "name": rig_name,
            "parent_index": parent_idx,
            "world_pos": world_pos,
            "source_bone": src,
        })

    # Compute inverse bind matrices (world → bone local)
    inverse_bind_matrices: list[np.ndarray] = []
    for rb in rig_bones:
        ibm = np.eye(4, dtype=np.float32)
        ibm[0, 3] = -rb["world_pos"][0]
        ibm[1, 3] = -rb["world_pos"][1]
        ibm[2, 3] = -rb["world_pos"][2]
        inverse_bind_matrices.append(ibm)

    # Generate segment meshes in world space
    segment_meshes: list[trimesh.Trimesh] = []
    for rb in rig_bones:
        src = rb["source_bone"]
        shape = SEGMENT_SHAPES.get(rb["name"], "capsule")
        depth = src.get("depth", src.get("width", src["length"] * 0.5))
        mesh = make_segment_mesh(shape, src["length"], src["width"], depth)
        # Translate to world position
        mesh.vertices += rb["world_pos"]
        segment_meshes.append(mesh)

    return rig_bones, inverse_bind_matrices, segment_meshes


def _pack_floats(data: np.ndarray) -> bytes:
    return data.astype(np.float32).tobytes()


def _pack_ushorts(data: np.ndarray) -> bytes:
    return data.astype(np.uint16).tobytes()


def build_glb(
    rig_bones: list[dict],
    inverse_bind_matrices: list[np.ndarray],
    segment_meshes: list[trimesh.Trimesh],
    body_name: str,
) -> GLTF2:
    """Assemble the glTF 2.0 structure with skinned mesh + skeleton."""

    # Merge all segment meshes into one, tracking which bone owns which vertex
    all_positions: list[np.ndarray] = []
    all_normals: list[np.ndarray] = []
    all_indices: list[np.ndarray] = []
    all_joints: list[np.ndarray] = []  # 4 joint indices per vertex
    all_weights: list[np.ndarray] = []  # 4 weights per vertex

    vertex_offset = 0
    for bone_idx, mesh in enumerate(segment_meshes):
        verts = np.asarray(mesh.vertices, dtype=np.float32)
        faces = np.asarray(mesh.faces, dtype=np.uint16)
        norms = compute_vertex_normals(verts, faces)

        n_verts = len(verts)
        all_positions.append(verts)
        all_normals.append(norms)
        all_indices.append(faces + vertex_offset)

        # Each vertex is 100% influenced by its owning bone
        joints = np.zeros((n_verts, 4), dtype=np.uint16)
        joints[:, 0] = bone_idx
        all_joints.append(joints)

        weights = np.zeros((n_verts, 4), dtype=np.float32)
        weights[:, 0] = 1.0
        all_weights.append(weights)

        vertex_offset += n_verts

    positions = np.vstack(all_positions).astype(np.float32)
    normals = np.vstack(all_normals).astype(np.float32)
    indices = np.vstack(all_indices).reshape(-1).astype(np.uint16)
    joints_arr = np.vstack(all_joints).astype(np.uint16)
    weights_arr = np.vstack(all_weights).astype(np.float32)
    ibm_arr = np.stack(inverse_bind_matrices).astype(np.float32)

    # Pack binary data
    pos_bytes = _pack_floats(positions)
    norm_bytes = _pack_floats(normals)
    idx_bytes = _pack_ushorts(indices)
    joint_bytes = _pack_ushorts(joints_arr)
    weight_bytes = _pack_floats(weights_arr)
    ibm_bytes = _pack_floats(ibm_arr)

    # Pad each to 4-byte alignment
    def pad4(b: bytes) -> bytes:
        r = len(b) % 4
        return b + b"\x00" * (4 - r) if r else b

    pos_bytes = pad4(pos_bytes)
    norm_bytes = pad4(norm_bytes)
    idx_bytes = pad4(idx_bytes)
    joint_bytes = pad4(joint_bytes)
    weight_bytes = pad4(weight_bytes)
    ibm_bytes = pad4(ibm_bytes)

    # Concatenate all into one buffer
    blob = pos_bytes + norm_bytes + idx_bytes + joint_bytes + weight_bytes + ibm_bytes

    # Offsets
    pos_offset = 0
    norm_offset = len(pos_bytes)
    idx_offset = norm_offset + len(norm_bytes)
    joint_offset = idx_offset + len(idx_bytes)
    weight_offset = joint_offset + len(joint_bytes)
    ibm_offset = weight_offset + len(weight_bytes)

    n_vertices = len(positions)
    n_indices = len(indices)
    n_bones = len(rig_bones)

    # Compute min/max for positions
    pos_min = positions.min(axis=0).tolist()
    pos_max = positions.max(axis=0).tolist()

    # Build glTF
    gltf = GLTF2()
    gltf.asset = Asset(version="2.0", generator=f"build_mannequin_glb / Claude Opus 4.6")

    # Buffer
    gltf.buffers = [Buffer(byteLength=len(blob))]

    # Buffer Views
    gltf.bufferViews = [
        BufferView(buffer=0, byteOffset=pos_offset, byteLength=len(pos_bytes),
                   target=ARRAY_BUFFER),                                          # 0: positions
        BufferView(buffer=0, byteOffset=norm_offset, byteLength=len(norm_bytes),
                   target=ARRAY_BUFFER),                                          # 1: normals
        BufferView(buffer=0, byteOffset=idx_offset, byteLength=len(idx_bytes),
                   target=ELEMENT_ARRAY_BUFFER),                                  # 2: indices
        BufferView(buffer=0, byteOffset=joint_offset, byteLength=len(joint_bytes),
                   target=ARRAY_BUFFER),                                          # 3: joints
        BufferView(buffer=0, byteOffset=weight_offset, byteLength=len(weight_bytes),
                   target=ARRAY_BUFFER),                                          # 4: weights
        BufferView(buffer=0, byteOffset=ibm_offset, byteLength=len(ibm_bytes)),   # 5: IBM
    ]

    # Accessors
    gltf.accessors = [
        # 0: POSITION
        Accessor(bufferView=0, byteOffset=0, componentType=FLOAT,
                 count=n_vertices, type=VEC3, max=pos_max, min=pos_min),
        # 1: NORMAL
        Accessor(bufferView=1, byteOffset=0, componentType=FLOAT,
                 count=n_vertices, type=VEC3),
        # 2: indices
        Accessor(bufferView=2, byteOffset=0, componentType=UNSIGNED_SHORT,
                 count=n_indices, type=SCALAR),
        # 3: JOINTS_0
        Accessor(bufferView=3, byteOffset=0, componentType=UNSIGNED_SHORT,
                 count=n_vertices, type=VEC4),
        # 4: WEIGHTS_0
        Accessor(bufferView=4, byteOffset=0, componentType=FLOAT,
                 count=n_vertices, type=VEC4),
        # 5: inverse bind matrices
        Accessor(bufferView=5, byteOffset=0, componentType=FLOAT,
                 count=n_bones, type=MAT4),
    ]

    # Nodes: one per rig bone + one mesh node
    # Bone nodes use local transforms (relative to parent)
    gltf.nodes = []
    bone_node_start = 0

    for i, rb in enumerate(rig_bones):
        parent_idx = rb["parent_index"]
        if parent_idx >= 0:
            parent_pos = rig_bones[parent_idx]["world_pos"]
            local_pos = rb["world_pos"] - parent_pos
        else:
            local_pos = rb["world_pos"].copy()

        node = Node(
            name=rb["name"],
            translation=[float(local_pos[0]), float(local_pos[1]), float(local_pos[2])],
        )
        gltf.nodes.append(node)

    # Set children on parent nodes
    for i, rb in enumerate(rig_bones):
        parent_idx = rb["parent_index"]
        if parent_idx >= 0:
            node_idx = bone_node_start + parent_idx
            if gltf.nodes[node_idx].children is None:
                gltf.nodes[node_idx].children = []
            gltf.nodes[node_idx].children.append(bone_node_start + i)

    # Mesh node (the skinned mesh)
    mesh_node_idx = len(gltf.nodes)
    gltf.nodes.append(Node(name=body_name, mesh=0, skin=0))

    # Mesh
    gltf.meshes = [
        Mesh(
            name=f"{body_name}_mannequin",
            primitives=[
                Primitive(
                    attributes=pygltflib.Attributes(
                        POSITION=0,
                        NORMAL=1,
                        JOINTS_0=3,
                        WEIGHTS_0=4,
                    ),
                    indices=2,
                )
            ],
        )
    ]

    # Skin
    joint_indices = list(range(bone_node_start, bone_node_start + n_bones))
    skeleton_root = bone_node_start  # hips
    gltf.skins = [
        Skin(
            name=f"{body_name}_rig",
            joints=joint_indices,
            skeleton=skeleton_root,
            inverseBindMatrices=5,
        )
    ]

    # Scene
    # Root nodes: skeleton root + mesh node
    root_bone_indices = [
        bone_node_start + i for i, rb in enumerate(rig_bones)
        if rb["parent_index"] < 0
    ]
    gltf.scenes = [Scene(name="Scene", nodes=root_bone_indices + [mesh_node_idx])]
    gltf.scene = 0

    # Set binary blob
    gltf.set_binary_blob(blob)

    return gltf


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Build a rigged humanoid mannequin GLB from a session-3 body JSON"
    )
    parser.add_argument("--body", required=True, type=str,
                        help="Path to a HumanBody v3.0.0 JSON (e.g. ../examples/david.json)")
    parser.add_argument("--output", required=True, type=str,
                        help="Output GLB file path")
    parser.add_argument("--debug-skeleton", action="store_true",
                        help="Print rig bone hierarchy to stdout")
    args = parser.parse_args()

    body_path = Path(args.body)
    output_path = Path(args.output)

    print(f"Loading body: {body_path}")
    body = load_body(body_path)
    body_name = body.get("name", "Mannequin")
    print(f"  Name: {body_name}")
    print(f"  Bones in JSON: {len(body.get('skeleton', []))}")

    print("Building humanoid rig...")
    rig_bones, ibms, meshes = compute_rig(body)
    print(f"  Rig bones: {len(rig_bones)}")

    if args.debug_skeleton:
        print("\n  Humanoid rig hierarchy:")
        for i, rb in enumerate(rig_bones):
            parent = rig_bones[rb["parent_index"]]["name"] if rb["parent_index"] >= 0 else "ROOT"
            pos = rb["world_pos"]
            print(f"    [{i:2d}] {rb['name']:20s} ← {parent:20s}  pos=({pos[0]:6.1f}, {pos[1]:6.1f}, {pos[2]:6.1f})")
        print()

    total_verts = sum(len(m.vertices) for m in meshes)
    total_tris = sum(len(m.faces) for m in meshes)
    print(f"  Segment meshes: {total_verts} vertices, {total_tris} triangles")

    print("Assembling GLB...")
    gltf = build_glb(rig_bones, ibms, meshes, body_name)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    gltf.save(str(output_path))
    size_kb = output_path.stat().st_size / 1024
    print(f"\n✓ Mannequin GLB written: {output_path} ({size_kb:.1f} KB)")
    print(f"  {len(rig_bones)} bones, {total_verts} vertices, {total_tris} triangles")
    print(f"  Ready for Three.js GLTFLoader + AnimationMixer")


if __name__ == "__main__":
    main()
