#!/usr/bin/env python3
"""Generate multiple valid HumanBody JSON instances conforming to the
session-3/schemas/src/ TypeScript (Zod) schema v3.0.0.

Full 206-bone adult human skeleton with:
  - 22 cranial/facial bones, hyoid, 6 ear ossicles
  - 26 vertebrae (C1–C7, T1–T12, L1–L5, sacrum, coccyx)
  - 25 thorax (sternum + 24 individual ribs)
  - 4 pectoral girdle, 6 upper limb long bones
  - 54 hand bones (8 carpals + 5 metacarpals + 14 phalanges × 2)
  - 2 pelvic, 8 lower limb long bones
  - 52 foot bones (7 tarsals + 5 metatarsals + 14 phalanges × 2)
  - 24 joints, 94 tendons, 48 muscles, 9 organs, 20 vessels
  - 13 nerves, 12 ligaments, 9 cartilage, 15 segments
  - currentPose, savedPoses, loadingConditions, derivationGraph, constitutiveLaws

Usage:
    python3 tools/generate_human_body.py                  # 1 body → stdout
    python3 tools/generate_human_body.py -n 5             # 5 bodies → stdout
    python3 tools/generate_human_body.py -n 2 -o out/     # 2 bodies → out/body_*.json
    python3 tools/generate_human_body.py -n 1 --pretty    # 1 body, indented

Generated by: Claude Opus 4.6 (1M context)
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import random
import sys
import uuid
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Callable

SCHEMA_VERSION = "3.0.0"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def uid() -> str:
    return str(uuid.uuid4())

def vec3(x: float = 0, y: float = 0, z: float = 0) -> dict:
    return {"x": round(x, 6), "y": round(y, 6), "z": round(z, 6)}

def unit_vec3(x: float = 0, y: float = 1, z: float = 0) -> dict:
    mag = math.sqrt(x * x + y * y + z * z) or 1.0
    return {"x": round(x / mag, 6), "y": round(y / mag, 6), "z": round(z / mag, 6)}

def identity_quat() -> dict:
    return {"w": 1.0, "x": 0.0, "y": 0.0, "z": 0.0}

def small_tilt_quat(pitch_deg: float = 0, yaw_deg: float = 0, roll_deg: float = 0) -> dict:
    p, y, r = math.radians(pitch_deg / 2), math.radians(yaw_deg / 2), math.radians(roll_deg / 2)
    w = math.cos(p) * math.cos(y) * math.cos(r) + math.sin(p) * math.sin(y) * math.sin(r)
    qx = math.sin(p) * math.cos(y) * math.cos(r) - math.cos(p) * math.sin(y) * math.sin(r)
    qy = math.cos(p) * math.sin(y) * math.cos(r) + math.sin(p) * math.cos(y) * math.sin(r)
    qz = math.cos(p) * math.cos(y) * math.sin(r) - math.sin(p) * math.sin(y) * math.cos(r)
    mag = math.sqrt(w*w + qx*qx + qy*qy + qz*qz)
    return {"w": round(w/mag, 4), "x": round(qx/mag, 4), "y": round(qy/mag, 4), "z": round(qz/mag, 4)}

def rigid_pose(px: float = 0, py: float = 0, pz: float = 0, q: dict | None = None) -> dict:
    return {"position": vec3(px, py, pz), "orientation": q or identity_quat()}

def tf(px: float = 0, py: float = 0, pz: float = 0,
       rx: float = 0, ry: float = 0, rz: float = 0) -> dict:
    return {"position": vec3(px, py, pz), "rotation": vec3(rx, ry, rz), "scale": vec3(1, 1, 1)}

def color(r: int = 200, g: int = 180, b: int = 160, a: float = 1.0) -> dict:
    return {"r": r, "g": g, "b": b, "a": a}

def sym_tensor(xx: float, yy: float, zz: float) -> dict:
    return {"xx": xx, "yy": yy, "zz": zz, "xy": 0, "xz": 0, "yz": 0}

def material(**kwargs: Any) -> dict:
    return kwargs

SEX_OPTIONS = ["male", "female", "intersex"]
G = 981  # cm/s²


# =============================================================================
# BONE INDEX CONSTANTS — 206 adult bones
#
# Layout:
#   0–1     Pelvic girdle (2 hip bones)
#   2–3     Sacrum, Coccyx
#   4–11    Cranial bones (8)
#   12–25   Facial bones (14)
#   26      Hyoid
#   27–32   Ear ossicles (6)
#   33      Sternum
#   34–57   Ribs (24: R1–R12 then L1–L12)
#   58–59   Scapulae
#   60–61   Clavicles
#   62–63   Humeri
#   64–65   Radii
#   66–67   Ulnae
#   68–69   Femora
#   70–71   Patellae
#   72–73   Tibiae
#   74–75   Fibulae
#   76–80   Lumbar L5–L1
#   81–92   Thoracic T12–T1
#   93–99   Cervical C7–C1
#   100–126 Hand R (27: 8 carpals + 5 metacarpals + 14 phalanges)
#   127–153 Hand L (27)
#   154–179 Foot R (26: 7 tarsals + 5 metatarsals + 14 phalanges)
#   180–205 Foot L (26)
# =============================================================================

# Pelvic girdle
B_HIP_R, B_HIP_L = 0, 1
B_SACRUM, B_COCCYX = 2, 3

# Cranial bones (8)
B_FRONTAL = 4
B_PARIETAL_R, B_PARIETAL_L = 5, 6
B_TEMPORAL_R, B_TEMPORAL_L = 7, 8
B_OCCIPITAL = 9
B_SPHENOID = 10
B_ETHMOID = 11

# Facial bones (14)
B_MAXILLA_R, B_MAXILLA_L = 12, 13
B_PALATINE_R, B_PALATINE_L = 14, 15
B_ZYGOMATIC_R, B_ZYGOMATIC_L = 16, 17
B_NASAL_R, B_NASAL_L = 18, 19
B_LACRIMAL_R, B_LACRIMAL_L = 20, 21
B_INF_CONCHA_R, B_INF_CONCHA_L = 22, 23
B_VOMER = 24
B_MANDIBLE = 25

B_HYOID = 26

# Ear ossicles
B_MALLEUS_R, B_INCUS_R, B_STAPES_R = 27, 28, 29
B_MALLEUS_L, B_INCUS_L, B_STAPES_L = 30, 31, 32

B_STERNUM = 33

# Ribs: R1–R12 = 34–45, L1–L12 = 46–57
B_RIB_R = [34 + i for i in range(12)]
B_RIB_L = [46 + i for i in range(12)]

B_SCAP_R, B_SCAP_L = 58, 59
B_CLAV_R, B_CLAV_L = 60, 61
B_HUMER_R, B_HUMER_L = 62, 63
B_RAD_R, B_RAD_L = 64, 65
B_ULNA_R, B_ULNA_L = 66, 67
B_FEM_R, B_FEM_L = 68, 69
B_PAT_R, B_PAT_L = 70, 71
B_TIB_R, B_TIB_L = 72, 73
B_FIB_R, B_FIB_L = 74, 75

# Vertebrae
B_L5 = 76; B_L4 = 77; B_L3 = 78; B_L2 = 79; B_L1 = 80
B_T12 = 81; B_T1 = 92
B_C7 = 93; B_C1 = 99

# Hand R carpals (8): 100–107
B_HAND_R_SCAPHOID = 100
B_HAND_R_LUNATE = 101
B_HAND_R_TRIQUETRUM = 102
B_HAND_R_PISIFORM = 103
B_HAND_R_TRAPEZIUM = 104
B_HAND_R_TRAPEZOID = 105
B_HAND_R_CAPITATE = 106
B_HAND_R_HAMATE = 107
# Hand R metacarpals (5): 108–112
B_HAND_R_MC = [108 + i for i in range(5)]
# Hand R phalanges (14): 113–126
# Thumb: PP=113, DP=114; Index: PP=115, MP=116, DP=117; etc.
B_HAND_R_PHAL_START = 113

B_HAND_L_START = 127  # Same layout +27

# Foot R tarsals (7): 154–160
B_FOOT_R_CALCANEUS = 154
B_FOOT_R_TALUS = 155
B_FOOT_R_NAVICULAR = 156
B_FOOT_R_CUBOID = 157
B_FOOT_R_CUNEIFORM_MED = 158
B_FOOT_R_CUNEIFORM_INT = 159
B_FOOT_R_CUNEIFORM_LAT = 160
# Foot R metatarsals (5): 161–165
B_FOOT_R_MT = [161 + i for i in range(5)]
# Foot R phalanges (14): 166–179
B_FOOT_R_PHAL_START = 166

B_FOOT_L_START = 180  # Same layout +26

# Joint index constants (unchanged count = 24)
J_HIP_R, J_HIP_L = 0, 1
J_KNEE_R, J_KNEE_L = 2, 3
J_SHOULDER_R, J_SHOULDER_L = 4, 5
J_ELBOW_R, J_ELBOW_L = 6, 7
J_L5S1 = 8
J_WRIST_R, J_WRIST_L = 20, 21
J_ANKLE_R, J_ANKLE_L = 22, 23

# Round 3 joint indices (appended after original 24)
J_SC_R, J_SC_L = 24, 25           # Sternoclavicular
J_AC_R, J_AC_L = 26, 27           # Acromioclavicular
J_SI_R, J_SI_L = 28, 29           # Sacroiliac
J_RU_PROX_R, J_RU_PROX_L = 30, 31 # Radioulnar proximal
J_TMJ_R, J_TMJ_L = 32, 33        # Temporomandibular
J_ATLANTO_OCC = 34                 # Atlanto-occipital
J_SUBTALAR_R, J_SUBTALAR_L = 35, 36
# IVDs: T11-T10=37, T10-T9=38, T8-T7=39, T7-T6=40, T6-T5=41, T4-T3=42, T3-T2=43
J_IVD_START = 37
# Hand/foot joints are generated programmatically starting at index 44
J_HAND_FOOT_START = 44

# Hand R phalanx bone indices for joint generation
_HR_MP = [None, 116, 119, 122, 125]  # middle phalanges (thumb has none)
_HL_MP = [None, 143, 146, 149, 152]  # Hand L middle phalanges (+27)
# Foot R phalanx middle bones
_FR_MP = [None, 169, 172, 175, 178]  # toe middle phalanges (hallux has none)
_FL_MP = [None, 195, 198, 201, 204]  # Foot L middle phalanges (+26)


# ---------------------------------------------------------------------------
# ID Registry
# ---------------------------------------------------------------------------

@dataclass
class Reg:
    bone_ids: list[str] = field(default_factory=list)
    joint_ids: list[str] = field(default_factory=list)
    tendon_ids: list[str] = field(default_factory=list)
    muscle_ids: list[str] = field(default_factory=list)
    organ_ids: list[str] = field(default_factory=list)
    vessel_ids: list[str] = field(default_factory=list)
    nerve_ids: list[str] = field(default_factory=list)
    segment_ids: list[str] = field(default_factory=list)
    ligament_ids: list[str] = field(default_factory=list)
    cartilage_ids: list[str] = field(default_factory=list)
    muscle_name_to_idx: dict[str, int] = field(default_factory=dict)
    tendon_name_to_idx: dict[str, int] = field(default_factory=dict)
    nerve_name_to_idx: dict[str, int] = field(default_factory=dict)
    pose_id: str = ""
    saved_pose_id: str = ""


# ---------------------------------------------------------------------------
# Proportions
# ---------------------------------------------------------------------------

def gen_proportions(v: int = 0) -> dict:
    sex = SEX_OPTIONS[v % len(SEX_OPTIONS)]
    height = random.uniform(160, 190)
    weight = random.uniform(60, 95)
    arm_length = height * random.uniform(0.42, 0.48)
    leg_length = height * random.uniform(0.46, 0.52)
    muscle_pct = random.uniform(30, 45)
    fat_pct = random.uniform(8, min(30, 74 - muscle_pct))
    return {
        "biologicalSex": sex,
        "totalHeight": round(height, 0),
        "weight": round(weight, 0),
        "shoulderWidth": round(random.uniform(38, 48), 0),
        "armLength": round(arm_length, 0),
        "legLength": round(leg_length, 0),
        "headCircumference": round(random.uniform(54, 59), 0),
        "muscleMassPercentage": round(muscle_pct, 0),
        "fatPercentage": round(fat_pct, 0),
    }


__all__ = [name for name in globals() if not name.startswith("__")]

