#!/usr/bin/env python3
"""
Manhattan Apartment Blueprint & 3D Model Generator

Data model mirrors building-model-3d-schema.ts v2.0.0.
Produces:
  1. Blueprint PNG — classic 2D plan view
  2. 3D isometric PNG — volumetric view with walls, floors, openings

Ownership tree (schema Rule 14):
  BuildingModel → Building → Floor → {Wall, Space, Slab, Fixture, Annotation}
  Wall → Opening

Generated by: Claude Opus 4.6 (Anthropic)
"""

from __future__ import annotations

import argparse
import math
import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from pathlib import Path
from typing import Optional

from PIL import Image, ImageDraw, ImageFont


# ═══════════════════════════════════════════════════════════════════════════════
# Schema version — mirrors building-model-3d-schema.ts v2.0.0
# ═══════════════════════════════════════════════════════════════════════════════

SCHEMA_VERSION = "2.0.0"

# ═══════════════════════════════════════════════════════════════════════════════
# Enums
# ═══════════════════════════════════════════════════════════════════════════════

class LengthUnit(str, Enum):
    MM = "mm"; CM = "cm"; M = "m"; IN = "in"; FT = "ft"

class LayerKind(str, Enum):
    STRUCTURAL = "structural"; ARCHITECTURAL = "architectural"
    ELECTRICAL = "electrical"; PLUMBING = "plumbing"
    ANNOTATION = "annotation"; EXTERIOR_ENVELOPE = "exterior_envelope"

class WallType(str, Enum):
    LOAD_BEARING = "load_bearing"; PARTITION = "partition"

class OpeningKind(str, Enum):
    SINGLE_DOOR = "single_door"; DOUBLE_DOOR = "double_door"
    SLIDING_DOOR = "sliding_door"; WINDOW = "window"; ARCHWAY = "archway"

class SwingDirection(str, Enum):
    INWARD_LEFT = "inward_left"; INWARD_RIGHT = "inward_right"
    NONE = "none"

class SpaceUsage(str, Enum):
    BEDROOM = "bedroom"; BATHROOM = "bathroom"; KITCHEN = "kitchen"
    LIVING_ROOM = "living_room"; DINING_ROOM = "dining_room"
    HALLWAY = "hallway"; CLOSET = "closet"; STORAGE = "storage"
    LAUNDRY = "laundry"; LOBBY = "lobby"; OTHER = "other"

class SlabKind(str, Enum):
    FLOOR = "floor"; CEILING = "ceiling"

class AnnotationKind(str, Enum):
    DIMENSION_LINEAR = "dimension_linear"; TEXT_LABEL = "text_label"
    AREA_CALLOUT = "area_callout"


# ═══════════════════════════════════════════════════════════════════════════════
# Geometry primitives — 2D + 3D
# ═══════════════════════════════════════════════════════════════════════════════

def _uuid() -> str:
    return str(uuid.uuid4())

@dataclass
class Point2D:
    x: float; y: float

@dataclass
class Point3D:
    x: float; y: float; z: float

@dataclass
class Vector3D:
    x: float; y: float; z: float

@dataclass
class Polygon2D:
    vertices: list[Point2D]

@dataclass
class BoundaryWithHoles2D:
    outer: Polygon2D
    holes: list[Polygon2D] = field(default_factory=list)

@dataclass
class MaterialSpec:
    name: str
    density_kg_per_m3: Optional[float] = None
    fire_rating_minutes: Optional[int] = None


# ═══════════════════════════════════════════════════════════════════════════════
# Metadata
# ═══════════════════════════════════════════════════════════════════════════════

@dataclass
class Metadata:
    created_at: str; updated_at: str; created_by: str; updated_by: str
    note: Optional[str] = None

def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()

def _meta(note: str = "") -> Metadata:
    now = _now_iso()
    return Metadata(now, now, "manhattan_blueprint.py", "manhattan_blueprint.py", note or None)


# ═══════════════════════════════════════════════════════════════════════════════
# Entity: Opening (v2 — height + sillHeight required)
# ═══════════════════════════════════════════════════════════════════════════════

@dataclass
class Opening:
    id: str
    kind: OpeningKind
    offset_along_wall: float
    width: float
    height: float
    sill_height: float = 0.0
    swing_direction: SwingDirection = SwingDirection.NONE


# ═══════════════════════════════════════════════════════════════════════════════
# Entity: Wall (v2 — height + baseElevation)
# ═══════════════════════════════════════════════════════════════════════════════

@dataclass
class Wall:
    id: str
    floor_id: str
    wall_type: WallType
    start: Point2D          # centerline start (plan XY)
    end: Point2D            # centerline end (plan XY)
    thickness: float
    height: float           # wall height from base to top
    base_elevation: float   # Z of wall bottom
    layer: LayerKind = LayerKind.ARCHITECTURAL
    material: Optional[MaterialSpec] = None
    openings: list[Opening] = field(default_factory=list)

    @property
    def length(self) -> float:
        dx = self.end.x - self.start.x
        dy = self.end.y - self.start.y
        return math.sqrt(dx * dx + dy * dy)


# ═══════════════════════════════════════════════════════════════════════════════
# Entity: Slab (new in v2)
# ═══════════════════════════════════════════════════════════════════════════════

@dataclass
class Slab:
    id: str
    floor_id: str
    kind: SlabKind
    boundary: BoundaryWithHoles2D
    thickness: float
    elevation: float    # Z of slab top surface


# ═══════════════════════════════════════════════════════════════════════════════
# Entity: Space (v2 — floorElevation + ceilingElevation)
# ═══════════════════════════════════════════════════════════════════════════════

@dataclass
class Space:
    id: str
    floor_id: str
    name: str
    usage: SpaceUsage
    boundary: BoundaryWithHoles2D
    floor_elevation: float      # Z of finished floor
    ceiling_elevation: float    # Z of finished ceiling
    area_sq_units: Optional[float] = None
    volume_cu_units: Optional[float] = None
    finish_floor: Optional[str] = None

    def computed_area(self) -> float:
        if self.area_sq_units is not None:
            return self.area_sq_units
        return _polygon_area(self.boundary.outer)

    def room_height(self) -> float:
        return self.ceiling_elevation - self.floor_elevation

    def centroid(self) -> Point2D:
        verts = self.boundary.outer.vertices
        return Point2D(
            sum(v.x for v in verts) / len(verts),
            sum(v.y for v in verts) / len(verts),
        )

    def bounding_box(self) -> tuple[float, float, float, float]:
        verts = self.boundary.outer.vertices
        xs = [v.x for v in verts]; ys = [v.y for v in verts]
        return min(xs), min(ys), max(xs), max(ys)


def _polygon_area(poly: Polygon2D) -> float:
    verts = poly.vertices; n = len(verts); area = 0.0
    for i in range(n):
        j = (i + 1) % n
        area += verts[i].x * verts[j].y - verts[j].x * verts[i].y
    return abs(area) / 2.0


# ═══════════════════════════════════════════════════════════════════════════════
# Entity: Floor (v2 — floorToFloorHeight required, slabs added)
# ═══════════════════════════════════════════════════════════════════════════════

@dataclass
class Floor:
    id: str
    building_id: str
    level: int
    name: str
    elevation_above_datum: float
    floor_to_floor_height: float
    walls: list[Wall] = field(default_factory=list)
    spaces: list[Space] = field(default_factory=list)
    slabs: list[Slab] = field(default_factory=list)


# ═══════════════════════════════════════════════════════════════════════════════
# Entity: Building
# ═══════════════════════════════════════════════════════════════════════════════

@dataclass
class Building:
    id: str
    name: str
    address: Optional[str] = None
    typology: Optional[str] = None


# ═══════════════════════════════════════════════════════════════════════════════
# Root: BuildingModel (renamed from Blueprint in v2)
# ═══════════════════════════════════════════════════════════════════════════════

@dataclass
class BuildingModel:
    schema_version: str
    id: str
    title: str
    length_unit: LengthUnit
    building: Building
    floors: list[Floor]
    metadata: Metadata
    origin: Point3D = field(default_factory=lambda: Point3D(0, 0, 0))
    true_north_deg: float = 0
    up_axis: str = "z"


# ═══════════════════════════════════════════════════════════════════════════════
# Structural validation
# ═══════════════════════════════════════════════════════════════════════════════

class Severity(Enum):
    ERROR = "error"
    WARNING = "warning"

@dataclass
class ValidationFinding:
    severity: Severity
    entity_id: str
    rule: str
    message: str

    def __str__(self) -> str:
        icon = "✗" if self.severity == Severity.ERROR else "⚠"
        return f"  {icon} [{self.entity_id}] {self.rule}: {self.message}"


def _rects_overlap(a: tuple[float,float,float,float],
                   b: tuple[float,float,float,float], eps: float = 0.05) -> bool:
    """Check if two axis-aligned rects (min_x, min_y, max_x, max_y) overlap interior."""
    return (a[0] + eps < b[2] and b[0] + eps < a[2]
            and a[1] + eps < b[3] and b[1] + eps < a[3])


def validate_model(model: BuildingModel) -> list[ValidationFinding]:
    """Validate a BuildingModel for structural impossibilities.

    Categories:
      G — Geometry: degenerate shapes, negative dimensions
      O — Openings: exceed wall, overlap, float above wall
      S — Spaces: overlapping rooms, inverted elevations
      F — Floors: elevation consistency, missing elements
      W — Walls: zero-length, excessive thickness, unsupported spans
    """
    findings: list[ValidationFinding] = []

    def err(eid: str, rule: str, msg: str) -> None:
        findings.append(ValidationFinding(Severity.ERROR, eid, rule, msg))

    def warn(eid: str, rule: str, msg: str) -> None:
        findings.append(ValidationFinding(Severity.WARNING, eid, rule, msg))

    if not model.floors:
        err(model.id, "F-01", "BuildingModel has no floors")
        return findings

    # ── Floor-level checks ──────────────────────────────────────────────
    sorted_floors = sorted(model.floors, key=lambda f: f.level)
    for i, floor in enumerate(sorted_floors):
        fid = f"floor[{floor.level}]"

        # F-01: floor-to-floor height must be positive and reasonable
        if floor.floor_to_floor_height <= 0:
            err(fid, "F-01", f"floor_to_floor_height={floor.floor_to_floor_height} ≤ 0")
        elif floor.floor_to_floor_height > 10:
            warn(fid, "F-01", f"floor_to_floor_height={floor.floor_to_floor_height}m exceeds 10m — verify")

        # F-02: elevation continuity between consecutive floors
        if i > 0:
            prev = sorted_floors[i - 1]
            expected = prev.elevation_above_datum + prev.floor_to_floor_height
            gap = abs(floor.elevation_above_datum - expected)
            if gap > 0.01:
                warn(fid, "F-02",
                     f"Elevation gap: expected {expected:.2f}m "
                     f"(prev {prev.elevation_above_datum:.2f} + {prev.floor_to_floor_height:.2f}), "
                     f"got {floor.elevation_above_datum:.2f}m (gap={gap:.2f}m)")

        # F-03: floor must have at least one space
        if not floor.spaces:
            warn(fid, "F-03", "Floor has no spaces defined")

        # ── Wall checks ─────────────────────────────────────────────────
        for wall in floor.walls:
            wid = f"wall:{wall.id[:8]}"

            # W-01: zero-length wall
            if wall.length < 0.01:
                err(wid, "W-01", "Wall has zero/near-zero length")
                continue

            # W-02: wall thickness ratio — thickness > length is structurally absurd
            if wall.thickness >= wall.length:
                err(wid, "W-02",
                    f"Thickness ({wall.thickness:.2f}m) ≥ length ({wall.length:.2f}m)")

            # W-03: wall height must be positive and ≤ floor-to-floor
            if wall.height <= 0:
                err(wid, "W-03", f"Wall height={wall.height}m ≤ 0")
            elif wall.height > floor.floor_to_floor_height + 0.01:
                warn(wid, "W-03",
                     f"Wall height ({wall.height:.2f}m) exceeds "
                     f"floor-to-floor ({floor.floor_to_floor_height:.2f}m)")

            # W-04: wall thickness sanity
            if wall.thickness <= 0:
                err(wid, "W-04", f"Wall thickness={wall.thickness}m ≤ 0")
            elif wall.thickness > 1.0:
                warn(wid, "W-04", f"Wall thickness={wall.thickness}m exceeds 1m — verify")

            # W-05: wall base elevation should be near the floor elevation
            elev_diff = abs(wall.base_elevation - floor.elevation_above_datum)
            if elev_diff > floor.floor_to_floor_height:
                err(wid, "W-05",
                    f"Wall base ({wall.base_elevation:.2f}m) is more than one storey "
                    f"away from floor datum ({floor.elevation_above_datum:.2f}m)")

            # ── Opening checks ──────────────────────────────────────────
            for j, op in enumerate(wall.openings):
                oid = f"opening:{op.id[:8]}"

                # O-01: opening must fit within wall length
                if op.offset_along_wall < -0.01:
                    err(oid, "O-01", f"Negative offset ({op.offset_along_wall:.2f}m)")
                if op.offset_along_wall + op.width > wall.length + 0.01:
                    err(oid, "O-01",
                        f"Opening extends past wall: offset({op.offset_along_wall:.2f}) + "
                        f"width({op.width:.2f}) = {op.offset_along_wall + op.width:.2f}m "
                        f"> wall length {wall.length:.2f}m")

                # O-02: opening must fit within wall height
                if op.sill_height + op.height > wall.height + 0.01:
                    err(oid, "O-02",
                        f"Opening exceeds wall height: sill({op.sill_height:.2f}) + "
                        f"height({op.height:.2f}) = {op.sill_height + op.height:.2f}m "
                        f"> wall height {wall.height:.2f}m")

                # O-03: opening dimensions must be positive
                if op.width <= 0:
                    err(oid, "O-03", f"Opening width={op.width}m ≤ 0")
                if op.height <= 0:
                    err(oid, "O-03", f"Opening height={op.height}m ≤ 0")

                # O-04: sill height must be non-negative
                if op.sill_height < -0.01:
                    err(oid, "O-04", f"Negative sill height ({op.sill_height:.2f}m)")

                # O-05: doors must start at floor level
                if op.kind in (OpeningKind.SINGLE_DOOR, OpeningKind.DOUBLE_DOOR):
                    if op.sill_height > 0.05:
                        warn(oid, "O-05",
                             f"Door has sill_height={op.sill_height:.2f}m — doors should start at floor level")

                # O-06: window sill should be above floor
                if op.kind == OpeningKind.WINDOW:
                    if op.sill_height < 0.3:
                        warn(oid, "O-06",
                             f"Window sill at {op.sill_height:.2f}m — "
                             f"residential code typically requires ≥0.6m for safety")

            # O-07: openings must not overlap each other
            sorted_ops = sorted(wall.openings, key=lambda o: o.offset_along_wall)
            for j in range(len(sorted_ops) - 1):
                a, b = sorted_ops[j], sorted_ops[j + 1]
                a_end = a.offset_along_wall + a.width
                if a_end > b.offset_along_wall + 0.01:
                    err(f"wall:{wall.id[:8]}", "O-07",
                        f"Openings overlap: [{a.offset_along_wall:.2f}–{a_end:.2f}] "
                        f"and [{b.offset_along_wall:.2f}–{b.offset_along_wall + b.width:.2f}]")

            # W-06: remaining wall material between openings — check pier widths
            # After subtracting all openings, each solid segment must be ≥ min pier width
            MIN_PIER = 0.10  # minimum 10cm of wall between openings
            solid_start = 0.0
            for op in sorted_ops:
                pier = op.offset_along_wall - solid_start
                if 0 < pier < MIN_PIER:
                    warn(f"wall:{wall.id[:8]}", "W-06",
                         f"Wall pier between openings is only {pier:.2f}m "
                         f"(minimum {MIN_PIER}m for structural integrity)")
                solid_start = op.offset_along_wall + op.width
            # Check trailing pier
            trailing = wall.length - solid_start
            if 0 < trailing < MIN_PIER and sorted_ops:
                warn(f"wall:{wall.id[:8]}", "W-06",
                     f"Trailing wall pier is only {trailing:.2f}m")

            # W-07: total opening width should not exceed wall length
            total_opening_w = sum(op.width for op in wall.openings)
            if total_opening_w > wall.length + 0.01:
                err(f"wall:{wall.id[:8]}", "W-07",
                    f"Total opening width ({total_opening_w:.2f}m) exceeds "
                    f"wall length ({wall.length:.2f}m)")

        # ── Space checks ────────────────────────────────────────────────
        for space in floor.spaces:
            sid = f"space:{space.name}"

            # S-01: ceiling must be above floor
            if space.ceiling_elevation <= space.floor_elevation:
                err(sid, "S-01",
                    f"Ceiling ({space.ceiling_elevation:.2f}m) ≤ "
                    f"floor ({space.floor_elevation:.2f}m)")

            # S-02: room height sanity
            rh = space.room_height()
            if rh < 2.0:
                warn(sid, "S-02", f"Room height {rh:.2f}m < 2.0m — below habitable minimum")
            elif rh > 6.0:
                warn(sid, "S-02", f"Room height {rh:.2f}m > 6.0m — verify for residential")

            # S-03: boundary must have ≥ 3 vertices
            nv = len(space.boundary.outer.vertices)
            if nv < 3:
                err(sid, "S-03", f"Boundary has {nv} vertices (minimum 3)")
                continue

            # S-04: area must be positive and reasonable
            area = space.computed_area()
            if area <= 0:
                err(sid, "S-04", f"Space area={area:.2f}m² ≤ 0 — degenerate polygon")
            elif area < 1.0:
                warn(sid, "S-04", f"Space area={area:.2f}m² < 1m² — unusably small")
            elif area > 500:
                warn(sid, "S-04", f"Space area={area:.2f}m² > 500m² — verify for apartment")

            # S-05: stored area must match computed area
            if space.area_sq_units is not None:
                computed = _polygon_area(space.boundary.outer)
                diff = abs(space.area_sq_units - computed)
                if diff > 0.5:
                    warn(sid, "S-05",
                         f"Stored area ({space.area_sq_units:.1f}m²) differs from "
                         f"computed ({computed:.1f}m²) by {diff:.1f}m²")

            # S-06: space floor elevation should match parent floor
            if abs(space.floor_elevation - floor.elevation_above_datum) > 1.0:
                warn(sid, "S-06",
                     f"Space floor elevation ({space.floor_elevation:.2f}m) deviates > 1m "
                     f"from floor datum ({floor.elevation_above_datum:.2f}m)")

        # S-07: overlapping spaces on the same floor
        bboxes = [(sp, sp.bounding_box()) for sp in floor.spaces]
        for i in range(len(bboxes)):
            for j in range(i + 1, len(bboxes)):
                sp_a, bb_a = bboxes[i]
                sp_b, bb_b = bboxes[j]
                if _rects_overlap(bb_a, bb_b):
                    warn(f"{fid}", "S-07",
                         f"Spaces overlap: '{sp_a.name}' and '{sp_b.name}'")

        # ── Slab checks ─────────────────────────────────────────────────
        for slab in floor.slabs:
            slid = f"slab:{slab.id[:8]}"

            # SL-01: slab thickness must be positive
            if slab.thickness <= 0:
                err(slid, "SL-01", f"Slab thickness={slab.thickness}m ≤ 0")
            elif slab.thickness > 1.0:
                warn(slid, "SL-01", f"Slab thickness={slab.thickness}m > 1m — verify")

            # SL-02: slab boundary must have ≥ 3 vertices
            if len(slab.boundary.outer.vertices) < 3:
                err(slid, "SL-02", "Slab boundary has < 3 vertices")

    return findings


def validate_or_raise(model: BuildingModel) -> None:
    """Validate and raise ValueError if any errors found."""
    findings = validate_model(model)
    if not findings:
        return
    errors = [f for f in findings if f.severity == Severity.ERROR]
    warnings = [f for f in findings if f.severity == Severity.WARNING]
    report = []
    if errors:
        report.append(f"\n{'='*60}")
        report.append(f"  STRUCTURAL VALIDATION FAILED — {len(errors)} error(s), {len(warnings)} warning(s)")
        report.append(f"{'='*60}")
        for f in errors:
            report.append(str(f))
    if warnings:
        if not errors:
            report.append(f"\n  Structural validation: {len(warnings)} warning(s)")
        for f in warnings:
            report.append(str(f))
    msg = "\n".join(report)
    if errors:
        raise ValueError(msg)
    print(msg)


# ═══════════════════════════════════════════════════════════════════════════════
# Rendering constants
# ═══════════════════════════════════════════════════════════════════════════════

BG_COLOR = (24, 40, 72)
WALL_COLOR = (200, 215, 235)
FILL_COLORS: dict[SpaceUsage, tuple[int, int, int]] = {
    SpaceUsage.LIVING_ROOM: (55, 80, 120),  SpaceUsage.BEDROOM: (45, 70, 110),
    SpaceUsage.KITCHEN: (70, 95, 130),       SpaceUsage.BATHROOM: (60, 88, 125),
    SpaceUsage.CLOSET: (38, 58, 95),         SpaceUsage.HALLWAY: (35, 55, 90),
    SpaceUsage.LOBBY: (40, 62, 100),         SpaceUsage.LAUNDRY: (50, 72, 108),
    SpaceUsage.STORAGE: (38, 58, 95),
}
DEFAULT_FILL = (48, 68, 105)
LABEL_COLOR = (220, 230, 245)
DIM_COLOR = (140, 165, 200)
TITLE_COLOR = (230, 240, 255)
GRID_COLOR = (30, 48, 82)
DOOR_ARC_COLOR = DIM_COLOR

PX_PER_UNIT = 55
WALL_PX = 4
PADDING = 100
TITLE_H = 90
LEGEND_H = 60

# 3D isometric colors
WALL_3D_FRONT = (160, 180, 210)
WALL_3D_SIDE = (120, 145, 180)
WALL_3D_TOP = (180, 195, 220)
FLOOR_3D = (40, 60, 95)
SLAB_3D = (50, 70, 105)
OPENING_3D = (30, 48, 78)
OUTLINE_3D = (90, 115, 150)


# ═══════════════════════════════════════════════════════════════════════════════
# 2D Blueprint Renderer (plan view)
# ═══════════════════════════════════════════════════════════════════════════════

class BlueprintRenderer:
    def __init__(self, model: BuildingModel):
        self.model = model
        self._compute_bounds()

    def _compute_bounds(self) -> None:
        min_x = min_y = float("inf"); max_x = max_y = float("-inf")
        for floor in self.model.floors:
            for space in floor.spaces:
                sx0, sy0, sx1, sy1 = space.bounding_box()
                min_x = min(min_x, sx0); min_y = min(min_y, sy0)
                max_x = max(max_x, sx1); max_y = max(max_y, sy1)
        self.plan_w = max_x - min_x; self.plan_h = max_y - min_y
        self.off_x = min_x; self.off_y = min_y

    def img_w(self) -> int: return int(self.plan_w * PX_PER_UNIT) + PADDING * 2
    def img_h(self) -> int: return int(self.plan_h * PX_PER_UNIT) + PADDING * 2 + TITLE_H + LEGEND_H

    def to_px(self, x: float, y: float) -> tuple[int, int]:
        return (PADDING + int((x - self.off_x) * PX_PER_UNIT),
                PADDING + TITLE_H + int((y - self.off_y) * PX_PER_UNIT))

    def render(self, path: str) -> str:
        img = Image.new("RGB", (self.img_w(), self.img_h()), BG_COLOR)
        draw = ImageDraw.Draw(img)
        self._grid(draw)
        for f in self.model.floors:
            self._spaces(draw, f)
            self._walls_2d(draw, f)
        self._dims(draw); self._title(draw); self._legend(draw)
        img.save(path); return path

    def _grid(self, d: ImageDraw.Draw) -> None:
        x0, y0 = self.to_px(self.off_x, self.off_y)
        x1, y1 = self.to_px(self.off_x + self.plan_w, self.off_y + self.plan_h)
        for m in range(int(self.plan_w) + 1):
            px, _ = self.to_px(self.off_x + m, self.off_y)
            if x0 <= px <= x1: d.line([(px, y0), (px, y1)], fill=GRID_COLOR)
        for m in range(int(self.plan_h) + 1):
            _, py = self.to_px(self.off_x, self.off_y + m)
            if y0 <= py <= y1: d.line([(x0, py), (x1, py)], fill=GRID_COLOR)

    def _spaces(self, d: ImageDraw.Draw, floor: Floor) -> None:
        fl, fa, fd = _load_font(14), _load_font(11), _load_font(10)
        for sp in floor.spaces:
            pxv = [self.to_px(v.x, v.y) for v in sp.boundary.outer.vertices]
            fill = FILL_COLORS.get(sp.usage, DEFAULT_FILL)
            d.polygon(pxv, fill=fill); d.polygon(pxv, outline=WALL_COLOR, width=WALL_PX)
            bb = sp.bounding_box()
            px0, py0 = self.to_px(bb[0], bb[1]); px1, py1 = self.to_px(bb[2], bb[3])
            cx, cy = (px0+px1)//2, (py0+py1)//2
            rpw, rph = abs(px1-px0), abs(py1-py0)
            w, h = bb[2]-bb[0], bb[3]-bb[1]
            area = sp.computed_area()
            if rpw > 50 and rph > 40:
                _ctxt(d, cx, cy-14, sp.name, fl, LABEL_COLOR)
                _ctxt(d, cx, cy+4, f"{area:.1f} m²", fa, DIM_COLOR)
                if rph > 60: _ctxt(d, cx, cy+20, f"{w:.1f} × {h:.1f} m", fd, DIM_COLOR)
            elif rpw > 30 and rph > 24:
                _ctxt(d, cx, cy-4, sp.name, fa, LABEL_COLOR)

    def _walls_2d(self, d: ImageDraw.Draw, floor: Floor) -> None:
        for wall in floor.walls:
            sx, sy = self.to_px(wall.start.x, wall.start.y)
            ex, ey = self.to_px(wall.end.x, wall.end.y)
            w = max(2, int(wall.thickness * PX_PER_UNIT))
            d.line([(sx,sy),(ex,ey)], fill=WALL_COLOR, width=w)
            for op in wall.openings:
                self._opening_2d(d, wall, op)

    def _opening_2d(self, d: ImageDraw.Draw, wall: Wall, op: Opening) -> None:
        wl = wall.length
        if wl == 0: return
        ux = (wall.end.x - wall.start.x) / wl
        uy = (wall.end.y - wall.start.y) / wl
        # Normal perpendicular to wall direction
        nx, ny = -uy, ux
        sx = wall.start.x + ux * op.offset_along_wall
        sy = wall.start.y + uy * op.offset_along_wall
        ex = wall.start.x + ux * (op.offset_along_wall + op.width)
        ey = wall.start.y + uy * (op.offset_along_wall + op.width)
        psx, psy = self.to_px(sx, sy); pex, pey = self.to_px(ex, ey)
        w = max(2, int(wall.thickness * PX_PER_UNIT)) + 2
        d.line([(psx,psy),(pex,pey)], fill=BG_COLOR, width=w)
        if op.kind in (OpeningKind.SINGLE_DOOR, OpeningKind.DOUBLE_DOOR):
            # Door arc
            dp = int(op.width * PX_PER_UNIT); half = dp // 2
            mcx, mcy = (psx+pex)//2, (psy+pey)//2
            d.arc([mcx-half, mcy-half, mcx+half, mcy+half], 180, 270, fill=DOOR_ARC_COLOR)
        elif op.kind == OpeningKind.WINDOW:
            # Window: draw a thin double line across the gap with tick marks
            # The double line represents the glass pane in plan view
            t = wall.thickness * PX_PER_UNIT * 0.3  # offset for double line
            pnx, pny = int(nx * t), int(ny * t)
            # Two parallel lines (glass panes)
            d.line([(psx+pnx, psy+pny), (pex+pnx, pey+pny)], fill=WALL_COLOR, width=1)
            d.line([(psx-pnx, psy-pny), (pex-pnx, pey-pny)], fill=WALL_COLOR, width=1)
            # Tick marks at each end (perpendicular to wall)
            tick = int(wall.thickness * PX_PER_UNIT * 0.6)
            tnx, tny = int(nx * tick), int(ny * tick)
            d.line([(psx-tnx, psy-tny), (psx+tnx, psy+tny)], fill=WALL_COLOR, width=1)
            d.line([(pex-tnx, pey-tny), (pex+tnx, pey+tny)], fill=WALL_COLOR, width=1)

    def _outer(self, d: ImageDraw.Draw) -> None:
        x0, y0 = self.to_px(self.off_x, self.off_y)
        x1, y1 = self.to_px(self.off_x+self.plan_w, self.off_y+self.plan_h)
        d.rectangle([x0,y0,x1,y1], outline=WALL_COLOR, width=WALL_PX+2)

    def _dims(self, d: ImageDraw.Draw) -> None:
        f = _load_font(10); off = 30
        x0, y0 = self.to_px(self.off_x, self.off_y)
        x1, y1 = self.to_px(self.off_x+self.plan_w, self.off_y+self.plan_h)
        _dim_h(d, x0, y0-off, x1, y0-off, f"{self.plan_w:.1f} m", f)
        _dim_v(d, x0-off, y0, x0-off, y1, f"{self.plan_h:.1f} m", f)

    def _title(self, d: ImageDraw.Draw) -> None:
        ft, fs = _load_font(22), _load_font(13)
        cx = self.img_w() // 2
        d.line([(PADDING, PADDING+TITLE_H-8), (self.img_w()-PADDING, PADDING+TITLE_H-8)], fill=WALL_COLOR, width=2)
        _ctxt(d, cx, PADDING+10, self.model.title, ft, TITLE_COLOR)
        area = sum(s.computed_area() for f in self.model.floors for s in f.spaces)
        _ctxt(d, cx, PADDING+42, f"{self.model.building.name}  |  ~{area:.0f} m²  |  1:100", fs, DIM_COLOR)

    def _legend(self, d: ImageDraw.Draw) -> None:
        f = _load_font(10); yb = self.img_h() - LEGEND_H + 15; x = PADDING
        d.line([(PADDING, yb-10), (self.img_w()-PADDING, yb-10)], fill=WALL_COLOR)
        for fl in self.model.floors:
            for sp in fl.spaces:
                bb = sp.bounding_box(); w, h = bb[2]-bb[0], bb[3]-bb[1]
                lbl = f"{sp.name}: {w:.1f}×{h:.1f} m ({sp.computed_area():.1f} m²)"
                tw = f.getbbox(lbl)[2] - f.getbbox(lbl)[0]
                if x+tw+20 > self.img_w()-PADDING: yb += 16; x = PADDING
                d.text((x, yb), lbl, fill=DIM_COLOR, font=f); x += tw + 24


# ═══════════════════════════════════════════════════════════════════════════════
# 3D Isometric Renderer
# ═══════════════════════════════════════════════════════════════════════════════

class IsometricRenderer:
    """Renders a BuildingModel as an isometric 3D projection."""

    # Isometric angles: 30° tilt
    COS30 = math.cos(math.radians(30))
    SIN30 = math.sin(math.radians(30))

    def __init__(self, model: BuildingModel, scale: float = 40):
        self.model = model
        self.scale = scale
        self._compute_bounds()

    def _iso(self, x: float, y: float, z: float) -> tuple[float, float]:
        """Convert 3D world coords to 2D isometric screen coords."""
        sx = (x - y) * self.COS30 * self.scale
        sy = -(x + y) * self.SIN30 * self.scale - z * self.scale
        return sx, sy

    def _compute_bounds(self) -> None:
        """Find screen-space bounding box of the entire model."""
        corners: list[tuple[float, float]] = []
        for floor in self.model.floors:
            z0 = floor.elevation_above_datum
            z1 = z0 + floor.floor_to_floor_height
            for space in floor.spaces:
                for v in space.boundary.outer.vertices:
                    corners.append(self._iso(v.x, v.y, z0))
                    corners.append(self._iso(v.x, v.y, z1))
        if not corners:
            self.sx_min = self.sy_min = 0; self.sx_max = self.sy_max = 400
            return
        self.sx_min = min(c[0] for c in corners) - 80
        self.sx_max = max(c[0] for c in corners) + 80
        self.sy_min = min(c[1] for c in corners) - 120
        self.sy_max = max(c[1] for c in corners) + 80

    def img_w(self) -> int: return int(self.sx_max - self.sx_min)
    def img_h(self) -> int: return int(self.sy_max - self.sy_min) + TITLE_H

    def to_px(self, x: float, y: float, z: float) -> tuple[int, int]:
        sx, sy = self._iso(x, y, z)
        return int(sx - self.sx_min), int(sy - self.sy_min) + TITLE_H

    def render(self, path: str) -> str:
        img = Image.new("RGB", (self.img_w(), self.img_h()), BG_COLOR)
        draw = ImageDraw.Draw(img)

        # Sort floors bottom-up, spaces back-to-front (painter's algorithm)
        for floor in sorted(self.model.floors, key=lambda f: f.elevation_above_datum):
            z0 = floor.elevation_above_datum

            # Draw floor slab
            self._draw_slab(draw, floor, z0)

            # Draw spaces (floor fills)
            for space in sorted(floor.spaces, key=lambda s: -(s.centroid().x + s.centroid().y)):
                self._draw_space_floor(draw, space, z0)

            # Draw walls back-to-front
            for wall in sorted(floor.walls, key=lambda w: -(w.start.x + w.start.y + w.end.x + w.end.y) / 2):
                self._draw_wall_3d(draw, wall)

        self._draw_title(draw)
        img.save(path)
        return path

    def _draw_slab(self, draw: ImageDraw.Draw, floor: Floor, z: float) -> None:
        """Draw the floor slab as an isometric quad."""
        # Use combined bounding box of all spaces
        min_x = min_y = float("inf"); max_x = max_y = float("-inf")
        for sp in floor.spaces:
            bb = sp.bounding_box()
            min_x = min(min_x, bb[0]); min_y = min(min_y, bb[1])
            max_x = max(max_x, bb[2]); max_y = max(max_y, bb[3])

        corners = [
            self.to_px(min_x, min_y, z), self.to_px(max_x, min_y, z),
            self.to_px(max_x, max_y, z), self.to_px(min_x, max_y, z),
        ]
        draw.polygon(corners, fill=SLAB_3D, outline=OUTLINE_3D)

    def _draw_space_floor(self, draw: ImageDraw.Draw, space: Space, z: float) -> None:
        """Draw the floor area of a space as a filled polygon."""
        verts = [self.to_px(v.x, v.y, z + 0.01) for v in space.boundary.outer.vertices]
        fill = FILL_COLORS.get(space.usage, DEFAULT_FILL)
        # Lighten slightly for 3D floor
        fill = tuple(min(255, c + 15) for c in fill)
        draw.polygon(verts, fill=fill, outline=OUTLINE_3D)

        # Label
        c = space.centroid()
        px, py = self.to_px(c.x, c.y, z + 0.01)
        font = _load_font(10)
        _ctxt(draw, px, py, space.name, font, LABEL_COLOR)

    def _draw_wall_3d(self, draw: ImageDraw.Draw, wall: Wall) -> None:
        """Draw a wall as a 3D extruded quad (front face + top face)."""
        z0 = wall.base_elevation
        z1 = z0 + wall.height

        # Wall centerline direction
        dx = wall.end.x - wall.start.x
        dy = wall.end.y - wall.start.y
        wl = wall.length
        if wl == 0:
            return

        # Normal perpendicular to wall (for thickness)
        nx = -dy / wl * wall.thickness / 2
        ny = dx / wl * wall.thickness / 2

        # 4 corners at base, 4 at top (outer face)
        bl = Point2D(wall.start.x + nx, wall.start.y + ny)
        br = Point2D(wall.end.x + nx, wall.end.y + ny)

        # Determine which faces to draw based on viewing direction
        # In isometric (x-y, 30°), we see the "south" and "east" faces
        # Front face (the side facing the camera)
        front = [
            self.to_px(bl.x, bl.y, z0),
            self.to_px(br.x, br.y, z0),
            self.to_px(br.x, br.y, z1),
            self.to_px(bl.x, bl.y, z1),
        ]
        draw.polygon(front, fill=WALL_3D_FRONT, outline=OUTLINE_3D)

        # Top face
        tl_inner = Point2D(wall.start.x - nx, wall.start.y - ny)
        tr_inner = Point2D(wall.end.x - nx, wall.end.y - ny)
        top = [
            self.to_px(bl.x, bl.y, z1),
            self.to_px(br.x, br.y, z1),
            self.to_px(tr_inner.x, tr_inner.y, z1),
            self.to_px(tl_inner.x, tl_inner.y, z1),
        ]
        draw.polygon(top, fill=WALL_3D_TOP, outline=OUTLINE_3D)

        # Draw openings as dark rectangles on the front face
        for op in wall.openings:
            self._draw_opening_3d(draw, wall, op, bl, br, z0)

    def _draw_opening_3d(self, draw: ImageDraw.Draw, wall: Wall, op: Opening,
                          bl: Point2D, br: Point2D, z0: float) -> None:
        """Draw an opening as a dark rectangle on the wall face."""
        wl = wall.length
        if wl == 0:
            return

        t0 = op.offset_along_wall / wl
        t1 = (op.offset_along_wall + op.width) / wl
        t0 = max(0, min(1, t0))
        t1 = max(0, min(1, t1))

        # Interpolate along the outer face edge
        ox0 = bl.x + (br.x - bl.x) * t0
        oy0 = bl.y + (br.y - bl.y) * t0
        ox1 = bl.x + (br.x - bl.x) * t1
        oy1 = bl.y + (br.y - bl.y) * t1

        oz_bot = z0 + op.sill_height
        oz_top = oz_bot + op.height

        opening_quad = [
            self.to_px(ox0, oy0, oz_bot),
            self.to_px(ox1, oy1, oz_bot),
            self.to_px(ox1, oy1, oz_top),
            self.to_px(ox0, oy0, oz_top),
        ]
        if op.kind == OpeningKind.WINDOW:
            # Windows: light blue tint (glass) with a cross mullion
            window_fill = (45, 70, 115)
            draw.polygon(opening_quad, fill=window_fill, outline=OUTLINE_3D)
            # Horizontal mullion at mid-height
            mz = (oz_bot + oz_top) / 2
            ml = self.to_px(ox0, oy0, mz)
            mr = self.to_px(ox1, oy1, mz)
            draw.line([ml, mr], fill=WALL_COLOR, width=1)
            # Vertical mullion at mid-width
            mx = (ox0 + ox1) / 2
            my = (oy0 + oy1) / 2
            mt = self.to_px(mx, my, oz_top)
            mb = self.to_px(mx, my, oz_bot)
            draw.line([mt, mb], fill=WALL_COLOR, width=1)
        else:
            # Doors: dark void
            draw.polygon(opening_quad, fill=OPENING_3D, outline=OUTLINE_3D)

    def _draw_title(self, draw: ImageDraw.Draw) -> None:
        ft, fs = _load_font(22), _load_font(13)
        cx = self.img_w() // 2
        _ctxt(draw, cx, 30, self.model.title, ft, TITLE_COLOR)
        area = sum(s.computed_area() for f in self.model.floors for s in f.spaces)
        _ctxt(draw, cx, 60, f"{self.model.building.name}  |  ~{area:.0f} m²  |  3D Isometric", fs, DIM_COLOR)


# ═══════════════════════════════════════════════════════════════════════════════
# Drawing helpers
# ═══════════════════════════════════════════════════════════════════════════════

def _load_font(size: int) -> ImageFont.FreeTypeFont:
    for p in ["/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
              "/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf",
              "/System/Library/Fonts/Helvetica.ttc"]:
        if Path(p).exists(): return ImageFont.truetype(p, size)
    return ImageFont.load_default()

def _ctxt(d: ImageDraw.Draw, cx: int, cy: int, text: str, font, color: tuple) -> None:
    bb = font.getbbox(text)
    d.text((cx - (bb[2]-bb[0])//2, cy - (bb[3]-bb[1])//2), text, fill=color, font=font)

def _dim_h(d, x0, y, x1, y2, label, font):
    s = 6; d.line([(x0,y),(x1,y)], fill=DIM_COLOR)
    d.line([(x0,y-s),(x0,y+s)], fill=DIM_COLOR); d.line([(x1,y-s),(x1,y+s)], fill=DIM_COLOR)
    _ctxt(d, (x0+x1)//2, y-12, label, font, DIM_COLOR)

def _dim_v(d, x, y0, x2, y1, label, font):
    s = 6; d.line([(x,y0),(x,y1)], fill=DIM_COLOR)
    d.line([(x-s,y0),(x+s,y0)], fill=DIM_COLOR); d.line([(x-s,y1),(x+s,y1)], fill=DIM_COLOR)
    bb = font.getbbox(label)
    tw, th = bb[2]-bb[0], bb[3]-bb[1]
    ti = Image.new("RGBA", (tw+4, th+4), (0,0,0,0))
    ImageDraw.Draw(ti).text((2,2), label, fill=DIM_COLOR, font=font)
    r = ti.rotate(90, expand=True)
    d._image.paste(r, (x-r.width//2, (y0+y1)//2-r.height//2), r)


# ═══════════════════════════════════════════════════════════════════════════════
# Builders — convenience helpers for rectangular geometry
# ═══════════════════════════════════════════════════════════════════════════════

WALL_HEIGHT = 2.7       # standard apartment wall height
SLAB_THICKNESS = 0.2    # floor slab thickness
FLOOR_TO_FLOOR = 3.0    # floor-to-floor height


def _rect_space(fid: str, name: str, usage: SpaceUsage,
                x: float, y: float, w: float, h: float,
                z: float = 0.0) -> Space:
    return Space(
        id=_uuid(), floor_id=fid, name=name, usage=usage,
        boundary=BoundaryWithHoles2D(outer=Polygon2D([
            Point2D(x,y), Point2D(x+w,y), Point2D(x+w,y+h), Point2D(x,y+h),
        ])),
        floor_elevation=z,
        ceiling_elevation=z + WALL_HEIGHT,
        area_sq_units=w * h,
        volume_cu_units=w * h * WALL_HEIGHT,
    )


def _rect_wall(fid: str, x0: float, y0: float, x1: float, y1: float,
               z: float = 0.0, *, openings: list[Opening] | None = None) -> Wall:
    return Wall(
        id=_uuid(), floor_id=fid, wall_type=WallType.PARTITION,
        start=Point2D(x0, y0), end=Point2D(x1, y1),
        thickness=0.15, height=WALL_HEIGHT, base_elevation=z,
        openings=openings or [],
    )


def _door(offset: float, width: float = 0.9) -> Opening:
    return Opening(id=_uuid(), kind=OpeningKind.SINGLE_DOOR,
                   offset_along_wall=offset, width=width,
                   height=2.1, sill_height=0.0,
                   swing_direction=SwingDirection.INWARD_RIGHT)


def _window(offset: float, width: float = 1.2, height: float = 1.4,
            sill: float = 0.9) -> Opening:
    """Create a window opening. Default sill at 0.9m, 1.4m tall, 1.2m wide."""
    return Opening(id=_uuid(), kind=OpeningKind.WINDOW,
                   offset_along_wall=offset, width=width,
                   height=height, sill_height=sill,
                   swing_direction=SwingDirection.NONE)


_NO_DOOR = {SpaceUsage.CLOSET, SpaceUsage.STORAGE}


def _derive_walls(fid: str, spaces: list[Space], z: float = 0.0) -> list[Wall]:
    """Derive interior walls with doors from adjacent rectangular spaces."""
    EPS = 0.05

    @dataclass
    class Edge:
        x0: float; y0: float; x1: float; y1: float
        idx: int; horiz: bool

    edges: list[Edge] = []
    for i, sp in enumerate(spaces):
        bb = sp.bounding_box(); sx0, sy0, sx1, sy1 = bb
        edges += [Edge(sx0,sy0,sx1,sy0,i,True), Edge(sx0,sy1,sx1,sy1,i,True),
                  Edge(sx0,sy0,sx0,sy1,i,False), Edge(sx1,sy0,sx1,sy1,i,False)]

    walls: list[Wall] = []; seen: set[tuple[int,int]] = set()
    for e1 in edges:
        for e2 in edges:
            if e1.idx >= e2.idx or e1.horiz != e2.horiz: continue
            pair = (e1.idx, e2.idx)
            if pair in seen: continue
            if e1.horiz:
                if abs(e1.y0 - e2.y0) > EPS: continue
                os, oe = max(e1.x0,e2.x0), min(e1.x1,e2.x1)
                if oe - os < EPS: continue
                seen.add(pair); wl = oe - os
                ops = []
                if spaces[e1.idx].usage not in _NO_DOOR and spaces[e2.idx].usage not in _NO_DOOR and wl >= 1.0:
                    dw = min(0.9, wl*0.6); ops.append(_door((wl-dw)/2, dw))
                walls.append(_rect_wall(fid, os, e1.y0, oe, e1.y0, z, openings=ops))
            else:
                if abs(e1.x0 - e2.x0) > EPS: continue
                os, oe = max(e1.y0,e2.y0), min(e1.y1,e2.y1)
                if oe - os < EPS: continue
                seen.add(pair); wl = oe - os
                ops = []
                if spaces[e1.idx].usage not in _NO_DOOR and spaces[e2.idx].usage not in _NO_DOOR and wl >= 1.0:
                    dw = min(0.9, wl*0.6); ops.append(_door((wl-dw)/2, dw))
                walls.append(_rect_wall(fid, e1.x0, os, e1.x0, oe, z, openings=ops))
    return walls


def _derive_exterior_walls(fid: str, spaces: list[Space], z: float = 0.0,
                            window_sides: set[str] | None = None) -> list[Wall]:
    """Create exterior (perimeter) walls with windows on specified sides.

    window_sides: subset of {"north", "south", "east", "west"} indicating
    which exterior walls get windows. Defaults to all sides.
    """
    if window_sides is None:
        window_sides = {"north", "south", "east", "west"}

    # Overall bounding box
    min_x = min_y = float("inf"); max_x = max_y = float("-inf")
    for sp in spaces:
        bb = sp.bounding_box()
        min_x = min(min_x, bb[0]); min_y = min(min_y, bb[1])
        max_x = max(max_x, bb[2]); max_y = max(max_y, bb[3])

    w = max_x - min_x; h = max_y - min_y
    ext_walls: list[Wall] = []

    def _wins(length: float) -> list[Opening]:
        """Place evenly-spaced windows along a wall."""
        win_w = 1.2
        spacing = 2.5  # center-to-center
        count = max(1, int((length - 1.0) / spacing))
        total = count * win_w + (count - 1) * (spacing - win_w)
        start = (length - total) / 2
        wins = []
        for i in range(count):
            offset = start + i * spacing
            if offset + win_w <= length + 0.01:
                wins.append(_window(offset, win_w))
        return wins

    # South wall (y = min_y, runs east)
    south_ops = _wins(w) if "south" in window_sides else []
    ext_walls.append(Wall(
        id=_uuid(), floor_id=fid, wall_type=WallType.LOAD_BEARING,
        start=Point2D(min_x, min_y), end=Point2D(max_x, min_y),
        thickness=0.25, height=WALL_HEIGHT, base_elevation=z,
        layer=LayerKind.EXTERIOR_ENVELOPE, openings=south_ops,
    ))
    # North wall (y = max_y, runs east)
    north_ops = _wins(w) if "north" in window_sides else []
    ext_walls.append(Wall(
        id=_uuid(), floor_id=fid, wall_type=WallType.LOAD_BEARING,
        start=Point2D(min_x, max_y), end=Point2D(max_x, max_y),
        thickness=0.25, height=WALL_HEIGHT, base_elevation=z,
        layer=LayerKind.EXTERIOR_ENVELOPE, openings=north_ops,
    ))
    # West wall (x = min_x, runs north)
    west_ops = _wins(h) if "west" in window_sides else []
    ext_walls.append(Wall(
        id=_uuid(), floor_id=fid, wall_type=WallType.LOAD_BEARING,
        start=Point2D(min_x, min_y), end=Point2D(min_x, max_y),
        thickness=0.25, height=WALL_HEIGHT, base_elevation=z,
        layer=LayerKind.EXTERIOR_ENVELOPE, openings=west_ops,
    ))
    # East wall (x = max_x, runs north)
    east_ops = _wins(h) if "east" in window_sides else []
    ext_walls.append(Wall(
        id=_uuid(), floor_id=fid, wall_type=WallType.LOAD_BEARING,
        start=Point2D(max_x, min_y), end=Point2D(max_x, max_y),
        thickness=0.25, height=WALL_HEIGHT, base_elevation=z,
        layer=LayerKind.EXTERIOR_ENVELOPE, openings=east_ops,
    ))
    return ext_walls


def _floor_slab(fid: str, spaces: list[Space], z: float = 0.0) -> Slab:
    """Create a floor slab covering all spaces."""
    min_x = min_y = float("inf"); max_x = max_y = float("-inf")
    for sp in spaces:
        bb = sp.bounding_box()
        min_x = min(min_x, bb[0]); min_y = min(min_y, bb[1])
        max_x = max(max_x, bb[2]); max_y = max(max_y, bb[3])
    return Slab(
        id=_uuid(), floor_id=fid, kind=SlabKind.FLOOR,
        boundary=BoundaryWithHoles2D(outer=Polygon2D([
            Point2D(min_x, min_y), Point2D(max_x, min_y),
            Point2D(max_x, max_y), Point2D(min_x, max_y),
        ])),
        thickness=SLAB_THICKNESS, elevation=z,
    )


# ═══════════════════════════════════════════════════════════════════════════════
# Apartment layouts
# ═══════════════════════════════════════════════════════════════════════════════

def _make_model(title: str, building_name: str, spaces_def: list[tuple],
                note: str = "",
                window_sides: set[str] | None = None) -> BuildingModel:
    """Generic builder: takes a list of (name, usage, x, y, w, h) tuples."""
    bid, fid = _uuid(), _uuid()
    spaces = [_rect_space(fid, n, u, x, y, w, h) for n, u, x, y, w, h in spaces_def]
    interior_walls = _derive_walls(fid, spaces)
    exterior_walls = _derive_exterior_walls(fid, spaces, window_sides=window_sides)
    slab = _floor_slab(fid, spaces)
    floor = Floor(id=fid, building_id=bid, level=0, name="Floor Plan",
                  elevation_above_datum=0, floor_to_floor_height=FLOOR_TO_FLOOR,
                  spaces=spaces, walls=interior_walls + exterior_walls, slabs=[slab])
    return BuildingModel(
        schema_version=SCHEMA_VERSION, id=_uuid(), title=title,
        length_unit=LengthUnit.M,
        building=Building(id=bid, name=building_name, typology="residential apartment"),
        floors=[floor], metadata=_meta(note),
    )


def studio_alcove() -> BuildingModel:
    # Pre-war studio: windows on south (street) and west (airshaft)
    return _make_model("Manhattan Alcove Studio", "Pre-war alcove studio, Upper West Side style", [
        ("Living Area",    SpaceUsage.LIVING_ROOM, 0,   0,   4.6, 4.0),
        ("Sleep Alcove",   SpaceUsage.BEDROOM,     4.6, 0,   3.0, 3.4),
        ("Galley Kitchen", SpaceUsage.KITCHEN,     4.6, 3.4, 3.0, 2.4),
        ("Bathroom",       SpaceUsage.BATHROOM,    0,   4.0, 2.4, 1.8),
        ("Closet",         SpaceUsage.CLOSET,      2.4, 4.0, 1.2, 1.2),
        ("Foyer",          SpaceUsage.LOBBY,       2.4, 5.2, 2.2, 1.5),
        ("Hall Closet",    SpaceUsage.CLOSET,      0,   5.8, 2.4, 0.9),
    ], "Classic Manhattan alcove studio ~42 m²",
       window_sides={"south", "west"})


def one_bedroom_prewar() -> BuildingModel:
    # Pre-war 1BR: windows on south and east
    return _make_model("Manhattan Pre-War 1-Bedroom", "Classic 6, doorman building, Midtown East", [
        ("Living Room",    SpaceUsage.LIVING_ROOM, 0,   0,   5.5, 4.6),
        ("Bedroom",        SpaceUsage.BEDROOM,     5.5, 0,   5.2, 4.0),
        ("Eat-In Kitchen", SpaceUsage.KITCHEN,     0,   4.6, 3.7, 2.7),
        ("Bathroom",       SpaceUsage.BATHROOM,    3.7, 4.6, 2.4, 2.7),
        ("WIC",            SpaceUsage.CLOSET,      6.1, 4.0, 2.4, 1.5),
        ("Closet",         SpaceUsage.CLOSET,      8.5, 4.0, 2.2, 1.5),
        ("Foyer",          SpaceUsage.LOBBY,       6.1, 5.5, 4.6, 1.8),
    ], "Pre-war 1-bedroom ~65 m²",
       window_sides={"south", "east"})


def railroad_two_bedroom() -> BuildingModel:
    # Railroad: windows on south (street) and north (airshaft/yard)
    return _make_model("Manhattan Railroad 2-Bedroom", "Railroad, walk-up tenement, East Village", [
        ("Bedroom 1",   SpaceUsage.BEDROOM,     0,    0,   4.0, 4.0),
        ("Living Room", SpaceUsage.LIVING_ROOM, 4.0,  0,   4.3, 4.0),
        ("Bedroom 2",   SpaceUsage.BEDROOM,     8.3,  0,   4.3, 4.0),
        ("Kitchen",     SpaceUsage.KITCHEN,     12.6, 0,   2.6, 4.0),
        ("Bathroom",    SpaceUsage.BATHROOM,    0,    4.0, 2.7, 1.5),
        ("Hallway",     SpaceUsage.HALLWAY,     2.7,  4.0, 8.6, 1.5),
        ("Closets",     SpaceUsage.CLOSET,      11.3, 4.0, 3.9, 1.5),
    ], "Railroad-style 2-bedroom ~79 m²",
       window_sides={"south", "north"})


def luxury_two_bedroom() -> BuildingModel:
    # Luxury high-rise: floor-to-ceiling on south and east (corner unit)
    return _make_model("Manhattan Luxury 2-Bedroom", "New construction, FiDi / Hudson Yards", [
        ("Living / Dining",  SpaceUsage.LIVING_ROOM, 0,    0,   6.7, 5.2),
        ("Primary Bedroom",  SpaceUsage.BEDROOM,     6.7,  0,   7.0, 4.0),
        ("Bedroom 2",        SpaceUsage.BEDROOM,     6.7,  4.0, 4.0, 2.7),
        ("En-Suite",         SpaceUsage.BATHROOM,    10.7, 4.0, 3.0, 2.1),
        ("Open Kitchen",     SpaceUsage.KITCHEN,     0,    5.2, 4.0, 2.7),
        ("Bathroom",         SpaceUsage.BATHROOM,    4.0,  5.2, 2.7, 1.8),
        ("W/D",              SpaceUsage.LAUNDRY,     4.0,  7.0, 2.7, 1.5),
        ("Foyer",            SpaceUsage.LOBBY,       6.7,  6.7, 4.0, 1.8),
        ("WIC",              SpaceUsage.CLOSET,      10.7, 6.1, 1.5, 2.4),
        ("Closet",           SpaceUsage.CLOSET,      12.2, 6.1, 1.5, 2.4),
    ], "Luxury 2BR ~111 m²",
       window_sides={"south", "east"})


LAYOUTS: dict[str, callable] = {
    "studio": studio_alcove, "1br": one_bedroom_prewar,
    "2br": railroad_two_bedroom, "luxury": luxury_two_bedroom,
}


# ═══════════════════════════════════════════════════════════════════════════════
# CLI
# ═══════════════════════════════════════════════════════════════════════════════

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Manhattan Apartment Blueprint & 3D Generator",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "Layouts: studio (~42 m²), 1br (~65 m²), 2br (~79 m²), luxury (~111 m²), all\n"
            "Outputs: blueprint_*.png (2D plan) + model_*.png (3D isometric)\n"
        ),
    )
    parser.add_argument("layout", nargs="?", default="all",
                        choices=[*LAYOUTS.keys(), "all"])
    parser.add_argument("-o", "--output-dir", default=".")
    parser.add_argument("--skip-validation", action="store_true",
                        help="Skip structural validation (render even if invalid)")
    args = parser.parse_args()

    out = Path(args.output_dir); out.mkdir(parents=True, exist_ok=True)
    keys = LAYOUTS.keys() if args.layout == "all" else [args.layout]

    for key in keys:
        model = LAYOUTS[key]()

        # Structural validation — errors halt, warnings print
        if not args.skip_validation:
            validate_or_raise(model)

        bp_path = out / f"blueprint_{key}.png"
        BlueprintRenderer(model).render(str(bp_path))
        print(f"  2D -> {bp_path}")

        iso_path = out / f"model_{key}.png"
        IsometricRenderer(model).render(str(iso_path))
        print(f"  3D -> {iso_path}")

    print("Done.")


if __name__ == "__main__":
    main()
