#!/usr/bin/env python3
"""
Pulp Fiction Coffee Shop — JSON → 2D Blueprint + 3D Isometric + POV Renderer

Loads a BuildingModel JSON file (conforming to building-model-3d-v2.1.ts)
and renders it as:
  1. 2D plan-view blueprint PNG
  2. 3D isometric projection PNG
  3. Perspective POV renders from named ViewPoints (v2.1)

Reuses the dataclass model and renderers from manhattan_blueprint.py.

Generated by: Claude Opus 4.6 (Anthropic)
"""

from __future__ import annotations

import argparse
import json
import math
import sys
from dataclasses import dataclass, field
from pathlib import Path

# Import the data model and renderers from the existing module
from manhattan_blueprint import (
    BlueprintRenderer,
    BuildingModel,
    Building,
    BoundaryWithHoles2D,
    Floor,
    IsometricRenderer,
    LayerKind,
    LengthUnit,
    MaterialSpec,
    Metadata,
    Opening,
    OpeningKind,
    Point2D,
    Point3D,
    Polygon2D,
    Slab,
    SlabKind,
    Space,
    SpaceUsage,
    SwingDirection,
    Wall,
    WallType,
)


# ═══════════════════════════════════════════════════════════════════════════════
# JSON → Dataclass Deserialization
# ═══════════════════════════════════════════════════════════════════════════════

def _enum_or_default(enum_cls, value, default=None):
    """Safely resolve an enum by value, falling back to default."""
    try:
        return enum_cls(value)
    except ValueError:
        return default if default is not None else list(enum_cls)[0]


def _parse_point2d(d: dict) -> Point2D:
    return Point2D(x=d["x"], y=d["y"])


def _parse_point3d(d: dict) -> Point3D:
    return Point3D(x=d["x"], y=d["y"], z=d["z"])


def _parse_polygon2d(d: dict) -> Polygon2D:
    return Polygon2D(vertices=[_parse_point2d(v) for v in d["vertices"]])


def _parse_boundary(d: dict) -> BoundaryWithHoles2D:
    outer = _parse_polygon2d(d["outer"])
    holes = [_parse_polygon2d(h) for h in d.get("holes", [])]
    return BoundaryWithHoles2D(outer=outer, holes=holes)


def _parse_material(d: dict | None) -> MaterialSpec | None:
    if d is None:
        return None
    return MaterialSpec(
        name=d["name"],
        density_kg_per_m3=d.get("densityKgPerM3"),
        fire_rating_minutes=d.get("fireRatingMinutes"),
    )


def _parse_opening(d: dict) -> Opening:
    return Opening(
        id=d["id"],
        kind=_enum_or_default(OpeningKind, d["kind"]),
        offset_along_wall=d["offsetAlongWall"],
        width=d["width"],
        height=d["height"],
        sill_height=d.get("sillHeight", 0.0),
        swing_direction=_enum_or_default(SwingDirection, d.get("swingDirection", "none")),
    )


def _parse_wall(d: dict) -> Wall:
    cl = d["centerline"]
    return Wall(
        id=d["id"],
        floor_id=d["floorId"],
        wall_type=_enum_or_default(WallType, d["wallType"]),
        start=_parse_point2d(cl["start"]),
        end=_parse_point2d(cl["end"]),
        thickness=d["thickness"],
        height=d["height"],
        base_elevation=d["baseElevation"],
        layer=_enum_or_default(LayerKind, d.get("layer", "architectural")),
        material=_parse_material(d.get("material")),
        openings=[_parse_opening(o) for o in d.get("openings", [])],
    )


def _parse_space(d: dict) -> Space:
    return Space(
        id=d["id"],
        floor_id=d["floorId"],
        name=d["name"],
        usage=_enum_or_default(SpaceUsage, d["usage"], SpaceUsage.OTHER),
        boundary=_parse_boundary(d["boundary"]),
        floor_elevation=d["floorElevation"],
        ceiling_elevation=d["ceilingElevation"],
        area_sq_units=d.get("areaSqUnits"),
        volume_cu_units=d.get("volumeCuUnits"),
        finish_floor=d.get("finishFloor"),
    )


def _parse_slab(d: dict) -> Slab:
    return Slab(
        id=d["id"],
        floor_id=d["floorId"],
        kind=_enum_or_default(SlabKind, d["kind"]),
        boundary=_parse_boundary(d["boundary"]),
        thickness=d["thickness"],
        elevation=d["elevation"],
    )


def _parse_floor(d: dict) -> Floor:
    return Floor(
        id=d["id"],
        building_id=d["buildingId"],
        level=d["level"],
        name=d["name"],
        elevation_above_datum=d["elevationAboveDatum"],
        floor_to_floor_height=d["floorToFloorHeight"],
        walls=[_parse_wall(w) for w in d.get("walls", [])],
        spaces=[_parse_space(s) for s in d.get("spaces", [])],
        slabs=[_parse_slab(s) for s in d.get("slabs", [])],
    )


# ═══════════════════════════════════════════════════════════════════════════════
# Terrain + Site Feature dataclasses (v3)
# ═══════════════════════════════════════════════════════════════════════════════

@dataclass
class TerrainTriangle:
    """A single terrain triangle with 3 vertices in site coordinates."""
    v0: Point3D
    v1: Point3D
    v2: Point3D


@dataclass
class TerrainData:
    """Parsed terrain surface — list of triangles."""
    name: str
    triangles: list[TerrainTriangle] = field(default_factory=list)


@dataclass
class SiteFeatureData:
    """Simplified site feature for rendering."""
    name: str
    kind: str
    geometry_type: str  # "point", "polyline", "polygon"
    position: Point3D | None = None
    path_points: list[Point3D] | None = None
    footprint: list[Point2D] | None = None
    height: float = 0.0
    canopy_radius: float = 0.0
    width: float = 0.0


@dataclass
class BuildingOffset:
    """Building placement on site — translation offset."""
    x: float = 0.0
    y: float = 0.0
    z: float = 0.0


def _parse_terrain(d: dict) -> TerrainData:
    mesh = d["mesh"]
    verts = [Point3D(v["x"], v["y"], v["z"]) for v in mesh["vertices"]]
    tris = []
    for t in mesh["triangles"]:
        tris.append(TerrainTriangle(verts[t[0]], verts[t[1]], verts[t[2]]))
    return TerrainData(name=d["name"], triangles=tris)


def _parse_site_feature(d: dict) -> SiteFeatureData:
    sf = SiteFeatureData(
        name=d.get("name", ""),
        kind=d.get("kind", "other"),
        geometry_type=d.get("geometryType", "point"),
    )
    if d.get("position"):
        sf.position = _parse_point3d(d["position"])
    if d.get("path") and d["path"].get("points"):
        sf.path_points = [_parse_point3d(p) for p in d["path"]["points"]]
    if d.get("footprint") and d["footprint"].get("vertices"):
        sf.footprint = [_parse_point2d(v) for v in d["footprint"]["vertices"]]
    sf.height = d.get("heightAboveGround", 0.0)
    sf.canopy_radius = d.get("canopyRadiusUnits", 0.0)
    sf.width = d.get("widthUnits", 0.0)
    return sf


def _parse_building(d: dict) -> Building:
    return Building(
        id=d["id"],
        name=d["name"],
        address=d.get("address"),
        typology=d.get("typology"),
    )


def _parse_metadata(d: dict) -> Metadata:
    return Metadata(
        created_at=d["createdAt"],
        updated_at=d["updatedAt"],
        created_by=d["createdBy"],
        updated_by=d["updatedBy"],
        note=d.get("note"),
    )


@dataclass
class SiteData:
    """All site-level data extracted from a v3 ProjectSite."""
    terrain: list[TerrainData] = field(default_factory=list)
    features: list[SiteFeatureData] = field(default_factory=list)
    placement: BuildingOffset = field(default_factory=BuildingOffset)


def load_building_model(path: str) -> tuple[BuildingModel, list[ViewPoint], SiteData]:
    """Load a BuildingModel, ViewPoints, and site data from a JSON file.

    Supports both v2.x (BuildingModel root) and v3.x (ProjectSite root).
    For v3, extracts the first building from the `buildings` array.
    """
    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)

    site = SiteData()

    # Detect v3 ProjectSite: root has `buildings` array instead of `building`
    if "buildings" in data and isinstance(data["buildings"], list):
        # v3.0.0 ProjectSite — extract first building
        if not data["buildings"]:
            raise ValueError("ProjectSite has no buildings")
        bld = data["buildings"][0]
        model = BuildingModel(
            schema_version=data["schemaVersion"],
            id=bld["id"],
            title=bld.get("title", data.get("name", "Untitled")),
            length_unit=_enum_or_default(LengthUnit, bld.get("lengthUnit", data["lengthUnit"])),
            building=_parse_building(bld["building"]),
            floors=[_parse_floor(fl) for fl in bld["floors"]],
            metadata=_parse_metadata(data["metadata"]),
            origin=_parse_point3d({"x": 0, "y": 0, "z": 0}),
            true_north_deg=bld.get("trueNorthDeg", 0),
            up_axis=bld.get("upAxis", "z"),
        )
        # Merge building-level + site-level viewpoints
        # Building-level viewpoints are in building-local coords — offset to site
        pl = bld.get("placement", {})
        ap = pl.get("anchorPoint", {})
        bx, by, bz = ap.get("x", 0), ap.get("y", 0), ap.get("z", 0)
        viewpoints = []
        for vp_data in bld.get("viewPoints", []):
            vp = _parse_viewpoint(vp_data)
            vp.eye = Point3D(vp.eye.x + bx, vp.eye.y + by, vp.eye.z + bz)
            vp.target = Point3D(vp.target.x + bx, vp.target.y + by, vp.target.z + bz)
            viewpoints.append(vp)
        # Site-level viewpoints are already in site coords
        viewpoints += [_parse_viewpoint(vp) for vp in data.get("viewPoints", [])]

        # Extract terrain
        for ts in data.get("terrainSurfaces", []):
            site.terrain.append(_parse_terrain(ts))

        # Extract site features
        for sf in data.get("features", []):
            site.features.append(_parse_site_feature(sf))

        # Extract building placement offset
        pl = bld.get("placement", {})
        ap = pl.get("anchorPoint", {})
        site.placement = BuildingOffset(
            x=ap.get("x", 0), y=ap.get("y", 0), z=ap.get("z", 0)
        )
    else:
        # v2.x BuildingModel root
        model = BuildingModel(
            schema_version=data["schemaVersion"],
            id=data["id"],
            title=data["title"],
            length_unit=_enum_or_default(LengthUnit, data["lengthUnit"]),
            building=_parse_building(data["building"]),
            floors=[_parse_floor(fl) for fl in data["floors"]],
            metadata=_parse_metadata(data["metadata"]),
            origin=_parse_point3d(data.get("origin", {"x": 0, "y": 0, "z": 0})),
            true_north_deg=data.get("trueNorthDeg", 0),
            up_axis=data.get("upAxis", "z"),
        )
        viewpoints = [_parse_viewpoint(vp) for vp in data.get("viewPoints", [])]

    return model, viewpoints, site


# ═══════════════════════════════════════════════════════════════════════════════
# ViewPoint dataclass (v2.1)
# ═══════════════════════════════════════════════════════════════════════════════

@dataclass
class ViewPoint:
    id: str
    name: str
    eye: Point3D
    target: Point3D
    up: Point3D
    projection: str = "perspective"
    fov_deg: float = 60.0
    ortho_height: float | None = None
    near_clip: float = 0.1
    far_clip: float = 100.0
    note: str | None = None


def _parse_viewpoint(d: dict) -> ViewPoint:
    up = d.get("up", {"x": 0, "y": 0, "z": 1})
    return ViewPoint(
        id=d["id"],
        name=d["name"],
        eye=_parse_point3d(d["eye"]),
        target=_parse_point3d(d["target"]),
        up=_parse_point3d(up),
        projection=d.get("projection", "perspective"),
        fov_deg=d.get("fovDeg", 60.0),
        ortho_height=d.get("orthoHeight"),
        near_clip=d.get("nearClip", 0.1),
        far_clip=d.get("farClip", 100.0),
        note=d.get("note"),
    )


# ═══════════════════════════════════════════════════════════════════════════════
# POV Renderer — perspective/orthographic from a ViewPoint
# ═══════════════════════════════════════════════════════════════════════════════

from PIL import Image, ImageDraw, ImageFont

# Colors for POV rendering
_POV_BG = (18, 28, 48)
_POV_FLOOR = (40, 55, 85)
_POV_CEILING = (30, 42, 68)
_POV_WALL_FRONT = (150, 170, 200)
_POV_WALL_SIDE = (110, 135, 170)
_POV_WALL_TOP = (170, 188, 215)
_POV_OUTLINE = (80, 105, 140)
_POV_WINDOW = (55, 85, 140)
_POV_WINDOW_FRAME = (170, 185, 210)
_POV_DOOR = (25, 38, 62)
_POV_SKY_TOP = (35, 55, 100)
_POV_SKY_BOT = (70, 100, 155)
_POV_GROUND = (32, 45, 70)
_POV_LABEL = (200, 215, 240)
_POV_DIM = (120, 145, 180)

# Terrain + site feature colors
_POV_TERRAIN_A = (38, 52, 78)     # terrain triangle alternating color A
_POV_TERRAIN_B = (42, 58, 84)     # terrain triangle alternating color B
_POV_TERRAIN_EDGE = (50, 68, 95)  # terrain wireframe edge
_POV_PARKING = (45, 55, 75)       # asphalt parking lot
_POV_PARKING_LINE = (70, 80, 100) # parking lot striping
_POV_SIDEWALK = (80, 90, 110)     # concrete sidewalk
_POV_ROAD = (35, 42, 58)          # road asphalt
_POV_ROAD_STRIPE = (90, 100, 120) # road center line
_POV_TREE_TRUNK = (55, 45, 35)    # tree trunk brown
_POV_TREE_CANOPY = (35, 65, 45)   # tree canopy green
_POV_FEATURE_PT = (100, 120, 150) # point feature marker
_POV_UTILITY = (80, 60, 100)      # underground utility purple


def _load_font(size: int) -> ImageFont.FreeTypeFont:
    for p in ["/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
              "/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf",
              "/System/Library/Fonts/Helvetica.ttc"]:
        if Path(p).exists():
            return ImageFont.truetype(p, size)
    return ImageFont.load_default()


def _v3_sub(a: Point3D, b: Point3D) -> tuple[float, float, float]:
    return (a.x - b.x, a.y - b.y, a.z - b.z)


def _v3_cross(a: tuple, b: tuple) -> tuple[float, float, float]:
    return (a[1]*b[2] - a[2]*b[1], a[2]*b[0] - a[0]*b[2], a[0]*b[1] - a[1]*b[0])


def _v3_dot(a: tuple, b: tuple) -> float:
    return a[0]*b[0] + a[1]*b[1] + a[2]*b[2]


def _v3_normalize(v: tuple) -> tuple[float, float, float]:
    mag = math.sqrt(v[0]**2 + v[1]**2 + v[2]**2)
    if mag < 1e-12:
        return (0.0, 0.0, 1.0)
    return (v[0]/mag, v[1]/mag, v[2]/mag)


def _v3_scale(v: tuple, s: float) -> tuple[float, float, float]:
    return (v[0]*s, v[1]*s, v[2]*s)


class POVRenderer:
    """Renders a BuildingModel from a named ViewPoint using software 3D projection."""

    IMG_W = 1600
    IMG_H = 900

    def __init__(self, model: BuildingModel, vp: ViewPoint,
                 site: SiteData | None = None):
        self.model = model
        self.vp = vp
        self.site = site or SiteData()
        self._build_camera()

    def _build_camera(self) -> None:
        """Build a look-at view matrix + perspective projection."""
        vp = self.vp
        # View direction
        fwd = _v3_normalize(_v3_sub(vp.target, vp.eye))
        up = (vp.up.x, vp.up.y, vp.up.z)

        # Camera basis: right, up, forward
        self.cam_right = _v3_normalize(_v3_cross(fwd, up))
        self.cam_up = _v3_normalize(_v3_cross(self.cam_right, fwd))
        self.cam_fwd = fwd
        self.eye = (vp.eye.x, vp.eye.y, vp.eye.z)

        # Perspective params
        self.aspect = self.IMG_W / self.IMG_H
        if vp.projection == "perspective":
            self.fov_scale = 1.0 / math.tan(math.radians(vp.fov_deg / 2))
        else:
            # orthographic/isometric
            h = vp.ortho_height or 20.0
            self.fov_scale = 2.0 / h

    def _project(self, p: Point3D) -> tuple[float, float, float] | None:
        """Project a 3D world point to screen (px_x, px_y, depth). None if behind camera."""
        # World to camera space
        rel = _v3_sub(p, Point3D(*self.eye))
        cx = _v3_dot(rel, self.cam_right)
        cy = _v3_dot(rel, self.cam_up)
        cz = _v3_dot(rel, self.cam_fwd)  # depth along view direction

        if cz < 0.05:
            return None  # behind camera

        if self.vp.projection == "perspective":
            # Perspective divide
            inv_z = self.fov_scale / cz
            sx = cx * inv_z
            sy = cy * inv_z
        else:
            sx = cx * self.fov_scale
            sy = cy * self.fov_scale

        # Normalized device coords → pixel coords
        px = self.IMG_W / 2 + sx * self.IMG_W / (2 * self.aspect)
        py = self.IMG_H / 2 - sy * self.IMG_H / 2

        return (px, py, cz)

    def _project_poly(self, pts: list[Point3D]) -> tuple[list[tuple[int, int]], float] | None:
        """Project N points and return (pixel_points, avg_depth), or None if any behind."""
        projected = []
        total_depth = 0.0
        for p in pts:
            r = self._project(p)
            if r is None:
                return None
            projected.append((int(r[0]), int(r[1])))
            total_depth += r[2]
        return projected, total_depth / len(pts)

    def _project_quad(self, pts: list[Point3D]) -> tuple[list[tuple[int, int]], float] | None:
        return self._project_poly(pts)

    def _project_tri(self, pts: list[Point3D]) -> tuple[list[tuple[int, int]], float] | None:
        return self._project_poly(pts)

    def render(self, path: str) -> str:
        img = Image.new("RGB", (self.IMG_W, self.IMG_H), _POV_BG)
        draw = ImageDraw.Draw(img)

        # Sky gradient
        for y in range(self.IMG_H // 2):
            t = y / (self.IMG_H // 2)
            r = int(_POV_SKY_TOP[0] + (_POV_SKY_BOT[0] - _POV_SKY_TOP[0]) * t)
            g = int(_POV_SKY_TOP[1] + (_POV_SKY_BOT[1] - _POV_SKY_TOP[1]) * t)
            b = int(_POV_SKY_TOP[2] + (_POV_SKY_BOT[2] - _POV_SKY_TOP[2]) * t)
            draw.line([(0, y), (self.IMG_W, y)], fill=(r, g, b))

        # Collect all renderable faces with depths for painter's algorithm
        faces: list[tuple[float, str, list[tuple[int, int]], tuple]] = []
        # (depth, type, pixel_points, color_data)

        ox, oy, oz = self.site.placement.x, self.site.placement.y, self.site.placement.z

        # ── Terrain TIN triangles ────────────────────────────────────────
        for td in self.site.terrain:
            for i, tri in enumerate(td.triangles):
                pts = [tri.v0, tri.v1, tri.v2]
                result = self._project_tri(pts)
                if result:
                    color = _POV_TERRAIN_A if i % 2 == 0 else _POV_TERRAIN_B
                    faces.append((result[1] + 200, "terrain", result[0], color))

        # ── Site features (polygon footprints) ───────────────────────────
        for sf in self.site.features:
            if sf.geometry_type == "polygon" and sf.footprint:
                # Use the terrain base elevation (~30m) but normalize to 0
                fz = 0.01  # just above terrain
                pts = [Point3D(v.x, v.y, fz) for v in sf.footprint]
                result = self._project_quad(pts) if len(pts) == 4 else self._project_tri(pts[:3])
                if result:
                    if sf.kind == "parking_lot":
                        color = _POV_PARKING
                    elif sf.kind in ("existing_structure", "demolished_structure"):
                        color = (55, 60, 75)
                    else:
                        color = _POV_GROUND
                    faces.append((result[1] + 150, "site_poly", result[0], color))

        # ── Building geometry (offset to site coords) ────────────────────
        for floor in self.model.floors:
            z0 = floor.elevation_above_datum

            # Ground plane fallback (only if no terrain)
            if not self.site.terrain:
                ground_pts = [
                    Point3D(-20, -20, z0), Point3D(50, -20, z0),
                    Point3D(50, 40, z0), Point3D(-20, 40, z0),
                ]
                result = self._project_quad(ground_pts)
                if result:
                    faces.append((result[1] + 100, "ground", result[0], _POV_GROUND))

            # Floor slab
            for slab in floor.slabs:
                verts = slab.boundary.outer.vertices
                pts = [Point3D(v.x + ox, v.y + oy, slab.elevation + oz) for v in verts]
                result = self._project_quad(pts)
                if result:
                    faces.append((result[1] + 50, "slab", result[0], _POV_FLOOR))

            # Space floors
            for space in floor.spaces:
                verts = space.boundary.outer.vertices
                pts = [Point3D(v.x + ox, v.y + oy, space.floor_elevation + oz + 0.01) for v in verts]
                result = self._project_quad(pts)
                if result:
                    from manhattan_blueprint import FILL_COLORS, DEFAULT_FILL
                    fill = FILL_COLORS.get(space.usage, DEFAULT_FILL)
                    fill = tuple(min(255, c + 20) for c in fill)
                    faces.append((result[1] + 40, "floor", result[0], fill))

            # Walls (offset applied inside)
            for wall in floor.walls:
                self._collect_wall_faces(faces, wall, ox, oy, oz)

        # Sort by depth — farthest first (painter's algorithm)
        faces.sort(key=lambda f: -f[0])

        # Draw all faces
        for depth, ftype, pixels, color_data in faces:
            if ftype == "terrain":
                draw.polygon(pixels, fill=color_data, outline=_POV_TERRAIN_EDGE)
            elif ftype == "site_poly":
                draw.polygon(pixels, fill=color_data, outline=_POV_PARKING_LINE)
            elif ftype in ("ground", "slab", "floor"):
                draw.polygon(pixels, fill=color_data, outline=_POV_OUTLINE)
            elif ftype == "wall_front":
                draw.polygon(pixels, fill=color_data, outline=_POV_OUTLINE)
            elif ftype == "wall_top":
                draw.polygon(pixels, fill=color_data, outline=_POV_OUTLINE)
            elif ftype == "wall_side":
                draw.polygon(pixels, fill=color_data, outline=_POV_OUTLINE)
            elif ftype == "window":
                draw.polygon(pixels, fill=_POV_WINDOW, outline=_POV_WINDOW_FRAME)
                if len(pixels) == 4:
                    draw.line([pixels[0], pixels[2]], fill=_POV_WINDOW_FRAME, width=1)
                    draw.line([pixels[1], pixels[3]], fill=_POV_WINDOW_FRAME, width=1)
            elif ftype == "door":
                draw.polygon(pixels, fill=_POV_DOOR, outline=_POV_OUTLINE)

        # ── Site features: lines and points (drawn on top of terrain) ────
        self._draw_site_features(draw)

        # Title overlay
        self._draw_overlay(draw)
        img.save(path)
        return path

    def _draw_site_features(self, draw: ImageDraw.Draw) -> None:
        """Draw polyline and point site features on top of the terrain."""
        for sf in self.site.features:
            if sf.geometry_type == "polyline" and sf.path_points:
                # Project and draw the line
                projected = []
                for p in sf.path_points:
                    r = self._project(p)
                    if r:
                        projected.append((int(r[0]), int(r[1])))
                if len(projected) >= 2:
                    if sf.kind == "road":
                        w = max(2, int(sf.width * 2))
                        draw.line(projected, fill=_POV_ROAD, width=w)
                        # Center stripe
                        draw.line(projected, fill=_POV_ROAD_STRIPE, width=1)
                    elif sf.kind == "sidewalk":
                        w = max(1, int(sf.width * 1.5))
                        draw.line(projected, fill=_POV_SIDEWALK, width=w)
                    elif sf.kind == "underground_utility":
                        draw.line(projected, fill=_POV_UTILITY, width=1)
                    else:
                        draw.line(projected, fill=_POV_FEATURE_PT, width=1)

            elif sf.geometry_type == "point" and sf.position:
                r = self._project(sf.position)
                if r:
                    px, py = int(r[0]), int(r[1])
                    if sf.kind in ("tree", "tree_cluster"):
                        # Draw trunk
                        trunk_top = self._project(
                            Point3D(sf.position.x, sf.position.y, sf.position.z + sf.height * 0.6))
                        canopy_center = self._project(
                            Point3D(sf.position.x, sf.position.y, sf.position.z + sf.height * 0.75))
                        if trunk_top and canopy_center:
                            tx, ty = int(trunk_top[0]), int(trunk_top[1])
                            cx, cy = int(canopy_center[0]), int(canopy_center[1])
                            # Trunk line
                            draw.line([(px, py), (tx, ty)], fill=_POV_TREE_TRUNK, width=2)
                            # Canopy circle (approximate size from depth)
                            canopy_px = max(4, int(sf.canopy_radius * 15 / max(1, r[2])))
                            draw.ellipse(
                                [cx - canopy_px, cy - canopy_px, cx + canopy_px, cy + canopy_px],
                                fill=_POV_TREE_CANOPY, outline=(25, 50, 35)
                            )
                    elif sf.kind in ("fire_hydrant", "manhole", "catch_basin"):
                        draw.ellipse([px-3, py-3, px+3, py+3], fill=(180, 50, 50), outline=(200, 70, 70))
                    elif sf.kind == "light_pole":
                        top = self._project(
                            Point3D(sf.position.x, sf.position.y, sf.position.z + sf.height))
                        if top:
                            draw.line([(px, py), (int(top[0]), int(top[1]))],
                                      fill=_POV_FEATURE_PT, width=2)
                            draw.ellipse([int(top[0])-4, int(top[1])-4,
                                          int(top[0])+4, int(top[1])+4],
                                         fill=(200, 200, 140))

    def _collect_wall_faces(self, faces: list, wall: Wall,
                            ox: float = 0, oy: float = 0, oz: float = 0) -> None:
        """Decompose a wall into front/top/side face quads with openings cut out."""
        z0 = wall.base_elevation + oz
        z1 = z0 + wall.height
        wl = wall.length
        if wl < 0.01:
            return

        sx, sy = wall.start.x + ox, wall.start.y + oy
        ex, ey = wall.end.x + ox, wall.end.y + oy
        dx = ex - sx
        dy = ey - sy
        ux, uy = dx / wl, dy / wl
        nx, ny = -uy * wall.thickness / 2, ux * wall.thickness / 2

        bl_o = Point3D(sx + nx, sy + ny, z0)
        br_o = Point3D(ex + nx, ey + ny, z0)
        tl_o = Point3D(sx + nx, sy + ny, z1)
        tr_o = Point3D(ex + nx, ey + ny, z1)

        bl_i = Point3D(sx - nx, sy - ny, z0)
        br_i = Point3D(ex - nx, ey - ny, z0)
        tl_i = Point3D(sx - nx, sy - ny, z1)
        tr_i = Point3D(ex - nx, ey - ny, z1)

        # Decide which face is "front" (facing camera) via dot product with view dir
        face_normal_outer = (nx, ny, 0)
        eye_to_wall = _v3_sub(
            Point3D((wall.start.x + wall.end.x) / 2, (wall.start.y + wall.end.y) / 2, (z0 + z1) / 2),
            Point3D(*self.eye),
        )
        dot_outer = _v3_dot(face_normal_outer, eye_to_wall)

        if dot_outer < 0:
            # Camera sees the outer face
            front_bl, front_br, front_tl, front_tr = bl_o, br_o, tl_o, tr_o
        else:
            # Camera sees the inner face
            front_bl, front_br, front_tl, front_tr = bl_i, br_i, tl_i, tr_i

        # Front face — full wall
        result = self._project_quad([front_bl, front_br, front_tr, front_tl])
        if result:
            faces.append((result[1], "wall_front", result[0], _POV_WALL_FRONT))

        # Top face
        result = self._project_quad([tl_o, tr_o, tr_i, tl_i])
        if result:
            faces.append((result[1] - 0.01, "wall_top", result[0], _POV_WALL_TOP))

        # Side faces (wall ends) — only the one facing the camera
        for side_pts in [[bl_o, bl_i, tl_i, tl_o], [br_i, br_o, tr_o, tr_i]]:
            mid = Point3D(
                sum(p.x for p in side_pts) / 4,
                sum(p.y for p in side_pts) / 4,
                sum(p.z for p in side_pts) / 4,
            )
            to_eye = _v3_sub(Point3D(*self.eye), mid)
            side_edge = _v3_sub(side_pts[1], side_pts[0])
            side_up = (0, 0, 1)
            side_n = _v3_cross(side_edge, side_up)
            if _v3_dot(side_n, to_eye) > 0:
                r = self._project_quad(side_pts)
                if r:
                    faces.append((r[1], "wall_side", r[0], _POV_WALL_SIDE))

        # Openings — rendered ON TOP of the wall face (closer depth)
        for op in wall.openings:
            t0 = op.offset_along_wall / wl
            t1 = (op.offset_along_wall + op.width) / wl
            oz_bot = z0 + op.sill_height
            oz_top = oz_bot + op.height

            if dot_outer < 0:
                o_bl = Point3D(bl_o.x + (br_o.x - bl_o.x) * t0, bl_o.y + (br_o.y - bl_o.y) * t0, oz_bot)
                o_br = Point3D(bl_o.x + (br_o.x - bl_o.x) * t1, bl_o.y + (br_o.y - bl_o.y) * t1, oz_bot)
                o_tr = Point3D(bl_o.x + (br_o.x - bl_o.x) * t1, bl_o.y + (br_o.y - bl_o.y) * t1, oz_top)
                o_tl = Point3D(bl_o.x + (br_o.x - bl_o.x) * t0, bl_o.y + (br_o.y - bl_o.y) * t0, oz_top)
            else:
                o_bl = Point3D(bl_i.x + (br_i.x - bl_i.x) * t0, bl_i.y + (br_i.y - bl_i.y) * t0, oz_bot)
                o_br = Point3D(bl_i.x + (br_i.x - bl_i.x) * t1, bl_i.y + (br_i.y - bl_i.y) * t1, oz_bot)
                o_tr = Point3D(bl_i.x + (br_i.x - bl_i.x) * t1, bl_i.y + (br_i.y - bl_i.y) * t1, oz_top)
                o_tl = Point3D(bl_i.x + (br_i.x - bl_i.x) * t0, bl_i.y + (br_i.y - bl_i.y) * t0, oz_top)

            r = self._project_quad([o_bl, o_br, o_tr, o_tl])
            if r:
                ftype = "window" if op.kind == OpeningKind.WINDOW else "door"
                faces.append((r[1] - 0.05, ftype, r[0], None))

    def _draw_overlay(self, draw: ImageDraw.Draw) -> None:
        """Draw title and viewpoint name overlay."""
        ft = _load_font(18)
        fs = _load_font(13)
        fn = _load_font(11)

        # Semi-transparent bar at top
        for y in range(50):
            alpha = max(0, 200 - y * 4)
            c = tuple(max(0, min(255, int(_POV_BG[i] * alpha / 255))) for i in range(3))
            draw.line([(0, y), (self.IMG_W, y)], fill=c)

        draw.text((20, 8), self.vp.name, fill=_POV_LABEL, font=ft)
        draw.text((20, 30), self.model.title, fill=_POV_DIM, font=fs)

        # Viewpoint info bottom-left
        info = f"eye=({self.vp.eye.x:.1f}, {self.vp.eye.y:.1f}, {self.vp.eye.z:.1f})  " \
               f"fov={self.vp.fov_deg:.0f}°  {self.vp.projection}"
        draw.text((20, self.IMG_H - 25), info, fill=_POV_DIM, font=fn)

        # Note in bottom-right if present
        if self.vp.note:
            note_text = self.vp.note[:100] + ("..." if len(self.vp.note) > 100 else "")
            bb = fn.getbbox(note_text)
            tw = bb[2] - bb[0]
            draw.text((self.IMG_W - tw - 20, self.IMG_H - 25), note_text, fill=_POV_DIM, font=fn)


# ═══════════════════════════════════════════════════════════════════════════════
# Diner-specific color palette override
# ═══════════════════════════════════════════════════════════════════════════════

def _apply_diner_palette():
    """Extend FILL_COLORS with diner-relevant SpaceUsage mappings."""
    import manhattan_blueprint as mb

    # The coffee shop uses SpaceUsage.commercial, .lobby, .restroom, .storage
    # which aren't in the default apartment palette — add warm diner tones
    extra = {
        SpaceUsage.OTHER: (65, 85, 115),       # general commercial
    }
    # Patch the module-level dict so renderers pick it up
    for k, v in extra.items():
        if k not in mb.FILL_COLORS:
            mb.FILL_COLORS[k] = v


# ═══════════════════════════════════════════════════════════════════════════════
# Main
# ═══════════════════════════════════════════════════════════════════════════════

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Render a BuildingModel JSON as 2D blueprint + 3D isometric + POV PNGs"
    )
    parser.add_argument(
        "json_file",
        nargs="?",
        default=str(Path(__file__).parent / "pulp-fiction-coffee-shop.json"),
        help="Path to the BuildingModel JSON file (default: pulp-fiction-coffee-shop.json)",
    )
    parser.add_argument(
        "-o", "--output-dir",
        default=str(Path(__file__).parent / "output"),
        help="Output directory for rendered PNGs (default: ./output)",
    )
    parser.add_argument(
        "--blueprint-only", action="store_true",
        help="Only render the 2D blueprint (skip 3D isometric and POVs)",
    )
    parser.add_argument(
        "--iso-only", action="store_true",
        help="Only render the 3D isometric (skip 2D blueprint and POVs)",
    )
    parser.add_argument(
        "--pov-only", action="store_true",
        help="Only render POV viewpoints (skip blueprint and isometric)",
    )
    parser.add_argument(
        "--pov", type=str, default=None,
        help="Render specific viewpoint(s) by name or index (comma-separated). "
             "Use 'all' for all viewpoints, or e.g. '0,2' or 'Booth,Robbery'.",
    )
    parser.add_argument(
        "--scale", type=float, default=40,
        help="Isometric renderer scale factor (default: 40)",
    )
    args = parser.parse_args()

    json_path = Path(args.json_file)
    if not json_path.exists():
        print(f"Error: JSON file not found: {json_path}", file=sys.stderr)
        sys.exit(1)

    out_dir = Path(args.output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    stem = json_path.stem

    print(f"Loading model from {json_path} ...")
    model, viewpoints, site = load_building_model(str(json_path))
    _apply_diner_palette()

    total_area = sum(s.computed_area() for fl in model.floors for s in fl.spaces)
    total_walls = sum(len(fl.walls) for fl in model.floors)
    total_openings = sum(len(w.openings) for fl in model.floors for w in fl.walls)
    total_spaces = sum(len(fl.spaces) for fl in model.floors)

    print(f"  Title:    {model.title}")
    print(f"  Building: {model.building.name}")
    print(f"  Floors:   {len(model.floors)}")
    print(f"  Spaces:   {total_spaces}  ({total_area:.0f} m²)")
    print(f"  Walls:    {total_walls}  (openings: {total_openings})")
    if site.terrain:
        ttris = sum(len(t.triangles) for t in site.terrain)
        print(f"  Terrain:  {len(site.terrain)} surface(s), {ttris} triangles")
    if site.features:
        print(f"  Features: {len(site.features)}")
    if viewpoints:
        print(f"  ViewPoints: {len(viewpoints)}")
        for i, vp in enumerate(viewpoints):
            print(f"    [{i}] {vp.name} ({vp.projection})")
    print()

    # Determine which renders to produce
    do_blueprint = not (args.iso_only or args.pov_only)
    do_iso = not (args.blueprint_only or args.pov_only)
    do_pov = args.pov_only or args.pov is not None

    # If --pov-only but no --pov specified, render all
    if args.pov_only and args.pov is None:
        args.pov = "all"

    # If no specific flags, render everything including all POVs
    if not (args.blueprint_only or args.iso_only or args.pov_only) and args.pov is None:
        do_pov = True
        args.pov = "all"

    if do_blueprint:
        bp_path = out_dir / f"{stem}-blueprint.png"
        print(f"Rendering 2D blueprint → {bp_path} ...")
        renderer_2d = BlueprintRenderer(model)
        renderer_2d.render(str(bp_path))
        print(f"  Done. {renderer_2d.img_w()}×{renderer_2d.img_h()} px")

    if do_iso:
        iso_path = out_dir / f"{stem}-isometric.png"
        print(f"Rendering 3D isometric → {iso_path} ...")
        renderer_3d = IsometricRenderer(model, scale=args.scale)
        renderer_3d.render(str(iso_path))
        print(f"  Done. {renderer_3d.img_w()}×{renderer_3d.img_h()} px")

    if do_pov and viewpoints:
        # Resolve which viewpoints to render
        selected = _resolve_viewpoints(viewpoints, args.pov)
        if not selected:
            print("  No matching viewpoints found.", file=sys.stderr)
        for vp in selected:
            safe_name = vp.name.lower().replace(" ", "-").replace("/", "-")
            safe_name = "".join(c for c in safe_name if c.isalnum() or c in "-_")[:60]
            pov_path = out_dir / f"{stem}-pov-{safe_name}.png"
            print(f"Rendering POV '{vp.name}' → {pov_path} ...")
            renderer = POVRenderer(model, vp, site=site)
            renderer.render(str(pov_path))
            print(f"  Done. {renderer.IMG_W}×{renderer.IMG_H} px")

    print("\nAll renders complete.")


def _resolve_viewpoints(viewpoints: list[ViewPoint], spec: str) -> list[ViewPoint]:
    """Resolve a viewpoint specifier to a list of ViewPoints."""
    if spec.lower() == "all":
        return viewpoints

    selected = []
    for part in spec.split(","):
        part = part.strip()
        # Try as index
        try:
            idx = int(part)
            if 0 <= idx < len(viewpoints):
                selected.append(viewpoints[idx])
                continue
        except ValueError:
            pass
        # Try as substring match on name
        for vp in viewpoints:
            if part.lower() in vp.name.lower() and vp not in selected:
                selected.append(vp)
    return selected


if __name__ == "__main__":
    main()
