#!/usr/bin/env python3
"""Generate multiple valid HumanBody JSON instances conforming to the
session-3/schemas/src/ TypeScript (Zod) schema v3.0.0.

Targets: matching the detail level of session-3/examples/david.json:
  - 52 bones (full vertebral column, bilateral limbs, hands, feet)
  - 24 joints with axes and ROM limits
  - 94 tendons, 48 muscles with pennation/Fmax/fiberDirection/antagonists
  - 9 organs, 20 vessels, 13 nerves, 12 ligaments, 9 cartilage
  - 15 segments, currentPose, savedPoses, loadingConditions (28 forces)
  - derivationGraph (10 rules), constitutiveLaws (11 laws), hair

All generated instances satisfy:
  - Referential integrity across all subsystems
  - Anthropometric ratio constraints
  - Unit quaternions and unit vectors where required
  - Discriminated union fields set correctly

Usage:
    python3 tools/generate_human_body.py                  # 3 bodies → stdout
    python3 tools/generate_human_body.py -n 5             # 5 bodies → stdout
    python3 tools/generate_human_body.py -n 2 -o out/     # 2 bodies → out/body_*.json
    python3 tools/generate_human_body.py -n 1 --pretty    # 1 body, indented

Generated by: Claude Opus 4.6 (1M context)
"""

from __future__ import annotations

import argparse
import json
import math
import random
import sys
import uuid
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

SCHEMA_VERSION = "3.0.0"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def uid() -> str:
    return str(uuid.uuid4())

def vec3(x: float = 0, y: float = 0, z: float = 0) -> dict:
    return {"x": round(x, 6), "y": round(y, 6), "z": round(z, 6)}

def unit_vec3(x: float = 0, y: float = 1, z: float = 0) -> dict:
    mag = math.sqrt(x * x + y * y + z * z) or 1.0
    return {"x": round(x / mag, 6), "y": round(y / mag, 6), "z": round(z / mag, 6)}

def identity_quat() -> dict:
    return {"w": 1.0, "x": 0.0, "y": 0.0, "z": 0.0}

def small_tilt_quat(pitch_deg: float = 0, yaw_deg: float = 0, roll_deg: float = 0) -> dict:
    """Small rotation quaternion for poses."""
    p, y, r = math.radians(pitch_deg / 2), math.radians(yaw_deg / 2), math.radians(roll_deg / 2)
    w = math.cos(p) * math.cos(y) * math.cos(r) + math.sin(p) * math.sin(y) * math.sin(r)
    qx = math.sin(p) * math.cos(y) * math.cos(r) - math.cos(p) * math.sin(y) * math.sin(r)
    qy = math.cos(p) * math.sin(y) * math.cos(r) + math.sin(p) * math.cos(y) * math.sin(r)
    qz = math.cos(p) * math.cos(y) * math.sin(r) - math.sin(p) * math.sin(y) * math.cos(r)
    mag = math.sqrt(w*w + qx*qx + qy*qy + qz*qz)
    return {"w": round(w/mag, 4), "x": round(qx/mag, 4), "y": round(qy/mag, 4), "z": round(qz/mag, 4)}

def rigid_pose(px: float = 0, py: float = 0, pz: float = 0, q: dict | None = None) -> dict:
    return {"position": vec3(px, py, pz), "orientation": q or identity_quat()}

def tf(px: float = 0, py: float = 0, pz: float = 0) -> dict:
    return {"position": vec3(px, py, pz), "rotation": vec3(0, 0, 0), "scale": vec3(1, 1, 1)}

def color(r: int = 200, g: int = 180, b: int = 160, a: float = 1.0) -> dict:
    return {"r": r, "g": g, "b": b, "a": a}

def sym_tensor(xx: float, yy: float, zz: float) -> dict:
    return {"xx": xx, "yy": yy, "zz": zz, "xy": 0, "xz": 0, "yz": 0}

SEX_OPTIONS = ["male", "female", "intersex"]
G = 981  # cm/s²


# ---------------------------------------------------------------------------
# Named bone index constants — makes cross-references readable
# ---------------------------------------------------------------------------
# Order matches david.json: 0–51

B_PELVIS, B_SACRUM, B_SKULL, B_STERNUM = 0, 1, 2, 3
B_RIBS_R, B_RIBS_L = 4, 5
B_SCAP_R, B_SCAP_L = 6, 7
B_CLAV_R, B_CLAV_L = 8, 9
B_HUMER_R, B_HUMER_L = 10, 11
B_RAD_R, B_RAD_L = 12, 13
B_ULNA_R, B_ULNA_L = 14, 15
B_FEM_R, B_FEM_L = 16, 17
B_PAT_R, B_PAT_L = 18, 19
B_TIB_R, B_TIB_L = 20, 21
B_FIB_R, B_FIB_L = 22, 23
# vertebrae L5..L1 = 24..28, T12..T1 = 29..40, C7..C1 = 41..47
B_L5 = 24
B_L1 = 28
B_T12 = 29
B_T1 = 40
B_C7 = 41
B_C1 = 47
B_HAND_R, B_HAND_L = 48, 49
B_FOOT_R, B_FOOT_L = 50, 51

# Joint index constants
J_HIP_R, J_HIP_L = 0, 1
J_KNEE_R, J_KNEE_L = 2, 3
J_SHOULDER_R, J_SHOULDER_L = 4, 5
J_ELBOW_R, J_ELBOW_L = 6, 7
J_L5S1 = 8
J_WRIST_R, J_WRIST_L = 20, 21
J_ANKLE_R, J_ANKLE_L = 22, 23


# ---------------------------------------------------------------------------
# ID Registry
# ---------------------------------------------------------------------------

@dataclass
class Reg:
    bone_ids: list[str] = field(default_factory=list)
    joint_ids: list[str] = field(default_factory=list)
    tendon_ids: list[str] = field(default_factory=list)
    muscle_ids: list[str] = field(default_factory=list)
    organ_ids: list[str] = field(default_factory=list)
    vessel_ids: list[str] = field(default_factory=list)
    nerve_ids: list[str] = field(default_factory=list)
    segment_ids: list[str] = field(default_factory=list)
    ligament_ids: list[str] = field(default_factory=list)
    cartilage_ids: list[str] = field(default_factory=list)
    # Named maps for muscle cross-references
    muscle_name_to_idx: dict[str, int] = field(default_factory=dict)
    tendon_name_to_idx: dict[str, int] = field(default_factory=dict)
    nerve_name_to_idx: dict[str, int] = field(default_factory=dict)
    pose_id: str = ""
    saved_pose_id: str = ""


# ---------------------------------------------------------------------------
# Proportions
# ---------------------------------------------------------------------------

def gen_proportions(v: int = 0) -> dict:
    sex = SEX_OPTIONS[v % len(SEX_OPTIONS)]
    height = random.uniform(160, 190)
    weight = random.uniform(60, 95)
    arm_length = height * random.uniform(0.42, 0.48)
    leg_length = height * random.uniform(0.46, 0.52)
    muscle_pct = random.uniform(30, 45)
    fat_pct = random.uniform(8, min(30, 74 - muscle_pct))
    return {
        "biologicalSex": sex,
        "totalHeight": round(height, 0),
        "weight": round(weight, 0),
        "shoulderWidth": round(random.uniform(38, 48), 0),
        "armLength": round(arm_length, 0),
        "legLength": round(leg_length, 0),
        "headCircumference": round(random.uniform(54, 59), 0),
        "muscleMassPercentage": round(muscle_pct, 0),
        "fatPercentage": round(fat_pct, 0),
    }


# ---------------------------------------------------------------------------
# Skeleton — 52 bones
# ---------------------------------------------------------------------------

BONE_DEFS: list[tuple[str, str, str, int | None, float, float, float, float, tuple[float, float, float]]] = [
    # (name, classification, region, parent_idx, length, width, depth, mass, (x,y,z))
    ("Pelvis", "irregular", "appendicular_pelvic", None, 18, 28, 16, 580, (0, 95, 0)),
    ("Sacrum", "irregular", "axial_vertebral", B_PELVIS, 12, 10, 3, 180, (0, 90, -3)),
    ("Skull", "flat", "axial_cranium", B_C1, 22, 15, 19, 680, (0, 165, 0)),
    ("Sternum", "flat", "axial_thorax", 35, 17, 5, 1.5, 40, (0, 130, 5)),  # parent=T6
    ("Ribs (R)", "flat", "axial_thorax", 35, 25, 1.2, 0.8, 140, (-10, 130, 0)),
    ("Ribs (L)", "flat", "axial_thorax", 35, 25, 1.2, 0.8, 140, (10, 130, 0)),
    ("Scapula (R)", "flat", "appendicular_pectoral", 35, 15, 10, 1, 60, (-18, 145, -5)),
    ("Scapula (L)", "flat", "appendicular_pectoral", 35, 15, 10, 1, 60, (18, 145, -5)),
    ("Clavicle (R)", "long", "appendicular_pectoral", B_STERNUM, 15, 1.3, 1.1, 25, (-8, 150, 3)),
    ("Clavicle (L)", "long", "appendicular_pectoral", B_STERNUM, 15, 1.3, 1.1, 25, (8, 150, 3)),
    ("Humerus (R)", "long", "appendicular_upper", B_SCAP_R, 36, 2.2, 2, 200, (-23, 148, 0)),
    ("Humerus (L)", "long", "appendicular_upper", B_SCAP_L, 36, 2.2, 2, 200, (23, 148, 0)),
    ("Radius (R)", "long", "appendicular_upper", B_HUMER_R, 26, 1.6, 1.4, 60, (-25, 112, 2)),
    ("Radius (L)", "long", "appendicular_upper", B_HUMER_L, 26, 1.6, 1.4, 60, (25, 112, 2)),
    ("Ulna (R)", "long", "appendicular_upper", B_HUMER_R, 28, 1.5, 1.3, 65, (-24, 112, -1)),
    ("Ulna (L)", "long", "appendicular_upper", B_HUMER_L, 28, 1.5, 1.3, 65, (24, 112, -1)),
    ("Femur (R)", "long", "appendicular_lower", B_PELVIS, 45, 3.2, 2.8, 450, (-9, 92, 0)),
    ("Femur (L)", "long", "appendicular_lower", B_PELVIS, 45, 3.2, 2.8, 450, (9, 92, 0)),
    ("Patella (R)", "sesamoid", "appendicular_lower", B_FEM_R, 4, 4.5, 2, 25, (-9, 50, 3)),
    ("Patella (L)", "sesamoid", "appendicular_lower", B_FEM_L, 4, 4.5, 2, 25, (9, 50, 3)),
    ("Tibia (R)", "long", "appendicular_lower", B_FEM_R, 40, 2.8, 2.4, 340, (-9, 47, 0)),
    ("Tibia (L)", "long", "appendicular_lower", B_FEM_L, 40, 2.8, 2.4, 340, (9, 47, 0)),
    ("Fibula (R)", "long", "appendicular_lower", B_TIB_R, 38, 1.2, 1, 55, (-12, 47, 0)),
    ("Fibula (L)", "long", "appendicular_lower", B_TIB_L, 38, 1.2, 1, 55, (12, 47, 0)),
]
# Lumbar vertebrae L5–L1 (indices 24–28)
for i, level in enumerate(range(5, 0, -1)):
    parent = B_SACRUM if i == 0 else (B_L5 + i - 1)
    y = 95 + i * 3.6
    BONE_DEFS.append((f"L{level} vertebra", "irregular", "axial_vertebral", parent, 3.2, 5, 3.5, 40, (0, y, -2)))

# Thoracic vertebrae T12–T1 (indices 29–40)
for i, level in enumerate(range(12, 0, -1)):
    parent = B_L1 if i == 0 else (B_T12 + i - 1)
    y = 113 + i * 2.3
    BONE_DEFS.append((f"T{level} vertebra", "irregular", "axial_vertebral", parent, 2.3, 4.5, 3, 23, (0, y, -2)))

# Cervical vertebrae C7–C1 (indices 41–47)
for i, level in enumerate(range(7, 0, -1)):
    name = f"C{level} vertebra" if level > 2 else ("C2 axis" if level == 2 else "C1 atlas")
    parent = B_T1 if i == 0 else (B_C7 + i - 1)
    y = 155 + i * 1.7
    BONE_DEFS.append((name, "irregular", "axial_vertebral", parent, 1.7, 3, 2.5, 11, (0, y, 0)))

# Hands and Feet (indices 48–51)
BONE_DEFS.append(("Hand (R)", "short", "appendicular_upper", B_RAD_R, 19, 8.5, 2.5, 400, (-26, 86, 3)))
BONE_DEFS.append(("Hand (L)", "short", "appendicular_upper", B_RAD_L, 19, 8.5, 2.5, 400, (26, 86, 3)))
BONE_DEFS.append(("Foot (R)", "short", "appendicular_lower", B_TIB_R, 26, 9, 7, 840, (-9, 0, 5)))
BONE_DEFS.append(("Foot (L)", "short", "appendicular_lower", B_TIB_L, 26, 9, 7, 840, (9, 0, 5)))

assert len(BONE_DEFS) == 52


def gen_skeleton(r: Reg) -> list[dict]:
    # First pass: assign IDs
    for _ in BONE_DEFS:
        r.bone_ids.append(uid())
    # Second pass: build bone objects (all IDs now exist for forward refs)
    bones = []
    for i, (name, cls, region, parent_idx, length, width, depth, mass, pos) in enumerate(BONE_DEFS):
        bones.append({
            "id": r.bone_ids[i], "name": name, "classification": cls, "region": region,
            "transform": tf(*pos),
            "length": length, "width": width, "depth": depth, "mass": mass,
            "parentBoneId": r.bone_ids[parent_idx] if parent_idx is not None else None,
        })
    return bones


# ---------------------------------------------------------------------------
# Joints — 24
# ---------------------------------------------------------------------------

# (name, type, bone_idxs, dof, axes, limits)
JOINT_DEFS: list[tuple[str, str, list[int], int, dict | None, dict | None]] = [
    ("Hip (R)", "ball_and_socket", [B_PELVIS, B_FEM_R], 3,
     {"primary": vec3(0, 0, 1), "secondary": vec3(1, 0, 0), "tertiary": vec3(0, 1, 0)},
     {"flexionExtension": {"min": -15, "max": 125}, "abductionAdduction": {"min": -30, "max": 45}, "internalExternalRotation": {"min": -45, "max": 45}}),
    ("Hip (L)", "ball_and_socket", [B_PELVIS, B_FEM_L], 3,
     {"primary": vec3(0, 0, 1), "secondary": vec3(1, 0, 0), "tertiary": vec3(0, 1, 0)},
     {"flexionExtension": {"min": -15, "max": 125}, "abductionAdduction": {"min": -30, "max": 45}, "internalExternalRotation": {"min": -45, "max": 45}}),
    ("Knee (R)", "hinge", [B_FEM_R, B_TIB_R, B_PAT_R], 1,
     {"primary": vec3(0, 0, 1)},
     {"flexionExtension": {"min": 0, "max": 140}}),
    ("Knee (L)", "hinge", [B_FEM_L, B_TIB_L, B_PAT_L], 1,
     {"primary": vec3(0, 0, 1)},
     {"flexionExtension": {"min": 0, "max": 140}}),
    ("Shoulder (R)", "ball_and_socket", [B_SCAP_R, B_HUMER_R], 3,
     {"primary": vec3(0, 0, 1), "secondary": vec3(1, 0, 0), "tertiary": vec3(0, 1, 0)},
     {"flexionExtension": {"min": -60, "max": 180}, "abductionAdduction": {"min": 0, "max": 180}, "internalExternalRotation": {"min": -90, "max": 90}}),
    ("Shoulder (L)", "ball_and_socket", [B_SCAP_L, B_HUMER_L], 3,
     {"primary": vec3(0, 0, 1), "secondary": vec3(1, 0, 0), "tertiary": vec3(0, 1, 0)},
     {"flexionExtension": {"min": -60, "max": 180}, "abductionAdduction": {"min": 0, "max": 180}, "internalExternalRotation": {"min": -90, "max": 90}}),
    ("Elbow (R)", "hinge", [B_HUMER_R, B_RAD_R, B_ULNA_R], 1,
     {"primary": vec3(0, 0, 1)}, {"flexionExtension": {"min": 0, "max": 150}}),
    ("Elbow (L)", "hinge", [B_HUMER_L, B_RAD_L, B_ULNA_L], 1,
     {"primary": vec3(0, 0, 1)}, {"flexionExtension": {"min": 0, "max": 150}}),
    ("L5-S1 lumbosacral", "cartilaginous", [B_SACRUM, B_L5], 3, None,
     {"flexionExtension": {"min": -5, "max": 15}, "abductionAdduction": {"min": -3, "max": 3}, "internalExternalRotation": {"min": -3, "max": 3}}),
    ("L5-L4 intervertebral", "cartilaginous", [B_L5, B_L5 + 1], 3, None,
     {"flexionExtension": {"min": -3, "max": 12}, "abductionAdduction": {"min": -3, "max": 3}}),
    ("L4-L3 intervertebral", "cartilaginous", [B_L5 + 1, B_L5 + 2], 3, None,
     {"flexionExtension": {"min": -3, "max": 12}, "abductionAdduction": {"min": -3, "max": 3}}),
    ("L3-L2 intervertebral", "cartilaginous", [B_L5 + 2, B_L5 + 3], 3, None,
     {"flexionExtension": {"min": -3, "max": 12}, "abductionAdduction": {"min": -3, "max": 3}}),
    ("L2-L1 intervertebral", "cartilaginous", [B_L5 + 3, B_L1], 3, None,
     {"flexionExtension": {"min": -3, "max": 12}, "abductionAdduction": {"min": -3, "max": 3}}),
    ("T12-L1 thoracolumbar", "cartilaginous", [B_L1, B_T12], 3, None,
     {"flexionExtension": {"min": -2, "max": 8}}),
    ("T12-T11 intervertebral", "cartilaginous", [B_T12, B_T12 + 1], 3, None,
     {"flexionExtension": {"min": -2, "max": 5}}),
    ("T9-T8 intervertebral", "cartilaginous", [B_T12 + 3, B_T12 + 4], 3, None,
     {"flexionExtension": {"min": -2, "max": 5}}),
    ("T5-T4 intervertebral", "cartilaginous", [B_T12 + 7, B_T12 + 8], 3, None,
     {"flexionExtension": {"min": -2, "max": 5}}),
    ("T2-T1 intervertebral", "cartilaginous", [B_T12 + 10, B_T1], 3, None,
     {"flexionExtension": {"min": -2, "max": 5}}),
    ("C7-T1 cervicothoracic", "cartilaginous", [B_T1, B_C7], 3, None,
     {"flexionExtension": {"min": -5, "max": 10}}),
    ("C1-C2 atlantoaxial", "pivot", [B_C1, B_C1 - 1], 1, None,
     {"internalExternalRotation": {"min": -45, "max": 45}}),
    ("Wrist (R)", "condyloid", [B_RAD_R, B_ULNA_R, B_HAND_R], 2, None,
     {"flexionExtension": {"min": -80, "max": 80}, "abductionAdduction": {"min": -20, "max": 35}}),
    ("Wrist (L)", "condyloid", [B_RAD_L, B_ULNA_L, B_HAND_L], 2, None,
     {"flexionExtension": {"min": -80, "max": 80}, "abductionAdduction": {"min": -20, "max": 35}}),
    ("Ankle (R)", "hinge", [B_TIB_R, B_FIB_R, B_FOOT_R], 1, None,
     {"flexionExtension": {"min": -20, "max": 50}}),
    ("Ankle (L)", "hinge", [B_TIB_L, B_FIB_L, B_FOOT_L], 1, None,
     {"flexionExtension": {"min": -20, "max": 50}}),
]
assert len(JOINT_DEFS) == 24


def gen_joints(r: Reg) -> list[dict]:
    joints = []
    for name, jtype, bone_idxs, dof, axes, limits in JOINT_DEFS:
        jid = uid()
        r.joint_ids.append(jid)
        j: dict[str, Any] = {
            "id": jid, "name": name, "type": jtype,
            "transform": tf(),
            "connectedBoneIds": [r.bone_ids[i] for i in bone_idxs],
            "degreesOfFreedom": dof,
        }
        if axes:
            j["axes"] = axes
        if limits:
            j["limits"] = limits
        joints.append(j)
    return joints


# ---------------------------------------------------------------------------
# Tendons — 94 (origin + insertion per muscle, some named)
# ---------------------------------------------------------------------------

# Each entry: (name, attached_bone_idx, length, csa_or_None)
# We build these dynamically from muscle defs below, but first define
# named tendons that are shared or have special names

def _make_tendon(r: Reg, name: str, bone_idx: int, length: float, csa: float | None = None) -> dict:
    tid = uid()
    r.tendon_ids.append(tid)
    r.tendon_name_to_idx[name] = len(r.tendon_ids) - 1
    t: dict[str, Any] = {
        "id": tid, "name": name,
        "attachedBoneId": r.bone_ids[bone_idx],
        "localPosition": vec3(random.uniform(-1, 1), random.uniform(-1, 1), random.uniform(-1, 1)),
        "length": length,
    }
    if csa is not None:
        t["crossSectionalArea"] = csa
    return t


# ---------------------------------------------------------------------------
# Muscles — 48 (bilateral) with full properties
# ---------------------------------------------------------------------------

# (name, region, arch, origin_bone, insert_bone, actions, secondary_actions,
#  spinal, nerve, artery, length, volume, mass, fmax, penn_or_None,
#  fiber_dir, antagonist_names, synergist_names,
#  origin_tendon_name, insert_tendon_name, origin_tendon_csa, insert_tendon_csa)

MuscleSpec = tuple[str, str, str, int, int, list[str], list[str] | None,
                   list[str], str, str, float, float, float, float, float | None,
                   tuple[float, float, float], list[str], list[str],
                   str | None, str | None, float | None, float | None]

def _bilateral(defs: list[MuscleSpec]) -> list[MuscleSpec]:
    """Expand unilateral defs to bilateral (R) + (L) where appropriate."""
    result: list[MuscleSpec] = []
    for d in defs:
        name = d[0]
        if "(R)" in name or "(L)" in name or name in ("Rectus Abdominis", "Diaphragm"):
            result.append(d)
        else:
            # Make (R) and (L) versions
            r_def = list(d)
            l_def = list(d)
            r_def[0] = f"{name} (R)"
            l_def[0] = f"{name} (L)"
            # Mirror x-components of fiber direction
            fx, fy, fz = d[15]
            l_def[15] = (-fx if fx != 0 else 0, fy, fz)
            # Mirror antagonist/synergist names
            r_antag = [n + " (R)" if not n.endswith(")") else n for n in d[16]]
            l_antag = [n.replace("(R)", "(L)") if "(R)" in n else (n + " (L)" if not n.endswith(")") else n) for n in d[16]]
            r_syn = [n + " (R)" if not n.endswith(")") else n for n in d[17]]
            l_syn = [n.replace("(R)", "(L)") if "(R)" in n else (n + " (L)" if not n.endswith(")") else n) for n in d[17]]
            r_def[16] = r_antag
            l_def[16] = l_antag
            r_def[17] = r_syn
            l_def[17] = l_syn
            result.append(tuple(r_def))
            result.append(tuple(l_def))
    return result

# Unilateral definitions (will be expanded to bilateral)
_MUSCLE_BASE: list[MuscleSpec] = [
    # name, region, arch, o_bone, i_bone, actions, sec_actions, spinal, nerve, artery, L, V, M, Fmax, penn, fdir, antag, syn, otn, itn, ocsa, icsa
    ("Rectus Femoris", "thigh_anterior", "bipennate", B_FEM_R, B_TIB_R, ["extension"], ["flexion"],
     ["L2", "L3", "L4"], "Femoral nerve", "Femoral artery", 40, 450, 450, 3500, 14,
     (0, -1, 0), ["Biceps Femoris"], [], "Quadriceps tendon", "Patellar tendon", 1.3, 1.5),
    ("Biceps Femoris", "thigh_posterior", "fusiform", B_PELVIS, B_TIB_R, ["flexion"], None,
     ["L5", "S1", "S2"], "Sciatic nerve", "Deep femoral artery", 38, 380, 380, 3200, None,
     (0, -1, 0), ["Rectus Femoris"], [], None, None, None, None),
    ("Biceps Brachii", "arm_anterior", "fusiform", B_SCAP_R, B_RAD_R, ["flexion"], None,
     ["C5", "C6", "C7"], "Musculocutaneous nerve", "Brachial artery", 32, 280, 280, 2800, None,
     (0, -1, 0), ["Triceps Brachii"], ["Deltoid"], None, None, None, None),
    ("Triceps Brachii", "arm_posterior", "multipennate", B_SCAP_R, B_ULNA_R, ["extension"], None,
     ["C6", "C7", "C8"], "Radial nerve", "Deep brachial artery", 28, 320, 320, 3100, 12,
     (0, -1, 0), ["Biceps Brachii"], [], None, None, None, None),
    ("Pectoralis Major", "thorax_anterior", "convergent", B_STERNUM, B_HUMER_R, ["flexion", "adduction"], None,
     ["C5", "C6", "C7", "C8", "T1"], "Pectoral nerves", "Thoracoacromial artery", 25, 520, 520, 4200, None,
     (-0.95, -0.31, 0), ["Latissimus Dorsi"], ["Deltoid"], None, None, None, None),
    ("Deltoid", "shoulder", "multipennate", B_CLAV_R, B_HUMER_R, ["abduction"], None,
     ["C5", "C6"], "Axillary nerve", "Posterior circumflex humeral artery", 20, 380, 380, 3400, 15,
     (-0.707107, -0.707107, 0), [], ["Pectoralis Major"], None, None, None, None),
    ("Rectus Abdominis", "abdomen", "parallel", B_STERNUM, B_PELVIS, ["flexion"], None,
     ["T7", "T8", "T9", "T10", "T11", "T12"], "Intercostal nerves", "Superior epigastric artery", 40, 280, 280, 2200, None,
     (0, -1, 0), ["Latissimus Dorsi (R)", "Latissimus Dorsi (L)"], [], None, None, None, None),
    ("Latissimus Dorsi", "back_superficial", "convergent", 34, B_HUMER_R, ["extension", "adduction"], None,
     ["C6", "C7", "C8"], "Thoracodorsal nerve", "Thoracodorsal artery", 35, 620, 620, 3800, None,
     (-0.707107, 0.707107, 0), ["Pectoralis Major", "Deltoid"], [], None, None, None, None),
    ("Gastrocnemius", "leg_posterior", "bipennate", B_FEM_R, B_TIB_R, ["plantarflexion"], None,
     ["S1", "S2"], "Tibial nerve", "Posterior tibial artery", 16, 180, 180, 2400, 17,
     (0, -1, 0), [], [], None, "Achilles tendon", None, 0.8),
    ("Erector Spinae", "back_deep", "parallel", B_SACRUM, B_T12, ["extension"], None,
     ["T1", "T2", "T3", "T4", "T5", "T6"], "Posterior rami", "Lumbar arteries", 45, 520, 520, 3600, None,
     (0, 1, 0), [], [], None, None, None, None),
    ("Multifidus", "back_deep", "multipennate", B_SACRUM, B_L5 + 2, ["extension"], None,
     ["L1", "L2", "L3"], "Posterior rami", "Lumbar arteries", 8, 120, 120, 1200, 25,
     (0, -1, 0), [], [], None, None, None, None),
    ("Quadratus Lumborum", "back_deep", "parallel", B_PELVIS, B_L1, ["lateral_flexion"], None,
     ["T12", "L1", "L2", "L3"], "Subcostal nerve", "Lumbar arteries", 12, 90, 90, 800, None,
     (0, -1, 0), [], [], None, None, None, None),
    ("Semispinalis Capitis", "back_deep", "multipennate", B_T12 + 8, B_SKULL, ["extension"], None,
     ["C1", "C2", "C3", "C4"], "Posterior rami", "Occipital artery", 18, 80, 80, 600, 20,
     (0, -1, 0), [], [], None, None, None, None),
    ("Gluteus Maximus", "hip", "convergent", B_PELVIS, B_FEM_R, ["extension"], None,
     ["L5", "S1", "S2"], "Inferior gluteal nerve", "Superior gluteal artery", 18, 850, 850, 2800, None,
     (0, -1, 0), [], [], None, None, None, None),
    ("Gluteus Medius", "hip", "multipennate", B_PELVIS, B_FEM_R, ["abduction"], None,
     ["L4", "L5", "S1"], "Superior gluteal nerve", "Superior gluteal artery", 12, 350, 350, 2200, 15,
     (0, -1, 0), [], [], None, None, None, None),
    ("Iliopsoas", "hip", "fusiform", B_L5, B_FEM_R, ["flexion"], None,
     ["L1", "L2", "L3"], "Femoral nerve", "Iliolumbar artery", 28, 280, 280, 2000, None,
     (0, -1, 0), [], [], None, None, None, None),
    ("Sternocleidomastoid", "head_and_neck", "parallel", B_STERNUM, B_SKULL, ["flexion"], None,
     ["C2", "C3"], "Spinal accessory nerve (XI)", "Occipital artery", 20, 80, 80, 400, None,
     (0, -1, 0), [], [], None, None, None, None),
    ("Supraspinatus", "shoulder", "unipennate", B_SCAP_R, B_HUMER_R, ["abduction"], None,
     ["C5", "C6"], "Suprascapular nerve", "Suprascapular artery", 10, 55, 55, 600, 7,
     (0, -1, 0), [], [], None, None, None, None),
    ("Infraspinatus", "shoulder", "multipennate", B_SCAP_R, B_HUMER_R, ["lateral_rotation"], None,
     ["C5", "C6"], "Suprascapular nerve", "Suprascapular artery", 14, 180, 180, 1200, 18,
     (0, -1, 0), [], [], None, None, None, None),
    ("Vastus Lateralis", "thigh_anterior", "bipennate", B_FEM_R, B_TIB_R, ["extension"], None,
     ["L2", "L3", "L4"], "Femoral nerve", "Femoral artery", 35, 420, 420, 3800, 14,
     (0, -1, 0), [], [], None, None, None, None),
    ("Soleus", "leg_posterior", "bipennate", B_TIB_R, B_FOOT_R, ["plantarflexion"], None,
     ["S1", "S2"], "Tibial nerve", "Posterior tibial artery", 10, 420, 420, 3500, 25,
     (0, -1, 0), [], [], None, None, None, None),
    ("Tibialis Anterior", "leg_anterior", "unipennate", B_TIB_R, B_FOOT_R, ["dorsiflexion"], None,
     ["L4", "L5"], "Common peroneal nerve", "Anterior tibial artery", 28, 140, 140, 1000, 10,
     (0, -1, 0), [], [], None, None, None, None),
    ("Trapezius Upper", "back_superficial", "convergent", B_SKULL, B_CLAV_R, ["elevation"], None,
     ["C1", "C2", "C3", "C4"], "Spinal accessory nerve (XI)", "Transverse cervical artery", 15, 80, 80, 500, None,
     (0, -1, 0), [], [], None, None, None, None),
    ("External Oblique", "abdomen", "parallel", B_T12 + 4, B_PELVIS, ["flexion", "lateral_flexion"], None,
     ["T7", "T8", "T9", "T10", "T11", "T12"], "Intercostal nerves", "Superior epigastric artery", 20, 100, 100, 600, None,
     (0, -1, 0), [], [], None, None, None, None),
    ("Diaphragm", "abdomen", "circular", 35, B_L5, ["elevation"], None,
     ["C3", "C4", "C5"], "Phrenic nerve", "Phrenic artery", 5, 35, 35, 300, None,
     (0, -1, 0), [], [], None, None, None, None),
]

MUSCLE_DEFS = _bilateral(_MUSCLE_BASE)
assert len(MUSCLE_DEFS) == 48, f"Expected 48 muscles, got {len(MUSCLE_DEFS)}"


def gen_tendons_and_muscles(r: Reg) -> tuple[list[dict], list[dict]]:
    """Generate tendons and muscles together (tendons are created per muscle)."""
    tendons: list[dict] = []
    muscles: list[dict] = []

    # Muscles whose origin tendon is shared between (R) and (L) variants
    # (midline origin with bilateral insertions, like David's Pectoralis Major and Latissimus Dorsi)
    SHARED_ORIGIN_BASES = {"Pectoralis Major", "Latissimus Dorsi"}
    shared_origin_tendon_idx: dict[str, int] = {}  # base_name → tendon_ids index

    # First pass: create all tendons and muscles (no cross-refs yet)
    for mdef in MUSCLE_DEFS:
        (name, region, arch, o_bone, i_bone, actions, sec_actions,
         spinal, nerve, artery, length, vol, mass, fmax, penn,
         fdir, _, _, otn, itn, ocsa, icsa) = mdef

        # Adjust bone index for (L) variants
        if "(L)" in name:
            o_bone = _mirror_bone(o_bone)
            i_bone = _mirror_bone(i_bone)

        # Check if this muscle shares an origin tendon with its bilateral partner
        base_name = name.replace(" (R)", "").replace(" (L)", "")
        origin_tendon_idx: int

        if base_name in SHARED_ORIGIN_BASES and base_name in shared_origin_tendon_idx:
            # Reuse the existing shared origin tendon
            origin_tendon_idx = shared_origin_tendon_idx[base_name]
        else:
            # Create a new origin tendon
            ot_name = f"{otn} ({name.split('(')[-1].strip(')')[-1]})" if otn and "(" in name else (otn or f"{name} origin tendon")
            tendons.append(_make_tendon(r, ot_name, o_bone, random.uniform(2, 5), ocsa))
            origin_tendon_idx = len(r.tendon_ids) - 1
            if base_name in SHARED_ORIGIN_BASES:
                shared_origin_tendon_idx[base_name] = origin_tendon_idx

        # Insertion tendon (always unique per muscle)
        it_name = f"{itn} ({name.split('(')[-1].strip(')')[-1]})" if itn and "(" in name else (itn or f"{name} insertion tendon")
        tendons.append(_make_tendon(r, it_name, i_bone, random.uniform(3, 6), icsa))

        mid = uid()
        r.muscle_ids.append(mid)
        r.muscle_name_to_idx[name] = len(r.muscle_ids) - 1

        m: dict[str, Any] = {
            "id": mid, "name": name, "region": region, "type": "skeletal",
            "origin": {"tendonId": r.tendon_ids[origin_tendon_idx], "description": f"Origin of {name}"},
            "insertion": {"tendonId": r.tendon_ids[-1], "description": f"Insertion of {name}"},
            "fascicleArchitecture": arch,
            "fiberDirection": unit_vec3(*fdir),
            "fiberComposition": "mixed",
            "restingLength": length, "volume": vol, "mass": mass,
            "maxIsometricForce": fmax,
            "maxContractionVelocity": round(random.uniform(4, 8), 1),
            "innervation": {"nerveName": nerve, "spinalRoots": spinal},
            "bloodSupply": {"primaryArteryName": artery},
            "primaryActions": actions,
        }
        if sec_actions:
            m["secondaryActions"] = sec_actions
        if penn is not None:
            m["pennationAngle"] = penn
        muscles.append(m)

    # Second pass: resolve antagonist/synergist IDs
    for i, mdef in enumerate(MUSCLE_DEFS):
        antag_names, syn_names = mdef[16], mdef[17]
        if antag_names:
            aids = [r.muscle_ids[r.muscle_name_to_idx[n]] for n in antag_names if n in r.muscle_name_to_idx]
            if aids:
                muscles[i]["antagonistIds"] = aids
        if syn_names:
            sids = [r.muscle_ids[r.muscle_name_to_idx[n]] for n in syn_names if n in r.muscle_name_to_idx]
            if sids:
                muscles[i]["synergistIds"] = sids

    # Resolve nerveId references
    for i, m in enumerate(muscles):
        nerve_name = m["innervation"]["nerveName"]
        if nerve_name in r.nerve_name_to_idx:
            m["innervation"]["nerveId"] = r.nerve_ids[r.nerve_name_to_idx[nerve_name]]

    return tendons, muscles


def _mirror_bone(idx: int) -> int:
    """Map R-side bone index to L-side."""
    mirrors = {
        B_SCAP_R: B_SCAP_L, B_CLAV_R: B_CLAV_L,
        B_HUMER_R: B_HUMER_L, B_RAD_R: B_RAD_L, B_ULNA_R: B_ULNA_L,
        B_FEM_R: B_FEM_L, B_PAT_R: B_PAT_L,
        B_TIB_R: B_TIB_L, B_FIB_R: B_FIB_L,
        B_HAND_R: B_HAND_L, B_FOOT_R: B_FOOT_L,
    }
    return mirrors.get(idx, idx)


# ---------------------------------------------------------------------------
# Nerves — 13
# ---------------------------------------------------------------------------

NERVE_DEFS = [
    ("Femoral nerve", "mixed", "lumbar", ["L2", "L3", "L4"], None),
    ("Sciatic nerve", "mixed", "sacral", ["L4", "L5", "S1", "S2", "S3"], None),
    ("Tibial nerve", "mixed", "sacral", ["L4", "L5", "S1", "S2", "S3"], "Sciatic nerve"),
    ("Musculocutaneous nerve", "mixed", "brachial", ["C5", "C6", "C7"], None),
    ("Radial nerve", "mixed", "brachial", ["C5", "C6", "C7", "C8", "T1"], None),
    ("Pectoral nerves", "motor", "brachial", ["C5", "C6", "C7", "C8", "T1"], None),
    ("Axillary nerve", "mixed", "brachial", ["C5", "C6"], None),
    ("Thoracodorsal nerve", "motor", "brachial", ["C6", "C7", "C8"], None),
    ("Superior gluteal nerve", "motor", "sacral", ["L4", "L5", "S1"], None),
    ("Inferior gluteal nerve", "motor", "sacral", ["L5", "S1", "S2"], None),
    ("Common peroneal nerve", "mixed", "sacral", ["L4", "L5", "S1", "S2"], "Sciatic nerve"),
    ("Phrenic nerve", "motor", "cervical", ["C3", "C4", "C5"], None),
    ("Spinal accessory nerve (XI)", "motor", "none", ["C1", "C2", "C3", "C4"], None),
]
assert len(NERVE_DEFS) == 13


def gen_nerves(r: Reg) -> list[dict]:
    nerves = []
    for name, ntype, plexus, roots, parent_name in NERVE_DEFS:
        nid = uid()
        r.nerve_ids.append(nid)
        r.nerve_name_to_idx[name] = len(r.nerve_ids) - 1
        parent_id = r.nerve_ids[r.nerve_name_to_idx[parent_name]] if parent_name else None
        nerves.append({
            "id": nid, "name": name, "type": ntype, "plexus": plexus,
            "spinalRoots": roots, "parentNerveId": parent_id,
            "path": [
                vec3(random.uniform(-5, 5), random.uniform(60, 120), random.uniform(-3, 3)),
                vec3(random.uniform(-5, 5), random.uniform(10, 60), random.uniform(-3, 3)),
            ],
        })
    return nerves


# ---------------------------------------------------------------------------
# Organs — 9
# ---------------------------------------------------------------------------

def gen_organs(r: Reg) -> list[dict]:
    defs = [
        ("Heart", "cardiovascular", 300, 310, True, False, "midline", (0, 130, 3)),
        ("Lung (R)", "respiratory", 1400, 600, True, True, "right", (-10, 135, 0)),
        ("Lung (L)", "respiratory", 1200, 530, True, True, "left", (10, 135, 0)),
        ("Liver", "digestive", 1500, 1400, True, False, "right", (-8, 115, 3)),
        ("Kidney (R)", "urinary", 150, 140, False, True, "right", (-6, 110, -5)),
        ("Kidney (L)", "urinary", 150, 140, False, True, "left", (6, 110, -5)),
        ("Brain", "nervous", 1400, 1400, True, False, "midline", (0, 168, 0)),
        ("Stomach", "digestive", 950, 150, False, False, "left", (5, 118, 3)),
        ("Spleen", "lymphatic", 200, 180, False, False, "left", (10, 115, -2)),
    ]
    organs = []
    for name, system, vol, mass, vital, paired, lat, pos in defs:
        oid = uid()
        r.organ_ids.append(oid)
        organs.append({
            "id": oid, "name": name, "system": system,
            "transform": tf(*pos),
            "volume": vol, "mass": mass,
            "isVital": vital, "pairedOrgan": paired, "laterality": lat,
        })
    return organs


# ---------------------------------------------------------------------------
# Vascular — 20 vessels (arteries + veins)
# ---------------------------------------------------------------------------

def gen_vascular(r: Reg) -> list[dict]:
    vessels: list[dict] = []

    def _art(name: str, parent_idx: int | None, radius: float, path: list[dict], **kw: Any) -> None:
        vid = uid()
        r.vessel_ids.append(vid)
        v: dict[str, Any] = {
            "id": vid, "name": name, "vesselType": "artery",
            "path": path, "averageLumenRadius": radius,
            "parentVesselId": r.vessel_ids[parent_idx] if parent_idx is not None else None,
        }
        v.update(kw)
        vessels.append(v)

    def _vein(name: str, parent_idx: int | None, radius: float, path: list[dict], **kw: Any) -> None:
        vid = uid()
        r.vessel_ids.append(vid)
        v: dict[str, Any] = {
            "id": vid, "name": name, "vesselType": "vein",
            "path": path, "averageLumenRadius": radius,
            "parentVesselId": r.vessel_ids[parent_idx] if parent_idx is not None else None,
            "hasValves": kw.pop("hasValves", True),
        }
        v.update(kw)
        vessels.append(v)

    # Arteries (indices 0–12)
    _art("Aorta", None, 1.5, [vec3(0, 135, 3), vec3(0, 100, 0), vec3(0, 70, -2)], systolicPressure=120, diastolicPressure=80, oxygenSaturation=98)
    _art("Common iliac (R)", 0, 0.8, [vec3(-3, 70, -2), vec3(-7, 60, -1)])
    _art("Common iliac (L)", 0, 0.8, [vec3(3, 70, -2), vec3(7, 60, -1)])
    _art("Femoral artery (R)", 1, 0.5, [vec3(-9, 60, 0), vec3(-9, 30, 0)])
    _art("Femoral artery (L)", 2, 0.5, [vec3(9, 60, 0), vec3(9, 30, 0)])
    _art("Brachial artery (R)", 0, 0.35, [vec3(-23, 148, 0), vec3(-25, 112, 0)])
    _art("Brachial artery (L)", 0, 0.35, [vec3(23, 148, 0), vec3(25, 112, 0)])
    # IVC index=7
    _vein("Inferior vena cava", None, 1.8, [vec3(1, 70, -2), vec3(1, 100, 0), vec3(1, 135, 3)], hasValves=False)
    _vein("Great saphenous (R)", 7, 0.4, [vec3(-10, 5, 2), vec3(-9, 60, 0)])
    _art("Celiac trunk", 0, 0.6, [vec3(0, 115, 3), vec3(0, 112, 5)])
    _art("Superior mesenteric artery", 0, 0.5, [vec3(0, 113, 3), vec3(0, 105, 5)])
    _art("Renal artery (R)", 0, 0.35, [vec3(-2, 110, -2), vec3(-6, 110, -5)])
    _art("Renal artery (L)", 0, 0.35, [vec3(2, 110, -2), vec3(6, 110, -5)])
    _art("Posterior tibial artery (R)", 3, 0.2, [vec3(-9, 30, 0), vec3(-9, 5, 2)])
    _vein("Popliteal vein (R)", 7, 0.5, [vec3(-9, 30, -1), vec3(-9, 50, -1)])
    _vein("Femoral vein (R)", 7, 0.55, [vec3(-9, 50, 0), vec3(-9, 70, 0)])
    _vein("Femoral vein (L)", 7, 0.55, [vec3(9, 50, 0), vec3(9, 70, 0)])
    _vein("Internal jugular vein (R)", 7, 0.7, [vec3(-3, 155, 2), vec3(-2, 135, 3)])
    _art("Carotid artery (R)", 0, 0.4, [vec3(-2, 135, 3), vec3(-3, 160, 2)])
    _art("Carotid artery (L)", 0, 0.4, [vec3(2, 135, 3), vec3(3, 160, 2)])

    assert len(vessels) == 20
    return vessels


# ---------------------------------------------------------------------------
# Ligaments — 12
# ---------------------------------------------------------------------------

def gen_ligaments(r: Reg) -> list[dict]:
    defs = [
        ("Anterior cruciate ligament (R)", B_FEM_R, B_TIB_R, J_KNEE_R, 3.2),
        ("Posterior cruciate ligament (R)", B_FEM_R, B_TIB_R, J_KNEE_R, 3.8),
        ("Medial collateral ligament (R)", B_FEM_R, B_TIB_R, J_KNEE_R, 8),
        ("Lateral collateral ligament (R)", B_FEM_R, B_TIB_R, J_KNEE_R, 5.5),
        ("Anterior cruciate ligament (L)", B_FEM_L, B_TIB_L, J_KNEE_L, 3.2),
        ("Posterior cruciate ligament (L)", B_FEM_L, B_TIB_L, J_KNEE_L, 3.8),
        ("Iliofemoral ligament (R)", B_PELVIS, B_FEM_R, J_HIP_R, 8.5),
        ("Iliofemoral ligament (L)", B_PELVIS, B_FEM_L, J_HIP_L, 8.5),
        ("Glenohumeral ligament (R)", B_SCAP_R, B_HUMER_R, J_SHOULDER_R, 3.5),
        ("Glenohumeral ligament (L)", B_SCAP_L, B_HUMER_L, J_SHOULDER_L, 3.5),
        ("Anterior longitudinal ligament (lumbar)", B_SACRUM, B_L1, J_L5S1, 15),
        ("Posterior longitudinal ligament (lumbar)", B_SACRUM, B_L1, J_L5S1, 14),
    ]
    ligs = []
    for name, ob, ib, ji, length in defs:
        lid = uid()
        r.ligament_ids.append(lid)
        ligs.append({
            "id": lid, "name": name,
            "originBoneId": r.bone_ids[ob],
            "originPosition": vec3(random.uniform(-1, 1), random.uniform(-1, 1), random.uniform(-1, 1)),
            "insertionBoneId": r.bone_ids[ib],
            "insertionPosition": vec3(random.uniform(-1, 1), random.uniform(-1, 1), random.uniform(-1, 1)),
            "jointId": r.joint_ids[ji],
            "restingLength": length,
        })
    assert len(ligs) == 12
    return ligs


# ---------------------------------------------------------------------------
# Cartilage — 9
# ---------------------------------------------------------------------------

def gen_cartilage(r: Reg) -> list[dict]:
    defs = [
        ("Femoral condyle articular cartilage (R)", "hyaline", B_FEM_R, J_KNEE_R, 3.5, 12),
        ("Tibial plateau articular cartilage (R)", "hyaline", B_TIB_R, J_KNEE_R, 3, 10),
        ("Medial meniscus (R)", "fibrocartilage", None, J_KNEE_R, 5, 8),
        ("Lateral meniscus (R)", "fibrocartilage", None, J_KNEE_R, 4.5, 7),
        ("Acetabular cartilage (R)", "hyaline", B_PELVIS, J_HIP_R, 2.5, 16),
        ("Femoral head cartilage (R)", "hyaline", B_FEM_R, J_HIP_R, 2, 14),
        ("Acetabular labrum (R)", "fibrocartilage", None, J_HIP_R, 4, 6),
        ("Glenoid labrum (R)", "fibrocartilage", None, J_SHOULDER_R, 3.5, 4),
        ("Glenoid labrum (L)", "fibrocartilage", None, J_SHOULDER_L, 3.5, 4),
    ]
    carts = []
    for name, ctype, bone_idx, joint_idx, thickness, area in defs:
        cid = uid()
        r.cartilage_ids.append(cid)
        c: dict[str, Any] = {"id": cid, "name": name, "type": ctype, "thickness": thickness, "surfaceArea": area}
        if bone_idx is not None:
            c["boneId"] = r.bone_ids[bone_idx]
        c["jointId"] = r.joint_ids[joint_idx]
        carts.append(c)
    assert len(carts) == 9
    return carts


# ---------------------------------------------------------------------------
# Hair
# ---------------------------------------------------------------------------

def gen_hair(height: float) -> dict:
    styles = ["Curly, short", "Straight, medium", "Wavy, long", "Buzz cut", "Afro"]
    return {
        "style": random.choice(styles),
        "color": color(random.randint(20, 80), random.randint(15, 60), random.randint(10, 50)),
        "length": random.randint(2, 25),
        "density": round(random.uniform(0.5, 0.95), 2),
        "transform": tf(0, height, 0),
    }


# ---------------------------------------------------------------------------
# Segments — 15
# ---------------------------------------------------------------------------

SEG_DEFS = [
    # (name, bone_idxs, proximal_joint_idx_or_None, distal_joint_idxs, mass_frac, length, com_ratio)
    ("Pelvis", [B_PELVIS, B_SACRUM], None, [J_HIP_R, J_HIP_L], 0.113, 18, 0.5),
    ("Thigh (R)", [B_FEM_R], J_HIP_R, [J_KNEE_R], 0.14, 45, 0.433),
    ("Thigh (L)", [B_FEM_L], J_HIP_L, [J_KNEE_L], 0.14, 45, 0.433),
    ("Shank (R)", [B_TIB_R, B_FIB_R, B_PAT_R], J_KNEE_R, [J_ANKLE_R], 0.046, 40, 0.433),
    ("Shank (L)", [B_TIB_L, B_FIB_L, B_PAT_L], J_KNEE_L, [J_ANKLE_L], 0.046, 40, 0.433),
    ("Trunk", list(range(B_L5, B_T1 + 1)) + [B_STERNUM, B_RIBS_R, B_RIBS_L, B_SCAP_R, B_SCAP_L, B_CLAV_R, B_CLAV_L],
     8, [J_SHOULDER_R, J_SHOULDER_L], 0.4306, 46, 0.5),  # proximal=L5-S1
    ("Head-neck", list(range(B_C7, B_C1 + 1)) + [B_SKULL], 18, [], 0.0714, 22, 0.5),  # proximal=C7-T1
    ("Upper arm (R)", [B_HUMER_R], J_SHOULDER_R, [J_ELBOW_R], 0.027, 36, 0.436),
    ("Upper arm (L)", [B_HUMER_L], J_SHOULDER_L, [J_ELBOW_L], 0.027, 36, 0.436),
    ("Forearm (R)", [B_RAD_R, B_ULNA_R], J_ELBOW_R, [J_WRIST_R], 0.0164, 26, 0.43),
    ("Forearm (L)", [B_RAD_L, B_ULNA_L], J_ELBOW_L, [J_WRIST_L], 0.0164, 26, 0.43),
    ("Hand (R)", [B_HAND_R], J_WRIST_R, [], 0.0061, 19, 0.506),
    ("Hand (L)", [B_HAND_L], J_WRIST_L, [], 0.0061, 19, 0.506),
    ("Foot (R)", [B_FOOT_R], J_ANKLE_R, [], 0.014, 26, 0.5),
    ("Foot (L)", [B_FOOT_L], J_ANKLE_L, [], 0.014, 26, 0.5),
]
assert len(SEG_DEFS) == 15


def gen_segments(r: Reg, weight: float) -> list[dict]:
    segs = []
    for name, bone_idxs, prox_j, distal_js, mass_frac, seg_len, com_ratio in SEG_DEFS:
        sid = uid()
        r.segment_ids.append(sid)
        seg_mass = round(weight * mass_frac, 2)
        com_y = seg_len * com_ratio
        segs.append({
            "id": sid, "name": name,
            "boneIds": [r.bone_ids[i] for i in bone_idxs],
            "proximalJointId": r.joint_ids[prox_j] if prox_j is not None else None,
            "distalJointIds": [r.joint_ids[j] for j in distal_js],
            "mass": seg_mass,
            "centerOfMass": vec3(0, com_y, 0),
            "inertiaTensor": sym_tensor(
                round(seg_mass * (seg_len * 0.3) ** 2, 1),
                round(seg_mass * (seg_len * 0.1) ** 2, 1),
                round(seg_mass * (seg_len * 0.3) ** 2, 1),
            ),
            "segmentLength": seg_len,
        })
    return segs


# ---------------------------------------------------------------------------
# Poses — currentPose (24 jointStates) + 1 savedPose (8 jointStates)
# ---------------------------------------------------------------------------

def gen_current_pose(r: Reg) -> dict:
    r.pose_id = uid()
    joint_states = []
    for i in range(24):
        dof = JOINT_DEFS[i][3]
        angles: dict[str, Any] = {"flexionExtension": round(random.uniform(-5, 15), 1), "abductionAdduction": 0, "internalExternalRotation": 0}
        if dof >= 2:
            angles["abductionAdduction"] = round(random.uniform(-5, 5), 1)
        if dof >= 3:
            angles["internalExternalRotation"] = round(random.uniform(-5, 5), 1)
        joint_states.append({"jointId": r.joint_ids[i], "angles": angles})

    return {
        "id": r.pose_id, "name": "contrapposto",
        "rootSegmentId": r.segment_ids[0],
        "rootPose": rigid_pose(0, 95, 0, small_tilt_quat(2, 5, 1)),
        "jointStates": joint_states,
    }


def gen_saved_poses(r: Reg) -> list[dict]:
    r.saved_pose_id = uid()
    # Anatomical position — 8 major joints at zero
    major_joints = [J_HIP_R, J_HIP_L, J_KNEE_R, J_KNEE_L, J_SHOULDER_R, J_SHOULDER_L, J_ELBOW_R, J_ELBOW_L]
    joint_states = [
        {"jointId": r.joint_ids[j], "angles": {"flexionExtension": 0, "abductionAdduction": 0, "internalExternalRotation": 0}}
        for j in major_joints
    ]
    return [{
        "id": r.saved_pose_id, "name": "anatomical_position",
        "rootSegmentId": r.segment_ids[0],
        "rootPose": rigid_pose(0, 95, 0),
        "jointStates": joint_states,
    }]


# ---------------------------------------------------------------------------
# Loading conditions — 28 forces, 1 moment, 2 contacts
# ---------------------------------------------------------------------------

def gen_loading_conditions(r: Reg, weight: float) -> list[dict]:
    forces: list[dict] = []

    def _grf(name: str, mag: float, side: str, seg_idx: int) -> dict:
        return {
            "id": uid(), "name": name, "forceType": "ground_reaction",
            "magnitude": mag, "direction": unit_vec3(0, 1, 0),
            "centerOfPressure": vec3(0, 0, 0),
            "vertical": mag * 0.98, "anteroposterior": mag * 0.02, "mediolateral": mag * 0.01,
            "contactSide": side, "contactSegmentId": r.segment_ids[seg_idx],
        }

    def _muscle_f(name: str, mag: float, muscle_name: str) -> dict:
        return {
            "id": uid(), "name": name, "forceType": "muscle",
            "magnitude": mag, "direction": unit_vec3(0, -1, 0),
            "muscleId": r.muscle_ids[r.muscle_name_to_idx[muscle_name]],
            "applicationPoint": vec3(0, 0, 0),
            "activeComponent": mag * 0.9, "passiveComponent": mag * 0.1,
        }

    def _grav(seg_idx: int) -> dict:
        name = SEG_DEFS[seg_idx][0]
        m = round(weight * SEG_DEFS[seg_idx][4], 2)
        return {
            "id": uid(), "name": f"Weight {name}", "forceType": "gravitational",
            "magnitude": round(m * G / 100, 2),  # N (G in cm/s², so /100 for m/s²)
            "direction": unit_vec3(0, -1, 0),
            "targetSegmentId": r.segment_ids[seg_idx],
            "gravitationalAcceleration": G,
        }

    def _jr(name: str, mag: float, joint_idx: int) -> dict:
        return {
            "id": uid(), "name": name, "forceType": "joint_reaction",
            "magnitude": mag, "direction": unit_vec3(0, 1, 0),
            "jointId": r.joint_ids[joint_idx],
            "applicationPoint": vec3(0, 0, 0),
        }

    # GRFs (2)
    total_w = weight * 9.81
    r_frac = random.uniform(0.55, 0.75)
    forces.append(_grf("GRF (R foot)", round(total_w * r_frac, 0), "right", 13))
    forces.append(_grf("GRF (L foot)", round(total_w * (1 - r_frac), 0), "left", 14))

    # Muscle forces (8)
    forces.append(_muscle_f("Rectus femoris force (R)", 285, "Rectus Femoris (R)"))
    forces.append(_muscle_f("Gastrocnemius force (R)", 180, "Gastrocnemius (R)"))
    forces.append(_muscle_f("L quad force", 120, "Rectus Femoris (L)"))
    forces.append(_muscle_f("L gastroc", 80, "Gastrocnemius (L)"))
    forces.append(_muscle_f("R erector spinae", 350, "Erector Spinae (R)"))
    forces.append(_muscle_f("L erector spinae", 340, "Erector Spinae (L)"))
    forces.append(_muscle_f("R gluteus max", 180, "Gluteus Maximus (R)"))
    forces.append(_muscle_f("R soleus", 220, "Soleus (R)"))

    # Gravitational forces (15 — one per segment)
    for si in range(15):
        forces.append(_grav(si))

    # Joint reaction forces (3)
    forces.append(_jr("R knee joint reaction", 1800, J_KNEE_R))
    forces.append(_jr("R hip joint reaction", 2400, J_HIP_R))
    forces.append(_jr("L5-S1 joint reaction", 900, J_L5S1))

    assert len(forces) == 28

    # Moment (1)
    moments = [{
        "id": uid(), "name": "Knee resultant moment (R)",
        "momentType": "joint_resultant",
        "aboutJointId": r.joint_ids[J_KNEE_R],
        "axis": unit_vec3(0, 0, 1),
        "magnitude": round(random.uniform(800, 1500), 0),
    }]

    # Contacts (2)
    contacts = [
        {
            "id": uid(), "name": "Right foot ground contact", "contactType": "foot_ground",
            "segmentId": r.segment_ids[13],
            "surfaceNormal": unit_vec3(0, 1, 0), "contactPoint": vec3(-9, 0, 5),
            "isActive": True,
        },
        {
            "id": uid(), "name": "Left foot ground contact", "contactType": "foot_ground",
            "segmentId": r.segment_ids[14],
            "surfaceNormal": unit_vec3(0, 1, 0), "contactPoint": vec3(9, 0, 5),
            "isActive": True,
        },
    ]

    net_fx = round(random.uniform(-0.5, 0.5), 2)
    net_fy = round(random.uniform(-0.5, 0.5), 2)
    net_fz = round(random.uniform(-0.2, 0.2), 2)
    net_res = round(math.sqrt(net_fx**2 + net_fy**2 + net_fz**2), 2)

    return [{
        "id": uid(), "name": "contrapposto_standing",
        "poseId": r.pose_id,
        "forces": forces, "moments": moments, "contacts": contacts,
        "equilibrium": {
            "netForce": vec3(net_fx, net_fy, net_fz),
            "netMoment": vec3(round(random.uniform(-1, 1), 1), round(random.uniform(-0.5, 0.5), 1), round(random.uniform(-0.5, 0.5), 1)),
            "isStatic": True,
            "residualForceMagnitude": net_res,
            "residualMomentMagnitude": round(random.uniform(0.5, 2), 1),
        },
    }]


# ---------------------------------------------------------------------------
# Derivation Graph — 10 rules
# ---------------------------------------------------------------------------

def gen_derivation_graph() -> dict:
    rule_ids = [uid() for _ in range(10)]
    rules = [
        {"id": rule_ids[0], "name": "muscle_pcsa",
         "law": {"name": "PCSA definition", "equation": "PCSA = V / L_opt", "domain": "definition"},
         "inputFields": ["muscles[*].volume", "muscles[*].optimalFiberLength"], "outputField": "muscles[*].pcsa"},
        {"id": rule_ids[1], "name": "forward_kinematics",
         "law": {"name": "Forward kinematics", "equation": "T_global = T_root × Π T_joint(θ)", "domain": "kinematics"},
         "inputFields": ["currentPose.rootPose", "currentPose.jointStates[*].angles", "segments[*].proximalJointId", "joints[*].axes"],
         "outputField": "currentPose.segmentStates[*].globalPose"},
        {"id": rule_ids[2], "name": "segment_global_com",
         "law": {"name": "Coordinate transformation", "equation": "r_global = T_global × r_local", "domain": "kinematics"},
         "inputFields": ["currentPose.segmentStates[*].globalPose", "segments[*].centerOfMass"],
         "outputField": "currentPose.segmentStates[*].globalCenterOfMass", "dependsOn": [rule_ids[1]]},
        {"id": rule_ids[3], "name": "whole_body_com",
         "law": {"name": "Center of mass definition", "equation": "r_com = Σ(mᵢrᵢ) / Σ(mᵢ)", "domain": "definition"},
         "inputFields": ["currentPose.segmentStates[*].globalCenterOfMass", "segments[*].mass"],
         "outputField": "currentPose.wholeBodyCenterOfMass", "dependsOn": [rule_ids[2]]},
        {"id": rule_ids[4], "name": "gravitational_force_magnitude",
         "law": {"name": "Newton's law of gravitation (uniform field)", "equation": "F = m × g", "domain": "rigid_body_dynamics"},
         "inputFields": ["segments[*].mass", "loadingConditions[*].forces[type=gravitational].gravitationalAcceleration"],
         "outputField": "loadingConditions[*].forces[type=gravitational].magnitude"},
        {"id": rule_ids[5], "name": "equilibrium_net_force",
         "law": {"name": "Force equilibrium", "equation": "F_net = Σ Fᵢ", "domain": "rigid_body_dynamics"},
         "inputFields": ["loadingConditions[*].forces[*].magnitude", "loadingConditions[*].forces[*].direction"],
         "outputField": "loadingConditions[*].equilibrium.netForce"},
        {"id": rule_ids[6], "name": "equilibrium_residual_magnitude",
         "law": {"name": "Vector magnitude", "equation": "|F| = √(Fx² + Fy² + Fz²)", "domain": "definition"},
         "inputFields": ["loadingConditions[*].equilibrium.netForce"],
         "outputField": "loadingConditions[*].equilibrium.residualForceMagnitude", "dependsOn": [rule_ids[5]]},
        {"id": rule_ids[7], "name": "equilibrium_static_check",
         "law": {"name": "Static equilibrium criterion", "equation": "|F_net| < ε AND |M_net| < ε", "domain": "rigid_body_dynamics"},
         "inputFields": ["loadingConditions[*].equilibrium.residualForceMagnitude", "loadingConditions[*].equilibrium.residualMomentMagnitude"],
         "outputField": "loadingConditions[*].equilibrium.isStatic", "dependsOn": [rule_ids[6]]},
        {"id": rule_ids[8], "name": "fbd_translational_residual",
         "law": {"name": "Newton's second law", "equation": "ΣF = ma", "domain": "rigid_body_dynamics"},
         "inputFields": ["freeBodyDiagrams[*].forces[*].magnitude", "freeBodyDiagrams[*].forces[*].direction",
                         "segments[matched].mass", "currentPose.segmentStates[matched].linearAcceleration"],
         "outputField": "freeBodyDiagrams[*].translationalResidual"},
        {"id": rule_ids[9], "name": "fbd_rotational_residual",
         "law": {"name": "Euler's equation of rotation", "equation": "ΣM = Iα", "domain": "rigid_body_dynamics"},
         "inputFields": ["freeBodyDiagrams[*].moments[*]", "segments[matched].inertiaTensor",
                         "currentPose.segmentStates[matched].angularAcceleration"],
         "outputField": "freeBodyDiagrams[*].rotationalResidual"},
    ]
    return {"version": "1.0.0", "rules": rules}


# ---------------------------------------------------------------------------
# Constitutive Laws — 11
# ---------------------------------------------------------------------------

HILL_EQ = "F_muscle ≤ F_max × [a × f_L(L̃) × f_V(Ṽ) + f_PE(L̃)]"
LIG_EQ = "F_lig = piecewise(ε ≤ 0: 0, ε ≤ ε_toe: k_toe×ε^n, ε ≤ ε_fail: k×(ε-ε₀), ε > ε_fail: FAILURE)"
BONE_YIELD_EQ = "σ_bone = F / A ≤ σ_yield (rigid body assumption valid when σ_bone << σ_yield)"

HILL_VALIDITY = [{"assumption": "Quasi-static muscle contraction", "validWhen": "Contraction velocity < V_max",
                   "violatedWhen": "Ballistic motion, electrical stimulation above physiological rates",
                   "consequence": "Force-velocity relationship underestimates eccentric forces"}]

LIG_VALIDITY = [{"assumption": "Ligament is intact and within elastic range", "validWhen": "Strain < ultimate strain",
                  "violatedWhen": "Ligament rupture, chronic laxity",
                  "consequence": "Force-strain model is invalid; joint becomes unstable"}]

BONE_VALIDITY = [{"assumption": "Bones are rigid bodies", "validWhen": "Bone stress << yield stress",
                   "violatedWhen": "Impact loading with strain rate > 1/s, stress near 130 MPa",
                   "consequence": "Rigid body dynamics underestimates deformation and energy absorption"}]


def _hill_law(name: str, muscle_name: str) -> dict:
    return {
        "lawType": "hill_muscle_model", "id": uid(), "name": name,
        "constrainedFields": {
            "muscleForce": f"loadingConditions[*].forces[type=muscle,muscleId={muscle_name}].magnitude",
            "activation": f"loadingConditions[*].forces[type=muscle,muscleId={muscle_name}].activationLevel",
            "currentLength": f"loadingConditions[*].forces[type=muscle,muscleId={muscle_name}].currentLength",
            "contractionVelocity": f"loadingConditions[*].forces[type=muscle,muscleId={muscle_name}].contractionVelocity",
            "maxIsometricForce": f"muscles[name={muscle_name}].maxIsometricForce",
            "optimalFiberLength": f"muscles[name={muscle_name}].optimalFiberLength",
            "maxContractionVelocity": f"muscles[name={muscle_name}].maxContractionVelocity",
        },
        "forceLength": {"widthParameter": 0.56, "minActiveForceLengthRatio": 0.5, "maxActiveForceLengthRatio": 1.5},
        "forceVelocity": {"concentricCurveShape": 0.25, "eccentricForceMax": 1.4, "eccentricCurveShape": 0.15},
        "passiveElement": {"strainAtMaxForce": 0.6, "exponentialShape": 4.0},
        "constraint": {"equation": HILL_EQ, "violationSeverity": "error", "toleranceFraction": 0.1},
        "validityBoundaries": HILL_VALIDITY,
    }


def _lig_law(name: str, lig_name: str) -> dict:
    return {
        "lawType": "ligament_force_strain", "id": uid(), "name": name,
        "constrainedFields": {
            "ligamentForce": f"loadingConditions[*].forces[type=ligamentous,name={lig_name}].magnitude",
            "strain": f"loadingConditions[*].forces[type=ligamentous,name={lig_name}].strain",
            "stiffness": f"ligaments[name={lig_name}].linearStiffness",
            "restingLength": f"ligaments[name={lig_name}].restingLength",
            "referenceStrain": f"ligaments[name={lig_name}].referenceStrain",
        },
        "toeRegion": {"maxStrain": 0.04, "curveExponent": 2.0},
        "linearRegion": {"stiffness": 200, "interceptStrain": 0.03},
        "failure": {"ultimateStrain": 0.12, "ultimateLoad": 2160, "reference": "Woo et al. (1999)"},
        "constraint": {"equation": LIG_EQ, "violationSeverity": "error", "strainTolerance": 0.005},
        "validityBoundaries": LIG_VALIDITY,
    }


def gen_constitutive_laws() -> dict:
    laws = [
        _hill_law("hill_model_rectus_femoris_r_", "Rectus Femoris (R)"),
        _hill_law("hill_model_biceps_femoris_r_", "Biceps Femoris (R)"),
        _hill_law("hill_model_biceps_brachii_r_", "Biceps Brachii (R)"),
        _hill_law("hill_model_triceps_brachii_r_", "Triceps Brachii (R)"),
        _hill_law("hill_model_pectoralis_major_r_", "Pectoralis Major (R)"),
        _hill_law("hill_model_deltoid_r_", "Deltoid (R)"),
        _lig_law("force_strain_anterior_cruciate_ligament_r_", "Anterior cruciate ligament (R)"),
        _lig_law("force_strain_posterior_cruciate_ligament_r_", "Posterior cruciate ligament (R)"),
        _lig_law("force_strain_medial_collateral_ligament_r_", "Medial collateral ligament (R)"),
        _lig_law("force_strain_lateral_collateral_ligament_r_", "Lateral collateral ligament (R)"),
        {
            "lawType": "bone_yield_criterion", "id": uid(), "name": "rigid_body_yield_check",
            "constrainedFields": {"jointReactionForce": "loadingConditions[*].forces[type=joint_reaction].magnitude"},
            "parameters": {
                "corticalTensileYield": 130, "corticalCompressiveYield": 190,
                "trabecularCompressiveYield": 5, "fatigueReductionFactor": 0.6,
            },
            "constraint": {"equation": BONE_YIELD_EQ, "violationSeverity": "error"},
            "validityBoundaries": BONE_VALIDITY,
        },
    ]
    assert len(laws) == 11
    return {"version": "1.0.0", "laws": laws}


# ---------------------------------------------------------------------------
# Root entity generator
# ---------------------------------------------------------------------------

def generate_human_body(variation: int = 0) -> dict:
    r = Reg()

    proportions = gen_proportions(variation)
    weight = proportions["weight"]
    height = proportions["totalHeight"]

    # Build in dependency order
    skeleton = gen_skeleton(r)
    joints = gen_joints(r)
    nerves = gen_nerves(r)
    tendons, muscles = gen_tendons_and_muscles(r)
    organs = gen_organs(r)
    vascular = gen_vascular(r)
    ligaments = gen_ligaments(r)
    cartilage = gen_cartilage(r)
    segments = gen_segments(r, weight)
    current_pose = gen_current_pose(r)
    saved_poses = gen_saved_poses(r)
    loading = gen_loading_conditions(r, weight)

    body: dict[str, Any] = {
        "schemaVersion": SCHEMA_VERSION,
        "id": uid(),
        "name": f"generated_body_{variation:03d}",
        "proportions": proportions,
        "skeleton": skeleton,
        "joints": joints,
        "tendons": tendons,
        "muscles": muscles,
        "organs": organs,
        "vascularSystem": vascular,
        "ligaments": ligaments,
        "cartilage": cartilage,
        "nerves": nerves,
        "hair": gen_hair(height),
        "clothing": [],
        "segments": segments,
        "currentPose": current_pose,
        "savedPoses": saved_poses,
        "loadingConditions": loading,
        "derivationGraph": gen_derivation_graph(),
        "constitutiveLaws": gen_constitutive_laws(),
    }
    return body


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(description="Generate valid HumanBody v3.0.0 JSON instances")
    parser.add_argument("-n", "--count", type=int, default=3, help="Number of bodies (default: 3)")
    parser.add_argument("-o", "--output-dir", type=str, default=None, help="Output directory (default: stdout)")
    parser.add_argument("--pretty", action="store_true", help="Pretty-print JSON")
    parser.add_argument("--seed", type=int, default=None, help="Random seed")
    args = parser.parse_args()

    if args.seed is not None:
        random.seed(args.seed)

    indent = 2 if args.pretty else None
    bodies = [generate_human_body(i) for i in range(args.count)]

    if args.output_dir:
        out = Path(args.output_dir)
        out.mkdir(parents=True, exist_ok=True)
        for i, body in enumerate(bodies):
            (out / f"body_{i:03d}.json").write_text(json.dumps(body, indent=indent, ensure_ascii=False) + "\n")
        print(f"Wrote {len(bodies)} file(s) to {out}/", file=sys.stderr)
    else:
        print(json.dumps(bodies[0] if len(bodies) == 1 else bodies, indent=indent, ensure_ascii=False))


if __name__ == "__main__":
    main()
