#!/usr/bin/env python3
"""Generate multiple valid HumanBody JSON instances conforming to the
session-3/schemas/src/ TypeScript (Zod) schema v3.0.0.

All generated instances satisfy:
  - Required fields present with correct types
  - Referential integrity (bones, joints, tendons, muscles, etc. cross-reference
    valid IDs)
  - Anthropometric ratio constraints (arm/height 0.35–0.55, leg/height 0.40–0.55,
    muscle% + fat% ≤ 75)
  - Unit quaternions and unit vectors where required
  - Discriminated union fields set correctly

Usage:
    python tools/generate_human_body.py                  # 3 bodies → stdout
    python tools/generate_human_body.py -n 5             # 5 bodies → stdout
    python tools/generate_human_body.py -n 2 -o out/     # 2 bodies → out/body_*.json
    python tools/generate_human_body.py -n 1 --pretty    # 1 body, indented

Generated by: Claude Opus 4.6 (1M context)
"""

from __future__ import annotations

import argparse
import json
import math
import os
import random
import sys
import uuid
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

SCHEMA_VERSION = "3.0.0"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def uid() -> str:
    return str(uuid.uuid4())


def vec3(x: float = 0, y: float = 0, z: float = 0) -> dict:
    return {"x": x, "y": y, "z": z}


def unit_vec3(x: float = 0, y: float = 1, z: float = 0) -> dict:
    mag = math.sqrt(x * x + y * y + z * z) or 1.0
    return {"x": x / mag, "y": y / mag, "z": z / mag}


def identity_quaternion() -> dict:
    return {"w": 1.0, "x": 0.0, "y": 0.0, "z": 0.0}


def random_unit_quaternion() -> dict:
    """Generate a random unit quaternion (uniform over SO(3))."""
    u1, u2, u3 = random.random(), random.random(), random.random()
    w = math.sqrt(1 - u1) * math.sin(2 * math.pi * u2)
    x = math.sqrt(1 - u1) * math.cos(2 * math.pi * u2)
    y = math.sqrt(u1) * math.sin(2 * math.pi * u3)
    z = math.sqrt(u1) * math.cos(2 * math.pi * u3)
    return {"w": w, "x": x, "y": y, "z": z}


def rigid_pose(px: float = 0, py: float = 0, pz: float = 0) -> dict:
    return {
        "position": vec3(px, py, pz),
        "orientation": identity_quaternion(),
    }


def transform(px: float = 0, py: float = 0, pz: float = 0) -> dict:
    return {
        "position": vec3(px, py, pz),
        "rotation": vec3(0, 0, 0),
        "scale": vec3(1, 1, 1),
    }


def color(r: int = 200, g: int = 180, b: int = 160, a: float = 1.0) -> dict:
    return {"r": r, "g": g, "b": b, "a": a}


def symmetric_tensor(xx: float = 1, yy: float = 1, zz: float = 1) -> dict:
    return {"xx": xx, "yy": yy, "zz": zz, "xy": 0, "xz": 0, "yz": 0}


def pick(choices: list[str]) -> str:
    return random.choice(choices)


# ---------------------------------------------------------------------------
# Anatomical data pools (minimal but realistic)
# ---------------------------------------------------------------------------

BONE_CLASSIFICATION = ["long", "short", "flat", "irregular", "sesamoid"]
BONE_REGIONS = [
    "axial_cranium", "axial_face", "axial_vertebral", "axial_thorax",
    "appendicular_upper", "appendicular_lower",
    "appendicular_pelvic", "appendicular_pectoral",
]
JOINT_TYPES = [
    "ball_and_socket", "hinge", "pivot", "condyloid",
    "saddle", "plane", "fixed", "cartilaginous",
]
MUSCLE_REGIONS = [
    "head_and_neck", "shoulder", "arm_anterior", "arm_posterior",
    "thigh_anterior", "thigh_posterior", "leg_anterior", "leg_posterior",
    "abdomen", "back_superficial", "hip",
]
FASCICLE_ARCHITECTURES = [
    "parallel", "convergent", "unipennate", "bipennate",
    "multipennate", "circular", "fusiform",
]
MUSCLE_ACTIONS = [
    "flexion", "extension", "abduction", "adduction",
    "medial_rotation", "lateral_rotation",
]
ORGAN_SYSTEMS = [
    "cardiovascular", "respiratory", "digestive", "nervous",
    "endocrine", "integumentary", "lymphatic", "urinary", "reproductive",
]
SEX_OPTIONS = ["male", "female", "intersex"]
CLOTHING_TYPES = ["headwear", "top", "bottom", "footwear", "accessory", "fullbody"]
NERVE_TYPES = ["motor", "sensory", "mixed", "autonomic"]
NERVE_PLEXUSES = ["cervical", "brachial", "lumbar", "sacral", "none"]


# ---------------------------------------------------------------------------
# Skeleton definitions for different body complexity levels
# ---------------------------------------------------------------------------

# Minimal anatomical skeleton (key bones only)
SKELETON_TEMPLATES: list[list[dict[str, Any]]] = [
    # Template 0: Minimal (pelvis → spine → skull, pelvis → femurs → tibias)
    [
        {"name": "pelvis", "class": "irregular", "region": "appendicular_pelvic",
         "parent_idx": None, "length": 20, "width": 30},
        {"name": "lumbar_spine", "class": "irregular", "region": "axial_vertebral",
         "parent_idx": 0, "length": 18, "width": 5},
        {"name": "thoracic_spine", "class": "irregular", "region": "axial_vertebral",
         "parent_idx": 1, "length": 28, "width": 5},
        {"name": "skull", "class": "flat", "region": "axial_cranium",
         "parent_idx": 2, "length": 20, "width": 15},
        {"name": "left_femur", "class": "long", "region": "appendicular_lower",
         "parent_idx": 0, "length": 45, "width": 3.5},
        {"name": "right_femur", "class": "long", "region": "appendicular_lower",
         "parent_idx": 0, "length": 45, "width": 3.5},
        {"name": "left_tibia", "class": "long", "region": "appendicular_lower",
         "parent_idx": 4, "length": 38, "width": 2.5},
        {"name": "right_tibia", "class": "long", "region": "appendicular_lower",
         "parent_idx": 5, "length": 38, "width": 2.5},
        {"name": "left_humerus", "class": "long", "region": "appendicular_upper",
         "parent_idx": 2, "length": 33, "width": 2.5},
        {"name": "right_humerus", "class": "long", "region": "appendicular_upper",
         "parent_idx": 2, "length": 33, "width": 2.5},
        {"name": "left_radius", "class": "long", "region": "appendicular_upper",
         "parent_idx": 8, "length": 25, "width": 1.5},
        {"name": "right_radius", "class": "long", "region": "appendicular_upper",
         "parent_idx": 9, "length": 25, "width": 1.5},
        {"name": "sternum", "class": "flat", "region": "axial_thorax",
         "parent_idx": 2, "length": 17, "width": 5},
        {"name": "left_scapula", "class": "flat", "region": "appendicular_pectoral",
         "parent_idx": 2, "length": 15, "width": 10},
        {"name": "right_scapula", "class": "flat", "region": "appendicular_pectoral",
         "parent_idx": 2, "length": 15, "width": 10},
    ],
]


# ---------------------------------------------------------------------------
# Joint definitions linking bones
# ---------------------------------------------------------------------------

JOINT_TEMPLATES: list[list[dict[str, Any]]] = [
    # Template 0: matches skeleton template 0
    [
        {"name": "L5_S1", "type": "cartilaginous", "bone_idxs": [0, 1], "dof": 3},
        {"name": "T12_L1", "type": "cartilaginous", "bone_idxs": [1, 2], "dof": 3},
        {"name": "atlantooccipital", "type": "condyloid", "bone_idxs": [2, 3], "dof": 2},
        {"name": "left_hip", "type": "ball_and_socket", "bone_idxs": [0, 4], "dof": 3},
        {"name": "right_hip", "type": "ball_and_socket", "bone_idxs": [0, 5], "dof": 3},
        {"name": "left_knee", "type": "hinge", "bone_idxs": [4, 6], "dof": 1},
        {"name": "right_knee", "type": "hinge", "bone_idxs": [5, 7], "dof": 1},
        {"name": "left_shoulder", "type": "ball_and_socket", "bone_idxs": [13, 8], "dof": 3},
        {"name": "right_shoulder", "type": "ball_and_socket", "bone_idxs": [14, 9], "dof": 3},
        {"name": "left_elbow", "type": "hinge", "bone_idxs": [8, 10], "dof": 1},
        {"name": "right_elbow", "type": "hinge", "bone_idxs": [9, 11], "dof": 1},
    ],
]


# ---------------------------------------------------------------------------
# Muscle definitions (name, region, bone indices for origin/insertion)
# ---------------------------------------------------------------------------

MUSCLE_TEMPLATES: list[list[dict[str, Any]]] = [
    [
        {"name": "rectus_femoris", "region": "thigh_anterior", "arch": "bipennate",
         "origin_bone": 0, "insert_bone": 6, "actions": ["extension"],
         "spinal": ["L2", "L3", "L4"], "nerve": "femoral nerve", "artery": "femoral artery",
         "length": 32, "volume": 120, "mass": 130},
        {"name": "biceps_femoris", "region": "thigh_posterior", "arch": "fusiform",
         "origin_bone": 0, "insert_bone": 7, "actions": ["flexion"],
         "spinal": ["L5", "S1", "S2"], "nerve": "sciatic nerve", "artery": "deep femoral artery",
         "length": 34, "volume": 100, "mass": 110},
        {"name": "biceps_brachii", "region": "arm_anterior", "arch": "fusiform",
         "origin_bone": 13, "insert_bone": 10, "actions": ["flexion"],
         "spinal": ["C5", "C6"], "nerve": "musculocutaneous nerve", "artery": "brachial artery",
         "length": 24, "volume": 60, "mass": 65},
        {"name": "triceps_brachii", "region": "arm_posterior", "arch": "multipennate",
         "origin_bone": 14, "insert_bone": 11, "actions": ["extension"],
         "spinal": ["C6", "C7", "C8"], "nerve": "radial nerve", "artery": "deep brachial artery",
         "length": 27, "volume": 80, "mass": 85},
        {"name": "erector_spinae", "region": "back_superficial", "arch": "parallel",
         "origin_bone": 0, "insert_bone": 2, "actions": ["extension"],
         "spinal": ["T1", "T2", "T3"], "nerve": "posterior rami", "artery": "lumbar arteries",
         "length": 40, "volume": 200, "mass": 220},
    ],
]


# ---------------------------------------------------------------------------
# ID Registry — tracks all generated IDs for cross-referencing
# ---------------------------------------------------------------------------

@dataclass
class IDRegistry:
    bone_ids: list[str] = field(default_factory=list)
    joint_ids: list[str] = field(default_factory=list)
    tendon_ids: list[str] = field(default_factory=list)
    muscle_ids: list[str] = field(default_factory=list)
    organ_ids: list[str] = field(default_factory=list)
    vessel_ids: list[str] = field(default_factory=list)
    nerve_ids: list[str] = field(default_factory=list)
    segment_ids: list[str] = field(default_factory=list)
    clothing_ids: list[str] = field(default_factory=list)


# ---------------------------------------------------------------------------
# Generator functions for each subsystem
# ---------------------------------------------------------------------------

def gen_proportions(variation: int = 0) -> dict:
    """Generate anthropometrically valid proportions."""
    sex = SEX_OPTIONS[variation % len(SEX_OPTIONS)]
    # Base values for an average adult
    height = random.uniform(155, 195)
    weight = random.uniform(50, 110)
    shoulder_w = random.uniform(35, 50)

    # Ensure arm/height ratio in [0.35, 0.55]
    arm_ratio = random.uniform(0.40, 0.50)
    arm_length = height * arm_ratio

    # Ensure leg/height ratio in [0.40, 0.55]
    leg_ratio = random.uniform(0.44, 0.52)
    leg_length = height * leg_ratio

    head_circ = random.uniform(53, 60)

    muscle_pct = random.uniform(25, 45)
    fat_pct = random.uniform(8, 30)
    # Ensure sum ≤ 75
    if muscle_pct + fat_pct > 74:
        fat_pct = 74 - muscle_pct

    return {
        "biologicalSex": sex,
        "totalHeight": round(height, 1),
        "weight": round(weight, 1),
        "shoulderWidth": round(shoulder_w, 1),
        "armLength": round(arm_length, 1),
        "legLength": round(leg_length, 1),
        "headCircumference": round(head_circ, 1),
        "muscleMassPercentage": round(muscle_pct, 1),
        "fatPercentage": round(fat_pct, 1),
    }


def gen_skeleton(reg: IDRegistry, template_idx: int = 0) -> list[dict]:
    """Generate skeleton bones from template."""
    template = SKELETON_TEMPLATES[template_idx % len(SKELETON_TEMPLATES)]
    bones = []
    for i, bt in enumerate(template):
        bone_id = uid()
        reg.bone_ids.append(bone_id)
        parent_id = reg.bone_ids[bt["parent_idx"]] if bt["parent_idx"] is not None else None
        y_offset = sum(t["length"] for t in template[:i] if t.get("parent_idx") is not None and t["parent_idx"] < i) * 0.3
        bones.append({
            "id": bone_id,
            "name": bt["name"],
            "classification": bt["class"],
            "region": bt["region"],
            "transform": transform(0, y_offset, 0),
            "length": bt["length"],
            "width": bt["width"],
            "mass": round(bt["length"] * bt["width"] * random.uniform(1.5, 4.0), 1),
            "parentBoneId": parent_id,
        })
    return bones


def gen_joints(reg: IDRegistry, template_idx: int = 0) -> list[dict]:
    """Generate joints connecting bones."""
    template = JOINT_TEMPLATES[template_idx % len(JOINT_TEMPLATES)]
    joints = []
    for jt in template:
        joint_id = uid()
        reg.joint_ids.append(joint_id)
        connected = [reg.bone_ids[idx] for idx in jt["bone_idxs"]]
        joints.append({
            "id": joint_id,
            "name": jt["name"],
            "type": jt["type"],
            "transform": transform(),
            "connectedBoneIds": connected,
            "degreesOfFreedom": jt["dof"],
        })
    return joints


def gen_tendons(reg: IDRegistry, template_idx: int = 0) -> list[dict]:
    """Generate tendons for muscle attachments.

    Each muscle needs an origin and insertion tendon, so we create 2 per muscle.
    """
    mt = MUSCLE_TEMPLATES[template_idx % len(MUSCLE_TEMPLATES)]
    tendons = []
    for m in mt:
        # Origin tendon
        origin_t_id = uid()
        reg.tendon_ids.append(origin_t_id)
        tendons.append({
            "id": origin_t_id,
            "name": f"{m['name']}_origin_tendon",
            "attachedBoneId": reg.bone_ids[m["origin_bone"]],
            "localPosition": vec3(
                random.uniform(-1, 1),
                random.uniform(-1, 1),
                random.uniform(-1, 1),
            ),
            "length": round(random.uniform(2, 8), 1),
        })
        # Insertion tendon
        insert_t_id = uid()
        reg.tendon_ids.append(insert_t_id)
        tendons.append({
            "id": insert_t_id,
            "name": f"{m['name']}_insertion_tendon",
            "attachedBoneId": reg.bone_ids[m["insert_bone"]],
            "localPosition": vec3(
                random.uniform(-1, 1),
                random.uniform(-1, 1),
                random.uniform(-1, 1),
            ),
            "length": round(random.uniform(2, 8), 1),
        })
    return tendons


def gen_muscles(reg: IDRegistry, template_idx: int = 0) -> list[dict]:
    """Generate muscles referencing tendons for origin/insertion."""
    mt = MUSCLE_TEMPLATES[template_idx % len(MUSCLE_TEMPLATES)]
    muscles = []
    for i, m in enumerate(mt):
        muscle_id = uid()
        reg.muscle_ids.append(muscle_id)
        origin_tendon_id = reg.tendon_ids[i * 2]
        insert_tendon_id = reg.tendon_ids[i * 2 + 1]
        muscles.append({
            "id": muscle_id,
            "name": m["name"],
            "region": m["region"],
            "type": "skeletal",
            "origin": {
                "tendonId": origin_tendon_id,
                "description": f"Origin of {m['name']}",
            },
            "insertion": {
                "tendonId": insert_tendon_id,
                "description": f"Insertion of {m['name']}",
            },
            "fascicleArchitecture": m["arch"],
            "fiberComposition": "mixed",
            "restingLength": m["length"],
            "volume": m["volume"],
            "mass": m["mass"],
            "innervation": {
                "nerveName": m["nerve"],
                "spinalRoots": m["spinal"],
            },
            "bloodSupply": {
                "primaryArteryName": m["artery"],
            },
            "primaryActions": m["actions"],
        })
    return muscles


def gen_organs(reg: IDRegistry) -> list[dict]:
    """Generate a small set of vital organs."""
    organs_data = [
        ("heart", "cardiovascular", 280, 300, True, False, "midline"),
        ("left_lung", "respiratory", 1200, 580, True, True, "left"),
        ("right_lung", "respiratory", 1400, 640, True, True, "right"),
        ("liver", "digestive", 1500, 1400, True, False, "right"),
        ("brain", "nervous", 1400, 1350, True, False, "midline"),
        ("left_kidney", "urinary", 150, 140, False, True, "left"),
        ("right_kidney", "urinary", 150, 140, False, True, "right"),
    ]
    organs = []
    for name, system, vol, mass, vital, paired, lat in organs_data:
        oid = uid()
        reg.organ_ids.append(oid)
        organs.append({
            "id": oid,
            "name": name,
            "system": system,
            "transform": transform(
                random.uniform(-5, 5),
                random.uniform(80, 140),
                random.uniform(-5, 5),
            ),
            "volume": vol + random.uniform(-vol * 0.1, vol * 0.1),
            "mass": mass + random.uniform(-mass * 0.1, mass * 0.1),
            "isVital": vital,
            "pairedOrgan": paired,
            "laterality": lat,
        })
    return organs


def gen_vascular_system(reg: IDRegistry) -> list[dict]:
    """Generate a minimal vascular system (aorta, vena cava, and a capillary)."""
    vessels = []

    aorta_id = uid()
    reg.vessel_ids.append(aorta_id)
    vessels.append({
        "id": aorta_id,
        "name": "aorta",
        "vesselType": "artery",
        "path": [vec3(0, 130, 0), vec3(0, 100, 0), vec3(0, 70, 0)],
        "averageLumenRadius": 1.5,
        "wallThickness": 0.2,
        "parentVesselId": None,
        "systolicPressure": 120,
        "diastolicPressure": 80,
        "oxygenSaturation": 98,
    })

    ivc_id = uid()
    reg.vessel_ids.append(ivc_id)
    vessels.append({
        "id": ivc_id,
        "name": "inferior_vena_cava",
        "vesselType": "vein",
        "path": [vec3(1, 70, 0), vec3(1, 100, 0), vec3(1, 130, 0)],
        "averageLumenRadius": 1.8,
        "wallThickness": 0.15,
        "parentVesselId": None,
        "hasValves": False,
        "oxygenSaturation": 70,
    })

    cap_id = uid()
    reg.vessel_ids.append(cap_id)
    vessels.append({
        "id": cap_id,
        "name": "pulmonary_capillary_bed",
        "vesselType": "capillary",
        "path": [vec3(3, 130, -3), vec3(3, 130, 3)],
        "averageLumenRadius": 0.004,
        "parentVesselId": None,
        "density": 600,
    })

    return vessels


def gen_clothing(reg: IDRegistry) -> list[dict]:
    """Generate minimal clothing set."""
    items = [
        ("t_shirt", "top", "cotton", "regular", color(50, 50, 150)),
        ("jeans", "bottom", "denim", "regular", color(30, 30, 80)),
        ("sneakers", "footwear", "synthetic_mesh", "regular", color(255, 255, 255)),
    ]
    clothing = []
    for name, ctype, fabric, fit, col in items:
        cid = uid()
        reg.clothing_ids.append(cid)
        clothing.append({
            "id": cid,
            "name": name,
            "type": ctype,
            "color": col,
            "transform": transform(),
            "fabric": fabric,
            "fit": fit,
        })
    return clothing


def gen_nerves(reg: IDRegistry) -> list[dict]:
    """Generate key peripheral nerves."""
    nerves_data = [
        ("sciatic_nerve", "mixed", "sacral", ["L4", "L5", "S1", "S2", "S3"], None),
        ("femoral_nerve", "mixed", "lumbar", ["L2", "L3", "L4"], None),
        ("musculocutaneous_nerve", "mixed", "brachial", ["C5", "C6", "C7"], None),
        ("radial_nerve", "mixed", "brachial", ["C5", "C6", "C7", "C8", "T1"], None),
    ]
    nerves = []
    for name, ntype, plexus, roots, parent_idx in nerves_data:
        nid = uid()
        reg.nerve_ids.append(nid)
        parent_id = reg.nerve_ids[parent_idx] if parent_idx is not None else None
        nerves.append({
            "id": nid,
            "name": name,
            "type": ntype,
            "plexus": plexus,
            "spinalRoots": roots,
            "parentNerveId": parent_id,
            "path": [
                vec3(random.uniform(-5, 5), random.uniform(50, 100), random.uniform(-3, 3)),
                vec3(random.uniform(-5, 5), random.uniform(20, 50), random.uniform(-3, 3)),
            ],
        })
    return nerves


def gen_ligaments(reg: IDRegistry) -> list[dict]:
    """Generate ligaments for key joints (optional field)."""
    if len(reg.joint_ids) < 6 or len(reg.bone_ids) < 8:
        return []
    ligaments = [
        {
            "id": uid(),
            "name": "anterior_cruciate_ligament_left",
            "originBoneId": reg.bone_ids[4],       # left_femur
            "originPosition": vec3(-0.5, -22, 0),
            "insertionBoneId": reg.bone_ids[6],     # left_tibia
            "insertionPosition": vec3(0, 1, 0),
            "jointId": reg.joint_ids[5],             # left_knee
            "restingLength": 3.8,
        },
        {
            "id": uid(),
            "name": "anterior_cruciate_ligament_right",
            "originBoneId": reg.bone_ids[5],       # right_femur
            "originPosition": vec3(0.5, -22, 0),
            "insertionBoneId": reg.bone_ids[7],     # right_tibia
            "insertionPosition": vec3(0, 1, 0),
            "jointId": reg.joint_ids[6],             # right_knee
            "restingLength": 3.8,
        },
    ]
    return ligaments


def gen_cartilage(reg: IDRegistry) -> list[dict]:
    """Generate cartilage structures (optional field)."""
    if len(reg.joint_ids) < 6 or len(reg.bone_ids) < 8:
        return []
    return [
        {
            "id": uid(),
            "name": "femoral_condyle_articular_cartilage_left",
            "type": "hyaline",
            "boneId": reg.bone_ids[4],
            "jointId": reg.joint_ids[5],
            "thickness": 3.5,
            "surfaceArea": 12.0,
            "youngsModulus": 0.8,
            "poissonRatio": 0.3,
        },
        {
            "id": uid(),
            "name": "left_medial_meniscus",
            "type": "fibrocartilage",
            "jointId": reg.joint_ids[5],
            "thickness": 5.0,
            "surfaceArea": 8.0,
        },
    ]


# ---------------------------------------------------------------------------
# Root entity generator
# ---------------------------------------------------------------------------

def generate_human_body(variation: int = 0) -> dict:
    """Generate a single valid HumanBody JSON object.

    Args:
        variation: Seed-like integer to vary the output across calls.
            Affects sex, proportions, and randomized values.

    Returns:
        dict conforming to HumanBodySchema v3.0.0.
    """
    reg = IDRegistry()

    # Core required subsystems
    proportions = gen_proportions(variation)
    skeleton = gen_skeleton(reg)
    joints = gen_joints(reg)
    tendons = gen_tendons(reg)
    muscles = gen_muscles(reg)
    organs = gen_organs(reg)
    vascular = gen_vascular_system(reg)
    clothing = gen_clothing(reg)

    # Optional subsystems
    nerves = gen_nerves(reg)
    ligaments = gen_ligaments(reg)
    cartilage = gen_cartilage(reg)

    body: dict[str, Any] = {
        "schemaVersion": SCHEMA_VERSION,
        "id": uid(),
        "name": f"generated_body_{variation:03d}",
        "proportions": proportions,
        "skeleton": skeleton,
        "joints": joints,
        "tendons": tendons,
        "muscles": muscles,
        "organs": organs,
        "vascularSystem": vascular,
        "clothing": clothing,
    }

    # Add optional subsystems
    if nerves:
        body["nerves"] = nerves
    if ligaments:
        body["ligaments"] = ligaments
    if cartilage:
        body["cartilage"] = cartilage

    return body


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate valid HumanBody v3.0.0 JSON instances",
    )
    parser.add_argument(
        "-n", "--count", type=int, default=3,
        help="Number of bodies to generate (default: 3)",
    )
    parser.add_argument(
        "-o", "--output-dir", type=str, default=None,
        help="Output directory for individual JSON files (default: stdout as array)",
    )
    parser.add_argument(
        "--pretty", action="store_true",
        help="Pretty-print JSON (2-space indent)",
    )
    parser.add_argument(
        "--seed", type=int, default=None,
        help="Random seed for reproducibility",
    )
    args = parser.parse_args()

    if args.seed is not None:
        random.seed(args.seed)

    indent = 2 if args.pretty else None
    bodies = [generate_human_body(i) for i in range(args.count)]

    if args.output_dir:
        out_dir = Path(args.output_dir)
        out_dir.mkdir(parents=True, exist_ok=True)
        for i, body in enumerate(bodies):
            path = out_dir / f"body_{i:03d}.json"
            path.write_text(json.dumps(body, indent=indent, ensure_ascii=False) + "\n")
        print(f"Wrote {len(bodies)} file(s) to {out_dir}/", file=sys.stderr)
    else:
        if len(bodies) == 1:
            print(json.dumps(bodies[0], indent=indent, ensure_ascii=False))
        else:
            print(json.dumps(bodies, indent=indent, ensure_ascii=False))


if __name__ == "__main__":
    main()
