import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import AnatomyViewer from "./renderer";
import bodyData from "./jhon-doe.json";
import type { HumanBodyData } from "./renderer";

// Generated by: Claude Opus 4.6 (1M context)

const body = (Array.isArray(bodyData) ? bodyData[0] : bodyData) as unknown as HumanBodyData;

const root = document.getElementById("root");
if (!root) throw new Error("Root element not found");

createRoot(root).render(
  <StrictMode>
    <AnatomyViewer body={body} />
  </StrictMode>,
);
