import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import AnatomyViewer from "./renderer";
import bodyData from "./jhon-doe.json";

// Generated by: Claude Opus 4.6 (1M context)

const root = document.getElementById("root");
if (!root) throw new Error("Root element not found");

createRoot(root).render(
  <StrictMode>
    <AnatomyViewer body={bodyData as Parameters<typeof AnatomyViewer>[0]["body"]} />
  </StrictMode>,
);
