import { useEffect, useRef, useCallback } from "react";
import * as THREE from "three";

// Generated by: Claude Opus 4.6 (1M context)

// ═══════════════════════════════════════════════════════════════════════
// CONSTANTS — Kinematic chain, segment lengths, joint definitions
// ═══════════════════════════════════════════════════════════════════════

const DEG = Math.PI / 180;

export const JOINTS: Record<string, { dof: number; rom: Record<string, [number, number]> }> = {
  L5S1:      { dof: 3, rom: { fe: [-15, 25], aa: [-8, 8], ie: [-12, 12] } },
  C7T1:      { dof: 3, rom: { fe: [-60, 60], aa: [-40, 40], ie: [-70, 70] } },
  shoulderR: { dof: 3, rom: { fe: [-60, 180], aa: [-10, 180], ie: [-90, 90] } },
  shoulderL: { dof: 3, rom: { fe: [-60, 180], aa: [-10, 180], ie: [-90, 90] } },
  elbowR:    { dof: 1, rom: { fe: [0, 150] } },
  elbowL:    { dof: 1, rom: { fe: [0, 150] } },
  wristR:    { dof: 2, rom: { fe: [-80, 70], aa: [-20, 30] } },
  wristL:    { dof: 2, rom: { fe: [-80, 70], aa: [-20, 30] } },
  hipR:      { dof: 3, rom: { fe: [-15, 125], aa: [-30, 45], ie: [-45, 45] } },
  hipL:      { dof: 3, rom: { fe: [-15, 125], aa: [-30, 45], ie: [-45, 45] } },
  kneeR:     { dof: 1, rom: { fe: [0, 140] } },
  kneeL:     { dof: 1, rom: { fe: [0, 140] } },
  ankleR:    { dof: 2, rom: { fe: [-50, 20], aa: [-35, 25] } },
  ankleL:    { dof: 2, rom: { fe: [-50, 20], aa: [-35, 25] } },
};

const SEG = {
  trunk: 0.53, headNeck: 0.24, upperArm: 0.33, forearm: 0.26,
  hand: 0.19, thigh: 0.43, shank: 0.39, foot: 0.20,
};

const ATTACH: Record<string, [number, number, number]> = {
  L5S1:      [0, 0, 0],
  C7T1:      [0, SEG.trunk, 0],
  shoulderR: [0, SEG.trunk * 0.92, -0.19],
  shoulderL: [0, SEG.trunk * 0.92, 0.19],
  hipR:      [0, -0.02, -0.09],
  hipL:      [0, -0.02, 0.09],
};

const REST: Record<string, [number, number, number]> = {
  trunk:    [0, 1, 0],
  headNeck: [0, 1, 0],
  upperArm: [0, -1, 0],
  forearm:  [0, -1, 0],
  hand:     [0, -1, 0],
  thigh:    [0, -1, 0],
  shank:    [0, -1, 0],
  foot:     [0.97, -0.26, 0],
};

// ═══════════════════════════════════════════════════════════════════════
// FORWARD KINEMATICS
// ═══════════════════════════════════════════════════════════════════════

export type JointAngles = Record<string, { fe?: number; aa?: number; ie?: number }>;
export type Landmarks = Record<string, THREE.Vector3>;

function clampAngle(val: number, min: number, max: number): number {
  return Math.max(min, Math.min(max, val || 0));
}

function clampJoint(name: string, angles: { fe?: number; aa?: number; ie?: number }) {
  const j = JOINTS[name];
  if (!j) return angles;
  const out = { ...angles };
  if (j.rom.fe) out.fe = clampAngle(out.fe ?? 0, j.rom.fe[0], j.rom.fe[1]);
  if (j.rom.aa) out.aa = clampAngle(out.aa ?? 0, j.rom.aa[0], j.rom.aa[1]);
  if (j.rom.ie) out.ie = clampAngle(out.ie ?? 0, j.rom.ie[0], j.rom.ie[1]);
  return out;
}

function jointQuaternion(parentQuat: THREE.Quaternion, fe?: number, aa?: number, ie?: number): THREE.Quaternion {
  const euler = new THREE.Euler(
    (aa || 0) * DEG,
    (ie || 0) * DEG,
    (fe || 0) * DEG,
    "ZXY",
  );
  const jq = new THREE.Quaternion().setFromEuler(euler);
  return parentQuat.clone().multiply(jq);
}

function transformPoint(origin: THREE.Vector3, quat: THREE.Quaternion, localPt: [number, number, number]): THREE.Vector3 {
  const v = new THREE.Vector3(localPt[0], localPt[1], localPt[2]);
  v.applyQuaternion(quat);
  return origin.clone().add(v);
}

function segEnd(origin: THREE.Vector3, quat: THREE.Quaternion, restDir: [number, number, number], length: number): THREE.Vector3 {
  const d = new THREE.Vector3(restDir[0], restDir[1], restDir[2]);
  d.applyQuaternion(quat).multiplyScalar(length);
  return origin.clone().add(d);
}

export function solveFK(rootPos: THREE.Vector3, rootYaw: number, angles: JointAngles): { landmarks: Landmarks; jointQuats: Record<string, THREE.Quaternion> } {
  const rq = new THREE.Quaternion().setFromAxisAngle(new THREE.Vector3(0, 1, 0), rootYaw);
  const L: Landmarks = {};
  const JQ: Record<string, THREE.Quaternion> = {};

  L.pelvis = rootPos.clone();

  const a_l5 = clampJoint("L5S1", angles.L5S1 || {});
  JQ.L5S1 = jointQuaternion(rq, a_l5.fe, a_l5.aa, a_l5.ie);
  const l5Pos = transformPoint(rootPos, rq, ATTACH.L5S1);

  L.shoulderR = transformPoint(l5Pos, JQ.L5S1, ATTACH.shoulderR);
  L.shoulderL = transformPoint(l5Pos, JQ.L5S1, ATTACH.shoulderL);
  L.c7t1 = transformPoint(l5Pos, JQ.L5S1, ATTACH.C7T1);

  const a_c7 = clampJoint("C7T1", angles.C7T1 || {});
  JQ.C7T1 = jointQuaternion(JQ.L5S1, a_c7.fe, a_c7.aa, a_c7.ie);
  L.headTop = segEnd(L.c7t1, JQ.C7T1, REST.headNeck, SEG.headNeck);
  L.headCenter = segEnd(L.c7t1, JQ.C7T1, REST.headNeck, SEG.headNeck * 0.65);

  const a_shR = clampJoint("shoulderR", angles.shoulderR || {});
  JQ.shoulderR = jointQuaternion(JQ.L5S1, a_shR.fe, a_shR.aa, a_shR.ie);
  L.elbowR = segEnd(L.shoulderR, JQ.shoulderR, REST.upperArm, SEG.upperArm);

  const a_elR = clampJoint("elbowR", angles.elbowR || {});
  JQ.elbowR = jointQuaternion(JQ.shoulderR, a_elR.fe, 0, 0);
  L.wristR = segEnd(L.elbowR, JQ.elbowR, REST.forearm, SEG.forearm);

  const a_wrR = clampJoint("wristR", angles.wristR || {});
  JQ.wristR = jointQuaternion(JQ.elbowR, a_wrR.fe, a_wrR.aa, 0);
  L.handR = segEnd(L.wristR, JQ.wristR, REST.hand, SEG.hand);

  const a_shL = clampJoint("shoulderL", angles.shoulderL || {});
  JQ.shoulderL = jointQuaternion(JQ.L5S1, a_shL.fe, -(a_shL.aa || 0), -(a_shL.ie || 0));
  L.elbowL = segEnd(L.shoulderL, JQ.shoulderL, REST.upperArm, SEG.upperArm);

  const a_elL = clampJoint("elbowL", angles.elbowL || {});
  JQ.elbowL = jointQuaternion(JQ.shoulderL, a_elL.fe, 0, 0);
  L.wristL = segEnd(L.elbowL, JQ.elbowL, REST.forearm, SEG.forearm);

  const a_wrL = clampJoint("wristL", angles.wristL || {});
  JQ.wristL = jointQuaternion(JQ.elbowL, a_wrL.fe, -(a_wrL.aa || 0), 0);
  L.handL = segEnd(L.wristL, JQ.wristL, REST.hand, SEG.hand);

  const hipRPos = transformPoint(rootPos, rq, ATTACH.hipR);
  L.hipR = hipRPos;
  const a_hR = clampJoint("hipR", angles.hipR || {});
  JQ.hipR = jointQuaternion(rq, a_hR.fe, a_hR.aa, a_hR.ie);
  L.kneeR = segEnd(hipRPos, JQ.hipR, REST.thigh, SEG.thigh);

  const a_kR = clampJoint("kneeR", angles.kneeR || {});
  JQ.kneeR = jointQuaternion(JQ.hipR, a_kR.fe, 0, 0);
  L.ankleR = segEnd(L.kneeR, JQ.kneeR, REST.shank, SEG.shank);

  const a_aR = clampJoint("ankleR", angles.ankleR || {});
  JQ.ankleR = jointQuaternion(JQ.kneeR, a_aR.fe, a_aR.aa, 0);
  L.footR = segEnd(L.ankleR, JQ.ankleR, REST.foot, SEG.foot);

  const hipLPos = transformPoint(rootPos, rq, ATTACH.hipL);
  L.hipL = hipLPos;
  const a_hL = clampJoint("hipL", angles.hipL || {});
  JQ.hipL = jointQuaternion(rq, a_hL.fe, -(a_hL.aa || 0), -(a_hL.ie || 0));
  L.kneeL = segEnd(hipLPos, JQ.hipL, REST.thigh, SEG.thigh);

  const a_kL = clampJoint("kneeL", angles.kneeL || {});
  JQ.kneeL = jointQuaternion(JQ.hipL, a_kL.fe, 0, 0);
  L.ankleL = segEnd(L.kneeL, JQ.kneeL, REST.shank, SEG.shank);

  const a_aL = clampJoint("ankleL", angles.ankleL || {});
  JQ.ankleL = jointQuaternion(JQ.kneeL, a_aL.fe, -(a_aL.aa || 0), 0);
  L.footL = segEnd(L.ankleL, JQ.ankleL, REST.foot, SEG.foot);

  return { landmarks: L, jointQuats: JQ };
}

// ═══════════════════════════════════════════════════════════════════════
// INTERPOLATION
// ═══════════════════════════════════════════════════════════════════════

export function lerpAngles(a1: JointAngles, a2: JointAngles, t: number): JointAngles {
  const out: JointAngles = {};
  const allKeys = new Set([...Object.keys(a1 || {}), ...Object.keys(a2 || {})]);
  for (const jn of allKeys) {
    const j1 = a1?.[jn] || {};
    const j2 = a2?.[jn] || {};
    out[jn] = {};
    for (const dof of ["fe", "aa", "ie"] as const) {
      const v1 = j1[dof] || 0;
      const v2 = j2[dof] || 0;
      out[jn][dof] = v1 + (v2 - v1) * t;
    }
  }
  return out;
}

export function smoothstep(t: number): number {
  const c = Math.max(0, Math.min(1, t));
  return c * c * (3 - 2 * c);
}

// ═══════════════════════════════════════════════════════════════════════
// THREE.JS FIGHTER MESH
// ═══════════════════════════════════════════════════════════════════════

const BODY_SEGS: [string, string, string][] = [
  ["pelvis", "c7t1", "torso"], ["shoulderR", "shoulderL", "shoulders"],
  ["hipR", "hipL", "hips"], ["c7t1", "headCenter", "neck"], ["headCenter", "headTop", "head"],
  ["shoulderR", "elbowR", "uaR"], ["elbowR", "wristR", "faR"], ["wristR", "handR", "hdR"],
  ["shoulderL", "elbowL", "uaL"], ["elbowL", "wristL", "faL"], ["wristL", "handL", "hdL"],
  ["hipR", "kneeR", "thR"], ["kneeR", "ankleR", "shR"], ["ankleR", "footR", "ftR"],
  ["hipL", "kneeL", "thL"], ["kneeL", "ankleL", "shL"], ["ankleL", "footL", "ftL"],
];

const SPHERE_MARKS = [
  "headCenter", "handR", "handL", "shoulderR", "shoulderL",
  "elbowR", "elbowL", "wristR", "wristL", "hipR", "hipL",
  "kneeR", "kneeL", "ankleR", "ankleL",
];

const RADII: Record<string, number> = {
  torso: 0.065, shoulders: 0.03, hips: 0.045, neck: 0.028, head: 0.058,
  uaR: 0.024, faR: 0.019, hdR: 0.022, uaL: 0.024, faL: 0.019, hdL: 0.022,
  thR: 0.042, shR: 0.028, ftR: 0.02, thL: 0.042, shL: 0.028, ftL: 0.02,
};

interface Fighter {
  group: THREE.Group;
  links: Record<string, THREE.Mesh>;
  spheres: Record<string, THREE.Mesh>;
}

function buildFighter(skinColor: number, shortsColor: number): Fighter {
  const group = new THREE.Group();
  const links: Record<string, THREE.Mesh> = {};
  const spheres: Record<string, THREE.Mesh> = {};
  const mat = (c: number) => new THREE.MeshPhongMaterial({ color: c, shininess: 30, specular: 0x222222 });

  for (const [, , name] of BODY_SEGS) {
    const r = RADII[name] || 0.02;
    const c = name.includes("th") || name.includes("hip") ? shortsColor : skinColor;
    const m = new THREE.Mesh(new THREE.CylinderGeometry(r, r, 1, 8), mat(c));
    m.castShadow = true;
    group.add(m);
    links[name] = m;
  }

  for (const mk of SPHERE_MARKS) {
    const r = mk.includes("head") ? 0.06
      : mk.includes("hand") ? 0.022
      : mk.includes("shoulder") ? 0.025
      : mk.includes("hip") ? 0.03
      : mk.includes("knee") ? 0.025
      : mk.includes("ankle") ? 0.022
      : 0.018;
    const c = mk.includes("hip") || mk.includes("knee") ? shortsColor : skinColor;
    const m = new THREE.Mesh(new THREE.SphereGeometry(r, 10, 10), mat(c));
    m.castShadow = true;
    group.add(m);
    spheres[mk] = m;
  }

  return { group, links, spheres };
}

function updateFighter(fighter: Fighter, landmarks: Landmarks): void {
  const v1 = new THREE.Vector3();
  const v2 = new THREE.Vector3();
  const up = new THREE.Vector3(0, 1, 0);

  for (const [from, to, name] of BODY_SEGS) {
    const m = fighter.links[name];
    const p1 = landmarks[from];
    const p2 = landmarks[to];
    if (!p1 || !p2) continue;
    v1.copy(p1);
    v2.copy(p2);
    const mid = v1.clone().add(v2).multiplyScalar(0.5);
    const dir = v2.clone().sub(v1);
    const len = dir.length();
    m.position.copy(mid);
    m.scale.y = len;
    if (len > 0.001) {
      dir.normalize();
      const q = new THREE.Quaternion();
      q.setFromUnitVectors(up, dir);
      m.quaternion.copy(q);
    }
  }

  for (const mk of SPHERE_MARKS) {
    if (landmarks[mk]) fighter.spheres[mk].position.copy(landmarks[mk]);
  }
}

// ═══════════════════════════════════════════════════════════════════════
// SCENE SETUP
// ═══════════════════════════════════════════════════════════════════════

export interface SceneHandle {
  scene: THREE.Scene;
  camera: THREE.PerspectiveCamera;
  renderer: THREE.WebGLRenderer;
  fighterA: Fighter;
  fighterB: Fighter;
  flashMesh: THREE.Mesh;
  rootA: THREE.Vector3;
  rootB: THREE.Vector3;
}

export function createScene(container: HTMLElement): SceneHandle {
  const W = container.clientWidth;
  const H = container.clientHeight;

  const scene = new THREE.Scene();
  scene.background = new THREE.Color(0x08080e);
  scene.fog = new THREE.Fog(0x08080e, 7, 16);

  const camera = new THREE.PerspectiveCamera(46, W / H, 0.1, 50);
  camera.position.set(0, 1.2, 3.6);
  camera.lookAt(0, 0.9, 0);

  const renderer = new THREE.WebGLRenderer({ antialias: true });
  renderer.setSize(W, H);
  renderer.setPixelRatio(Math.min(devicePixelRatio, 2));
  renderer.shadowMap.enabled = true;
  renderer.shadowMap.type = THREE.PCFSoftShadowMap;
  container.appendChild(renderer.domElement);

  // Lights
  scene.add(new THREE.AmbientLight(0x334466, 0.6));

  const kl = new THREE.DirectionalLight(0xffeedd, 1.0);
  kl.position.set(3, 5, 4);
  kl.castShadow = true;
  kl.shadow.mapSize.set(1024, 1024);
  kl.shadow.camera.near = 0.5;
  kl.shadow.camera.far = 15;
  kl.shadow.camera.left = -3;
  kl.shadow.camera.right = 3;
  kl.shadow.camera.top = 3;
  kl.shadow.camera.bottom = -1;
  scene.add(kl);

  const fl = new THREE.DirectionalLight(0x4466aa, 0.4);
  fl.position.set(-2, 3, -2);
  scene.add(fl);

  const rl = new THREE.DirectionalLight(0xff6644, 0.3);
  rl.position.set(0, 2, -4);
  scene.add(rl);

  // Ground
  const ground = new THREE.Mesh(
    new THREE.PlaneGeometry(14, 14),
    new THREE.MeshPhongMaterial({ color: 0x14141e, shininess: 60, specular: 0x222233 }),
  );
  ground.rotation.x = -Math.PI / 2;
  ground.receiveShadow = true;
  scene.add(ground);

  const grid = new THREE.GridHelper(8, 16, 0x222244, 0x161628);
  grid.position.set(0, 0.002, 0);
  scene.add(grid);

  // Ring posts
  const pm = new THREE.MeshPhongMaterial({ color: 0x888888 });
  for (const [x, , z] of [[-2.5, 0, -2.5], [2.5, 0, -2.5], [-2.5, 0, 2.5], [2.5, 0, 2.5]] as [number, number, number][]) {
    const p = new THREE.Mesh(new THREE.CylinderGeometry(0.03, 0.03, 1.6, 6), pm);
    p.position.set(x, 0.8, z);
    p.castShadow = true;
    scene.add(p);
  }

  // Ring ropes
  const rm = new THREE.MeshBasicMaterial({ color: 0x444466 });
  for (const ry of [0.5, 0.9, 1.3]) {
    const pts: [number, number, number][] = [[-2.5, 0, -2.5], [2.5, 0, -2.5], [2.5, 0, 2.5], [-2.5, 0, 2.5]];
    for (let i = 0; i < 4; i++) {
      const [x1, , z1] = pts[i];
      const [x2, , z2] = pts[(i + 1) % 4];
      const d = new THREE.Vector3(x2 - x1, 0, z2 - z1);
      const l = d.length();
      const rope = new THREE.Mesh(new THREE.CylinderGeometry(0.008, 0.008, l, 4), rm);
      rope.position.set((x1 + x2) / 2, ry, (z1 + z2) / 2);
      const q = new THREE.Quaternion();
      q.setFromUnitVectors(new THREE.Vector3(0, 1, 0), d.normalize());
      rope.quaternion.copy(q);
      scene.add(rope);
    }
  }

  // Fighters
  const fighterA = buildFighter(0xd4a574, 0x1a3a6b);
  const fighterB = buildFighter(0xc49060, 0x6b1a1a);
  scene.add(fighterA.group);
  scene.add(fighterB.group);

  // Flash effect
  const flashMesh = new THREE.Mesh(
    new THREE.SphereGeometry(0.1, 16, 16),
    new THREE.MeshBasicMaterial({ color: 0xffffcc, transparent: true, opacity: 0 }),
  );
  scene.add(flashMesh);

  const rootA = new THREE.Vector3(-0.5, 0.95, 0);
  const rootB = new THREE.Vector3(0.5, 0.95, 0);

  return { scene, camera, renderer, fighterA, fighterB, flashMesh, rootA, rootB };
}

export function disposeScene(container: HTMLElement, handle: SceneHandle): void {
  handle.renderer.dispose();
  if (container.contains(handle.renderer.domElement)) {
    container.removeChild(handle.renderer.domElement);
  }
}

export function handleResize(handle: SceneHandle, container: HTMLElement): void {
  const w = container.clientWidth;
  const h = container.clientHeight;
  handle.camera.aspect = w / h;
  handle.camera.updateProjectionMatrix();
  handle.renderer.setSize(w, h);
}

// ═══════════════════════════════════════════════════════════════════════
// ANIMATION TICK
// ═══════════════════════════════════════════════════════════════════════

export interface AnimState {
  anglesA: JointAngles;
  anglesB: JointAngles;
  targetA: JointAngles;
  targetB: JointAngles;
  fromA: JointAngles;
  fromB: JointAngles;
  blend: number;
  flashAlpha: number;
  flashSide: "a" | "b" | null;
}

export function tick(
  handle: SceneHandle,
  anim: AnimState,
  dt: number,
  ts: number,
): { anglesA: JointAngles; anglesB: JointAngles } {
  if (anim.blend < 1) {
    anim.blend = Math.min(1, anim.blend + dt * 2.5);
    const t = smoothstep(anim.blend);
    anim.anglesA = lerpAngles(anim.fromA, anim.targetA, t);
    anim.anglesB = lerpAngles(anim.fromB, anim.targetB, t);
  }

  const rA = solveFK(handle.rootA, 0, anim.anglesA);
  const rB = solveFK(handle.rootB, Math.PI, anim.anglesB);
  updateFighter(handle.fighterA, rA.landmarks);
  updateFighter(handle.fighterB, rB.landmarks);

  if (anim.flashAlpha > 0) {
    anim.flashAlpha = Math.max(0, anim.flashAlpha - dt * 3);
    (handle.flashMesh.material as THREE.MeshBasicMaterial).opacity = anim.flashAlpha;
    handle.flashMesh.scale.setScalar(1 + (1 - anim.flashAlpha) * 2.5);
    const target = anim.flashSide === "a" ? rA.landmarks.headCenter : rB.landmarks.headCenter;
    if (target) handle.flashMesh.position.copy(target);
  }

  handle.camera.position.y = 1.2 + Math.sin(ts * 0.002) * 0.003;
  handle.renderer.render(handle.scene, handle.camera);

  return { anglesA: anim.anglesA, anglesB: anim.anglesB };
}

// ═══════════════════════════════════════════════════════════════════════
// REACT HOOK — useScene
// ═══════════════════════════════════════════════════════════════════════

export function useScene(
  mountRef: React.RefObject<HTMLDivElement | null>,
  animRef: React.MutableRefObject<AnimState>,
  onAnglesUpdate: (anglesA: JointAngles, anglesB: JointAngles) => void,
): void {
  useEffect(() => {
    const ct = mountRef.current;
    if (!ct) return;

    const handle = createScene(ct);

    // Initial FK
    const initAngles = animRef.current.anglesA;
    const rA = solveFK(handle.rootA, 0, initAngles);
    const rB = solveFK(handle.rootB, Math.PI, initAngles);
    updateFighter(handle.fighterA, rA.landmarks);
    updateFighter(handle.fighterB, rB.landmarks);

    let lastT = 0;
    let rafId: number;

    function loop(ts: number) {
      rafId = requestAnimationFrame(loop);
      const dt = Math.min((ts - lastT) / 1000, 0.05);
      lastT = ts;

      const result = tick(handle, animRef.current, dt, ts);

      // Throttled angle display update (~5 Hz)
      if (Math.floor(ts / 200) !== Math.floor((ts - dt * 1000) / 200)) {
        onAnglesUpdate(result.anglesA, result.anglesB);
      }
    }

    rafId = requestAnimationFrame(loop);

    const onResize = () => handleResize(handle, ct);
    window.addEventListener("resize", onResize);

    return () => {
      cancelAnimationFrame(rafId);
      window.removeEventListener("resize", onResize);
      disposeScene(ct, handle);
    };
  }, []);
}

// ═══════════════════════════════════════════════════════════════════════
// UI COMPONENTS (pure presentational)
// ═══════════════════════════════════════════════════════════════════════

interface JointRowProps {
  name: string;
  angles: { fe?: number; aa?: number; ie?: number } | undefined;
}

export function JointRow({ name, angles }: JointRowProps) {
  if (!angles) return null;
  const j = JOINTS[name];
  if (!j) return null;

  return (
    <div style={{ display: "flex", gap: 4, fontSize: 8, alignItems: "center", marginBottom: 1 }}>
      <span style={{ width: 64, color: "#667799", textAlign: "right" }}>{name}</span>
      {(["fe", "aa", "ie"] as const).map((d) => {
        if (!j.rom[d]) return null;
        const v = Math.round(angles[d] || 0);
        const pct = ((v - j.rom[d][0]) / (j.rom[d][1] - j.rom[d][0])) * 100;
        return (
          <div key={d} style={{ width: 48, display: "flex", flexDirection: "column", alignItems: "center" }}>
            <div style={{ width: "100%", height: 3, background: "rgba(60,70,100,.3)", borderRadius: 1, position: "relative" }}>
              <div style={{
                position: "absolute", height: "100%", borderRadius: 1,
                background: d === "fe" ? "#4488cc" : d === "aa" ? "#44aa66" : "#cc8833",
                width: `${Math.max(2, Math.min(100, pct))}%`,
              }} />
            </div>
            <span style={{ color: "#556677" }}>{v}°</span>
          </div>
        );
      })}
    </div>
  );
}

interface FighterPanelProps {
  side: "A" | "B";
  hp: number;
  stamina: number;
  action: string | null;
  reasoning: string;
  actionSchema: string | undefined;
}

export function FighterPanel({ side, hp, stamina, action, reasoning, actionSchema }: FighterPanelProps) {
  const isA = side === "A";
  const accent = isA ? "#3a7bd5" : "#d53a3a";
  const border = isA ? "rgba(58,123,213,.2)" : "rgba(213,58,58,.2)";
  const hpLabel = isA ? "#88aacc" : "#cc8888";
  const staColor = isA ? "#3388cc" : "#cc5533";
  const reasonColor = isA ? "#556688" : "#776655";
  const schemaColor = isA ? "#445566" : "#554444";
  const schemaBorder = isA ? "rgba(60,80,120,.15)" : "rgba(120,60,60,.15)";

  return (
    <div style={{
      position: "absolute", top: 42, [isA ? "left" : "right"]: 6, zIndex: 10,
      background: "rgba(8,8,14,.9)", border: `1px solid ${border}`,
      borderRadius: 8, padding: "6px 10px", backdropFilter: "blur(8px)",
      width: 172, textAlign: isA ? undefined : "right",
    }}>
      <div style={{ fontSize: 10, fontWeight: 700, color: accent, letterSpacing: 1, marginBottom: 3 }}>FIGHTER {side}</div>
      <div style={{ marginBottom: 2 }}>
        <div style={{ display: "flex", justifyContent: "space-between", fontSize: 8, color: hpLabel }}><span>HP</span><span>{hp}</span></div>
        <div style={{ height: 5, background: "rgba(60,70,100,.3)", borderRadius: 2, overflow: "hidden" }}>
          <div style={{ height: "100%", width: `${hp}%`, background: hp > 50 ? "#22aa55" : hp > 25 ? "#cc8822" : "#cc3333", borderRadius: 2, transition: "width .5s" }} />
        </div>
      </div>
      <div style={{ marginBottom: 3 }}>
        <div style={{ display: "flex", justifyContent: "space-between", fontSize: 8, color: hpLabel }}><span>STA</span><span>{stamina}</span></div>
        <div style={{ height: 3, background: "rgba(60,70,100,.3)", borderRadius: 1, overflow: "hidden" }}>
          <div style={{ height: "100%", width: `${stamina}%`, background: staColor, borderRadius: 1, transition: "width .5s" }} />
        </div>
      </div>
      {action && (
        <div style={{ fontSize: 9 }}>
          <span style={{ color: accent, fontWeight: 700 }}>{action.toUpperCase()}</span>
          {reasoning && <div style={{ fontSize: 8, color: reasonColor, fontStyle: "italic" }}>"{reasoning}"</div>}
        </div>
      )}
      {action && actionSchema && (
        <div style={{ fontSize: 7, color: schemaColor, marginTop: 2, lineHeight: 1.4, borderTop: `1px solid ${schemaBorder}`, paddingTop: 2 }}>
          {actionSchema.slice(0, 120)}
        </div>
      )}
    </div>
  );
}

interface NarrativeOverlayProps {
  lastLog: { narr: string; dA: number; dB: number; out?: string } | undefined;
  phase: string;
}

export function NarrativeOverlay({ lastLog, phase }: NarrativeOverlayProps) {
  if (!lastLog) return null;
  const borderColor = lastLog.out?.includes("a_wins") ? "rgba(58,123,213,.3)"
    : lastLog.out?.includes("b_wins") ? "rgba(213,58,58,.3)"
    : "rgba(100,120,180,.2)";

  return (
    <div style={{
      position: "absolute", top: "50%", left: "50%", transform: "translate(-50%,-50%)", zIndex: 10,
      background: "rgba(8,8,14,.92)", border: `1px solid ${borderColor}`,
      borderRadius: 8, padding: "6px 16px", maxWidth: 360, textAlign: "center",
      pointerEvents: "none", opacity: phase === "animating" ? 1 : 0.12, transition: "opacity .5s",
    }}>
      <div style={{ fontSize: 10, color: "#c8ccd4", lineHeight: 1.4 }}>{lastLog.narr}</div>
      <div style={{ fontSize: 8, color: "#556688", marginTop: 2 }}>
        {lastLog.dA > 0 && <span style={{ color: "#cc4444" }}>A:-{lastLog.dA}hp </span>}
        {lastLog.dB > 0 && <span style={{ color: "#4488cc" }}>B:-{lastLog.dB}hp </span>}
      </div>
    </div>
  );
}

interface WinnerBannerProps {
  winner: string | null;
}

export function WinnerBanner({ winner }: WinnerBannerProps) {
  if (!winner) return null;
  const color = winner === "A" ? "#3a7bd5" : winner === "B" ? "#d53a3a" : "#888";
  return (
    <div style={{ position: "absolute", top: "36%", left: "50%", transform: "translate(-50%,-50%)", zIndex: 20, textAlign: "center" }}>
      <div style={{ fontSize: 26, fontWeight: 800, letterSpacing: 4, color, textShadow: "0 0 30px rgba(100,100,200,.4)" }}>
        {winner === "DRAW" ? "DRAW" : `FIGHTER ${winner} WINS`}
      </div>
    </div>
  );
}

interface JointAnglePanelProps {
  visible: boolean;
  anglesA: JointAngles;
  anglesB: JointAngles;
}

export function JointAnglePanel({ visible, anglesA, anglesB }: JointAnglePanelProps) {
  if (!visible) return null;
  const header = (side: "A" | "B") => (
    <div style={{ fontSize: 7, color: side === "A" ? "#445566" : "#554444", marginBottom: 2, display: "flex", gap: 4, justifyContent: "flex-end", paddingRight: 4 }}>
      <span style={{ width: 48, textAlign: "center", color: "#4488cc" }}>F/E</span>
      <span style={{ width: 48, textAlign: "center", color: "#44aa66" }}>Ab/Ad</span>
      <span style={{ width: 48, textAlign: "center", color: "#cc8833" }}>I/E</span>
    </div>
  );

  return (
    <div style={{ position: "absolute", top: 42, left: "50%", transform: "translateX(-50%)", zIndex: 15, display: "flex", gap: 8 }}>
      <div style={{ background: "rgba(4,4,8,.95)", border: "1px solid rgba(58,123,213,.2)", borderRadius: 6, padding: 6, width: 200 }}>
        <div style={{ fontSize: 8, color: "#3a7bd5", fontWeight: 700, marginBottom: 3, letterSpacing: 1 }}>FIGHTER A — JOINT ANGLES</div>
        {header("A")}
        {Object.keys(JOINTS).map((jn) => <JointRow key={jn} name={jn} angles={anglesA[jn]} />)}
      </div>
      <div style={{ background: "rgba(4,4,8,.95)", border: "1px solid rgba(213,58,58,.2)", borderRadius: 6, padding: 6, width: 200 }}>
        <div style={{ fontSize: 8, color: "#d53a3a", fontWeight: 700, marginBottom: 3, letterSpacing: 1 }}>FIGHTER B — JOINT ANGLES</div>
        {header("B")}
        {Object.keys(JOINTS).map((jn) => <JointRow key={jn} name={jn} angles={anglesB[jn]} />)}
      </div>
    </div>
  );
}

interface DebugPanelProps {
  visible: boolean;
  entries: { t: string; m: string; l: string }[];
  dbRef: React.RefObject<HTMLDivElement | null>;
}

const LOG_COLORS: Record<string, string> = { info: "#556688", ok: "#44aa66", warn: "#ccaa33", error: "#cc4444" };

export function DebugPanel({ visible, entries, dbRef }: DebugPanelProps) {
  if (!visible) return null;
  return (
    <div style={{ position: "absolute", bottom: 110, left: 6, zIndex: 15, width: 320 }}>
      <div ref={dbRef} style={{ background: "rgba(2,2,6,.97)", border: "1px solid rgba(100,120,180,.15)", borderRadius: 6, padding: 4, maxHeight: 140, overflowY: "auto", fontSize: 8, lineHeight: 1.5 }}>
        {entries.length === 0
          ? <div style={{ color: "#334455", textAlign: "center", padding: 4 }}>Press EXCHANGE to start</div>
          : entries.map((d, i) => (
            <div key={i} style={{ color: LOG_COLORS[d.l], borderBottom: "1px solid rgba(50,60,80,.1)", wordBreak: "break-all" }}>
              <span style={{ color: "#2a3344" }}>{d.t}</span> {d.m}
            </div>
          ))}
      </div>
    </div>
  );
}

interface TitleBarProps {
  round: number;
  exchange: number;
  phase: string;
}

export function TitleBar({ round, exchange, phase }: TitleBarProps) {
  const totalDofs = Object.keys(JOINTS).reduce((a, k) => {
    const j = JOINTS[k];
    return a + (j.rom.fe ? 1 : 0) + (j.rom.aa ? 1 : 0) + (j.rom.ie ? 1 : 0);
  }, 0);
  const phaseColor = phase === "thinking" ? "#ccaa33" : phase === "animating" ? "#44aa66" : phase === "finished" ? "#cc4444" : "#556688";

  return (
    <div style={{ position: "absolute", top: 8, left: "50%", transform: "translateX(-50%)", zIndex: 10, textAlign: "center" }}>
      <div style={{ fontSize: 9, letterSpacing: 3, textTransform: "uppercase", color: "#556688" }}>FK-Driven AI Fight — Schema v3 Joint Angles</div>
      <div style={{ fontSize: 8, color: "#3a5577", marginTop: 2 }}>
        Rd{round}/3 Ex{exchange}/12{" "}
        <span style={{ color: phaseColor, fontWeight: 700 }}>{phase.toUpperCase()}</span>
        {" "}· 14 joints · {totalDofs} DOFs · ROM-clamped
      </div>
    </div>
  );
}

interface ControlBarProps {
  phase: string;
  apiKey: string;
  auto: boolean;
  speed: string;
  showJoints: boolean;
  showDebug: boolean;
  debugErrorCount: number;
  log: { ex: number; aA: string; aB: string; narr: string }[];
  onExchange: () => void;
  onToggleAuto: () => void;
  onSetSpeed: (s: string) => void;
  onToggleJoints: () => void;
  onToggleDebug: () => void;
  onApiKeyChange: (key: string) => void;
  onReset: () => void;
}

export function ControlBar({
  phase, apiKey, auto, speed, showJoints, showDebug, debugErrorCount, log,
  onExchange, onToggleAuto, onSetSpeed, onToggleJoints, onToggleDebug, onApiKeyChange, onReset,
}: ControlBarProps) {
  return (
    <div style={{ position: "absolute", bottom: 0, left: 0, right: 0, zIndex: 10, background: "rgba(8,8,14,.94)", borderTop: "1px solid rgba(100,120,180,.15)", padding: "6px 10px" }}>
      <div style={{ display: "flex", alignItems: "center", gap: 6, flexWrap: "wrap" }}>
        <button onClick={onExchange} disabled={phase !== "idle" || !apiKey} style={{
          background: phase === "thinking" ? "rgba(200,170,50,.15)" : "rgba(58,123,213,.15)",
          border: `1px solid ${phase === "thinking" ? "rgba(200,170,50,.3)" : "rgba(58,123,213,.3)"}`,
          color: phase === "thinking" ? "#ccaa33" : !apiKey ? "#556677" : "#88bbdd",
          borderRadius: 6, padding: "5px 12px", cursor: phase === "idle" && apiKey ? "pointer" : "wait",
          fontSize: 10, fontFamily: "inherit",
        }}>
          {phase === "thinking" ? "⧖ THINKING" : phase === "animating" ? "⚡ RESOLVING" : !apiKey ? "🔑 SET KEY" : "⚡ EXCHANGE"}
        </button>

        <button onClick={onToggleAuto} disabled={phase === "finished"} style={{
          background: auto ? "rgba(50,180,80,.15)" : "none",
          border: `1px solid ${auto ? "rgba(50,180,80,.3)" : "rgba(100,120,180,.2)"}`,
          color: auto ? "#66cc88" : "#88aabb",
          borderRadius: 6, padding: "5px 10px", cursor: "pointer", fontSize: 10, fontFamily: "inherit",
        }}>
          {auto ? "■ STOP" : "▶ AUTO"}
        </button>

        <div style={{ display: "flex", gap: 3 }}>
          {([["normal", "1×"], ["fast", "2×"], ["blitz", "4×"]] as const).map(([v, l]) => (
            <button key={v} onClick={() => onSetSpeed(v)} style={{
              background: speed === v ? "rgba(60,100,180,.2)" : "none",
              border: "1px solid rgba(100,120,180,.15)",
              color: speed === v ? "#88bbdd" : "#556677",
              borderRadius: 4, padding: "2px 6px", cursor: "pointer", fontSize: 8, fontFamily: "inherit",
            }}>{l}</button>
          ))}
        </div>

        <button onClick={onToggleJoints} style={{
          background: showJoints ? "rgba(100,100,200,.15)" : "none",
          border: "1px solid rgba(100,120,180,.2)", color: showJoints ? "#8899cc" : "#556677",
          borderRadius: 6, padding: "5px 8px", cursor: "pointer", fontSize: 8, fontFamily: "inherit",
        }}>
          {showJoints ? "HIDE" : "SHOW"} JOINTS
        </button>

        <button onClick={onToggleDebug} style={{
          background: showDebug ? "rgba(100,100,200,.15)" : "none",
          border: "1px solid rgba(100,120,180,.2)", color: showDebug ? "#8899cc" : "#556677",
          borderRadius: 6, padding: "5px 8px", cursor: "pointer", fontSize: 8, fontFamily: "inherit",
        }}>
          DEBUG{debugErrorCount > 0 ? ` (${debugErrorCount}err)` : ""}
        </button>

        <input
          type="password" placeholder="sk-ant-… API key" value={apiKey}
          onChange={(e) => onApiKeyChange(e.target.value)}
          style={{
            background: "rgba(20,20,30,.8)",
            border: `1px solid ${apiKey ? "rgba(50,180,80,.3)" : "rgba(180,80,80,.3)"}`,
            color: "#88aabb", borderRadius: 4, padding: "4px 8px",
            fontSize: 9, fontFamily: "inherit", width: 140, marginLeft: "auto",
          }}
        />

        <button onClick={onReset} style={{
          background: "none", border: "1px solid rgba(180,80,80,.2)", color: "#aa6666",
          borderRadius: 6, padding: "5px 10px", cursor: "pointer", fontSize: 10, fontFamily: "inherit",
        }}>
          ↺ RESET
        </button>
      </div>

      {log.length > 0 && (
        <div style={{ marginTop: 4, maxHeight: 52, overflowY: "auto", fontSize: 8, lineHeight: 1.4 }}>
          {log.slice(-4).map((l, i) => (
            <div key={i} style={{ color: "#667799", borderBottom: "1px solid rgba(100,120,180,.06)" }}>
              <span style={{ color: "#445566" }}>#{l.ex}</span>{" "}
              <span style={{ color: "#3a7bd5" }}>A:{l.aA}</span> vs{" "}
              <span style={{ color: "#d53a3a" }}>B:{l.aB}</span>{" "}
              <span style={{ color: "#88aacc" }}>→ {l.narr}</span>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
