/**
 * High-fidelity anatomical renderer for HumanBody schema v3.0.0.
 *
 * Renders all 206 bones, 616 muscles, 1230 tendons, 94 vessels, 51 nerves,
 * 38 organs, 43 ligaments, and 36 cartilage structures with PBR materials,
 * anatomical coloring, and interactive layer toggling.
 *
 * Coordinate system: positions in cm, Y-up. Body range ≈ X[-30,30] Y[0,180] Z[-5,21].
 * All geometry is generated from the schema data — no hardcoded meshes.
 *
 * Dependencies: three, three/addons (OrbitControls, EffectComposer, passes, GLTFLoader)
 *
 * Generated by: Claude Opus 4.6 (1M context)
 */

import { useEffect, useRef, useState, useCallback, useMemo } from "react";
import * as THREE from "three";
import { OrbitControls } from "three/addons/controls/OrbitControls.js";
import { EffectComposer } from "three/addons/postprocessing/EffectComposer.js";
import { RenderPass } from "three/addons/postprocessing/RenderPass.js";
import { UnrealBloomPass } from "three/addons/postprocessing/UnrealBloomPass.js";
import { csgTreeToGeometry, type CSGNode } from "./renderer-csg";

// ═══════════════════════════════════════════════════════════════════════
// 1. TYPE INTERFACES — mirrors HumanBody JSON schema
// ═══════════════════════════════════════════════════════════════════════

export interface Vec3 {
  x: number;
  y: number;
  z: number;
}

export interface RGBAColor {
  r: number;
  g: number;
  b: number;
  a: number;
}

export interface Transform {
  position: Vec3;
  rotation: Vec3;
  scale: Vec3;
}

export interface BoneData {
  id: string;
  name: string;
  classification: "long" | "short" | "flat" | "irregular" | "sesamoid";
  region: string;
  transform: Transform;
  length: number;
  width: number;
  depth: number;
  mass: number;
  parentBoneId: string | null;
}

export interface TendonData {
  id: string;
  name: string;
  attachedBoneId: string;
  localPosition: Vec3;
  length: number;
  crossSectionalArea?: number;
}

export interface MuscleData {
  id: string;
  name: string;
  region: string;
  type: string;
  origin: { tendonId: string; description: string };
  insertion: { tendonId: string; description: string };
  fiberDirection: Vec3;
  restingLength: number;
  volume: number;
  mass: number;
  fascicleArchitecture: string;
  pennationAngle?: number;
}

export interface JointData {
  id: string;
  name: string;
  type: string;
  transform: Transform;
  connectedBoneIds: string[];
  degreesOfFreedom: number;
}

export interface OrganData {
  id: string;
  name: string;
  system: string;
  transform: Transform;
  volume: number;
  mass: number;
  isVital: boolean;
  laterality: string;
}

export interface VesselData {
  id: string;
  name: string;
  vesselType: "artery" | "vein";
  path: Vec3[];
  averageLumenRadius: number;
  parentVesselId?: string | null;
}

export interface NerveData {
  id: string;
  name: string;
  type: string;
  path: Vec3[];
  parentNerveId?: string | null;
}

export interface LigamentData {
  id: string;
  name: string;
  originBoneId: string;
  originPosition: Vec3;
  insertionBoneId: string;
  insertionPosition: Vec3;
  restingLength: number;
}

export interface CartilageData {
  id: string;
  name: string;
  type: "hyaline" | "fibrocartilage";
  thickness: number;
  surfaceArea: number;
  boneId?: string;
  jointId: string;
}

export interface HumanBodyData {
  schemaVersion: string;
  id: string;
  name?: string;
  proportions: {
    biologicalSex?: string;
    totalHeight: number;
    weight: number;
  };
  skeleton: BoneData[];
  joints: JointData[];
  tendons: TendonData[];
  muscles: MuscleData[];
  organs: OrganData[];
  vascularSystem: VesselData[];
  nerves: NerveData[];
  ligaments: LigamentData[];
  cartilage: CartilageData[];
  boneGeometries?: BoneGeometryData[];
  rendering?: RenderingLayerData;
}

export interface PBRMaterialData {
  baseColor?: RGBAColor;
  metalness?: number;
  roughness?: number;
  clearcoat?: number;
  clearcoatRoughness?: number;
  transmission?: number;
  thickness?: number;
  sheen?: number;
  sheenRoughness?: number;
  sheenColor?: RGBAColor;
  emissive?: RGBAColor;
  emissiveIntensity?: number;
}

export interface EntityRenderOverrideData {
  entityId: string;
  color?: RGBAColor;
  opacity?: number;
  visible?: boolean;
  material?: PBRMaterialData;
}

export interface RenderingLayerData {
  muscleOverrides?: EntityRenderOverrideData[];
  boneOverrides?: EntityRenderOverrideData[];
  organOverrides?: EntityRenderOverrideData[];
  vesselOverrides?: EntityRenderOverrideData[];
  globalOpacity?: number;
}

export interface IndexedMeshLODData {
  level: number;
  vertexCount: number;
  triangleCount: number;
  vertices: {
    positions: number[];
    normals?: number[];
    uvs?: number[];
  };
  indices: number[];
}

export interface IndexedMeshGeometryData {
  geometryType: "indexed_mesh";
  id: string;
  boneId: string;
  lods: IndexedMeshLODData[];
  isClosed?: boolean;
  isManifold?: boolean;
}

export interface ExternalAssetGeometryData {
  geometryType: "external_asset";
  id: string;
  boneId: string;
  uri: string;
  format: string;
  contentHash?: string;
  byteSize?: number;
  coordinateSpace?: { upAxis: string; units: string; handedness: string };
  lodVariants?: { level: number; uri: string; format: string; approximateTriangleCount?: number }[];
}

export type BoneGeometryData =
  | { geometryType: "parametric_csg"; id: string; boneId: string; csgTree: CSGNode; collisionHull?: string }
  | { geometryType: "indexed_mesh"; id: string; boneId: string; lods: IndexedMeshLODData[]; isClosed?: boolean; isManifold?: boolean }
  | ExternalAssetGeometryData;

// ═══════════════════════════════════════════════════════════════════════
// 2. ANATOMICAL COLOR PALETTE — region-based PBR coloring
// ═══════════════════════════════════════════════════════════════════════

const BONE_COLORS: Record<string, number> = {
  axial_cranium:         0xf5edd6,
  axial_face:            0xf0e6cc,
  axial_vertebral:       0xede0c0,
  axial_thorax:          0xe8dbb8,
  appendicular_pectoral: 0xeadcba,
  appendicular_upper:    0xe5d7b2,
  appendicular_pelvic:   0xe0d0aa,
  appendicular_lower:    0xdbc9a2,
};

const MUSCLE_COLORS: Record<string, number> = {
  face:               0xcc6666,
  head_and_neck:      0xc45555,
  shoulder:           0xb83333,
  arm_anterior:       0xc04040,
  arm_posterior:      0xaa3535,
  forearm_anterior:   0xc04848,
  forearm_posterior:  0xaa3838,
  hand_intrinsic:     0xd06060,
  thorax_anterior:    0xb02828,
  back_superficial:   0xa02020,
  back_deep:          0x8a1818,
  abdomen:            0xb53030,
  hip:                0x992222,
  thigh_anterior:     0xb82828,
  thigh_posterior:    0xa02020,
  thigh_medial:       0xa82828,
  leg_anterior:       0xc03838,
  leg_posterior:      0xa83030,
  leg_lateral:        0xb53333,
  foot_intrinsic:     0xd06060,
};

const ORGAN_COLORS: Record<string, number> = {
  cardiovascular: 0xcc2233,
  respiratory:    0xeeaaaa,
  digestive:      0xddaa77,
  nervous:        0xffddcc,
  urinary:        0xccaa66,
  endocrine:      0xddbb88,
  lymphatic:      0x996688,
  reproductive:   0xdd8899,
  integumentary:  0xeeccaa,
};

// ═══════════════════════════════════════════════════════════════════════
// 3. MATERIAL FACTORY — PBR materials for each tissue type
// ═══════════════════════════════════════════════════════════════════════

const _materialCache = new Map<string, THREE.Material>();

function boneMaterial(region: string): THREE.MeshPhysicalMaterial {
  const key = `bone_${region}`;
  if (_materialCache.has(key)) return _materialCache.get(key) as THREE.MeshPhysicalMaterial;
  const mat = new THREE.MeshPhysicalMaterial({
    color: BONE_COLORS[region] ?? 0xe8dbb8,
    roughness: 0.45,
    metalness: 0.02,
    clearcoat: 0.2,
    clearcoatRoughness: 0.35,
    sheen: 0.15,
    sheenRoughness: 0.5,
    sheenColor: new THREE.Color(0xfffff0),
  });
  _materialCache.set(key, mat);
  return mat;
}

function muscleMaterial(region: string): THREE.MeshPhysicalMaterial {
  const key = `muscle_${region}`;
  if (_materialCache.has(key)) return _materialCache.get(key) as THREE.MeshPhysicalMaterial;
  const mat = new THREE.MeshPhysicalMaterial({
    color: MUSCLE_COLORS[region] ?? 0xaa3333,
    roughness: 0.55,
    metalness: 0.0,
    clearcoat: 0.15,
    clearcoatRoughness: 0.4,
    transmission: 0.03,
    thickness: 0.8,
    sheen: 0.25,
    sheenRoughness: 0.4,
    sheenColor: new THREE.Color(0xff8888),
    side: THREE.DoubleSide,
  });
  _materialCache.set(key, mat);
  return mat;
}

function tendonMaterial(): THREE.MeshPhysicalMaterial {
  const key = "tendon";
  if (_materialCache.has(key)) return _materialCache.get(key) as THREE.MeshPhysicalMaterial;
  const mat = new THREE.MeshPhysicalMaterial({
    color: 0xf0f0e8,
    roughness: 0.5,
    metalness: 0.0,
    clearcoat: 0.25,
    clearcoatRoughness: 0.25,
    sheen: 0.4,
    sheenRoughness: 0.35,
    sheenColor: new THREE.Color(0xeeeedd),
  });
  _materialCache.set(key, mat);
  return mat;
}

function arteryMaterial(): THREE.MeshPhysicalMaterial {
  const key = "artery";
  if (_materialCache.has(key)) return _materialCache.get(key) as THREE.MeshPhysicalMaterial;
  const mat = new THREE.MeshPhysicalMaterial({
    color: 0xdd3322,
    roughness: 0.4,
    metalness: 0.0,
    clearcoat: 0.35,
    clearcoatRoughness: 0.15,
    transmission: 0.12,
    thickness: 0.4,
  });
  _materialCache.set(key, mat);
  return mat;
}

function veinMaterial(): THREE.MeshPhysicalMaterial {
  const key = "vein";
  if (_materialCache.has(key)) return _materialCache.get(key) as THREE.MeshPhysicalMaterial;
  const mat = new THREE.MeshPhysicalMaterial({
    color: 0x3344aa,
    roughness: 0.4,
    metalness: 0.0,
    clearcoat: 0.35,
    clearcoatRoughness: 0.15,
    transmission: 0.12,
    thickness: 0.4,
  });
  _materialCache.set(key, mat);
  return mat;
}

function nerveMaterial(): THREE.MeshPhysicalMaterial {
  const key = "nerve";
  if (_materialCache.has(key)) return _materialCache.get(key) as THREE.MeshPhysicalMaterial;
  const mat = new THREE.MeshPhysicalMaterial({
    color: 0xeedd44,
    roughness: 0.5,
    metalness: 0.0,
    emissive: 0x332200,
    emissiveIntensity: 0.15,
    clearcoat: 0.15,
    clearcoatRoughness: 0.4,
  });
  _materialCache.set(key, mat);
  return mat;
}

function organMaterial(system: string): THREE.MeshPhysicalMaterial {
  const key = `organ_${system}`;
  if (_materialCache.has(key)) return _materialCache.get(key) as THREE.MeshPhysicalMaterial;
  const mat = new THREE.MeshPhysicalMaterial({
    color: ORGAN_COLORS[system] ?? 0xddaa88,
    roughness: 0.5,
    metalness: 0.0,
    clearcoat: 0.3,
    clearcoatRoughness: 0.25,
    transmission: 0.1,
    thickness: 1.5,
    sheen: 0.15,
    sheenRoughness: 0.5,
    sheenColor: new THREE.Color(0xffcccc),
    side: THREE.DoubleSide,
  });
  _materialCache.set(key, mat);
  return mat;
}

function ligamentMaterial(): THREE.MeshPhysicalMaterial {
  const key = "ligament";
  if (_materialCache.has(key)) return _materialCache.get(key) as THREE.MeshPhysicalMaterial;
  const mat = new THREE.MeshPhysicalMaterial({
    color: 0xd0d8c0,
    roughness: 0.55,
    metalness: 0.0,
    clearcoat: 0.2,
    clearcoatRoughness: 0.35,
    sheen: 0.25,
    sheenRoughness: 0.45,
    sheenColor: new THREE.Color(0xeeeedd),
  });
  _materialCache.set(key, mat);
  return mat;
}

function cartilageMaterial(type: string): THREE.MeshPhysicalMaterial {
  const key = `cartilage_${type}`;
  if (_materialCache.has(key)) return _materialCache.get(key) as THREE.MeshPhysicalMaterial;
  const color = type === "hyaline" ? 0xc8dde8 : 0xb0c8d0;
  const mat = new THREE.MeshPhysicalMaterial({
    color,
    roughness: 0.3,
    metalness: 0.0,
    clearcoat: 0.5,
    clearcoatRoughness: 0.15,
    transmission: 0.2,
    thickness: 0.6,
  });
  _materialCache.set(key, mat);
  return mat;
}

function jointMaterial(): THREE.MeshPhysicalMaterial {
  const key = "joint";
  if (_materialCache.has(key)) return _materialCache.get(key) as THREE.MeshPhysicalMaterial;
  const mat = new THREE.MeshPhysicalMaterial({
    color: 0x66aadd,
    roughness: 0.25,
    metalness: 0.1,
    clearcoat: 0.5,
    clearcoatRoughness: 0.1,
    emissive: 0x112244,
    emissiveIntensity: 0.2,
  });
  _materialCache.set(key, mat);
  return mat;
}

function toThreeColor(c?: RGBAColor): THREE.Color | undefined {
  if (!c) return undefined;
  return new THREE.Color(c.r / 255, c.g / 255, c.b / 255);
}

function applyRenderOverride(
  base: THREE.MeshPhysicalMaterial,
  override?: EntityRenderOverrideData,
  globalOpacity = 1,
): THREE.MeshPhysicalMaterial {
  if (!override) return base;
  const mat = base.clone();
  const baseColor = toThreeColor(override.material?.baseColor ?? override.color);
  if (baseColor) mat.color = baseColor;
  if (override.opacity !== undefined) {
    mat.opacity = Math.max(0, Math.min(1, override.opacity * globalOpacity));
    mat.transparent = mat.opacity < 1;
  } else if (globalOpacity < 1) {
    mat.opacity = globalOpacity;
    mat.transparent = true;
  }
  if (override.material?.metalness !== undefined) mat.metalness = override.material.metalness;
  if (override.material?.roughness !== undefined) mat.roughness = override.material.roughness;
  if (override.material?.clearcoat !== undefined) mat.clearcoat = override.material.clearcoat;
  if (override.material?.clearcoatRoughness !== undefined) mat.clearcoatRoughness = override.material.clearcoatRoughness;
  if (override.material?.transmission !== undefined) mat.transmission = override.material.transmission;
  if (override.material?.thickness !== undefined) mat.thickness = override.material.thickness;
  if (override.material?.sheen !== undefined) mat.sheen = override.material.sheen;
  if (override.material?.sheenRoughness !== undefined) mat.sheenRoughness = override.material.sheenRoughness;
  const sheenColor = toThreeColor(override.material?.sheenColor);
  if (sheenColor) mat.sheenColor = sheenColor;
  const emissive = toThreeColor(override.material?.emissive);
  if (emissive) mat.emissive = emissive;
  if (override.material?.emissiveIntensity !== undefined) mat.emissiveIntensity = override.material.emissiveIntensity;
  return mat;
}

// ═══════════════════════════════════════════════════════════════════════
// 4. GEOMETRY FACTORIES
// ═══════════════════════════════════════════════════════════════════════

/**
 * Creates a tube geometry with varying radius along its length.
 * This is the key function for realistic muscle bellies and tapered bones.
 */
function variableRadiusTube(
  path: THREE.Vector3[],
  tubularSegments: number,
  radiusFn: (t: number) => number,
  radialSegments: number = 8,
): THREE.BufferGeometry {
  if (path.length < 2) return new THREE.SphereGeometry(radiusFn(0.5), 8, 6);

  const curve = new THREE.CatmullRomCurve3(path, false, "catmullrom", 0.5);
  const frames = curve.computeFrenetFrames(tubularSegments, false);

  const vertices: number[] = [];
  const normals: number[] = [];
  const uvs: number[] = [];
  const indices: number[] = [];

  for (let i = 0; i <= tubularSegments; i++) {
    const t = i / tubularSegments;
    const P = curve.getPointAt(t);
    const N = frames.normals[i]!;
    const B = frames.binormals[i]!;
    const r = radiusFn(t);

    for (let j = 0; j <= radialSegments; j++) {
      const v = (j / radialSegments) * Math.PI * 2;
      const sin = Math.sin(v);
      const cos = -Math.cos(v);

      const nx = cos * N.x + sin * B.x;
      const ny = cos * N.y + sin * B.y;
      const nz = cos * N.z + sin * B.z;
      const len = Math.sqrt(nx * nx + ny * ny + nz * nz) || 1;

      vertices.push(P.x + r * nx, P.y + r * ny, P.z + r * nz);
      normals.push(nx / len, ny / len, nz / len);
      uvs.push(j / radialSegments, t);
    }
  }

  for (let i = 0; i < tubularSegments; i++) {
    for (let j = 0; j < radialSegments; j++) {
      const a = i * (radialSegments + 1) + j;
      const b = (i + 1) * (radialSegments + 1) + j;
      const c = (i + 1) * (radialSegments + 1) + (j + 1);
      const d = i * (radialSegments + 1) + (j + 1);
      indices.push(a, b, d, b, c, d);
    }
  }

  const geo = new THREE.BufferGeometry();
  geo.setIndex(indices);
  geo.setAttribute("position", new THREE.Float32BufferAttribute(vertices, 3));
  geo.setAttribute("normal", new THREE.Float32BufferAttribute(normals, 3));
  geo.setAttribute("uv", new THREE.Float32BufferAttribute(uvs, 2));
  return geo;
}

function tubeFromPath(points: THREE.Vector3[], radius: number, segments?: number): THREE.BufferGeometry {
  if (points.length < 2) return new THREE.SphereGeometry(radius, 6, 4);
  const curve = new THREE.CatmullRomCurve3(points, false, "catmullrom", 0.5);
  const tubeSeg = segments ?? Math.max(4, Math.min(32, Math.ceil(curve.getLength() / 2)));
  return new THREE.TubeGeometry(curve, tubeSeg, radius, 6, false);
}

function longBoneGeometry(length: number, width: number, depth: number): THREE.BufferGeometry {
  const r = (width + depth) / 4;
  const epiphR = r * 1.35;
  const diaphR = r * 0.7;
  const h = Math.max(0.5, length);

  const nPts = 7;
  const pts: THREE.Vector3[] = [];
  for (let i = 0; i < nPts; i++) {
    pts.push(new THREE.Vector3(0, -h / 2 + (h * i) / (nPts - 1), 0));
  }

  return variableRadiusTube(pts, 16, (t) => {
    const endProx = Math.exp(-((t * 5) ** 2));
    const endDist = Math.exp(-(((1 - t) * 5) ** 2));
    const endInfluence = Math.max(endProx, endDist);
    return diaphR + (epiphR - diaphR) * endInfluence;
  }, 10);
}

function boneGeometry(bone: BoneData): THREE.BufferGeometry {
  const cls = bone.classification;
  const l = bone.length;
  const w = bone.width;
  const d = bone.depth;

  switch (cls) {
    case "long": {
      return longBoneGeometry(l, w, d);
    }
    case "flat": {
      // Flattened box — cranial/rib bones, with slight curvature
      const geo = new THREE.BoxGeometry(w, l * 0.15, d, 4, 1, 4);
      // Bend flat bones slightly for anatomical curvature
      const pos = geo.attributes.position as THREE.BufferAttribute;
      for (let i = 0; i < pos.count; i++) {
        const x = pos.getX(i);
        const z = pos.getZ(i);
        const dist = Math.sqrt(x * x + z * z);
        pos.setY(i, pos.getY(i) + dist * 0.05);
      }
      geo.computeVertexNormals();
      return geo;
    }
    case "irregular": {
      // Organic-looking shape: smooth icosahedron with subtle perturbation
      const ico = new THREE.IcosahedronGeometry(1, 2);
      const pos = ico.attributes.position as THREE.BufferAttribute;
      for (let i = 0; i < pos.count; i++) {
        const x = pos.getX(i), y = pos.getY(i), z = pos.getZ(i);
        const len = Math.sqrt(x * x + y * y + z * z) || 1;
        const nx = x / len, ny = y / len, nz = z / len;
        // Subtle organic noise — just enough to break perfect symmetry
        const noise = 1.0
          + 0.04 * Math.sin(nx * 5.3 + ny * 3.1)
          + 0.03 * Math.cos(nz * 4.7 + nx * 2.2);
        pos.setXYZ(i, nx * (w / 2) * noise, ny * (l / 2) * noise, nz * (d / 2) * noise);
      }
      ico.computeVertexNormals();
      return ico;
    }
    case "short": {
      // Rounded cube — carpals, tarsals
      const geo = new THREE.IcosahedronGeometry(1, 1);
      geo.scale(w / 2, l / 2, d / 2);
      return geo;
    }
    case "sesamoid": {
      // Smooth sphere — patella, sesamoids
      const r = Math.max(w, d, l) / 2;
      return new THREE.SphereGeometry(r, 12, 10);
    }
    default:
      return new THREE.SphereGeometry(l / 2, 8, 6);
  }
}

function indexedMeshToGeometry(mesh: IndexedMeshGeometryData): THREE.BufferGeometry {
  const lod = [...mesh.lods].sort((a, b) => a.level - b.level)[0];
  if (!lod) {
    return new THREE.BufferGeometry();
  }
  const geo = new THREE.BufferGeometry();
  geo.setAttribute("position", new THREE.Float32BufferAttribute(lod.vertices.positions, 3));
  geo.setIndex(lod.indices);
  if (lod.vertices.normals && lod.vertices.normals.length === lod.vertices.positions.length) {
    geo.setAttribute("normal", new THREE.Float32BufferAttribute(lod.vertices.normals, 3));
  } else {
    geo.computeVertexNormals();
  }
  if (lod.vertices.uvs && lod.vertices.uvs.length === (lod.vertexCount * 2)) {
    geo.setAttribute("uv", new THREE.Float32BufferAttribute(lod.vertices.uvs, 2));
  }
  return geo;
}

/**
 * Organ-specific geometry based on organ name/system.
 * Each organ type gets a distinct silhouette instead of a generic ellipsoid.
 */
function organGeometry(organ: OrganData): THREE.BufferGeometry {
  const name = organ.name.toLowerCase();
  const vol = organ.volume;
  const k = Math.cbrt(vol / ((4 / 3) * Math.PI));

  if (name.includes("heart")) {
    return heartGeometry(k);
  }
  if (name.includes("lung")) {
    return lungGeometry(k, name.includes("(l)") || name.includes("left") ? -1 : 1);
  }
  if (name.includes("brain") || name.includes("cerebr")) {
    return brainGeometry(k);
  }
  if (name.includes("kidney")) {
    return kidneyGeometry(k);
  }
  if (name.includes("liver")) {
    return liverGeometry(k);
  }
  if (name.includes("stomach")) {
    return stomachGeometry(k);
  }
  if (name.includes("intestin")) {
    return intestineGeometry(k, name.includes("large") || name.includes("colon"));
  }
  if (name.includes("bladder")) {
    return bladderGeometry(k);
  }

  // Default: organic ellipsoid with perturbation
  return defaultOrganGeometry(vol);
}

function heartGeometry(k: number): THREE.BufferGeometry {
  // Heart-like shape: rounded top with tapered bottom (apex)
  const pts: THREE.Vector2[] = [];
  for (let i = 0; i <= 20; i++) {
    const t = i / 20;
    const angle = t * Math.PI;
    // Heart profile: wide at top 1/3, tapering to apex at bottom
    let r: number;
    if (t < 0.15) {
      // Flat top (base of heart, where vessels attach)
      r = 0.6 + t * 1.5;
    } else if (t < 0.55) {
      // Wide rounded body
      r = Math.sin(angle) * 1.1;
    } else {
      // Taper to apex
      const taper = (1 - t) / 0.45;
      r = Math.sin(angle) * 0.9 * taper;
    }
    pts.push(new THREE.Vector2(Math.max(0.01, r * k * 1.0), (t - 0.5) * k * 2.8));
  }
  const geo = new THREE.LatheGeometry(pts, 16);
  geo.computeVertexNormals();
  return geo;
}

function lungGeometry(k: number, side: number): THREE.BufferGeometry {
  // Elongated ellipsoid with medial flat surface and rounded lateral
  const geo = new THREE.SphereGeometry(1, 16, 12);
  const pos = geo.attributes.position as THREE.BufferAttribute;
  for (let i = 0; i < pos.count; i++) {
    let x = pos.getX(i), y = pos.getY(i), z = pos.getZ(i);
    // Flatten medial side (towards center of body)
    if (x * side < 0) {
      x *= 0.6;
    }
    // Taper top (apex)
    const yNorm = (y + 1) / 2; // 0=bottom, 1=top
    const taperTop = yNorm > 0.7 ? 1 - (yNorm - 0.7) / 0.3 * 0.4 : 1;
    // Widen bottom
    const widenBot = yNorm < 0.3 ? 1 + (0.3 - yNorm) / 0.3 * 0.15 : 1;
    pos.setXYZ(i,
      x * k * 1.2 * taperTop * widenBot,
      y * k * 1.8,
      z * k * 1.0 * taperTop * widenBot,
    );
  }
  geo.computeVertexNormals();
  return geo;
}

function brainGeometry(k: number): THREE.BufferGeometry {
  // Sphere with sulci/gyri wrinkles via vertex displacement
  const geo = new THREE.IcosahedronGeometry(k * 1.3, 4);
  const pos = geo.attributes.position as THREE.BufferAttribute;
  for (let i = 0; i < pos.count; i++) {
    const x = pos.getX(i), y = pos.getY(i), z = pos.getZ(i);
    const len = Math.sqrt(x * x + y * y + z * z) || 1;
    const nx = x / len, ny = y / len, nz = z / len;
    // Multi-frequency noise for wrinkled surface
    const wrinkle =
      0.06 * Math.sin(nx * 18 + nz * 12) * Math.cos(ny * 15 + nx * 8) +
      0.04 * Math.sin(ny * 22 + nz * 16) * Math.cos(nx * 20) +
      0.03 * Math.cos(nz * 28 + nx * 14 + ny * 10);
    const r = len * (1 + wrinkle);
    // Slightly flatten top, elongate front-back
    pos.setXYZ(i, nx * r * 1.05, ny * r * 0.85, nz * r * 1.15);
  }
  geo.computeVertexNormals();
  return geo;
}

function kidneyGeometry(k: number): THREE.BufferGeometry {
  // Bean shape using a torus section
  const geo = new THREE.TorusGeometry(k * 0.8, k * 0.5, 12, 16, Math.PI * 1.3);
  geo.rotateX(Math.PI / 2);
  geo.rotateZ(Math.PI * 0.15);
  geo.computeVertexNormals();
  return geo;
}

function liverGeometry(k: number): THREE.BufferGeometry {
  // Wide, flat, wedge-shaped organ
  const geo = new THREE.SphereGeometry(1, 14, 10);
  const pos = geo.attributes.position as THREE.BufferAttribute;
  for (let i = 0; i < pos.count; i++) {
    let x = pos.getX(i), y = pos.getY(i), z = pos.getZ(i);
    // Flatten vertically, widen horizontally
    // Right lobe larger than left
    const xBias = x > 0 ? 1.3 : 0.8;
    pos.setXYZ(i, x * k * 2.0 * xBias, y * k * 0.6, z * k * 1.4);
  }
  geo.computeVertexNormals();
  return geo;
}

function stomachGeometry(k: number): THREE.BufferGeometry {
  // J-shaped curved tube with variable radius
  const pts: THREE.Vector3[] = [];
  for (let i = 0; i <= 12; i++) {
    const t = i / 12;
    const angle = t * Math.PI * 0.8;
    pts.push(new THREE.Vector3(
      Math.sin(angle) * k * 1.5,
      -t * k * 2.5,
      Math.cos(angle) * k * 0.3,
    ));
  }
  return variableRadiusTube(pts, 16, (t) => {
    // Wide at fundus (top), narrow at pylorus (bottom)
    const fundus = Math.exp(-((t * 3) ** 2)) * 0.4;
    const body = Math.sin(t * Math.PI) * 0.6;
    return k * (0.3 + fundus + body);
  }, 10);
}

function intestineGeometry(k: number, isLarge: boolean): THREE.BufferGeometry {
  // Coiled tube
  const r = isLarge ? k * 0.5 : k * 0.2;
  const coilR = isLarge ? k * 2.0 : k * 1.5;
  const turns = isLarge ? 1.5 : 4;
  const pts: THREE.Vector3[] = [];
  const nPts = Math.ceil(turns * 12);
  for (let i = 0; i <= nPts; i++) {
    const t = i / nPts;
    const angle = t * turns * Math.PI * 2;
    pts.push(new THREE.Vector3(
      Math.cos(angle) * coilR * (0.5 + t * 0.5),
      -t * k * 3,
      Math.sin(angle) * coilR * (0.5 + t * 0.5),
    ));
  }
  return variableRadiusTube(pts, Math.max(12, nPts * 2), () => r, 8);
}

function bladderGeometry(k: number): THREE.BufferGeometry {
  // Pear-shaped: wider at top, narrow at base
  const pts: THREE.Vector2[] = [];
  for (let i = 0; i <= 16; i++) {
    const t = i / 16;
    const r = Math.sin(t * Math.PI) * (1 - t * 0.3);
    pts.push(new THREE.Vector2(Math.max(0.01, r * k * 1.0), (t - 0.5) * k * 1.6));
  }
  return new THREE.LatheGeometry(pts, 12);
}

function defaultOrganGeometry(vol: number): THREE.BufferGeometry {
  // Organic ellipsoid with slight perturbation
  const k = Math.cbrt(vol / ((4 / 3) * Math.PI * 1.0 * 1.5 * 0.8));
  const a = k * 1.0;
  const b = k * 1.5;
  const c = k * 0.8;

  const geo = new THREE.SphereGeometry(1, 14, 10);
  const pos = geo.attributes.position as THREE.BufferAttribute;
  for (let i = 0; i < pos.count; i++) {
    const x = pos.getX(i), y = pos.getY(i), z = pos.getZ(i);
    const len = Math.sqrt(x * x + y * y + z * z) || 1;
    const nx = x / len, ny = y / len, nz = z / len;
    // Subtle organic noise
    const noise = 1.0 + 0.05 * Math.sin(nx * 10 + ny * 8) * Math.cos(nz * 12);
    pos.setXYZ(i, nx * a * noise, ny * b * noise, nz * c * noise);
  }
  geo.computeVertexNormals();
  return geo;
}

// ═══════════════════════════════════════════════════════════════════════
// 4b. POSE SYSTEM — Forward Kinematics for pose selection
// ═══════════════════════════════════════════════════════════════════════

interface PoseJointRotation {
  /** Regex matched against bone.name (case-insensitive) */
  boneNamePattern: RegExp;
  /** Euler rotation [x, y, z] in radians applied at this bone's proximal joint */
  euler: [number, number, number];
}

export interface PoseDefinition {
  id: string;
  label: string;
  rotations: PoseJointRotation[];
}

/**
 * Available poses. Rotations are defined per-bone and propagate down
 * the kinematic chain via forward kinematics.
 *
 * Coordinate convention (Y-up):
 *   Z rotation: arms lateral (+ = right arm down, − = left arm down)
 *   X rotation: legs sagittal (− = hip flexion/forward, + = hip extension/back)
 */
export const AVAILABLE_POSES: PoseDefinition[] = [
  {
    id: "rest",
    label: "T-Pose",
    rotations: [],
  },
  {
    id: "a-pose",
    label: "A-Pose",
    rotations: [
      { boneNamePattern: /^humerus\s*\(r\)/i, euler: [0, 0, 0.75] },
      { boneNamePattern: /^humerus\s*\(l\)/i, euler: [0, 0, -0.75] },
    ],
  },
  {
    id: "anatomical",
    label: "Anatomical",
    rotations: [
      { boneNamePattern: /^humerus\s*\(r\)/i, euler: [0, 0, 1.4] },
      { boneNamePattern: /^humerus\s*\(l\)/i, euler: [0, 0, -1.4] },
    ],
  },
  {
    id: "relaxed",
    label: "Relaxed",
    rotations: [
      { boneNamePattern: /^humerus\s*\(r\)/i, euler: [0.15, 0, 1.35] },
      { boneNamePattern: /^humerus\s*\(l\)/i, euler: [0.15, 0, -1.35] },
      { boneNamePattern: /^radius\s*\(r\)/i, euler: [0.3, 0, 0] },
      { boneNamePattern: /^ulna\s*\(r\)/i, euler: [0.3, 0, 0] },
      { boneNamePattern: /^radius\s*\(l\)/i, euler: [0.3, 0, 0] },
      { boneNamePattern: /^ulna\s*\(l\)/i, euler: [0.3, 0, 0] },
    ],
  },
  {
    id: "walking",
    label: "Walking",
    rotations: [
      // Arms swing (opposite to legs)
      { boneNamePattern: /^humerus\s*\(r\)/i, euler: [0.3, 0, 1.3] },
      { boneNamePattern: /^humerus\s*\(l\)/i, euler: [-0.3, 0, -1.3] },
      { boneNamePattern: /^radius\s*\(r\)/i, euler: [0.35, 0, 0] },
      { boneNamePattern: /^ulna\s*\(r\)/i, euler: [0.35, 0, 0] },
      // Right leg forward, knee bent
      { boneNamePattern: /^femur\s*\(r\)/i, euler: [-0.4, 0, 0] },
      { boneNamePattern: /^tibia\s*\(r\)/i, euler: [0.5, 0, 0] },
      { boneNamePattern: /^fibula\s*\(r\)/i, euler: [0.5, 0, 0] },
      // Left leg back
      { boneNamePattern: /^femur\s*\(l\)/i, euler: [0.2, 0, 0] },
    ],
  },
  {
    id: "arms-raised",
    label: "Arms Raised",
    rotations: [
      { boneNamePattern: /^humerus\s*\(r\)/i, euler: [0, 0, -1.2] },
      { boneNamePattern: /^humerus\s*\(l\)/i, euler: [0, 0, 1.2] },
    ],
  },
  {
    id: "fighting",
    label: "Fighter",
    rotations: [
      // Guard stance: arms up, fists near face
      { boneNamePattern: /^humerus\s*\(r\)/i, euler: [0.8, 0.3, 0.5] },
      { boneNamePattern: /^humerus\s*\(l\)/i, euler: [0.8, -0.3, -0.5] },
      { boneNamePattern: /^radius\s*\(r\)/i, euler: [1.2, 0, 0] },
      { boneNamePattern: /^ulna\s*\(r\)/i, euler: [1.2, 0, 0] },
      { boneNamePattern: /^radius\s*\(l\)/i, euler: [1.4, 0, 0] },
      { boneNamePattern: /^ulna\s*\(l\)/i, euler: [1.4, 0, 0] },
      // Staggered stance
      { boneNamePattern: /^femur\s*\(r\)/i, euler: [-0.15, 0, 0.08] },
      { boneNamePattern: /^femur\s*\(l\)/i, euler: [-0.1, 0, -0.08] },
      { boneNamePattern: /^tibia\s*\(r\)/i, euler: [0.2, 0, 0] },
      { boneNamePattern: /^tibia\s*\(l\)/i, euler: [0.15, 0, 0] },
      { boneNamePattern: /^fibula\s*\(r\)/i, euler: [0.2, 0, 0] },
      { boneNamePattern: /^fibula\s*\(l\)/i, euler: [0.15, 0, 0] },
    ],
  },
];

/**
 * Applies a pose to body data using forward kinematics.
 * Returns a new HumanBodyData with updated bone and joint positions.
 * Muscles, tendons, and ligaments automatically follow since they
 * reference bone positions at render time.
 */
export function applyPoseToBody(body: HumanBodyData, pose: PoseDefinition): HumanBodyData {
  if (pose.rotations.length === 0) return body;

  const boneById = new Map(body.skeleton.map((b) => [b.id, b]));

  // Build parent→children map
  const childrenOf = new Map<string, string[]>();
  for (const bone of body.skeleton) {
    if (bone.parentBoneId) {
      const list = childrenOf.get(bone.parentBoneId) || [];
      list.push(bone.id);
      childrenOf.set(bone.parentBoneId, list);
    }
  }

  // Map bone IDs to their pose rotation (first matching pattern wins)
  const rotationMap = new Map<string, THREE.Quaternion>();
  for (const bone of body.skeleton) {
    for (const rot of pose.rotations) {
      if (rot.boneNamePattern.test(bone.name)) {
        rotationMap.set(
          bone.id,
          new THREE.Quaternion().setFromEuler(new THREE.Euler(rot.euler[0], rot.euler[1], rot.euler[2])),
        );
        break;
      }
    }
  }

  // FK traversal: compute new world positions
  const newPositions = new Map<string, Vec3>();

  function processNode(boneId: string, parentNewPos: Vec3, parentRestPos: Vec3, parentAccumQ: THREE.Quaternion): void {
    const bone = boneById.get(boneId)!;

    // This bone's local rotation (at its proximal joint)
    const localQ = rotationMap.get(boneId) ?? new THREE.Quaternion();
    const accumQ = parentAccumQ.clone().multiply(localQ);

    let newPos: Vec3;
    if (!bone.parentBoneId) {
      // Root bone: stays in place
      newPos = { ...bone.transform.position };
    } else {
      // Rotate rest-pose offset by accumulated rotation
      const offset = new THREE.Vector3(
        bone.transform.position.x - parentRestPos.x,
        bone.transform.position.y - parentRestPos.y,
        bone.transform.position.z - parentRestPos.z,
      );
      offset.applyQuaternion(accumQ);
      newPos = {
        x: parentNewPos.x + offset.x,
        y: parentNewPos.y + offset.y,
        z: parentNewPos.z + offset.z,
      };
    }

    newPositions.set(boneId, newPos);

    // Recurse to children
    for (const childId of childrenOf.get(boneId) || []) {
      processNode(childId, newPos, bone.transform.position, accumQ);
    }
  }

  // Start FK from root bones
  for (const bone of body.skeleton) {
    if (!bone.parentBoneId) {
      const rootQ = rotationMap.get(bone.id) ?? new THREE.Quaternion();
      newPositions.set(bone.id, { ...bone.transform.position });
      for (const childId of childrenOf.get(bone.id) || []) {
        processNode(childId, bone.transform.position, bone.transform.position, rootQ);
      }
    }
  }

  // Build modified skeleton with posed positions
  const newSkeleton = body.skeleton.map((bone) => {
    const p = newPositions.get(bone.id);
    if (!p) return bone;
    return { ...bone, transform: { ...bone.transform, position: p } };
  });

  // Update joint positions: average of connected bone positions
  const newJoints = body.joints.map((joint) => {
    if (joint.connectedBoneIds.length === 0) return joint;
    let sx = 0, sy = 0, sz = 0, n = 0;
    for (const bId of joint.connectedBoneIds) {
      const p = newPositions.get(bId);
      if (p) { sx += p.x; sy += p.y; sz += p.z; n++; }
    }
    if (n === 0) return joint;
    return { ...joint, transform: { ...joint.transform, position: { x: sx / n, y: sy / n, z: sz / n } } };
  });

  return { ...body, skeleton: newSkeleton, joints: newJoints };
}

// ═══════════════════════════════════════════════════════════════════════
// 5. SCENE LAYER GROUPS — toggleable visibility
// ═══════════════════════════════════════════════════════════════════════

export type LayerName =
  | "skeleton"
  | "joints"
  | "muscles"
  | "tendons"
  | "organs"
  | "arteries"
  | "veins"
  | "nerves"
  | "ligaments"
  | "cartilage";

export const ALL_LAYERS: LayerName[] = [
  "skeleton", "joints", "muscles", "tendons",
  "organs", "arteries", "veins", "nerves",
  "ligaments", "cartilage",
];

export const DEFAULT_VISIBLE: Set<LayerName> = new Set(["skeleton", "joints", "muscles"]);

// ═══════════════════════════════════════════════════════════════════════
// 6. SCENE ASSEMBLY — builds Three.js scene from HumanBody JSON
// ═══════════════════════════════════════════════════════════════════════

export type ThemeMode = "dark" | "light";

interface ThemeConfig {
  sceneBg: number;
  fogColor: number;
  fogDensity: number;
  groundColor: number;
  gridA: number;
  gridB: number;
  hemiSky: number;
  hemiGround: number;
  hemiIntensity: number;
  ambientColor: number;
  ambientIntensity: number;
  keyIntensity: number;
  fillIntensity: number;
  rimIntensity: number;
  exposure: number;
  bloomStrength: number;
}

const THEMES: Record<ThemeMode, ThemeConfig> = {
  dark: {
    sceneBg: 0x0c0c14, fogColor: 0x0c0c14, fogDensity: 0.0008,
    groundColor: 0x111118, gridA: 0x222244, gridB: 0x181828,
    hemiSky: 0xddeeff, hemiGround: 0x886644, hemiIntensity: 1.5,
    ambientColor: 0xffffff, ambientIntensity: 0.8,
    keyIntensity: 2.5, fillIntensity: 1.2, rimIntensity: 0.8,
    exposure: 1.6, bloomStrength: 0.1,
  },
  light: {
    sceneBg: 0xeef2f7, fogColor: 0xeef2f7, fogDensity: 0.0004,
    groundColor: 0xd8dce4, gridA: 0xbbc0cc, gridB: 0xd0d4dc,
    hemiSky: 0xffffff, hemiGround: 0xccbbaa, hemiIntensity: 2.0,
    ambientColor: 0xffffff, ambientIntensity: 1.0,
    keyIntensity: 2.0, fillIntensity: 1.5, rimIntensity: 0.6,
    exposure: 1.8, bloomStrength: 0.03,
  },
};

export interface UITheme {
  bg: string;
  bgOverlay: string;
  border: string;
  text: string;
  textMuted: string;
  textDim: string;
  panelBg: string;
  panelBorder: string;
  btnBg: string;
  btnBorder: string;
  btnText: string;
  btnActiveText: string;
  inactiveText: string;
}

const UI_THEMES: Record<ThemeMode, UITheme> = {
  dark: {
    bg: "#0c0c14", bgOverlay: "rgba(12,12,20,.92)", border: "rgba(100,120,180,.15)",
    text: "#e8e8f0", textMuted: "#556688", textDim: "#334455",
    panelBg: "rgba(12,12,20,.92)", panelBorder: "rgba(100,120,180,.15)",
    btnBg: "rgba(60,80,120,.12)", btnBorder: "rgba(80,100,140,.2)",
    btnText: "#8899bb", btnActiveText: "#c8ccd4", inactiveText: "#556677",
  },
  light: {
    bg: "#eef2f7", bgOverlay: "rgba(255,255,255,.94)", border: "rgba(100,120,160,.2)",
    text: "#1a1e2a", textMuted: "#667889", textDim: "#8899aa",
    panelBg: "rgba(255,255,255,.94)", panelBorder: "rgba(100,120,160,.18)",
    btnBg: "rgba(100,120,160,.08)", btnBorder: "rgba(100,120,160,.2)",
    btnText: "#4a5568", btnActiveText: "#1a1e2a", inactiveText: "#8899aa",
  },
};

export interface SceneHandle {
  scene: THREE.Scene;
  camera: THREE.PerspectiveCamera;
  renderer: THREE.WebGLRenderer;
  composer: EffectComposer;
  controls: OrbitControls;
  layers: Record<LayerName, THREE.Group>;
  boneMap: Map<string, THREE.Mesh>;
  jointMap: Map<string, THREE.Mesh>;
  themeRefs: {
    hemi: THREE.HemisphereLight;
    ambient: THREE.AmbientLight;
    keyLight: THREE.DirectionalLight;
    fillLight: THREE.DirectionalLight;
    rimLight: THREE.DirectionalLight;
    ground: THREE.Mesh;
    grid: THREE.GridHelper;
    bloom: UnrealBloomPass;
  };
  dispose: () => void;
}

export function applyTheme(handle: SceneHandle, mode: ThemeMode): void {
  const t = THEMES[mode];
  const { scene, renderer, themeRefs } = handle;

  scene.background = new THREE.Color(t.sceneBg);
  (scene.fog as THREE.FogExp2).color.set(t.fogColor);
  (scene.fog as THREE.FogExp2).density = t.fogDensity;

  renderer.toneMappingExposure = t.exposure;

  themeRefs.hemi.color.set(t.hemiSky);
  themeRefs.hemi.groundColor.set(t.hemiGround);
  themeRefs.hemi.intensity = t.hemiIntensity;

  themeRefs.ambient.color.set(t.ambientColor);
  themeRefs.ambient.intensity = t.ambientIntensity;

  themeRefs.keyLight.intensity = t.keyIntensity;
  themeRefs.fillLight.intensity = t.fillIntensity;
  themeRefs.rimLight.intensity = t.rimIntensity;

  ((themeRefs.ground as THREE.Mesh).material as THREE.MeshStandardMaterial).color.set(t.groundColor);

  themeRefs.grid.geometry.dispose();
  (themeRefs.grid.material as THREE.Material).dispose();
  scene.remove(themeRefs.grid);
  const newGrid = new THREE.GridHelper(200, 40, t.gridA, t.gridB);
  newGrid.position.y = 0.05;
  scene.add(newGrid);
  themeRefs.grid = newGrid;

  themeRefs.bloom.strength = t.bloomStrength;
}

function toV3(v: Vec3): THREE.Vector3 {
  return new THREE.Vector3(v.x, v.y, v.z);
}

export function buildScene(container: HTMLElement, body: HumanBodyData): SceneHandle {
  const W = container.clientWidth;
  const H = container.clientHeight;

  // ── Renderer ──
  const renderer = new THREE.WebGLRenderer({
    antialias: true,
    powerPreference: "high-performance",
  });
  renderer.setSize(W, H);
  renderer.setPixelRatio(Math.min(devicePixelRatio, 2));
  renderer.shadowMap.enabled = true;
  renderer.shadowMap.type = THREE.PCFSoftShadowMap;
  renderer.toneMapping = THREE.ACESFilmicToneMapping;
  renderer.toneMappingExposure = 1.6;
  renderer.outputColorSpace = THREE.SRGBColorSpace;
  container.appendChild(renderer.domElement);

  // ── Scene ──
  const scene = new THREE.Scene();
  scene.background = new THREE.Color(0x0c0c14);
  scene.fog = new THREE.FogExp2(0x0c0c14, 0.0008);

  // Environment map disabled — direct lighting is sufficient for bone/muscle PBR.
  // PMREM generation can corrupt materials on some WebGL implementations.

  // ── Camera — framing full body (Y range 0–180 cm) ──
  const camera = new THREE.PerspectiveCamera(40, W / H, 0.5, 500);
  camera.position.set(60, 100, 120);
  camera.lookAt(0, 90, 0);

  // ── Controls ──
  const controls = new OrbitControls(camera, renderer.domElement);
  controls.target.set(0, 90, 0);
  controls.enableDamping = true;
  controls.dampingFactor = 0.08;
  controls.minDistance = 15;
  controls.maxDistance = 350;
  controls.maxPolarAngle = Math.PI * 0.95;
  controls.update();

  // ── Lighting — bright clinical/studio setup ──
  // Higher intensities to counteract ACES filmic tone mapping compression.
  // Target: bones should appear as warm ivory, not dark gray.
  const hemi = new THREE.HemisphereLight(0xddeeff, 0x886644, 1.5);
  scene.add(hemi);

  const ambient = new THREE.AmbientLight(0xffffff, 0.8);
  scene.add(ambient);

  const keyLight = new THREE.DirectionalLight(0xfff5e6, 2.5);
  keyLight.position.set(60, 150, 80);
  keyLight.castShadow = true;
  keyLight.shadow.mapSize.set(2048, 2048);
  keyLight.shadow.camera.near = 1;
  keyLight.shadow.camera.far = 400;
  keyLight.shadow.camera.left = -80;
  keyLight.shadow.camera.right = 80;
  keyLight.shadow.camera.top = 200;
  keyLight.shadow.camera.bottom = -20;
  keyLight.shadow.bias = -0.001;
  scene.add(keyLight);

  const fillLight = new THREE.DirectionalLight(0xaaccff, 1.2);
  fillLight.position.set(-50, 100, -40);
  scene.add(fillLight);

  const rimLight = new THREE.DirectionalLight(0xffcc88, 0.8);
  rimLight.position.set(0, 50, -100);
  scene.add(rimLight);

  const topLight = new THREE.PointLight(0xffffff, 1.0, 400);
  topLight.position.set(0, 200, 0);
  scene.add(topLight);

  // ── Ground plane ──
  const ground = new THREE.Mesh(
    new THREE.PlaneGeometry(600, 600),
    new THREE.MeshStandardMaterial({ color: 0x111118, roughness: 0.9, metalness: 0.1 }),
  );
  ground.rotation.x = -Math.PI / 2;
  ground.receiveShadow = true;
  scene.add(ground);

  let grid = new THREE.GridHelper(200, 40, 0x222244, 0x181828);
  grid.position.y = 0.05;
  scene.add(grid);

  // ── Post-processing ──
  const composer = new EffectComposer(renderer);
  composer.addPass(new RenderPass(scene, camera));

  const bloomPass = new UnrealBloomPass(
    new THREE.Vector2(W, H), 0.15, 0.4, 0.9,
  );
  composer.addPass(bloomPass);

  // SMAA omitted — rely on renderer MSAA (antialias: true in WebGLRenderer)

  // ── Layer groups ──
  const layers: Record<LayerName, THREE.Group> = {} as any;
  for (const ln of ALL_LAYERS) {
    const g = new THREE.Group();
    g.name = ln;
    g.visible = DEFAULT_VISIBLE.has(ln);
    scene.add(g);
    layers[ln] = g;
  }

  // ── Index maps ──
  const boneMap = new Map<string, THREE.Mesh>();
  const boneDataById = new Map<string, BoneData>();
  const tendonById = new Map<string, TendonData>();
  const jointMap = new Map<string, THREE.Mesh>();
  const jointDataById = new Map<string, JointData>();

  for (const b of body.skeleton) boneDataById.set(b.id, b);
  for (const t of body.tendons) tendonById.set(t.id, t);
  for (const j of body.joints) jointDataById.set(j.id, j);

  // ════════════════════════════════════════════════════════════════════
  // SKELETON — 206 bones
  //
  // Placement rules:
  //   - Each bone's transform.position = its proximal joint (origin).
  //   - LONG bones span from their OWN position toward their children's
  //     positions. The mesh is placed at the midpoint, Y axis aligned
  //     along self→children direction. Span length = bone.length.
  //   - ALL OTHER bones (flat, irregular, short, sesamoid): placed at
  //     their own anatomical position with rotation from transform.
  // ════════════════════════════════════════════════════════════════════

  const geometryByBoneId = new Map<string, BoneGeometryData>();
  if (body.boneGeometries) {
    for (const bg of body.boneGeometries) {
      geometryByBoneId.set(bg.boneId, bg);
    }
  }
  const globalOpacity = body.rendering?.globalOpacity ?? 1;
  const boneOverrideById = new Map((body.rendering?.boneOverrides ?? []).map((o) => [o.entityId, o]));
  const muscleOverrideById = new Map((body.rendering?.muscleOverrides ?? []).map((o) => [o.entityId, o]));
  const organOverrideById = new Map((body.rendering?.organOverrides ?? []).map((o) => [o.entityId, o]));
  const vesselOverrideById = new Map((body.rendering?.vesselOverrides ?? []).map((o) => [o.entityId, o]));

  // Build parent→children map for long bone span computation
  const childrenOfBone = new Map<string, BoneData[]>();
  for (const b of body.skeleton) {
    if (b.parentBoneId) {
      const list = childrenOfBone.get(b.parentBoneId) || [];
      list.push(b);
      childrenOfBone.set(b.parentBoneId, list);
    }
  }

  // Compute the distal end of a long bone: average position of its children,
  // or fall back to extending along parent→self direction by bone.length.
  function longBoneDistalEnd(bone: BoneData): THREE.Vector3 {
    const bonePos = toV3(bone.transform.position);
    const children = childrenOfBone.get(bone.id);
    if (children && children.length > 0) {
      const avg = new THREE.Vector3();
      for (const child of children) {
        avg.add(toV3(child.transform.position));
      }
      avg.divideScalar(children.length);
      return avg;
    }
    // No children: extend along parent→self direction by bone.length
    const parent = bone.parentBoneId ? boneDataById.get(bone.parentBoneId) : undefined;
    if (parent) {
      const dir = bonePos.clone().sub(toV3(parent.transform.position));
      if (dir.lengthSq() > 0.01) {
        dir.normalize();
        return bonePos.clone().add(dir.multiplyScalar(bone.length));
      }
    }
    // Last resort: extend downward
    return bonePos.clone().add(new THREE.Vector3(0, -bone.length, 0));
  }

  // Helper: build inline geometry from indexed_mesh or parametric_csg
  const buildInlineGeometry = (
    geometryEntry: BoneGeometryData | undefined,
    bone: BoneData,
    spanLen?: number,
  ): THREE.BufferGeometry => {
    if (geometryEntry?.geometryType === "indexed_mesh" && "lods" in geometryEntry) {
      return indexedMeshToGeometry(geometryEntry as IndexedMeshGeometryData);
    }
    if (geometryEntry?.geometryType === "parametric_csg" && "csgTree" in geometryEntry) {
      return csgTreeToGeometry((geometryEntry as { csgTree: CSGNode }).csgTree);
    }
    if (spanLen !== undefined) {
      return longBoneGeometry(spanLen, bone.width, bone.depth);
    }
    return boneGeometry(bone);
  };

  for (const bone of body.skeleton) {
    const renderOverride = boneOverrideById.get(bone.id);
    if (renderOverride?.visible === false) continue;
    const mat = applyRenderOverride(boneMaterial(bone.region), renderOverride, globalOpacity);
    const geometryEntry = geometryByBoneId.get(bone.id);
    const bonePos = toV3(bone.transform.position);

    const isLong = bone.classification === "long";
    let meshPos: THREE.Vector3;
    let meshQuat: THREE.Quaternion | undefined;
    let meshEuler: THREE.Euler | undefined;
    let spanLen: number | undefined;

    if (isLong) {
      // Long bones span from own position (proximal) to distal end (children avg)
      const distalEnd = longBoneDistalEnd(bone);
      const dir = distalEnd.clone().sub(bonePos);
      const dist = dir.length();
      spanLen = Math.max(1, dist);
      meshPos = bonePos.clone().add(distalEnd).multiplyScalar(0.5);
      if (dist > 0.1) {
        const d = dir.normalize();
        const up = new THREE.Vector3(0, 1, 0);
        if (Math.abs(d.dot(up)) < 0.9999) {
          meshQuat = new THREE.Quaternion().setFromUnitVectors(up, d);
        }
      }
    } else {
      meshPos = bonePos;
      const rot = bone.transform.rotation;
      if (rot.x !== 0 || rot.y !== 0 || rot.z !== 0) {
        const D2R = Math.PI / 180;
        meshEuler = new THREE.Euler(rot.x * D2R, rot.y * D2R, rot.z * D2R, "XYZ");
      }
    }

    // Build mesh — use inline geometry (indexed_mesh, parametric_csg, or procedural).
    // External GLB assets are skipped: the available GLBs are procedural placeholders
    // with inverted normals and coordinate-space mismatches. The inline procedural
    // generators produce correct geometry with proper normals and placement.
    const inlineEntry = geometryEntry?.geometryType === "external_asset" ? undefined : geometryEntry;
    const geo = buildInlineGeometry(inlineEntry, bone, spanLen);
    const mesh = new THREE.Mesh(geo, mat);
    mesh.position.copy(meshPos);
    if (meshQuat) mesh.quaternion.copy(meshQuat);
    if (meshEuler) mesh.rotation.copy(meshEuler);

    mesh.castShadow = true;
    mesh.receiveShadow = true;
    mesh.userData = { type: "bone", id: bone.id, name: bone.name, region: bone.region };
    layers.skeleton.add(mesh);
    boneMap.set(bone.id, mesh);
  }

  // ════════════════════════════════════════════════════════════════════
  // JOINTS — 130
  // ════════════════════════════════════════════════════════════════════

  for (const joint of body.joints) {
    const dof = joint.degreesOfFreedom;
    const r = dof >= 3 ? 1.2 : dof === 2 ? 0.9 : 0.65;
    const geo = new THREE.SphereGeometry(r, 12, 8);
    const mesh = new THREE.Mesh(geo, jointMaterial());
    mesh.position.set(
      joint.transform.position.x,
      joint.transform.position.y,
      joint.transform.position.z,
    );
    mesh.userData = { type: "joint", id: joint.id, name: joint.name, dof };
    layers.joints.add(mesh);
    jointMap.set(joint.id, mesh);
  }

  // ════════════════════════════════════════════════════════════════════
  // MUSCLES — spindle-shaped bellies with variable radius
  // ════════════════════════════════════════════════════════════════════

  const tMat = tendonMaterial();
  for (const muscle of body.muscles) {
    const renderOverride = muscleOverrideById.get(muscle.id);
    if (renderOverride?.visible === false) continue;
    const originTendon = tendonById.get(muscle.origin.tendonId);
    const insertionTendon = tendonById.get(muscle.insertion.tendonId);
    if (!originTendon || !insertionTendon) continue;

    const originBone = boneDataById.get(originTendon.attachedBoneId);
    const insertionBone = boneDataById.get(insertionTendon.attachedBoneId);
    if (!originBone || !insertionBone) continue;

    // World positions = bone position + tendon local offset
    const oPos = new THREE.Vector3(
      originBone.transform.position.x + originTendon.localPosition.x,
      originBone.transform.position.y + originTendon.localPosition.y,
      originBone.transform.position.z + originTendon.localPosition.z,
    );
    const iPos = new THREE.Vector3(
      insertionBone.transform.position.x + insertionTendon.localPosition.x,
      insertionBone.transform.position.y + insertionTendon.localPosition.y,
      insertionBone.transform.position.z + insertionTendon.localPosition.z,
    );

    // Muscle belly: curved spindle tube between origin and insertion
    // Multiple control points for anatomical curvature
    const mid = oPos.clone().add(iPos).multiplyScalar(0.5);
    const span = oPos.distanceTo(iPos);
    const bulge = span * 0.15;

    // Compute a bulge direction perpendicular to the muscle span.
    // fiberDirection points along the fiber axis (roughly parallel to span),
    // so using it directly as the bulge offset creates loops/twists.
    // Instead: cross(spanDir, fiberDir) gives a perpendicular direction,
    // and we bias it outward from the body centerline (x=0, z≈10).
    const spanDir = iPos.clone().sub(oPos);
    if (spanDir.lengthSq() > 0) spanDir.normalize();
    const fiberDir = toV3(muscle.fiberDirection).normalize();
    const bulgeDir = new THREE.Vector3().crossVectors(spanDir, fiberDir);
    if (bulgeDir.lengthSq() < 1e-6) {
      // fiberDir is parallel to span — pick an arbitrary perpendicular
      const ref = Math.abs(spanDir.y) < 0.9
        ? new THREE.Vector3(0, 1, 0)
        : new THREE.Vector3(1, 0, 0);
      bulgeDir.crossVectors(spanDir, ref);
    }
    bulgeDir.normalize();

    // Ensure bulge pushes outward from body center (x=0, z≈10)
    const outward = new THREE.Vector3(mid.x, 0, mid.z - 10);
    if (outward.lengthSq() > 0.01 && bulgeDir.dot(outward) < 0) {
      bulgeDir.negate();
    }

    // 5 control points for smoother curvature
    const q1 = oPos.clone().lerp(mid, 0.25).add(bulgeDir.clone().multiplyScalar(bulge * 0.6));
    const q2 = oPos.clone().lerp(mid, 0.5).add(bulgeDir.clone().multiplyScalar(bulge));
    const q3 = mid.clone().lerp(iPos, 0.5).add(bulgeDir.clone().multiplyScalar(bulge * 0.8));
    const q4 = mid.clone().lerp(iPos, 0.75).add(bulgeDir.clone().multiplyScalar(bulge * 0.4));

    // Belly radius from volume: V ≈ π r² L → r = sqrt(V / (π L))
    const bellyR = Math.max(0.2, Math.min(3.0, Math.sqrt(muscle.volume / (Math.PI * Math.max(1, muscle.restingLength)))));
    const tR = bellyR * 0.2; // Tendon is much thinner than belly

    // Spindle-shaped tube: thin at tendons, thick at belly center
    const muscleGeo = variableRadiusTube(
      [oPos, q1, q2, q3, q4, iPos],
      24, // more segments for smooth spindle
      (t) => {
        // Smooth spindle profile: sin^0.7 creates a natural muscle belly shape
        const s = Math.pow(Math.sin(t * Math.PI), 0.7);
        return tR + (bellyR - tR) * s;
      },
      8,
    );

    const muscleMesh = new THREE.Mesh(
      muscleGeo,
      applyRenderOverride(muscleMaterial(muscle.region), renderOverride, globalOpacity),
    );
    muscleMesh.castShadow = true;
    muscleMesh.userData = { type: "muscle", id: muscle.id, name: muscle.name, region: muscle.region };
    layers.muscles.add(muscleMesh);

    // Tendons: tapered tubes at origin and insertion ends
    const tendonR = Math.max(0.08, bellyR * 0.25);
    if (originTendon.length > 0.5) {
      const tEnd = oPos.clone().lerp(new THREE.Vector3(
        originBone.transform.position.x,
        originBone.transform.position.y,
        originBone.transform.position.z,
      ), 0.8);
      const tGeo = tubeFromPath([tEnd, oPos], tendonR, 4);
      const tMesh = new THREE.Mesh(tGeo, tMat);
      tMesh.userData = { type: "tendon", name: originTendon.name };
      layers.tendons.add(tMesh);
    }
    if (insertionTendon.length > 0.5) {
      const tEnd = iPos.clone().lerp(new THREE.Vector3(
        insertionBone.transform.position.x,
        insertionBone.transform.position.y,
        insertionBone.transform.position.z,
      ), 0.8);
      const tGeo = tubeFromPath([iPos, tEnd], tendonR, 4);
      const tMesh = new THREE.Mesh(tGeo, tMat);
      tMesh.userData = { type: "tendon", name: insertionTendon.name };
      layers.tendons.add(tMesh);
    }
  }

  // ════════════════════════════════════════════════════════════════════
  // VASCULAR SYSTEM — 94 vessels (arteries + veins)
  // ════════════════════════════════════════════════════════════════════

  for (const vessel of body.vascularSystem) {
    const renderOverride = vesselOverrideById.get(vessel.id);
    if (renderOverride?.visible === false) continue;
    if (vessel.path.length < 2) continue;
    const pts = vessel.path.map(toV3);
    const r = Math.max(0.08, vessel.averageLumenRadius * 0.6);
    const geo = tubeFromPath(pts, r);
    const mat = applyRenderOverride(
      vessel.vesselType === "artery" ? arteryMaterial() : veinMaterial(),
      renderOverride,
      globalOpacity,
    );
    const mesh = new THREE.Mesh(geo, mat);
    mesh.userData = { type: "vessel", id: vessel.id, name: vessel.name, vesselType: vessel.vesselType };
    const layer = vessel.vesselType === "artery" ? layers.arteries : layers.veins;
    layer.add(mesh);
  }

  // ════════════════════════════════════════════════════════════════════
  // NERVES — 51
  // ════════════════════════════════════════════════════════════════════

  for (const nerve of body.nerves) {
    if (nerve.path.length < 2) continue;
    const pts = nerve.path.map(toV3);
    const r = nerve.type === "motor" ? 0.12 : nerve.type === "sensory" ? 0.1 : 0.15;
    const geo = tubeFromPath(pts, r);
    const mesh = new THREE.Mesh(geo, nerveMaterial());
    mesh.userData = { type: "nerve", id: nerve.id, name: nerve.name };
    layers.nerves.add(mesh);
  }

  // ════════════════════════════════════════════════════════════════════
  // ORGANS — 38 (with organ-specific geometries)
  // ════════════════════════════════════════════════════════════════════

  for (const organ of body.organs) {
    const renderOverride = organOverrideById.get(organ.id);
    if (renderOverride?.visible === false) continue;
    const geo = organGeometry(organ);
    const mesh = new THREE.Mesh(
      geo,
      applyRenderOverride(organMaterial(organ.system), renderOverride, globalOpacity),
    );
    mesh.position.set(
      organ.transform.position.x,
      organ.transform.position.y,
      organ.transform.position.z,
    );
    mesh.castShadow = true;
    mesh.receiveShadow = true;
    mesh.userData = { type: "organ", id: organ.id, name: organ.name, system: organ.system };
    layers.organs.add(mesh);
  }

  // ════════════════════════════════════════════════════════════════════
  // LIGAMENTS — 43
  // ════════════════════════════════════════════════════════════════════

  const ligMat = ligamentMaterial();
  for (const lig of body.ligaments) {
    const oBone = boneDataById.get(lig.originBoneId);
    const iBone = boneDataById.get(lig.insertionBoneId);
    if (!oBone || !iBone) continue;

    const oPos = new THREE.Vector3(
      oBone.transform.position.x + lig.originPosition.x,
      oBone.transform.position.y + lig.originPosition.y,
      oBone.transform.position.z + lig.originPosition.z,
    );
    const iPos = new THREE.Vector3(
      iBone.transform.position.x + lig.insertionPosition.x,
      iBone.transform.position.y + lig.insertionPosition.y,
      iBone.transform.position.z + lig.insertionPosition.z,
    );

    const r = Math.max(0.1, Math.min(0.6, lig.restingLength * 0.04));
    const geo = tubeFromPath([oPos, iPos], r, 4);
    const mesh = new THREE.Mesh(geo, ligMat);
    mesh.userData = { type: "ligament", id: lig.id, name: lig.name };
    layers.ligaments.add(mesh);
  }

  // ════════════════════════════════════════════════════════════════════
  // CARTILAGE — 36
  // ════════════════════════════════════════════════════════════════════

  for (const cart of body.cartilage) {
    const jointData = jointDataById.get(cart.jointId);
    if (!jointData) continue;

    const r = Math.sqrt(cart.surfaceArea / Math.PI);
    const geo = new THREE.CylinderGeometry(r, r, cart.thickness * 0.5, 12, 1);
    const mesh = new THREE.Mesh(geo, cartilageMaterial(cart.type));
    mesh.position.set(
      jointData.transform.position.x,
      jointData.transform.position.y,
      jointData.transform.position.z,
    );
    mesh.userData = { type: "cartilage", id: cart.id, name: cart.name };
    layers.cartilage.add(mesh);
  }

  // ── Dispose helper ──
  function dispose() {
    composer.dispose();
    renderer.dispose();
    controls.dispose();
    _materialCache.forEach((m) => m.dispose());
    _materialCache.clear();
    scene.traverse((obj: THREE.Object3D) => {
      if (obj instanceof THREE.Mesh) {
        obj.geometry.dispose();
        if (Array.isArray(obj.material)) {
          obj.material.forEach((m) => m.dispose());
        } else {
          obj.material.dispose();
        }
      }
    });
    if (container.contains(renderer.domElement)) {
      container.removeChild(renderer.domElement);
    }
  }

  const themeRefs = { hemi, ambient, keyLight, fillLight, rimLight, ground, grid, bloom: bloomPass };

  return { scene, camera, renderer, composer, controls, layers, boneMap, jointMap, themeRefs, dispose };
}

// ═══════════════════════════════════════════════════════════════════════
// 7. HOVER / PICK — raycaster for tooltip
// ═══════════════════════════════════════════════════════════════════════

export interface PickResult {
  name: string;
  type: string;
  extra: Record<string, unknown>;
}

// Reusable raycaster — avoids GC pressure from per-frame allocation
const _raycaster = new THREE.Raycaster();

export function pick(
  handle: SceneHandle,
  ndc: THREE.Vector2,
  visibleLayers: Set<LayerName>,
): PickResult | null {
  _raycaster.setFromCamera(ndc, handle.camera);

  const targets: THREE.Object3D[] = [];
  for (const ln of ALL_LAYERS) {
    if (visibleLayers.has(ln)) targets.push(handle.layers[ln]);
  }

  const hits = _raycaster.intersectObjects(targets, true);
  if (hits.length === 0) return null;

  const hit = hits[0];
  if (!hit) return null;
  const ud = hit.object.userData as Record<string, unknown>;
  if (!ud?.name) return null;
  return { name: ud.name as string, type: ud.type as string, extra: ud };
}

// ═══════════════════════════════════════════════════════════════════════
// 8. REACT COMPONENT — <AnatomyViewer />
// ═══════════════════════════════════════════════════════════════════════

export interface AnatomyViewerProps {
  body: HumanBodyData;
}

const LAYER_ICONS: Record<LayerName, string> = {
  skeleton: "\u{1F9B4}",
  joints: "\u{1F535}",
  muscles: "\u{1F4AA}",
  tendons: "\u{1FAA2}",
  organs: "\u{1FAC0}",
  arteries: "\u{1F534}",
  veins: "\u{1F535}",
  nerves: "\u26A1",
  ligaments: "\u{1FA79}",
  cartilage: "\u{1FAE7}",
};

const LAYER_COLORS: Record<LayerName, string> = {
  skeleton: "#e8dbb8",
  joints: "#66aadd",
  muscles: "#bb3333",
  tendons: "#f0f0e8",
  organs: "#ddaa77",
  arteries: "#dd3322",
  veins: "#3344aa",
  nerves: "#eedd44",
  ligaments: "#d0d8c0",
  cartilage: "#c8dde8",
};

export default function AnatomyViewer({ body }: AnatomyViewerProps) {
  const mountRef = useRef<HTMLDivElement>(null);
  const handleRef = useRef<SceneHandle | null>(null);
  const [visibleLayers, setVisibleLayers] = useState<Set<LayerName>>(new Set(DEFAULT_VISIBLE));
  const [hovered, setHovered] = useState<PickResult | null>(null);
  const [stats, setStats] = useState({ fps: 0, tris: 0 });
  const [theme, setTheme] = useState<ThemeMode>("dark");
  const [selectedPose, setSelectedPose] = useState<string>("rest");
  const mouseRef = useRef<THREE.Vector2>(new THREE.Vector2(-10, -10));
  const ui = UI_THEMES[theme];

  // Apply pose via forward kinematics — produces modified body data
  const posedBody = useMemo(() => {
    const pose = AVAILABLE_POSES.find((p) => p.id === selectedPose);
    if (!pose || pose.rotations.length === 0) return body;
    return applyPoseToBody(body, pose);
  }, [body, selectedPose]);

  const toggleTheme = useCallback(() => {
    setTheme((prev) => {
      const next: ThemeMode = prev === "dark" ? "light" : "dark";
      if (handleRef.current) applyTheme(handleRef.current, next);
      return next;
    });
  }, []);

  const toggleLayer = useCallback((layer: LayerName) => {
    setVisibleLayers((prev: Set<LayerName>) => {
      const next = new Set(prev);
      if (next.has(layer)) next.delete(layer);
      else next.add(layer);
      return next;
    });
  }, []);

  // Sync layer visibility to Three.js groups
  useEffect(() => {
    const h = handleRef.current;
    if (!h) return;
    for (const ln of ALL_LAYERS) {
      h.layers[ln].visible = visibleLayers.has(ln);
    }
  }, [visibleLayers]);

  // Scene lifecycle
  useEffect(() => {
    const ct = mountRef.current;
    if (!ct) return;

    const handle = buildScene(ct, posedBody);
    handleRef.current = handle;

    let rafId: number;
    let lastTime = 0;
    let frameCount = 0;
    let fpsAccum = 0;

    function loop(ts: number) {
      rafId = requestAnimationFrame(loop);
      const dt = ts - lastTime;
      lastTime = ts;

      handle.controls.update();
      handle.renderer.render(handle.scene, handle.camera);

      // FPS counter
      frameCount++;
      fpsAccum += dt;
      if (fpsAccum >= 1000) {
        const info = handle.renderer.info.render;
        setStats({ fps: Math.round(frameCount * 1000 / fpsAccum), tris: info.triangles });
        frameCount = 0;
        fpsAccum = 0;
      }

      // Hover pick (throttled to every 3rd frame)
      if (frameCount % 3 === 0) {
        const result = pick(handle, mouseRef.current, visibleLayers);
        setHovered(result);
      }
    }

    rafId = requestAnimationFrame(loop);

    const onResize = () => {
      const w = ct.clientWidth;
      const h = ct.clientHeight;
      handle.camera.aspect = w / h;
      handle.camera.updateProjectionMatrix();
      handle.renderer.setSize(w, h);
      handle.composer.setSize(w, h);
    };
    window.addEventListener("resize", onResize);

    const onPointerMove = (e: PointerEvent) => {
      const rect = ct.getBoundingClientRect();
      mouseRef.current.x = ((e.clientX - rect.left) / rect.width) * 2 - 1;
      mouseRef.current.y = -((e.clientY - rect.top) / rect.height) * 2 + 1;
    };
    ct.addEventListener("pointermove", onPointerMove);

    return () => {
      cancelAnimationFrame(rafId);
      window.removeEventListener("resize", onResize);
      ct.removeEventListener("pointermove", onPointerMove);
      handle.dispose();
      handleRef.current = null;
    };
  }, [posedBody]);

  // Presets
  const presetAll = () => setVisibleLayers(new Set(ALL_LAYERS));
  const presetSkeleton = () => setVisibleLayers(new Set(["skeleton", "joints", "cartilage"]));
  const presetMuscular = () => setVisibleLayers(new Set(["muscles", "tendons"]));
  const presetVascular = () => setVisibleLayers(new Set(["arteries", "veins"]));
  const presetNervous = () => setVisibleLayers(new Set(["nerves", "skeleton"]));
  const presetOrgans = () => setVisibleLayers(new Set(["organs", "skeleton"]));

  const layerCounts: Record<LayerName, number> = {
    skeleton: body.skeleton.length,
    joints: body.joints.length,
    muscles: body.muscles.length,
    tendons: body.tendons.length,
    organs: body.organs.length,
    arteries: body.vascularSystem.filter((v) => v.vesselType === "artery").length,
    veins: body.vascularSystem.filter((v) => v.vesselType === "vein").length,
    nerves: body.nerves.length,
    ligaments: body.ligaments.length,
    cartilage: body.cartilage.length,
  };

  return (
    <div style={{ width: "100%", height: "100vh", position: "relative", fontFamily: "'Inter','SF Pro','Segoe UI',sans-serif", background: "#0c0c14", color: "#c8ccd4", overflow: "hidden" }}>
      {/* Three.js canvas mount */}
      <div ref={mountRef} style={{ position: "absolute", inset: 0, zIndex: 1 }} />

      {/* Title / identity */}
      <div style={{ position: "absolute", top: 12, left: 16, zIndex: 10 }}>
        <div style={{ fontSize: 14, fontWeight: 700, letterSpacing: 1, color: "#e8e8f0" }}>
          {body.name ?? "Human Body"} — Schema v{body.schemaVersion}
        </div>
        <div style={{ fontSize: 10, color: "#556688", marginTop: 2 }}>
          {body.proportions.biologicalSex ?? "unknown"} · {body.proportions.totalHeight}cm · {body.proportions.weight}kg
        </div>
      </div>

      {/* Stats */}
      <div style={{ position: "absolute", top: 12, right: 16, zIndex: 10, fontSize: 9, color: "#445566", textAlign: "right" }}>
        <div>{stats.fps} FPS · {(stats.tris / 1000).toFixed(1)}K tris</div>
        <div>{body.skeleton.length} bones · {body.muscles.length} muscles · {body.joints.length} joints</div>
      </div>

      {/* Layer control panel */}
      <div style={{
        position: "absolute", top: 70, left: 16, zIndex: 10,
        background: "rgba(12,12,20,.92)", border: "1px solid rgba(100,120,180,.15)",
        borderRadius: 10, padding: 12, backdropFilter: "blur(12px)", width: 200,
      }}>
        <div style={{ fontSize: 10, fontWeight: 700, color: "#8899bb", letterSpacing: 1, marginBottom: 8, textTransform: "uppercase" }}>
          Layers
        </div>
        {ALL_LAYERS.map((ln) => {
          const active = visibleLayers.has(ln);
          return (
            <button
              key={ln}
              onClick={() => toggleLayer(ln)}
              style={{
                display: "flex", alignItems: "center", gap: 8, width: "100%",
                background: active ? `${LAYER_COLORS[ln]}18` : "transparent",
                border: `1px solid ${active ? LAYER_COLORS[ln] + "55" : "rgba(80,90,120,.15)"}`,
                borderRadius: 6, padding: "4px 8px", marginBottom: 3, cursor: "pointer",
                color: active ? LAYER_COLORS[ln] : "#556677", fontSize: 10,
                fontFamily: "inherit", textAlign: "left", transition: "all .15s",
              }}
            >
              <span style={{ fontSize: 12 }}>{LAYER_ICONS[ln]}</span>
              <span style={{ flex: 1, textTransform: "capitalize" }}>{ln}</span>
              <span style={{ fontSize: 8, opacity: 0.7 }}>{layerCounts[ln]}</span>
            </button>
          );
        })}

        {/* Presets */}
        <div style={{ marginTop: 10, borderTop: "1px solid rgba(80,90,120,.15)", paddingTop: 8 }}>
          <div style={{ fontSize: 9, fontWeight: 700, color: "#667788", letterSpacing: 1, marginBottom: 6, textTransform: "uppercase" }}>
            Presets
          </div>
          <div style={{ display: "flex", flexWrap: "wrap", gap: 4 }}>
            {([
              ["All", presetAll],
              ["Skeletal", presetSkeleton],
              ["Muscular", presetMuscular],
              ["Vascular", presetVascular],
              ["Nervous", presetNervous],
              ["Organs", presetOrgans],
            ] as [string, () => void][]).map(([label, fn]) => (
              <button
                key={label}
                onClick={fn}
                style={{
                  background: "rgba(60,80,120,.12)", border: "1px solid rgba(80,100,140,.2)",
                  color: "#8899bb", borderRadius: 4, padding: "2px 8px",
                  cursor: "pointer", fontSize: 9, fontFamily: "inherit",
                }}
              >
                {label}
              </button>
            ))}
          </div>
        </div>

        {/* Pose selector */}
        <div style={{ marginTop: 10, borderTop: "1px solid rgba(80,90,120,.15)", paddingTop: 8 }}>
          <div style={{ fontSize: 9, fontWeight: 700, color: "#667788", letterSpacing: 1, marginBottom: 6, textTransform: "uppercase" }}>
            Pose
          </div>
          <div style={{ display: "flex", flexWrap: "wrap", gap: 4 }}>
            {AVAILABLE_POSES.map((pose) => {
              const active = selectedPose === pose.id;
              return (
                <button
                  key={pose.id}
                  onClick={() => setSelectedPose(pose.id)}
                  style={{
                    background: active ? "rgba(80,140,220,.2)" : "rgba(60,80,120,.12)",
                    border: `1px solid ${active ? "rgba(80,140,220,.5)" : "rgba(80,100,140,.2)"}`,
                    color: active ? "#aaccff" : "#8899bb",
                    borderRadius: 4, padding: "2px 8px",
                    cursor: "pointer", fontSize: 9, fontFamily: "inherit",
                    fontWeight: active ? 600 : 400,
                  }}
                >
                  {pose.label}
                </button>
              );
            })}
          </div>
        </div>
      </div>

      {/* Hover tooltip */}
      {hovered && (
        <div style={{
          position: "absolute", bottom: 16, left: "50%", transform: "translateX(-50%)", zIndex: 10,
          background: "rgba(12,12,20,.94)", border: "1px solid rgba(100,120,180,.2)",
          borderRadius: 8, padding: "8px 16px", backdropFilter: "blur(10px)",
          textAlign: "center", pointerEvents: "none",
        }}>
          <div style={{ fontSize: 12, fontWeight: 600, color: "#e8e8f0" }}>{hovered.name}</div>
          <div style={{ fontSize: 9, color: "#667799", marginTop: 2, textTransform: "uppercase", letterSpacing: 1 }}>
            {hovered.type}
            {hovered.extra?.region ? ` · ${hovered.extra.region}` : ""}
            {hovered.extra?.system ? ` · ${hovered.extra.system}` : ""}
            {hovered.extra?.dof ? ` · ${hovered.extra.dof} DOF` : ""}
          </div>
        </div>
      )}

      {/* Theme toggle */}
      <button
        onClick={toggleTheme}
        style={{
          position: "absolute", top: 12, right: 200, zIndex: 10,
          background: ui.btnBg, border: `1px solid ${ui.btnBorder}`,
          color: ui.btnText, borderRadius: 6, padding: "4px 10px",
          cursor: "pointer", fontSize: 10, fontFamily: "inherit",
        }}
      >
        {theme === "dark" ? "Light" : "Dark"} Mode
      </button>

      {/* Controls hint */}
      <div style={{ position: "absolute", bottom: 16, right: 16, zIndex: 10, fontSize: 9, color: ui.textDim, textAlign: "right" }}>
        <div>LMB drag — orbit</div>
        <div>RMB drag — pan</div>
        <div>Scroll — zoom</div>
        <div>Hover — inspect</div>
      </div>
    </div>
  );
}
