/**
 * High-fidelity anatomical renderer for HumanBody schema v3.0.0.
 *
 * Renders all 206 bones, 616 muscles, 1230 tendons, 94 vessels, 51 nerves,
 * 38 organs, 43 ligaments, and 36 cartilage structures with PBR materials,
 * anatomical coloring, and interactive layer toggling.
 *
 * Coordinate system: positions in cm, Y-up. Body range ≈ X[-30,30] Y[0,180] Z[-5,21].
 * All geometry is generated from the schema data — no hardcoded meshes.
 *
 * Dependencies: three, three/addons (OrbitControls, EffectComposer, passes)
 *
 * Generated by: Claude Opus 4.6 (1M context)
 */

import { useEffect, useRef, useState, useCallback } from "react";
import * as THREE from "three";
import { OrbitControls } from "three/addons/controls/OrbitControls.js";
import { EffectComposer } from "three/addons/postprocessing/EffectComposer.js";
import { RenderPass } from "three/addons/postprocessing/RenderPass.js";
import { UnrealBloomPass } from "three/addons/postprocessing/UnrealBloomPass.js";
import { SMAAPass } from "three/addons/postprocessing/SMAAPass.js";

// ═══════════════════════════════════════════════════════════════════════
// 1. TYPE INTERFACES — mirrors HumanBody JSON schema
// ═══════════════════════════════════════════════════════════════════════

export interface Vec3 {
  x: number;
  y: number;
  z: number;
}

export interface Transform {
  position: Vec3;
  rotation: Vec3;
  scale: Vec3;
}

export interface BoneData {
  id: string;
  name: string;
  classification: "long" | "short" | "flat" | "irregular" | "sesamoid";
  region: string;
  transform: Transform;
  length: number;
  width: number;
  depth: number;
  mass: number;
  parentBoneId: string | null;
}

export interface TendonData {
  id: string;
  name: string;
  attachedBoneId: string;
  localPosition: Vec3;
  length: number;
  crossSectionalArea?: number;
}

export interface MuscleData {
  id: string;
  name: string;
  region: string;
  type: string;
  origin: { tendonId: string; description: string };
  insertion: { tendonId: string; description: string };
  fiberDirection: Vec3;
  restingLength: number;
  volume: number;
  mass: number;
  fascicleArchitecture: string;
  pennationAngle?: number;
}

export interface JointData {
  id: string;
  name: string;
  type: string;
  transform: Transform;
  connectedBoneIds: string[];
  degreesOfFreedom: number;
}

export interface OrganData {
  id: string;
  name: string;
  system: string;
  transform: Transform;
  volume: number;
  mass: number;
  isVital: boolean;
  laterality: string;
}

export interface VesselData {
  id: string;
  name: string;
  vesselType: "artery" | "vein";
  path: Vec3[];
  averageLumenRadius: number;
  parentVesselId?: string | null;
}

export interface NerveData {
  id: string;
  name: string;
  type: string;
  path: Vec3[];
  parentNerveId?: string | null;
}

export interface LigamentData {
  id: string;
  name: string;
  originBoneId: string;
  originPosition: Vec3;
  insertionBoneId: string;
  insertionPosition: Vec3;
  restingLength: number;
}

export interface CartilageData {
  id: string;
  name: string;
  type: "hyaline" | "fibrocartilage";
  thickness: number;
  surfaceArea: number;
  boneId?: string;
  jointId: string;
}

export interface HumanBodyData {
  schemaVersion: string;
  id: string;
  name?: string;
  proportions: {
    biologicalSex?: string;
    totalHeight: number;
    weight: number;
  };
  skeleton: BoneData[];
  joints: JointData[];
  tendons: TendonData[];
  muscles: MuscleData[];
  organs: OrganData[];
  vascularSystem: VesselData[];
  nerves: NerveData[];
  ligaments: LigamentData[];
  cartilage: CartilageData[];
}

// ═══════════════════════════════════════════════════════════════════════
// 2. ANATOMICAL COLOR PALETTE — region-based PBR coloring
// ═══════════════════════════════════════════════════════════════════════

const BONE_COLORS: Record<string, number> = {
  axial_cranium:         0xf5edd6,
  axial_face:            0xf0e6cc,
  axial_vertebral:       0xede0c0,
  axial_thorax:          0xe8dbb8,
  appendicular_pectoral: 0xeadcba,
  appendicular_upper:    0xe5d7b2,
  appendicular_pelvic:   0xe0d0aa,
  appendicular_lower:    0xdbc9a2,
};

const MUSCLE_COLORS: Record<string, number> = {
  face:               0xcc6666,
  head_and_neck:      0xc45555,
  shoulder:           0xb83333,
  arm_anterior:       0xc04040,
  arm_posterior:      0xaa3535,
  forearm_anterior:   0xc04848,
  forearm_posterior:  0xaa3838,
  hand_intrinsic:     0xd06060,
  thorax_anterior:    0xb02828,
  back_superficial:   0xa02020,
  back_deep:          0x8a1818,
  abdomen:            0xb53030,
  hip:                0x992222,
  thigh_anterior:     0xb82828,
  thigh_posterior:    0xa02020,
  thigh_medial:       0xa82828,
  leg_anterior:       0xc03838,
  leg_posterior:      0xa83030,
  leg_lateral:        0xb53333,
  foot_intrinsic:     0xd06060,
};

const ORGAN_COLORS: Record<string, number> = {
  cardiovascular: 0xcc2233,
  respiratory:    0xeeaaaa,
  digestive:      0xddaa77,
  nervous:        0xffddcc,
  urinary:        0xccaa66,
  endocrine:      0xddbb88,
  lymphatic:      0x996688,
  reproductive:   0xdd8899,
  integumentary:  0xeeccaa,
};

// ═══════════════════════════════════════════════════════════════════════
// 3. MATERIAL FACTORY — PBR materials for each tissue type
// ═══════════════════════════════════════════════════════════════════════

const _materialCache = new Map<string, THREE.Material>();

function boneMaterial(region: string): THREE.MeshPhysicalMaterial {
  const key = `bone_${region}`;
  if (_materialCache.has(key)) return _materialCache.get(key) as THREE.MeshPhysicalMaterial;
  const mat = new THREE.MeshPhysicalMaterial({
    color: BONE_COLORS[region] ?? 0xe8dbb8,
    roughness: 0.55,
    metalness: 0.02,
    clearcoat: 0.15,
    clearcoatRoughness: 0.4,
    sheen: 0.1,
    sheenRoughness: 0.6,
    sheenColor: new THREE.Color(0xfffff0),
  });
  _materialCache.set(key, mat);
  return mat;
}

function muscleMaterial(region: string): THREE.MeshPhysicalMaterial {
  const key = `muscle_${region}`;
  if (_materialCache.has(key)) return _materialCache.get(key) as THREE.MeshPhysicalMaterial;
  const mat = new THREE.MeshPhysicalMaterial({
    color: MUSCLE_COLORS[region] ?? 0xaa3333,
    roughness: 0.7,
    metalness: 0.0,
    clearcoat: 0.08,
    clearcoatRoughness: 0.6,
    transmission: 0.02,
    thickness: 0.5,
    sheen: 0.15,
    sheenRoughness: 0.5,
    sheenColor: new THREE.Color(0xff8888),
    side: THREE.DoubleSide,
  });
  _materialCache.set(key, mat);
  return mat;
}

function tendonMaterial(): THREE.MeshPhysicalMaterial {
  const key = "tendon";
  if (_materialCache.has(key)) return _materialCache.get(key) as THREE.MeshPhysicalMaterial;
  const mat = new THREE.MeshPhysicalMaterial({
    color: 0xf0f0e8,
    roughness: 0.6,
    metalness: 0.0,
    clearcoat: 0.2,
    clearcoatRoughness: 0.3,
    sheen: 0.3,
    sheenRoughness: 0.4,
    sheenColor: new THREE.Color(0xeeeedd),
  });
  _materialCache.set(key, mat);
  return mat;
}

function arteryMaterial(): THREE.MeshPhysicalMaterial {
  const key = "artery";
  if (_materialCache.has(key)) return _materialCache.get(key) as THREE.MeshPhysicalMaterial;
  const mat = new THREE.MeshPhysicalMaterial({
    color: 0xdd3322,
    roughness: 0.5,
    metalness: 0.0,
    clearcoat: 0.3,
    clearcoatRoughness: 0.2,
    transmission: 0.1,
    thickness: 0.3,
  });
  _materialCache.set(key, mat);
  return mat;
}

function veinMaterial(): THREE.MeshPhysicalMaterial {
  const key = "vein";
  if (_materialCache.has(key)) return _materialCache.get(key) as THREE.MeshPhysicalMaterial;
  const mat = new THREE.MeshPhysicalMaterial({
    color: 0x3344aa,
    roughness: 0.5,
    metalness: 0.0,
    clearcoat: 0.3,
    clearcoatRoughness: 0.2,
    transmission: 0.1,
    thickness: 0.3,
  });
  _materialCache.set(key, mat);
  return mat;
}

function nerveMaterial(): THREE.MeshPhysicalMaterial {
  const key = "nerve";
  if (_materialCache.has(key)) return _materialCache.get(key) as THREE.MeshPhysicalMaterial;
  const mat = new THREE.MeshPhysicalMaterial({
    color: 0xeedd44,
    roughness: 0.6,
    metalness: 0.0,
    emissive: 0x332200,
    emissiveIntensity: 0.15,
    clearcoat: 0.1,
    clearcoatRoughness: 0.5,
  });
  _materialCache.set(key, mat);
  return mat;
}

function organMaterial(system: string): THREE.MeshPhysicalMaterial {
  const key = `organ_${system}`;
  if (_materialCache.has(key)) return _materialCache.get(key) as THREE.MeshPhysicalMaterial;
  const mat = new THREE.MeshPhysicalMaterial({
    color: ORGAN_COLORS[system] ?? 0xddaa88,
    roughness: 0.65,
    metalness: 0.0,
    clearcoat: 0.2,
    clearcoatRoughness: 0.4,
    transmission: 0.08,
    thickness: 1.0,
    sheen: 0.1,
    sheenRoughness: 0.6,
    sheenColor: new THREE.Color(0xffcccc),
    side: THREE.DoubleSide,
  });
  _materialCache.set(key, mat);
  return mat;
}

function ligamentMaterial(): THREE.MeshPhysicalMaterial {
  const key = "ligament";
  if (_materialCache.has(key)) return _materialCache.get(key) as THREE.MeshPhysicalMaterial;
  const mat = new THREE.MeshPhysicalMaterial({
    color: 0xd0d8c0,
    roughness: 0.65,
    metalness: 0.0,
    clearcoat: 0.15,
    clearcoatRoughness: 0.4,
    sheen: 0.2,
    sheenRoughness: 0.5,
    sheenColor: new THREE.Color(0xeeeedd),
  });
  _materialCache.set(key, mat);
  return mat;
}

function cartilageMaterial(type: string): THREE.MeshPhysicalMaterial {
  const key = `cartilage_${type}`;
  if (_materialCache.has(key)) return _materialCache.get(key) as THREE.MeshPhysicalMaterial;
  const color = type === "hyaline" ? 0xc8dde8 : 0xb0c8d0;
  const mat = new THREE.MeshPhysicalMaterial({
    color,
    roughness: 0.4,
    metalness: 0.0,
    clearcoat: 0.4,
    clearcoatRoughness: 0.2,
    transmission: 0.15,
    thickness: 0.5,
  });
  _materialCache.set(key, mat);
  return mat;
}

function jointMaterial(): THREE.MeshPhysicalMaterial {
  const key = "joint";
  if (_materialCache.has(key)) return _materialCache.get(key) as THREE.MeshPhysicalMaterial;
  const mat = new THREE.MeshPhysicalMaterial({
    color: 0x66aadd,
    roughness: 0.3,
    metalness: 0.1,
    clearcoat: 0.5,
    clearcoatRoughness: 0.15,
    emissive: 0x112244,
    emissiveIntensity: 0.2,
  });
  _materialCache.set(key, mat);
  return mat;
}

// ═══════════════════════════════════════════════════════════════════════
// 4. GEOMETRY FACTORIES
// ═══════════════════════════════════════════════════════════════════════

// Reusable geometry templates (pooled by LOD segments)
const _capsuleGeoCache = new Map<string, THREE.BufferGeometry>();

function capsuleGeometry(radius: number, height: number, radialSeg: number = 8): THREE.BufferGeometry {
  const key = `${radius.toFixed(3)}_${height.toFixed(3)}_${radialSeg}`;
  if (_capsuleGeoCache.has(key)) return _capsuleGeoCache.get(key)!;
  const geo = new THREE.CapsuleGeometry(radius, Math.max(0.01, height), Math.max(2, radialSeg >> 1), radialSeg);
  _capsuleGeoCache.set(key, geo);
  return geo;
}

function boneGeometry(bone: BoneData): THREE.BufferGeometry {
  const cls = bone.classification;
  // All lengths in cm
  const l = bone.length;
  const w = bone.width;
  const d = bone.depth;

  switch (cls) {
    case "long": {
      // Capsule along Y axis: radius = avg(w,d)/2, cylindrical height = length - 2*radius
      const r = (w + d) / 4;
      const cylH = Math.max(0.1, l - 2 * r);
      return capsuleGeometry(r, cylH, 10);
    }
    case "flat": {
      // Flattened box — cranial/rib bones
      return new THREE.BoxGeometry(w, l * 0.15, d).toNonIndexed();
    }
    case "irregular": {
      // Icosahedron scaled to bone dimensions — vertebrae, hip
      const ico = new THREE.IcosahedronGeometry(1, 1);
      ico.scale(w / 2, l / 2, d / 2);
      return ico;
    }
    case "short": {
      // Rounded box — carpals, tarsals
      const r = Math.min(w, d, l) / 4;
      return capsuleGeometry(r, Math.max(0.1, l - 2 * r), 6);
    }
    case "sesamoid": {
      // Sphere — patella
      const r = Math.max(w, d, l) / 2;
      return new THREE.SphereGeometry(r, 10, 8);
    }
    default:
      return new THREE.SphereGeometry(l / 2, 8, 6);
  }
}

function tubeFromPath(points: THREE.Vector3[], radius: number, segments?: number): THREE.BufferGeometry {
  if (points.length < 2) return new THREE.SphereGeometry(radius, 6, 4);
  const curve = new THREE.CatmullRomCurve3(points, false, "catmullrom", 0.5);
  const tubeSeg = segments ?? Math.max(4, Math.min(32, Math.ceil(curve.getLength() / 2)));
  return new THREE.TubeGeometry(curve, tubeSeg, radius, 6, false);
}

function organGeometry(organ: OrganData): THREE.BufferGeometry {
  // Approximate organ volume as ellipsoid: V = 4/3 π abc
  // Assume a:b:c ≈ 1:1.5:0.8 and solve for scale
  const vol = organ.volume; // cm³
  const k = Math.cbrt(vol / (4 / 3 * Math.PI * 1.0 * 1.5 * 0.8));
  const a = k * 1.0;
  const b = k * 1.5;
  const c = k * 0.8;

  const sp = new THREE.SphereGeometry(1, 14, 10);
  sp.scale(a, b, c);
  return sp;
}

// ═══════════════════════════════════════════════════════════════════════
// 5. SCENE LAYER GROUPS — toggleable visibility
// ═══════════════════════════════════════════════════════════════════════

export type LayerName =
  | "skeleton"
  | "joints"
  | "muscles"
  | "tendons"
  | "organs"
  | "arteries"
  | "veins"
  | "nerves"
  | "ligaments"
  | "cartilage";

export const ALL_LAYERS: LayerName[] = [
  "skeleton", "joints", "muscles", "tendons",
  "organs", "arteries", "veins", "nerves",
  "ligaments", "cartilage",
];

export const DEFAULT_VISIBLE: Set<LayerName> = new Set(["skeleton", "joints", "muscles"]);

// ═══════════════════════════════════════════════════════════════════════
// 6. SCENE ASSEMBLY — builds Three.js scene from HumanBody JSON
// ═══════════════════════════════════════════════════════════════════════

export type ThemeMode = "dark" | "light";

interface ThemeConfig {
  sceneBg: number;
  fogColor: number;
  fogDensity: number;
  groundColor: number;
  gridA: number;
  gridB: number;
  hemiSky: number;
  hemiGround: number;
  hemiIntensity: number;
  ambientColor: number;
  ambientIntensity: number;
  keyIntensity: number;
  fillIntensity: number;
  rimIntensity: number;
  exposure: number;
  bloomStrength: number;
}

const THEMES: Record<ThemeMode, ThemeConfig> = {
  dark: {
    sceneBg: 0x0c0c14, fogColor: 0x0c0c14, fogDensity: 0.0008,
    groundColor: 0x111118, gridA: 0x222244, gridB: 0x181828,
    hemiSky: 0xb0c8e8, hemiGround: 0x2a1a0a, hemiIntensity: 0.5,
    ambientColor: 0x303848, ambientIntensity: 0.4,
    keyIntensity: 1.2, fillIntensity: 0.5, rimIntensity: 0.35,
    exposure: 1.1, bloomStrength: 0.15,
  },
  light: {
    sceneBg: 0xeef2f7, fogColor: 0xeef2f7, fogDensity: 0.0004,
    groundColor: 0xd8dce4, gridA: 0xbbc0cc, gridB: 0xd0d4dc,
    hemiSky: 0xffffff, hemiGround: 0x8899aa, hemiIntensity: 0.8,
    ambientColor: 0xc0c8d4, ambientIntensity: 0.7,
    keyIntensity: 1.0, fillIntensity: 0.6, rimIntensity: 0.25,
    exposure: 1.3, bloomStrength: 0.05,
  },
};

export interface UITheme {
  bg: string;
  bgOverlay: string;
  border: string;
  text: string;
  textMuted: string;
  textDim: string;
  panelBg: string;
  panelBorder: string;
  btnBg: string;
  btnBorder: string;
  btnText: string;
  btnActiveText: string;
  inactiveText: string;
}

const UI_THEMES: Record<ThemeMode, UITheme> = {
  dark: {
    bg: "#0c0c14", bgOverlay: "rgba(12,12,20,.92)", border: "rgba(100,120,180,.15)",
    text: "#e8e8f0", textMuted: "#556688", textDim: "#334455",
    panelBg: "rgba(12,12,20,.92)", panelBorder: "rgba(100,120,180,.15)",
    btnBg: "rgba(60,80,120,.12)", btnBorder: "rgba(80,100,140,.2)",
    btnText: "#8899bb", btnActiveText: "#c8ccd4", inactiveText: "#556677",
  },
  light: {
    bg: "#eef2f7", bgOverlay: "rgba(255,255,255,.94)", border: "rgba(100,120,160,.2)",
    text: "#1a1e2a", textMuted: "#6678889", textDim: "#8899aa",
    panelBg: "rgba(255,255,255,.94)", panelBorder: "rgba(100,120,160,.18)",
    btnBg: "rgba(100,120,160,.08)", btnBorder: "rgba(100,120,160,.2)",
    btnText: "#4a5568", btnActiveText: "#1a1e2a", inactiveText: "#8899aa",
  },
};

export interface SceneHandle {
  scene: THREE.Scene;
  camera: THREE.PerspectiveCamera;
  renderer: THREE.WebGLRenderer;
  composer: EffectComposer;
  controls: OrbitControls;
  layers: Record<LayerName, THREE.Group>;
  boneMap: Map<string, THREE.Mesh>;
  jointMap: Map<string, THREE.Mesh>;
  themeRefs: {
    hemi: THREE.HemisphereLight;
    ambient: THREE.AmbientLight;
    keyLight: THREE.DirectionalLight;
    fillLight: THREE.DirectionalLight;
    rimLight: THREE.DirectionalLight;
    ground: THREE.Mesh;
    grid: THREE.GridHelper; // mutable — replaced on theme swap
    bloom: UnrealBloomPass;
  };
  dispose: () => void;
}

export function applyTheme(handle: SceneHandle, mode: ThemeMode): void {
  const t = THEMES[mode];
  const { scene, renderer, themeRefs } = handle;

  scene.background = new THREE.Color(t.sceneBg);
  (scene.fog as THREE.FogExp2).color.set(t.fogColor);
  (scene.fog as THREE.FogExp2).density = t.fogDensity;

  renderer.toneMappingExposure = t.exposure;

  themeRefs.hemi.color.set(t.hemiSky);
  themeRefs.hemi.groundColor.set(t.hemiGround);
  themeRefs.hemi.intensity = t.hemiIntensity;

  themeRefs.ambient.color.set(t.ambientColor);
  themeRefs.ambient.intensity = t.ambientIntensity;

  themeRefs.keyLight.intensity = t.keyIntensity;
  themeRefs.fillLight.intensity = t.fillIntensity;
  themeRefs.rimLight.intensity = t.rimIntensity;

  ((themeRefs.ground as THREE.Mesh).material as THREE.MeshStandardMaterial).color.set(t.groundColor);

  scene.remove(themeRefs.grid);
  const newGrid = new THREE.GridHelper(200, 40, t.gridA, t.gridB);
  newGrid.position.y = 0.05;
  scene.add(newGrid);
  themeRefs.grid = newGrid;

  themeRefs.bloom.strength = t.bloomStrength;
}

function toV3(v: Vec3): THREE.Vector3 {
  return new THREE.Vector3(v.x, v.y, v.z);
}

export function buildScene(container: HTMLElement, body: HumanBodyData): SceneHandle {
  const W = container.clientWidth;
  const H = container.clientHeight;

  // ── Renderer ──
  const renderer = new THREE.WebGLRenderer({
    antialias: true,
    powerPreference: "high-performance",
  });
  renderer.setSize(W, H);
  renderer.setPixelRatio(Math.min(devicePixelRatio, 2));
  renderer.shadowMap.enabled = true;
  renderer.shadowMap.type = THREE.PCFSoftShadowMap;
  renderer.toneMapping = THREE.ACESFilmicToneMapping;
  renderer.toneMappingExposure = 1.1;
  renderer.outputColorSpace = THREE.SRGBColorSpace;
  container.appendChild(renderer.domElement);

  // ── Scene ──
  const scene = new THREE.Scene();
  scene.background = new THREE.Color(0x0c0c14);
  scene.fog = new THREE.FogExp2(0x0c0c14, 0.0008);

  // ── Camera — framing full body (Y range 0–180 cm) ──
  const camera = new THREE.PerspectiveCamera(40, W / H, 0.5, 500);
  camera.position.set(60, 100, 120);
  camera.lookAt(0, 90, 0);

  // ── Controls ──
  const controls = new OrbitControls(camera, renderer.domElement);
  controls.target.set(0, 90, 0);
  controls.enableDamping = true;
  controls.dampingFactor = 0.08;
  controls.minDistance = 15;
  controls.maxDistance = 350;
  controls.maxPolarAngle = Math.PI * 0.95;
  controls.update();

  // ── Lighting — 3-point + ambient + hemisphere ──
  const hemi = new THREE.HemisphereLight(0xb0c8e8, 0x2a1a0a, 0.5);
  scene.add(hemi);

  const ambient = new THREE.AmbientLight(0x303848, 0.4);
  scene.add(ambient);

  const keyLight = new THREE.DirectionalLight(0xffeedd, 1.2);
  keyLight.position.set(60, 150, 80);
  keyLight.castShadow = true;
  keyLight.shadow.mapSize.set(2048, 2048);
  keyLight.shadow.camera.near = 1;
  keyLight.shadow.camera.far = 400;
  keyLight.shadow.camera.left = -80;
  keyLight.shadow.camera.right = 80;
  keyLight.shadow.camera.top = 200;
  keyLight.shadow.camera.bottom = -20;
  keyLight.shadow.bias = -0.001;
  scene.add(keyLight);

  const fillLight = new THREE.DirectionalLight(0x6688cc, 0.5);
  fillLight.position.set(-50, 100, -40);
  scene.add(fillLight);

  const rimLight = new THREE.DirectionalLight(0xffa060, 0.35);
  rimLight.position.set(0, 50, -100);
  scene.add(rimLight);

  const topLight = new THREE.PointLight(0xeeeeff, 0.3, 300);
  topLight.position.set(0, 200, 0);
  scene.add(topLight);

  // ── Ground plane ──
  const ground = new THREE.Mesh(
    new THREE.PlaneGeometry(600, 600),
    new THREE.MeshStandardMaterial({ color: 0x111118, roughness: 0.9, metalness: 0.1 }),
  );
  ground.rotation.x = -Math.PI / 2;
  ground.receiveShadow = true;
  scene.add(ground);

  let grid = new THREE.GridHelper(200, 40, 0x222244, 0x181828);
  grid.position.y = 0.05;
  scene.add(grid);

  // ── Post-processing ──
  const composer = new EffectComposer(renderer);
  composer.addPass(new RenderPass(scene, camera));

  const bloomPass = new UnrealBloomPass(
    new THREE.Vector2(W, H), 0.15, 0.4, 0.9,
  );
  composer.addPass(bloomPass);

  const smaaPass = new SMAAPass();
  composer.addPass(smaaPass);

  // ── Layer groups ──
  const layers: Record<LayerName, THREE.Group> = {} as any;
  for (const ln of ALL_LAYERS) {
    const g = new THREE.Group();
    g.name = ln;
    g.visible = DEFAULT_VISIBLE.has(ln);
    scene.add(g);
    layers[ln] = g;
  }

  // ── Index maps ──
  const boneMap = new Map<string, THREE.Mesh>();
  const boneDataById = new Map<string, BoneData>();
  const tendonById = new Map<string, TendonData>();
  const jointMap = new Map<string, THREE.Mesh>();
  const jointDataById = new Map<string, JointData>();

  for (const b of body.skeleton) boneDataById.set(b.id, b);
  for (const t of body.tendons) tendonById.set(t.id, t);
  for (const j of body.joints) jointDataById.set(j.id, j);

  // ════════════════════════════════════════════════════════════════════
  // SKELETON — 206 bones
  // ════════════════════════════════════════════════════════════════════

  for (const bone of body.skeleton) {
    const geo = boneGeometry(bone);
    const mat = boneMaterial(bone.region);
    const mesh = new THREE.Mesh(geo, mat);

    mesh.position.set(
      bone.transform.position.x,
      bone.transform.position.y,
      bone.transform.position.z,
    );

    // Orient long bones along parent→child vector
    if (bone.parentBoneId && bone.classification === "long") {
      const parent = boneDataById.get(bone.parentBoneId);
      if (parent) {
        const from = toV3(parent.transform.position);
        const to = toV3(bone.transform.position);
        const dir = to.clone().sub(from).normalize();
        const up = new THREE.Vector3(0, 1, 0);
        if (Math.abs(dir.dot(up)) < 0.999) {
          const q = new THREE.Quaternion().setFromUnitVectors(up, dir);
          mesh.quaternion.copy(q);
        }
      }
    }

    mesh.castShadow = true;
    mesh.receiveShadow = true;
    mesh.userData = { type: "bone", id: bone.id, name: bone.name, region: bone.region };
    layers.skeleton.add(mesh);
    boneMap.set(bone.id, mesh);
  }

  // ════════════════════════════════════════════════════════════════════
  // JOINTS — 130
  // ════════════════════════════════════════════════════════════════════

  for (const joint of body.joints) {
    const dof = joint.degreesOfFreedom;
    const r = dof >= 3 ? 1.2 : dof === 2 ? 0.9 : 0.65;
    const geo = new THREE.SphereGeometry(r, 12, 8);
    const mesh = new THREE.Mesh(geo, jointMaterial());
    mesh.position.set(
      joint.transform.position.x,
      joint.transform.position.y,
      joint.transform.position.z,
    );
    mesh.userData = { type: "joint", id: joint.id, name: joint.name, dof };
    layers.joints.add(mesh);
    jointMap.set(joint.id, mesh);
  }

  // ════════════════════════════════════════════════════════════════════
  // MUSCLES — 322 (with fiber tubes from origin to insertion)
  // ════════════════════════════════════════════════════════════════════

  const tMat = tendonMaterial();
  for (const muscle of body.muscles) {
    const originTendon = tendonById.get(muscle.origin.tendonId);
    const insertionTendon = tendonById.get(muscle.insertion.tendonId);
    if (!originTendon || !insertionTendon) continue;

    const originBone = boneDataById.get(originTendon.attachedBoneId);
    const insertionBone = boneDataById.get(insertionTendon.attachedBoneId);
    if (!originBone || !insertionBone) continue;

    // World positions = bone position + tendon local offset
    const oPos = new THREE.Vector3(
      originBone.transform.position.x + originTendon.localPosition.x,
      originBone.transform.position.y + originTendon.localPosition.y,
      originBone.transform.position.z + originTendon.localPosition.z,
    );
    const iPos = new THREE.Vector3(
      insertionBone.transform.position.x + insertionTendon.localPosition.x,
      insertionBone.transform.position.y + insertionTendon.localPosition.y,
      insertionBone.transform.position.z + insertionTendon.localPosition.z,
    );

    // Muscle belly: curved tube between origin and insertion
    // Bulge control point offset by fiber direction for anatomical curvature
    const mid = oPos.clone().add(iPos).multiplyScalar(0.5);
    const fiberDir = toV3(muscle.fiberDirection);
    const span = oPos.distanceTo(iPos);
    const bulge = span * 0.12;
    const ctrl1 = oPos.clone().lerp(mid, 0.33).add(fiberDir.clone().multiplyScalar(bulge));
    const ctrl2 = mid.clone().lerp(iPos, 0.33).add(fiberDir.clone().multiplyScalar(bulge * 0.7));

    // Radius from volume: V ≈ π r² L → r = sqrt(V / (π L))
    const bellyR = Math.max(0.15, Math.min(2.5, Math.sqrt(muscle.volume / (Math.PI * Math.max(1, muscle.restingLength)))));

    const muscleTube = tubeFromPath([oPos, ctrl1, ctrl2, iPos], bellyR);
    const muscleMesh = new THREE.Mesh(muscleTube, muscleMaterial(muscle.region));
    muscleMesh.castShadow = true;
    muscleMesh.userData = { type: "muscle", id: muscle.id, name: muscle.name, region: muscle.region };
    layers.muscles.add(muscleMesh);

    // Tendons: thin tubes at origin and insertion ends
    const tR = Math.max(0.08, bellyR * 0.3);
    if (originTendon.length > 0.5) {
      const tEnd = oPos.clone().lerp(new THREE.Vector3(
        originBone.transform.position.x,
        originBone.transform.position.y,
        originBone.transform.position.z,
      ), 0.8);
      const tGeo = tubeFromPath([tEnd, oPos], tR, 4);
      const tMesh = new THREE.Mesh(tGeo, tMat);
      tMesh.userData = { type: "tendon", name: originTendon.name };
      layers.tendons.add(tMesh);
    }
    if (insertionTendon.length > 0.5) {
      const tEnd = iPos.clone().lerp(new THREE.Vector3(
        insertionBone.transform.position.x,
        insertionBone.transform.position.y,
        insertionBone.transform.position.z,
      ), 0.8);
      const tGeo = tubeFromPath([iPos, tEnd], tR, 4);
      const tMesh = new THREE.Mesh(tGeo, tMat);
      tMesh.userData = { type: "tendon", name: insertionTendon.name };
      layers.tendons.add(tMesh);
    }
  }

  // ════════════════════════════════════════════════════════════════════
  // VASCULAR SYSTEM — 94 vessels (arteries + veins)
  // ════════════════════════════════════════════════════════════════════

  for (const vessel of body.vascularSystem) {
    if (vessel.path.length < 2) continue;
    const pts = vessel.path.map(toV3);
    const r = Math.max(0.08, vessel.averageLumenRadius * 0.6);
    const geo = tubeFromPath(pts, r);
    const mat = vessel.vesselType === "artery" ? arteryMaterial() : veinMaterial();
    const mesh = new THREE.Mesh(geo, mat);
    mesh.userData = { type: "vessel", id: vessel.id, name: vessel.name, vesselType: vessel.vesselType };
    const layer = vessel.vesselType === "artery" ? layers.arteries : layers.veins;
    layer.add(mesh);
  }

  // ════════════════════════════════════════════════════════════════════
  // NERVES — 51
  // ════════════════════════════════════════════════════════════════════

  for (const nerve of body.nerves) {
    if (nerve.path.length < 2) continue;
    const pts = nerve.path.map(toV3);
    const r = nerve.type === "motor" ? 0.12 : nerve.type === "sensory" ? 0.1 : 0.15;
    const geo = tubeFromPath(pts, r);
    const mesh = new THREE.Mesh(geo, nerveMaterial());
    mesh.userData = { type: "nerve", id: nerve.id, name: nerve.name };
    layers.nerves.add(mesh);
  }

  // ════════════════════════════════════════════════════════════════════
  // ORGANS — 38
  // ════════════════════════════════════════════════════════════════════

  for (const organ of body.organs) {
    const geo = organGeometry(organ);
    const mesh = new THREE.Mesh(geo, organMaterial(organ.system));
    mesh.position.set(
      organ.transform.position.x,
      organ.transform.position.y,
      organ.transform.position.z,
    );
    mesh.castShadow = true;
    mesh.receiveShadow = true;
    mesh.userData = { type: "organ", id: organ.id, name: organ.name, system: organ.system };
    layers.organs.add(mesh);
  }

  // ════════════════════════════════════════════════════════════════════
  // LIGAMENTS — 43
  // ════════════════════════════════════════════════════════════════════

  const ligMat = ligamentMaterial();
  for (const lig of body.ligaments) {
    const oBone = boneDataById.get(lig.originBoneId);
    const iBone = boneDataById.get(lig.insertionBoneId);
    if (!oBone || !iBone) continue;

    const oPos = new THREE.Vector3(
      oBone.transform.position.x + lig.originPosition.x,
      oBone.transform.position.y + lig.originPosition.y,
      oBone.transform.position.z + lig.originPosition.z,
    );
    const iPos = new THREE.Vector3(
      iBone.transform.position.x + lig.insertionPosition.x,
      iBone.transform.position.y + lig.insertionPosition.y,
      iBone.transform.position.z + lig.insertionPosition.z,
    );

    const r = Math.max(0.1, Math.min(0.6, lig.restingLength * 0.04));
    const geo = tubeFromPath([oPos, iPos], r, 4);
    const mesh = new THREE.Mesh(geo, ligMat);
    mesh.userData = { type: "ligament", id: lig.id, name: lig.name };
    layers.ligaments.add(mesh);
  }

  // ════════════════════════════════════════════════════════════════════
  // CARTILAGE — 36
  // ════════════════════════════════════════════════════════════════════

  for (const cart of body.cartilage) {
    const jointData = jointDataById.get(cart.jointId);
    if (!jointData) continue;

    // Disc/meniscus at joint position, sized by surfaceArea
    const r = Math.sqrt(cart.surfaceArea / Math.PI);
    const geo = new THREE.CylinderGeometry(r, r, cart.thickness * 0.5, 12, 1);
    const mesh = new THREE.Mesh(geo, cartilageMaterial(cart.type));
    mesh.position.set(
      jointData.transform.position.x,
      jointData.transform.position.y,
      jointData.transform.position.z,
    );
    mesh.userData = { type: "cartilage", id: cart.id, name: cart.name };
    layers.cartilage.add(mesh);
  }

  // ── Dispose helper ──
  function dispose() {
    composer.dispose();
    renderer.dispose();
    controls.dispose();
    _materialCache.forEach((m) => m.dispose());
    _materialCache.clear();
    _capsuleGeoCache.forEach((g) => g.dispose());
    _capsuleGeoCache.clear();
    scene.traverse((obj: THREE.Object3D) => {
      if (obj instanceof THREE.Mesh) {
        obj.geometry.dispose();
      }
    });
    if (container.contains(renderer.domElement)) {
      container.removeChild(renderer.domElement);
    }
  }

  const themeRefs = { hemi, ambient, keyLight, fillLight, rimLight, ground, grid, bloom: bloomPass };

  return { scene, camera, renderer, composer, controls, layers, boneMap, jointMap, themeRefs, dispose };
}

// ═══════════════════════════════════════════════════════════════════════
// 7. HOVER / PICK — raycaster for tooltip
// ═══════════════════════════════════════════════════════════════════════

export interface PickResult {
  name: string;
  type: string;
  extra: Record<string, unknown>;
}

export function pick(
  handle: SceneHandle,
  ndc: THREE.Vector2,
  visibleLayers: Set<LayerName>,
): PickResult | null {
  const raycaster = new THREE.Raycaster();
  raycaster.setFromCamera(ndc, handle.camera);

  const targets: THREE.Object3D[] = [];
  for (const ln of ALL_LAYERS) {
    if (visibleLayers.has(ln)) targets.push(handle.layers[ln]);
  }

  const hits = raycaster.intersectObjects(targets, true);
  if (hits.length === 0) return null;

  const hit = hits[0];
  if (!hit) return null;
  const ud = hit.object.userData as Record<string, unknown>;
  if (!ud?.name) return null;
  return { name: ud.name as string, type: ud.type as string, extra: ud };
}

// ═══════════════════════════════════════════════════════════════════════
// 8. REACT COMPONENT — <AnatomyViewer />
// ═══════════════════════════════════════════════════════════════════════

export interface AnatomyViewerProps {
  body: HumanBodyData;
}

const LAYER_ICONS: Record<LayerName, string> = {
  skeleton: "🦴",
  joints: "🔵",
  muscles: "💪",
  tendons: "🪢",
  organs: "🫀",
  arteries: "🔴",
  veins: "🔵",
  nerves: "⚡",
  ligaments: "🩹",
  cartilage: "🫧",
};

const LAYER_COLORS: Record<LayerName, string> = {
  skeleton: "#e8dbb8",
  joints: "#66aadd",
  muscles: "#bb3333",
  tendons: "#f0f0e8",
  organs: "#ddaa77",
  arteries: "#dd3322",
  veins: "#3344aa",
  nerves: "#eedd44",
  ligaments: "#d0d8c0",
  cartilage: "#c8dde8",
};

export default function AnatomyViewer({ body }: AnatomyViewerProps) {
  const mountRef = useRef<HTMLDivElement>(null);
  const handleRef = useRef<SceneHandle | null>(null);
  const [visibleLayers, setVisibleLayers] = useState<Set<LayerName>>(new Set(DEFAULT_VISIBLE));
  const [hovered, setHovered] = useState<PickResult | null>(null);
  const [stats, setStats] = useState({ fps: 0, tris: 0 });
  const [theme, setTheme] = useState<ThemeMode>("dark");
  const mouseRef = useRef<THREE.Vector2>(new THREE.Vector2(-10, -10));
  const ui = UI_THEMES[theme];

  const toggleTheme = useCallback(() => {
    setTheme((prev) => {
      const next: ThemeMode = prev === "dark" ? "light" : "dark";
      if (handleRef.current) applyTheme(handleRef.current, next);
      return next;
    });
  }, []);

  const toggleLayer = useCallback((layer: LayerName) => {
    setVisibleLayers((prev: Set<LayerName>) => {
      const next = new Set(prev);
      if (next.has(layer)) next.delete(layer);
      else next.add(layer);
      return next;
    });
  }, []);

  // Sync layer visibility to Three.js groups
  useEffect(() => {
    const h = handleRef.current;
    if (!h) return;
    for (const ln of ALL_LAYERS) {
      h.layers[ln].visible = visibleLayers.has(ln);
    }
  }, [visibleLayers]);

  // Scene lifecycle
  useEffect(() => {
    const ct = mountRef.current;
    if (!ct) return;

    const handle = buildScene(ct, body);
    handleRef.current = handle;

    let rafId: number;
    let lastTime = 0;
    let frameCount = 0;
    let fpsAccum = 0;

    function loop(ts: number) {
      rafId = requestAnimationFrame(loop);
      const dt = ts - lastTime;
      lastTime = ts;

      handle.controls.update();
      handle.composer.render();

      // FPS counter
      frameCount++;
      fpsAccum += dt;
      if (fpsAccum >= 1000) {
        const info = handle.renderer.info.render;
        setStats({ fps: Math.round(frameCount * 1000 / fpsAccum), tris: info.triangles });
        frameCount = 0;
        fpsAccum = 0;
      }

      // Hover pick (throttled to every 3rd frame)
      if (frameCount % 3 === 0) {
        const result = pick(handle, mouseRef.current, visibleLayers);
        setHovered(result);
      }
    }

    rafId = requestAnimationFrame(loop);

    const onResize = () => {
      const w = ct.clientWidth;
      const h = ct.clientHeight;
      handle.camera.aspect = w / h;
      handle.camera.updateProjectionMatrix();
      handle.renderer.setSize(w, h);
      handle.composer.setSize(w, h);
    };
    window.addEventListener("resize", onResize);

    const onPointerMove = (e: PointerEvent) => {
      const rect = ct.getBoundingClientRect();
      mouseRef.current.x = ((e.clientX - rect.left) / rect.width) * 2 - 1;
      mouseRef.current.y = -((e.clientY - rect.top) / rect.height) * 2 + 1;
    };
    ct.addEventListener("pointermove", onPointerMove);

    return () => {
      cancelAnimationFrame(rafId);
      window.removeEventListener("resize", onResize);
      ct.removeEventListener("pointermove", onPointerMove);
      handle.dispose();
      handleRef.current = null;
    };
  }, [body]);

  // Presets
  const presetAll = () => setVisibleLayers(new Set(ALL_LAYERS));
  const presetSkeleton = () => setVisibleLayers(new Set(["skeleton", "joints", "cartilage"]));
  const presetMuscular = () => setVisibleLayers(new Set(["muscles", "tendons"]));
  const presetVascular = () => setVisibleLayers(new Set(["arteries", "veins"]));
  const presetNervous = () => setVisibleLayers(new Set(["nerves", "skeleton"]));
  const presetOrgans = () => setVisibleLayers(new Set(["organs", "skeleton"]));

  const layerCounts: Record<LayerName, number> = {
    skeleton: body.skeleton.length,
    joints: body.joints.length,
    muscles: body.muscles.length,
    tendons: body.tendons.length,
    organs: body.organs.length,
    arteries: body.vascularSystem.filter((v) => v.vesselType === "artery").length,
    veins: body.vascularSystem.filter((v) => v.vesselType === "vein").length,
    nerves: body.nerves.length,
    ligaments: body.ligaments.length,
    cartilage: body.cartilage.length,
  };

  return (
    <div style={{ width: "100%", height: "100vh", position: "relative", fontFamily: "'Inter','SF Pro','Segoe UI',sans-serif", background: "#0c0c14", color: "#c8ccd4", overflow: "hidden" }}>
      {/* Three.js canvas mount */}
      <div ref={mountRef} style={{ position: "absolute", inset: 0, zIndex: 1 }} />

      {/* Title / identity */}
      <div style={{ position: "absolute", top: 12, left: 16, zIndex: 10 }}>
        <div style={{ fontSize: 14, fontWeight: 700, letterSpacing: 1, color: "#e8e8f0" }}>
          {body.name ?? "Human Body"} — Schema v{body.schemaVersion}
        </div>
        <div style={{ fontSize: 10, color: "#556688", marginTop: 2 }}>
          {body.proportions.biologicalSex ?? "unknown"} · {body.proportions.totalHeight}cm · {body.proportions.weight}kg
        </div>
      </div>

      {/* Stats */}
      <div style={{ position: "absolute", top: 12, right: 16, zIndex: 10, fontSize: 9, color: "#445566", textAlign: "right" }}>
        <div>{stats.fps} FPS · {(stats.tris / 1000).toFixed(1)}K tris</div>
        <div>{body.skeleton.length} bones · {body.muscles.length} muscles · {body.joints.length} joints</div>
      </div>

      {/* Layer control panel */}
      <div style={{
        position: "absolute", top: 70, left: 16, zIndex: 10,
        background: "rgba(12,12,20,.92)", border: "1px solid rgba(100,120,180,.15)",
        borderRadius: 10, padding: 12, backdropFilter: "blur(12px)", width: 200,
      }}>
        <div style={{ fontSize: 10, fontWeight: 700, color: "#8899bb", letterSpacing: 1, marginBottom: 8, textTransform: "uppercase" }}>
          Layers
        </div>

        {ALL_LAYERS.map((ln) => {
          const active = visibleLayers.has(ln);
          return (
            <button
              key={ln}
              onClick={() => toggleLayer(ln)}
              style={{
                display: "flex", alignItems: "center", gap: 8, width: "100%",
                background: active ? `${LAYER_COLORS[ln]}18` : "transparent",
                border: `1px solid ${active ? LAYER_COLORS[ln] + "55" : "rgba(80,90,120,.15)"}`,
                borderRadius: 6, padding: "4px 8px", marginBottom: 3, cursor: "pointer",
                color: active ? LAYER_COLORS[ln] : "#556677", fontSize: 10,
                fontFamily: "inherit", textAlign: "left", transition: "all .15s",
              }}
            >
              <span style={{ fontSize: 12 }}>{LAYER_ICONS[ln]}</span>
              <span style={{ flex: 1, textTransform: "capitalize" }}>{ln}</span>
              <span style={{ fontSize: 8, opacity: 0.7 }}>{layerCounts[ln]}</span>
            </button>
          );
        })}

        {/* Presets */}
        <div style={{ marginTop: 10, borderTop: "1px solid rgba(80,90,120,.15)", paddingTop: 8 }}>
          <div style={{ fontSize: 9, fontWeight: 700, color: "#667788", letterSpacing: 1, marginBottom: 6, textTransform: "uppercase" }}>
            Presets
          </div>
          <div style={{ display: "flex", flexWrap: "wrap", gap: 4 }}>
            {([
              ["All", presetAll],
              ["Skeletal", presetSkeleton],
              ["Muscular", presetMuscular],
              ["Vascular", presetVascular],
              ["Nervous", presetNervous],
              ["Organs", presetOrgans],
            ] as [string, () => void][]).map(([label, fn]) => (
              <button
                key={label}
                onClick={fn}
                style={{
                  background: "rgba(60,80,120,.12)", border: "1px solid rgba(80,100,140,.2)",
                  color: "#8899bb", borderRadius: 4, padding: "2px 8px",
                  cursor: "pointer", fontSize: 9, fontFamily: "inherit",
                }}
              >
                {label}
              </button>
            ))}
          </div>
        </div>
      </div>

      {/* Hover tooltip */}
      {hovered && (
        <div style={{
          position: "absolute", bottom: 16, left: "50%", transform: "translateX(-50%)", zIndex: 10,
          background: "rgba(12,12,20,.94)", border: "1px solid rgba(100,120,180,.2)",
          borderRadius: 8, padding: "8px 16px", backdropFilter: "blur(10px)",
          textAlign: "center", pointerEvents: "none",
        }}>
          <div style={{ fontSize: 12, fontWeight: 600, color: "#e8e8f0" }}>{hovered.name}</div>
          <div style={{ fontSize: 9, color: "#667799", marginTop: 2, textTransform: "uppercase", letterSpacing: 1 }}>
            {hovered.type}
            {hovered.extra?.region ? ` · ${hovered.extra.region}` : ""}
            {hovered.extra?.system ? ` · ${hovered.extra.system}` : ""}
            {hovered.extra?.dof ? ` · ${hovered.extra.dof} DOF` : ""}
          </div>
        </div>
      )}

      {/* Controls hint */}
      <div style={{ position: "absolute", bottom: 16, right: 16, zIndex: 10, fontSize: 9, color: "#334455", textAlign: "right" }}>
        <div>LMB drag — orbit</div>
        <div>RMB drag — pan</div>
        <div>Scroll — zoom</div>
        <div>Hover — inspect</div>
      </div>
    </div>
  );
}
