/**
 * Regression tests for the anatomical renderer.
 *
 * These tests verify that:
 * 1. Body JSON loads without errors
 * 2. All bone geometries produce non-degenerate meshes
 * 3. Materials render with visible color (not black)
 * 4. Scene triangle count > 0 after construction
 * 5. Indexed mesh normals are unit-length and non-zero
 * 6. External asset URIs are resolvable
 * 7. No NaN positions in bone transforms
 *
 * Run: npx tsx src/renderer.test.ts
 *
 * Generated by: Claude Opus 4.6 (1M context)
 */

import * as fs from "fs";
import * as path from "path";
import * as THREE from "three";
import { fileURLToPath } from "url";
import { csgPrimitiveToGeometry, csgTreeToGeometry, type CSGNode } from "./renderer-csg";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

interface Vec3 { x: number; y: number; z: number }
interface BoneData {
  id: string; name: string; classification: string; region: string;
  transform: { position: Vec3; rotation: Vec3; scale: Vec3 };
  length: number; width: number; depth: number; parentBoneId: string | null;
}
interface LODData {
  level: number; vertexCount: number; triangleCount: number;
  vertices: { positions: number[]; normals?: number[]; uvs?: number[] };
  indices: number[];
}
interface BoneGeo {
  geometryType: string; id: string; boneId: string;
  lods?: LODData[]; uri?: string; csgTree?: unknown;
}
interface BodyData {
  skeleton: BoneData[];
  boneGeometries?: BoneGeo[];
  muscles: { id: string; name: string }[];
  joints: { id: string }[];
  tendons: { id: string }[];
  vascularSystem: { id: string }[];
}

const BODY_PATH = path.join(__dirname, "jhon-doe.json");
const ASSETS_DIR = path.join(__dirname, "..", "public", "assets", "bones");

let body: BodyData;
let errors: string[] = [];
let warnings: string[] = [];
let passed = 0;
let failed = 0;

function assert(condition: boolean, msg: string): void {
  if (condition) { passed++; }
  else { failed++; errors.push(`FAIL: ${msg}`); }
}

function warn(msg: string): void { warnings.push(`WARN: ${msg}`); }

// ── Load body JSON ──
try {
  const raw = fs.readFileSync(BODY_PATH, "utf-8");
  const parsed = JSON.parse(raw);
  body = Array.isArray(parsed) ? parsed[0] : parsed;
  assert(true, "Body JSON loads");
} catch (e) {
  console.error(`FATAL: Cannot load ${BODY_PATH}: ${e}`);
  process.exit(1);
}

// ── Test 1: Entity counts ──
assert(body.skeleton.length === 206, `Expected 206 bones, got ${body.skeleton.length}`);
assert(body.muscles.length >= 600, `Expected ≥600 muscles, got ${body.muscles.length}`);
assert(body.joints.length >= 100, `Expected ≥100 joints, got ${body.joints.length}`);

// ── Test 2: No NaN in bone positions ──
for (const bone of body.skeleton) {
  const p = bone.transform.position;
  const hasNaN = [p.x, p.y, p.z].some(v => isNaN(v));
  assert(!hasNaN, `Bone "${bone.name}" has NaN position`);
}

// ── Test 3: Bone geometries exist and match bone count ──
const geos = body.boneGeometries ?? [];
assert(geos.length === 206, `Expected 206 boneGeometries, got ${geos.length}`);

// ── Test 4: All bone IDs in geometries reference existing bones ──
const boneIds = new Set(body.skeleton.map(b => b.id));
for (const g of geos) {
  assert(boneIds.has(g.boneId), `Geometry ${g.id} references non-existent bone ${g.boneId}`);
}

// ── Test 5: Indexed mesh integrity ──
const indexedMeshGeos = geos.filter(g => g.geometryType === "indexed_mesh" && g.lods);
for (const g of indexedMeshGeos) {
  const boneName = body.skeleton.find(b => b.id === g.boneId)?.name ?? "?";
  const lod0 = g.lods![0]!;

  // Positions array length = vertexCount * 3
  assert(
    lod0.vertices.positions.length === lod0.vertexCount * 3,
    `${boneName}: positions.length (${lod0.vertices.positions.length}) !== vertexCount*3 (${lod0.vertexCount * 3})`,
  );

  // Indices array length = triangleCount * 3
  assert(
    lod0.indices.length === lod0.triangleCount * 3,
    `${boneName}: indices.length (${lod0.indices.length}) !== triangleCount*3 (${lod0.triangleCount * 3})`,
  );

  // All indices < vertexCount
  const maxIdx = Math.max(...lod0.indices);
  assert(
    maxIdx < lod0.vertexCount,
    `${boneName}: max index (${maxIdx}) >= vertexCount (${lod0.vertexCount})`,
  );

  // Triangle count > 0
  assert(lod0.triangleCount > 0, `${boneName}: zero triangles`);

  // Normals exist and are unit-length (CRITICAL for lighting)
  const normals = lod0.vertices.normals;
  if (normals && normals.length > 0) {
    assert(
      normals.length === lod0.vertexCount * 3,
      `${boneName}: normals.length (${normals.length}) !== vertexCount*3`,
    );
    // Check first 10 normals are unit-length
    let allUnit = true;
    let anyZero = false;
    for (let i = 0; i < Math.min(30, normals.length); i += 3) {
      const nx = normals[i]!, ny = normals[i + 1]!, nz = normals[i + 2]!;
      const mag = Math.sqrt(nx * nx + ny * ny + nz * nz);
      if (Math.abs(mag - 1.0) > 0.01) allUnit = false;
      if (mag < 0.001) anyZero = true;
    }
    assert(allUnit, `${boneName}: normals not unit-length`);
    assert(!anyZero, `${boneName}: has zero-length normals (renders as BLACK)`);
  } else {
    warn(`${boneName}: no normals — will compute at runtime (slow, may be wrong)`);
  }

  // No NaN in positions
  const hasNaN = lod0.vertices.positions.some(v => isNaN(v));
  assert(!hasNaN, `${boneName}: NaN in vertex positions`);

  // No NaN in normals
  if (normals) {
    const normNaN = normals.some(v => isNaN(v));
    assert(!normNaN, `${boneName}: NaN in normals`);
  }
}

// ── Test 6: External asset URIs point to existing files ──
const externalGeos = geos.filter(g => g.geometryType === "external_asset" && g.uri);
for (const g of externalGeos) {
  const boneName = body.skeleton.find(b => b.id === g.boneId)?.name ?? "?";
  const uri = g.uri!;
  // Convert asset:///bones/X.glb to local path
  const filename = uri.replace("asset:///bones/", "").replace("asset://bones/", "");
  const localPath = path.join(ASSETS_DIR, filename);
  const exists = fs.existsSync(localPath);
  assert(exists, `${boneName}: external asset ${filename} not found at ${localPath}`);
  if (exists) {
    const size = fs.statSync(localPath).size;
    assert(size > 100, `${boneName}: ${filename} is only ${size} bytes (corrupt?)`);
  }
}

// ── Test 7: Material color regression — bone colors must NOT be black ──
const BONE_COLORS: Record<string, number> = {
  axial_cranium: 0xf5edd6, axial_face: 0xf0e6cc, axial_vertebral: 0xede0c0,
  axial_thorax: 0xe8dbb8, appendicular_pectoral: 0xeadcba,
  appendicular_upper: 0xe5d7b2, appendicular_pelvic: 0xe0d0aa,
  appendicular_lower: 0xdbc9a2,
};
for (const [region, color] of Object.entries(BONE_COLORS)) {
  const r = (color >> 16) & 0xff;
  const g = (color >> 8) & 0xff;
  const b = color & 0xff;
  const brightness = (r + g + b) / 3;
  assert(brightness > 100, `Bone color for ${region} is too dark: RGB(${r},${g},${b}) brightness=${brightness}`);
}

// ── Test 8: No envMapIntensity > 0 without scene.environment ──
// This is the regression that caused black rendering.
// MeshPhysicalMaterial with envMapIntensity > 0 but no env map = black.
// The renderer.tsx file should NOT set envMapIntensity OR should set scene.environment.
const rendererSrc = fs.readFileSync(path.join(__dirname, "renderer.tsx"), "utf-8");
const hasEnvMapIntensity = /envMapIntensity\s*:\s*[0-9.]+/.test(rendererSrc);
const hasSceneEnvironment = /scene\.environment\s*=/.test(rendererSrc);
if (hasEnvMapIntensity && !hasSceneEnvironment) {
  errors.push("FAIL: renderer.tsx sets envMapIntensity but never sets scene.environment — materials render BLACK");
  failed++;
} else {
  passed++;
}

// ── Test 9: Bloom pass doesn't swallow output ──
const hasSMAANoArgs = /new SMAAPass\(\s*\)/.test(rendererSrc);
assert(!hasSMAANoArgs, "SMAAPass() with no args creates 0-pixel render target — scene renders BLACK");

// ── Test 10: Composer uses correct render order ──
const hasRenderPass = /new RenderPass\(/.test(rendererSrc);
assert(hasRenderPass, "EffectComposer needs a RenderPass as first pass");

// ── Test 11: CSG subtraction changes rendered geometry ──
const outerSphere: CSGNode = {
  nodeType: "primitive",
  primitive: { primitiveType: "sphere", radius: 1, position: { x: 0, y: 0, z: 0 } },
};
const subtractedSphere: CSGNode = {
  nodeType: "operation",
  operation: "subtract",
  children: [
    outerSphere,
    {
      nodeType: "primitive",
      primitive: { primitiveType: "sphere", radius: 0.55, position: { x: 0.45, y: 0, z: 0 } },
    },
  ],
};
const outerGeo = csgPrimitiveToGeometry(outerSphere.primitive);
const subtractGeo = csgTreeToGeometry(subtractedSphere);
const outerPos = outerGeo.getAttribute("position") as THREE.BufferAttribute;
const subtractPos = subtractGeo.getAttribute("position") as THREE.BufferAttribute;
assert(subtractPos.count !== outerPos.count, "CSG subtract should not render as the original minuend mesh");
let subtractHasInnerSurface = false;
for (let i = 0; i < subtractPos.count; i++) {
  const x = subtractPos.getX(i);
  const y = subtractPos.getY(i);
  const z = subtractPos.getZ(i);
  const distToSubtractorCenter = Math.sqrt(((x - 0.45) ** 2) + (y * y) + (z * z));
  if (distToSubtractorCenter < 0.58) {
    subtractHasInnerSurface = true;
    break;
  }
}
assert(subtractHasInnerSurface, "CSG subtract should add cavity-facing surface vertices");
outerGeo.dispose();
subtractGeo.dispose();

// ── Report ──
console.log("\n════════════════════════════════════════");
console.log(`  RENDERER REGRESSION TESTS`);
console.log("════════════════════════════════════════");
console.log(`  Passed: ${passed}`);
console.log(`  Failed: ${failed}`);
console.log(`  Warnings: ${warnings.length}`);
console.log("════════════════════════════════════════\n");

if (errors.length > 0) {
  console.log("ERRORS:");
  for (const e of errors) console.log(`  ${e}`);
}
if (warnings.length > 0) {
  console.log("\nWARNINGS:");
  for (const w of warnings) console.log(`  ${w}`);
}

process.exit(failed > 0 ? 1 : 0);
